(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_p2d_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/p2d.svelte */ "./src/components/p2d.svelte");
/* src/routes/index.svelte generated by Svelte v3.9.2 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1tlnjco-style';
	style.textContent = ".landing-page--hero.svelte-1tlnjco{width:50%;margin:20px auto;display:block;background-image:var(--avatar);background-size:cover;width:300px;height:300px}li.svelte-1tlnjco,ul.svelte-1tlnjco{margin:5px;margin-top:10px;list-style-type:none}span.svelte-1tlnjco{font-family:var(--font)}.repo--name.svelte-1tlnjco{font-size:1em;padding:0;margin:0}.repo--badges.svelte-1tlnjco{margin:5px;padding:5px;border-radius:5px;border:1px solid rgba(var(--text-base), 0.1);font-size:0.75em}.repo--badges.svelte-1tlnjco span.svelte-1tlnjco{margin:2px}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcbiAgICBsZXQgcmVwb3NcblxuICAgIC8vIGZldGNoKFwiLy5uZXRsaWZ5L2Z1bmN0aW9ucy9naXRodWJcIikudGhlbihyZXMgPT4gcmVzLmpzb24oKSkudGhlbihqc29uID0+IHtcbiAgICAvLyAgICAgcmVwb3MgPSBqc29uXG4gICAgLy8gfSlcblxuXG4gICAgcmVwb3MgPSBbXG4gICAge1xuICAgICAgICBcImZvcmtDb3VudFwiOiAyNyxcbiAgICAgICAgXCJ1cmxcIjogXCJibHVlXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIkxldGljaWEgSGFuc2VuXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkphdmFTY3JpcHRcIixcbiAgICAgICAgICAgIFwiY29sb3JcIjogXCIjMDBmXCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAzMFxuICAgICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiZm9ya0NvdW50XCI6IDQwLFxuICAgICAgICBcInVybFwiOiBcImJyb3duXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIkNhbmR5IFZhc3F1ZXpcIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4gICAgICAgICAgICBcImNvbG9yXCI6IFwiI2ZmMFwiXG4gICAgICAgIH0sXG4gICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4gICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMjZcbiAgICAgICAgfVxuICAgIH0sXG4gICAge1xuICAgICAgICBcImZvcmtDb3VudFwiOiAzNixcbiAgICAgICAgXCJ1cmxcIjogXCJncmVlblwiLFxuICAgICAgICBcIm5hbWVcIjogXCJMYW1iIEpvaG5zb25cIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4gICAgICAgICAgICBcImNvbG9yXCI6IFwiI2YwMFwiXG4gICAgICAgIH0sXG4gICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4gICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMjRcbiAgICAgICAgfVxuICAgIH0sXG4gICAge1xuICAgICAgICBcImZvcmtDb3VudFwiOiAyMyxcbiAgICAgICAgXCJ1cmxcIjogXCJibHVlXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlNvbG9tb24gTWVkaW5hXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmMDBcIlxuICAgICAgICB9LFxuICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDM5XG4gICAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJmb3JrQ291bnRcIjogMjYsXG4gICAgICAgIFwidXJsXCI6IFwiYmx1ZVwiLFxuICAgICAgICBcIm5hbWVcIjogXCJSaWNobW9uZCBIZXNzXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjBcIlxuICAgICAgICB9LFxuICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDI0XG4gICAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJmb3JrQ291bnRcIjogMzgsXG4gICAgICAgIFwidXJsXCI6IFwiZ3JlZW5cIixcbiAgICAgICAgXCJuYW1lXCI6IFwiU3BlbmNlciBCdXNoXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjBcIlxuICAgICAgICB9LFxuICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDMzXG4gICAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJmb3JrQ291bnRcIjogMjIsXG4gICAgICAgIFwidXJsXCI6IFwiZ3JlZW5cIixcbiAgICAgICAgXCJuYW1lXCI6IFwiSGFtbW9uZCBNYW5uXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkphdmFTY3JpcHRcIixcbiAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZmYwXCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyMlxuICAgICAgICB9XG4gICAgfVxuXVxuXG48L3NjcmlwdD5cblxuPHN0eWxlIGxhbmc9XCJzYXNzXCI+LmxhbmRpbmctcGFnZS0taGVybyB7XG4gIHdpZHRoOiA1MCU7XG4gIG1hcmdpbjogMjBweCBhdXRvO1xuICBkaXNwbGF5OiBibG9jaztcbiAgYmFja2dyb3VuZC1pbWFnZTogdmFyKC0tYXZhdGFyKTtcbiAgYmFja2dyb3VuZC1zaXplOiBjb3ZlcjtcbiAgd2lkdGg6IDMwMHB4O1xuICBoZWlnaHQ6IDMwMHB4OyB9XG5cbmxpLCB1bCB7XG4gIG1hcmdpbjogNXB4O1xuICBtYXJnaW4tdG9wOiAxMHB4O1xuICBsaXN0LXN0eWxlLXR5cGU6IG5vbmU7IH1cblxuc3BhbiB7XG4gIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250KTsgfVxuXG4ucmVwby0tbmFtZSB7XG4gIGZvbnQtc2l6ZTogMWVtO1xuICBwYWRkaW5nOiAwO1xuICBtYXJnaW46IDA7IH1cblxuLnJlcG8tLWJhZGdlcyB7XG4gIG1hcmdpbjogNXB4O1xuICBwYWRkaW5nOiA1cHg7XG4gIGJvcmRlci1yYWRpdXM6IDVweDtcbiAgYm9yZGVyOiAxcHggc29saWQgcmdiYSh2YXIoLS10ZXh0LWJhc2UpLCAwLjEpO1xuICBmb250LXNpemU6IDAuNzVlbTsgfVxuICAucmVwby0tYmFkZ2VzIHNwYW4ge1xuICAgIG1hcmdpbjogMnB4OyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICAgIDx0aXRsZT5Ib21lPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxkaXYgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLWhlcm9cIj48L2Rpdj48cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tdGl0bGVcIj5NYXJjdXMgTWF0aGlhc3NlbjwvcD48cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tc3VidGl0bGVcIj5JIGRvIGNvbXBpbGVycyBhbmQgbGFuZ3VhZ2VzLlxuSW50ZXJlc3RlZCBpbiBzeXN0ZW1zIGRlc2lnbiBhbmQgVVguPC9wPlxuPGJyPlxuPGgyPlJlcG9zaXRvcmllczwvaDI+XG48dWw+XG5cdHsjZWFjaCByZXBvcyBhcyByZXBvfVxuICAgIDxsaT5cbiAgICAgICAgPGEgaHJlZj1cIntyZXBvLnVybH1cIiB0YXJnZXQ9XCJfYmxhbmtcIiByZWw9XCJub29wZW5lclwiPlxuICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLW5hbWVcIj57cmVwby5uYW1lfVxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJyZXBvLS1iYWRnZXNcIj5cbiAgICAgICAgICAgICAgICB7I2lmIHJlcG8ucHJpbWFyeUxhbmd1YWdlfVxuICAgICAgICAgICAgICAgICAgICA8c3BhbiBzdHlsZT1cImNvbG9yOiB7cmVwby5wcmltYXJ5TGFuZ3VhZ2UuY29sb3J9XCI+IHtyZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lfTwvc3Bhbj5cbiAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgIHsjaWYgcmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtc3RhclwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+e3JlcG8uc3RhcmdhemVycy50b3RhbENvdW50fTwvc3Bhbj48L2k+XG4gICAgICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgIHsjaWYgcmVwby5mb3JrQ291bnR9XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtY29kZS1icmFuY2hcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPntyZXBvLmZvcmtDb3VudH08L3NwYW4+PC9pPlxuICAgICAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgPC9zcGFuPlxuICAgICAgICA8L2E+XG4gICAgPC9saT5cblx0ey9lYWNofVxuPC91bD5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFrR21CLG1CQUFtQixlQUFDLENBQUMsQUFDdEMsS0FBSyxDQUFFLEdBQUcsQ0FDVixNQUFNLENBQUUsSUFBSSxDQUFDLElBQUksQ0FDakIsT0FBTyxDQUFFLEtBQUssQ0FDZCxnQkFBZ0IsQ0FBRSxJQUFJLFFBQVEsQ0FBQyxDQUMvQixlQUFlLENBQUUsS0FBSyxDQUN0QixLQUFLLENBQUUsS0FBSyxDQUNaLE1BQU0sQ0FBRSxLQUFLLEFBQUUsQ0FBQyxBQUVsQixpQkFBRSxDQUFFLEVBQUUsZUFBQyxDQUFDLEFBQ04sTUFBTSxDQUFFLEdBQUcsQ0FDWCxVQUFVLENBQUUsSUFBSSxDQUNoQixlQUFlLENBQUUsSUFBSSxBQUFFLENBQUMsQUFFMUIsSUFBSSxlQUFDLENBQUMsQUFDSixXQUFXLENBQUUsSUFBSSxNQUFNLENBQUMsQUFBRSxDQUFDLEFBRTdCLFdBQVcsZUFBQyxDQUFDLEFBQ1gsU0FBUyxDQUFFLEdBQUcsQ0FDZCxPQUFPLENBQUUsQ0FBQyxDQUNWLE1BQU0sQ0FBRSxDQUFDLEFBQUUsQ0FBQyxBQUVkLGFBQWEsZUFBQyxDQUFDLEFBQ2IsTUFBTSxDQUFFLEdBQUcsQ0FDWCxPQUFPLENBQUUsR0FBRyxDQUNaLGFBQWEsQ0FBRSxHQUFHLENBQ2xCLE1BQU0sQ0FBRSxHQUFHLENBQUMsS0FBSyxDQUFDLEtBQUssSUFBSSxXQUFXLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUM3QyxTQUFTLENBQUUsTUFBTSxBQUFFLENBQUMsQUFDcEIsNEJBQWEsQ0FBQyxJQUFJLGVBQUMsQ0FBQyxBQUNsQixNQUFNLENBQUUsR0FBRyxBQUFFLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.repo = list[i];
	return child_ctx;
}

// (146:16) {#if repo.primaryLanguage}
function create_if_block_2(ctx) {
	var span, t_value = ctx.repo.primaryLanguage.name + "", t;

	return {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { style: true, class: true }, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span, "color", ctx.repo.primaryLanguage.color);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span, "class", "svelte-1tlnjco");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 146, 20, 3120);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.primaryLanguage.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t, t_value);
			}

			if (changed.repos) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span, "color", ctx.repo.primaryLanguage.color);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span);
			}
		}
	};
}

// (149:16) {#if repo.stargazers.totalCount}
function create_if_block_1(ctx) {
	var span1, i, span0, t_value = ctx.repo.stargazers.totalCount + "", t;

	return {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(i_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "svelte-1tlnjco");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 151, 24, 3376);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(i, "class", "fas fa-star");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 150, 24, 3328);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "svelte-1tlnjco");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 149, 20, 3297);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(i, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.stargazers.totalCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span1);
			}
		}
	};
}

// (155:16) {#if repo.forkCount}
function create_if_block(ctx) {
	var span1, i, span0, t_value = ctx.repo.forkCount + "", t;

	return {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(i_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "svelte-1tlnjco");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 157, 24, 3615);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(i, "class", "fas fa-code-branch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 156, 24, 3560);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "svelte-1tlnjco");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 155, 20, 3529);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(i, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.forkCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span1);
			}
		}
	};
}

// (141:1) {#each repos as repo}
function create_each_block(ctx) {
	var li, a, span1, t0_value = ctx.repo.name + "", t0, t1, span0, t2, t3, a_href_value, t4;

	var if_block0 = (ctx.repo.primaryLanguage) && create_if_block_2(ctx);

	var if_block1 = (ctx.repo.stargazers.totalCount) && create_if_block_1(ctx);

	var if_block2 = (ctx.repo.forkCount) && create_if_block(ctx);

	return {
		c: function create() {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			if (if_block0) if_block0.c();
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "LI", { class: true }, false);
			var li_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "A", { href: true, target: true, rel: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n            ");

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			if (if_block0) if_block0.l(span0_nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, "\n                ");
			if (if_block1) if_block1.l(span0_nodes);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, "\n                ");
			if (if_block2) if_block2.l(span0_nodes);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li_nodes, "\n    ");
			li_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "repo--badges svelte-1tlnjco");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 144, 12, 3029);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "repo--name svelte-1tlnjco");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 143, 8, 2980);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "href", a_href_value = ctx.repo.url);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 142, 8, 2919);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(li, "class", "svelte-1tlnjco");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li, file, 141, 4, 2906);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, li, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, span0);
			if (if_block0) if_block0.m(span0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t2);
			if (if_block1) if_block1.m(span0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t3);
			if (if_block2) if_block2.m(span0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li, t4);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t0_value !== (t0_value = ctx.repo.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, t0_value);
			}

			if (ctx.repo.primaryLanguage) {
				if (if_block0) {
					if_block0.p(changed, ctx);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(span0, t2);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (ctx.repo.stargazers.totalCount) {
				if (if_block1) {
					if_block1.p(changed, ctx);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(span0, t3);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (ctx.repo.forkCount) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(span0, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if ((changed.repos) && a_href_value !== (a_href_value = ctx.repo.url)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "href", a_href_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(li);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
		}
	};
}

function create_fragment(ctx) {
	var t0, div, p0, t1, p1, t2, t3, br, t4, h2, t5, t6, ul;

	var each_value = ctx.repos;

	var each_blocks = [];

	for (var i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Marcus Mathiassen");
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I do compilers and languages.\nInterested in systems design and UX.");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Repositories");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Marcus Mathiassen");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "I do compilers and languages.\nInterested in systems design and UX.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "BR", {}, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "H2", {}, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Repositories");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Home";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div, "class", "landing-page--hero svelte-1tlnjco");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 135, 0, 2652);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p0, "class", "landing-page--title");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 135, 38, 2690);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p1, "class", "landing-page--subtitle");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 135, 90, 2742);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 137, 0, 2847);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 138, 0, 2852);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(ul, "class", "svelte-1tlnjco");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 139, 0, 2874);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, br, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t4, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, h2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h2, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t6, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, ul, anchor);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.repos) {
				each_value = ctx.repos;

				for (var i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p1);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t3);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(br);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t4);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(h2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t6);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(ul);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let repos

    // fetch("/.netlify/functions/github").then(res => res.json()).then(json => {
    //     repos = json
    // })


    $$invalidate('repos', repos = [
    {
        "forkCount": 27,
        "url": "blue",
        "name": "Leticia Hansen",
        "primaryLanguage": {
            "name": "JavaScript",
            "color": "#00f"
        },
        "stargazers": {
            "totalCount": 30
        }
    },
    {
        "forkCount": 40,
        "url": "brown",
        "name": "Candy Vasquez",
        "primaryLanguage": {
            "name": "C++",
            "color": "#ff0"
        },
        "stargazers": {
            "totalCount": 26
        }
    },
    {
        "forkCount": 36,
        "url": "green",
        "name": "Lamb Johnson",
        "primaryLanguage": {
            "name": "C++",
            "color": "#f00"
        },
        "stargazers": {
            "totalCount": 24
        }
    },
    {
        "forkCount": 23,
        "url": "blue",
        "name": "Solomon Medina",
        "primaryLanguage": {
            "name": "C++",
            "color": "#f00"
        },
        "stargazers": {
            "totalCount": 39
        }
    },
    {
        "forkCount": 26,
        "url": "blue",
        "name": "Richmond Hess",
        "primaryLanguage": {
            "name": "C++",
            "color": "#ff0"
        },
        "stargazers": {
            "totalCount": 24
        }
    },
    {
        "forkCount": 38,
        "url": "green",
        "name": "Spencer Bush",
        "primaryLanguage": {
            "name": "C++",
            "color": "#ff0"
        },
        "stargazers": {
            "totalCount": 33
        }
    },
    {
        "forkCount": 22,
        "url": "green",
        "name": "Hammond Mann",
        "primaryLanguage": {
            "name": "JavaScript",
            "color": "#ff0"
        },
        "stargazers": {
            "totalCount": 22
        }
    }
])

	return { repos };
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1tlnjco-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9pbmRleC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkFrSndFLElBQUksQ0FBQyxlQUFlLENBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt3RkFBeEQsSUFBSSxDQUFDLGVBQWUsQ0FBQyxLQUFLOzs7Ozs7Ozs7OztxREFBSyxJQUFJLENBQUMsZUFBZSxDQUFDLElBQUk7Ozs7O3lGQUF4RCxJQUFJLENBQUMsZUFBZSxDQUFDLEtBQUs7Ozs7Ozs7Ozs7Ozs7O29DQUtwQyxJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxREFBMUIsSUFBSSxDQUFDLFVBQVUsQ0FBQyxVQUFVOzs7Ozs7Ozs7Ozs7Ozs7b0NBTTFCLElBQUksQ0FBQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7cURBQWQsSUFBSSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7OztrQ0FkWCxJQUFJLENBQUMsSUFBSTs7c0JBRXRCLElBQUksQ0FBQyxlQUFlOztzQkFHcEIsSUFBSSxDQUFDLFVBQVUsQ0FBQyxVQUFVOztzQkFNMUIsSUFBSSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzhGQVpqQixJQUFJLENBQUMsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VEQUNRLElBQUksQ0FBQyxJQUFJOzs7O1dBRXRCLElBQUksQ0FBQyxlQUFlOzs7Ozs7Ozs7Ozs7O1dBR3BCLElBQUksQ0FBQyxVQUFVLENBQUMsVUFBVTs7Ozs7Ozs7Ozs7OztXQU0xQixJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7OzsrREFaakIsSUFBSSxDQUFDLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NCQUZsQixLQUFLOzs7O2dDQUFWOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7OztxQkFBSyxLQUFLOzttQ0FBVjs7Ozs7Ozs7Ozs7OzJCQUFBOzs7Z0JBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztDQTFJQyxJQUFJLEtBQUs7Ozs7Ozs7MEJBT1QsS0FBSyxHQUFHO0lBQ1I7UUFDSSxXQUFXLEVBQUUsRUFBRTtRQUNmLEtBQUssRUFBRSxNQUFNO1FBQ2IsTUFBTSxFQUFFLGdCQUFnQjtRQUN4QixpQkFBaUIsRUFBRTtZQUNmLE1BQU0sRUFBRSxZQUFZO1lBQ3BCLE9BQU8sRUFBRSxNQUFNO1NBQ2xCO1FBQ0QsWUFBWSxFQUFFO1lBQ1YsWUFBWSxFQUFFLEVBQUU7U0FDbkI7S0FDSjtJQUNEO1FBQ0ksV0FBVyxFQUFFLEVBQUU7UUFDZixLQUFLLEVBQUUsT0FBTztRQUNkLE1BQU0sRUFBRSxlQUFlO1FBQ3ZCLGlCQUFpQixFQUFFO1lBQ2YsTUFBTSxFQUFFLEtBQUs7WUFDYixPQUFPLEVBQUUsTUFBTTtTQUNsQjtRQUNELFlBQVksRUFBRTtZQUNWLFlBQVksRUFBRSxFQUFFO1NBQ25CO0tBQ0o7SUFDRDtRQUNJLFdBQVcsRUFBRSxFQUFFO1FBQ2YsS0FBSyxFQUFFLE9BQU87UUFDZCxNQUFNLEVBQUUsY0FBYztRQUN0QixpQkFBaUIsRUFBRTtZQUNmLE1BQU0sRUFBRSxLQUFLO1lBQ2IsT0FBTyxFQUFFLE1BQU07U0FDbEI7UUFDRCxZQUFZLEVBQUU7WUFDVixZQUFZLEVBQUUsRUFBRTtTQUNuQjtLQUNKO0lBQ0Q7UUFDSSxXQUFXLEVBQUUsRUFBRTtRQUNmLEtBQUssRUFBRSxNQUFNO1FBQ2IsTUFBTSxFQUFFLGdCQUFnQjtRQUN4QixpQkFBaUIsRUFBRTtZQUNmLE1BQU0sRUFBRSxLQUFLO1lBQ2IsT0FBTyxFQUFFLE1BQU07U0FDbEI7UUFDRCxZQUFZLEVBQUU7WUFDVixZQUFZLEVBQUUsRUFBRTtTQUNuQjtLQUNKO0lBQ0Q7UUFDSSxXQUFXLEVBQUUsRUFBRTtRQUNmLEtBQUssRUFBRSxNQUFNO1FBQ2IsTUFBTSxFQUFFLGVBQWU7UUFDdkIsaUJBQWlCLEVBQUU7WUFDZixNQUFNLEVBQUUsS0FBSztZQUNiLE9BQU8sRUFBRSxNQUFNO1NBQ2xCO1FBQ0QsWUFBWSxFQUFFO1lBQ1YsWUFBWSxFQUFFLEVBQUU7U0FDbkI7S0FDSjtJQUNEO1FBQ0ksV0FBVyxFQUFFLEVBQUU7UUFDZixLQUFLLEVBQUUsT0FBTztRQUNkLE1BQU0sRUFBRSxjQUFjO1FBQ3RCLGlCQUFpQixFQUFFO1lBQ2YsTUFBTSxFQUFFLEtBQUs7WUFDYixPQUFPLEVBQUUsTUFBTTtTQUNsQjtRQUNELFlBQVksRUFBRTtZQUNWLFlBQVksRUFBRSxFQUFFO1NBQ25CO0tBQ0o7SUFDRDtRQUNJLFdBQVcsRUFBRSxFQUFFO1FBQ2YsS0FBSyxFQUFFLE9BQU87UUFDZCxNQUFNLEVBQUUsY0FBYztRQUN0QixpQkFBaUIsRUFBRTtZQUNmLE1BQU0sRUFBRSxZQUFZO1lBQ3BCLE9BQU8sRUFBRSxNQUFNO1NBQ2xCO1FBQ0QsWUFBWSxFQUFFO1lBQ1YsWUFBWSxFQUFFLEVBQUU7U0FDbkI7S0FDSjtDQUNKIiwiZmlsZSI6ImRkMjM4MDIzYTUwNGE1YTA1ZjNjL2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcbiAgICBsZXQgcmVwb3NcblxuICAgIC8vIGZldGNoKFwiLy5uZXRsaWZ5L2Z1bmN0aW9ucy9naXRodWJcIikudGhlbihyZXMgPT4gcmVzLmpzb24oKSkudGhlbihqc29uID0+IHtcbiAgICAvLyAgICAgcmVwb3MgPSBqc29uXG4gICAgLy8gfSlcblxuXG4gICAgcmVwb3MgPSBbXG4gICAge1xuICAgICAgICBcImZvcmtDb3VudFwiOiAyNyxcbiAgICAgICAgXCJ1cmxcIjogXCJibHVlXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIkxldGljaWEgSGFuc2VuXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkphdmFTY3JpcHRcIixcbiAgICAgICAgICAgIFwiY29sb3JcIjogXCIjMDBmXCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAzMFxuICAgICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiZm9ya0NvdW50XCI6IDQwLFxuICAgICAgICBcInVybFwiOiBcImJyb3duXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIkNhbmR5IFZhc3F1ZXpcIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4gICAgICAgICAgICBcImNvbG9yXCI6IFwiI2ZmMFwiXG4gICAgICAgIH0sXG4gICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4gICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMjZcbiAgICAgICAgfVxuICAgIH0sXG4gICAge1xuICAgICAgICBcImZvcmtDb3VudFwiOiAzNixcbiAgICAgICAgXCJ1cmxcIjogXCJncmVlblwiLFxuICAgICAgICBcIm5hbWVcIjogXCJMYW1iIEpvaG5zb25cIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4gICAgICAgICAgICBcImNvbG9yXCI6IFwiI2YwMFwiXG4gICAgICAgIH0sXG4gICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4gICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMjRcbiAgICAgICAgfVxuICAgIH0sXG4gICAge1xuICAgICAgICBcImZvcmtDb3VudFwiOiAyMyxcbiAgICAgICAgXCJ1cmxcIjogXCJibHVlXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlNvbG9tb24gTWVkaW5hXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmMDBcIlxuICAgICAgICB9LFxuICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDM5XG4gICAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJmb3JrQ291bnRcIjogMjYsXG4gICAgICAgIFwidXJsXCI6IFwiYmx1ZVwiLFxuICAgICAgICBcIm5hbWVcIjogXCJSaWNobW9uZCBIZXNzXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjBcIlxuICAgICAgICB9LFxuICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDI0XG4gICAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJmb3JrQ291bnRcIjogMzgsXG4gICAgICAgIFwidXJsXCI6IFwiZ3JlZW5cIixcbiAgICAgICAgXCJuYW1lXCI6IFwiU3BlbmNlciBCdXNoXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjBcIlxuICAgICAgICB9LFxuICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDMzXG4gICAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJmb3JrQ291bnRcIjogMjIsXG4gICAgICAgIFwidXJsXCI6IFwiZ3JlZW5cIixcbiAgICAgICAgXCJuYW1lXCI6IFwiSGFtbW9uZCBNYW5uXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkphdmFTY3JpcHRcIixcbiAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZmYwXCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyMlxuICAgICAgICB9XG4gICAgfVxuXVxuXG48L3NjcmlwdD5cblxuPHN0eWxlIGxhbmc9XCJzYXNzXCI+LmxhbmRpbmctcGFnZS0taGVybyB7XG4gIHdpZHRoOiA1MCU7XG4gIG1hcmdpbjogMjBweCBhdXRvO1xuICBkaXNwbGF5OiBibG9jaztcbiAgYmFja2dyb3VuZC1pbWFnZTogdmFyKC0tYXZhdGFyKTtcbiAgYmFja2dyb3VuZC1zaXplOiBjb3ZlcjtcbiAgd2lkdGg6IDMwMHB4O1xuICBoZWlnaHQ6IDMwMHB4OyB9XG5cbmxpLCB1bCB7XG4gIG1hcmdpbjogNXB4O1xuICBtYXJnaW4tdG9wOiAxMHB4O1xuICBsaXN0LXN0eWxlLXR5cGU6IG5vbmU7IH1cblxuc3BhbiB7XG4gIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250KTsgfVxuXG4ucmVwby0tbmFtZSB7XG4gIGZvbnQtc2l6ZTogMWVtO1xuICBwYWRkaW5nOiAwO1xuICBtYXJnaW46IDA7IH1cblxuLnJlcG8tLWJhZGdlcyB7XG4gIG1hcmdpbjogNXB4O1xuICBwYWRkaW5nOiA1cHg7XG4gIGJvcmRlci1yYWRpdXM6IDVweDtcbiAgYm9yZGVyOiAxcHggc29saWQgcmdiYSh2YXIoLS10ZXh0LWJhc2UpLCAwLjEpO1xuICBmb250LXNpemU6IDAuNzVlbTsgfVxuICAucmVwby0tYmFkZ2VzIHNwYW4ge1xuICAgIG1hcmdpbjogMnB4OyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICAgIDx0aXRsZT5Ib21lPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxkaXYgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLWhlcm9cIj48L2Rpdj48cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tdGl0bGVcIj5NYXJjdXMgTWF0aGlhc3NlbjwvcD48cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tc3VidGl0bGVcIj5JIGRvIGNvbXBpbGVycyBhbmQgbGFuZ3VhZ2VzLlxuSW50ZXJlc3RlZCBpbiBzeXN0ZW1zIGRlc2lnbiBhbmQgVVguPC9wPlxuPGJyPlxuPGgyPlJlcG9zaXRvcmllczwvaDI+XG48dWw+XG5cdHsjZWFjaCByZXBvcyBhcyByZXBvfVxuICAgIDxsaT5cbiAgICAgICAgPGEgaHJlZj1cIntyZXBvLnVybH1cIiB0YXJnZXQ9XCJfYmxhbmtcIiByZWw9XCJub29wZW5lclwiPlxuICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLW5hbWVcIj57cmVwby5uYW1lfVxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJyZXBvLS1iYWRnZXNcIj5cbiAgICAgICAgICAgICAgICB7I2lmIHJlcG8ucHJpbWFyeUxhbmd1YWdlfVxuICAgICAgICAgICAgICAgICAgICA8c3BhbiBzdHlsZT1cImNvbG9yOiB7cmVwby5wcmltYXJ5TGFuZ3VhZ2UuY29sb3J9XCI+IHtyZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lfTwvc3Bhbj5cbiAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgIHsjaWYgcmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtc3RhclwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+e3JlcG8uc3RhcmdhemVycy50b3RhbENvdW50fTwvc3Bhbj48L2k+XG4gICAgICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgIHsjaWYgcmVwby5mb3JrQ291bnR9XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtY29kZS1icmFuY2hcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPntyZXBvLmZvcmtDb3VudH08L3NwYW4+PC9pPlxuICAgICAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgPC9zcGFuPlxuICAgICAgICA8L2E+XG4gICAgPC9saT5cblx0ey9lYWNofVxuPC91bD5cbiJdLCJzb3VyY2VSb290IjoiIn0=