(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_p2d_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/p2d.svelte */ "./src/components/p2d.svelte");
/* src/routes/index.svelte generated by Svelte v3.9.2 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1jn40vy-style';
	style.textContent = ".landing-page--hero.svelte-1jn40vy{width:50%;margin:20px auto;display:block;background-image:var(--avatar);background-size:cover;width:300px;height:300px}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcblxuICAgIGxldCByZXNwb25zZSA9IFwiXCJcblxuXG4gICAgLy8gICAgZmV0Y2goYGh0dHBzOi8vYXBpLmdpdGh1Yi5jb20vZ3JhcGhxbGAsIHtcbiAgICAvLyAgICAgbWV0aG9kOiAncG9zdCcsXG4gICAgLy8gICAgIGhlYWRlcnM6IHtcbiAgICAvLyAgICAgICAgIEF1dGhvcml6YXRpb246IGBiZWFyZXIgJHtwcm9jZXNzLmVudi5HSVRIVUJfVE9LRU59YCxcbiAgICAvLyAgICAgICAgICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicsXG4gICAgLy8gICAgIH0sXG4gICAgLy8gICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHtcbiAgICAvLyAgICAgICAgIHF1ZXJ5OiBgcXVlcnkgeyB2aWV3ZXIgeyByZXBvc2l0b3JpZXMoZmlyc3Q6IDIwKSB7IGVkZ2VzIHsgbm9kZSB7IG5hbWUgcHVzaGVkQXQgfSB9IH0gfSB9YCxcbiAgICAvLyAgICAgfSksXG4gICAgLy8gfSlcbiAgICAvLyAgICAgLnRoZW4ocmVzID0+IHJlcy5qc29uKCkpXG4gICAgLy8gICAgIC50aGVuKGpzb24gPT4ge1xuICAgIC8vICAgICAgICAgdmFyIGVkZ2VzID0ganNvbi5kYXRhLnZpZXdlci5yZXBvc2l0b3JpZXMuZWRnZXNcbiAgICAvLyAgICAgICAgIC8vIFNvcnQgdGhlIHJlcG9zaXRvcmllcyBieSBwdXNoZGF0ZVxuICAgIC8vICAgICAgICAgZWRnZXMuc29ydCgoYSwgYikgPT4ge1xuICAgIC8vICAgICAgICAgICAgIHJldHVybiAoXG4gICAgLy8gICAgICAgICAgICAgICAgIG5ldyBEYXRlKGIubm9kZS5wdXNoZWRBdCkuZ2V0VGltZSgpIC1cbiAgICAvLyAgICAgICAgICAgICAgICAgbmV3IERhdGUoYS5ub2RlLnB1c2hlZEF0KS5nZXRUaW1lKClcbiAgICAvLyAgICAgICAgICAgICApXG4gICAgLy8gICAgICAgICB9KVxuICAgIC8vICAgICAgICAgY29uc3QgbmFtZU9mTGFzdFJlcG9VcGRhdGVkID0gZWRnZXNbMF0ubm9kZS5uYW1lXG4gICAgLy8gICAgICAgICBmZXRjaChgaHR0cHM6Ly9hcGkuZ2l0aHViLmNvbS9ncmFwaHFsYCwge1xuICAgIC8vICAgICAgICAgICAgIG1ldGhvZDogJ3Bvc3QnLFxuICAgIC8vICAgICAgICAgICAgIGhlYWRlcnM6IHtcbiAgICAvLyAgICAgICAgICAgICAgICAgQXV0aG9yaXphdGlvbjpcbiAgICAvLyAgICAgICAgICAgICAgICAgICAgIGBiZWFyZXIgJHtwcm9jZXNzLmVudi5HSVRIVUJfVE9LRU59YCxcbiAgICAvLyAgICAgICAgICAgICAgICAgJ0NvbnRlbnQtVHlwZSc6ICdhcHBsaWNhdGlvbi9qc29uJyxcbiAgICAvLyAgICAgICAgICAgICB9LFxuICAgIC8vICAgICAgICAgICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHtcbiAgICAvLyAgICAgICAgICAgICAgICAgcXVlcnk6IGBxdWVyeSB7IHZpZXdlciB7IHJlcG9zaXRvcnkobmFtZTpcIiR7bmFtZU9mTGFzdFJlcG9VcGRhdGVkfVwiKSB7IGRlc2NyaXB0aW9uIH0gfSB9YCxcbiAgICAvLyAgICAgICAgICAgICB9KSxcbiAgICAvLyAgICAgICAgIH0pXG4gICAgLy8gICAgICAgICAgICAgLnRoZW4ocmVzID0+IHJlcy5qc29uKCkpXG4gICAgLy8gICAgICAgICAgICAgLnRoZW4oanNvbiA9PiB7XG4gICAgLy8gICAgICAgICAgICAgICAgIGNvbnNvbGUubG9nKGpzb24pXG4gICAgLy8gICAgICAgICAgICAgICAgIGNvbnN0IGRlc2MgPSBqc29uLmRhdGEudmlld2VyLnJlcG9zaXRvcnkuZGVzY3JpcHRpb25cbiAgICAvLyAgICAgICAgICAgICAgICAgLy8gJChcbiAgICAvLyAgICAgICAgICAgICAgICAgLy8gICAgICcjbGFzdC1yZXBvLXVwZGF0ZWQnXG4gICAgLy8gICAgICAgICAgICAgICAgIC8vICkuaW5uZXJIVE1MID0gYEN1cnJlbnRseSB3b3JraW5nIG9uIDxoMT4ke25hbWVPZkxhc3RSZXBvVXBkYXRlZH08L2gxPiA8cD4ke2Rlc2N9PC9wPmBcbiAgICAvLyAgICAgICAgICAgICB9KVxuICAgIC8vICAgICB9KVxuXG4gICAgZnVuY3Rpb24gaGFuZGxlQ2xpY2soZXZlbnQpIHtcbiAgICAgICAgZmV0Y2goXCIvLm5ldGxpZnkvZnVuY3Rpb25zL2hlbGxvLXdvcmxkXCIpLnRoZW4ocmVzID0+IHJlcy50ZXh0KCkpLnRoZW4odGV4dCA9PiB7XG4gICAgICAgICAgICAgICAgcmVzcG9uc2UgPSB0ZXh0XG4gICAgICAgICAgICB9KVxuICAgIH1cbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4ubGFuZGluZy1wYWdlLS1oZXJvIHtcbiAgd2lkdGg6IDUwJTtcbiAgbWFyZ2luOiAyMHB4IGF1dG87XG4gIGRpc3BsYXk6IGJsb2NrO1xuICBiYWNrZ3JvdW5kLWltYWdlOiB2YXIoLS1hdmF0YXIpO1xuICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICB3aWR0aDogMzAwcHg7XG4gIGhlaWdodDogMzAwcHg7IH1cblxuLyojIHNvdXJjZU1hcHBpbmdVUkw9aW5kZXguc3ZlbHRlLmNzcy5tYXAgKi88L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gICAgPHRpdGxlPkhvbWU8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPGRpdiBjbGFzcz1cImxhbmRpbmctcGFnZS0taGVyb1wiPjwvZGl2PjxwIGNsYXNzPVwibGFuZGluZy1wYWdlLS10aXRsZVwiPk1hcmN1cyBNYXRoaWFzc2VuPC9wPjxwIGNsYXNzPVwibGFuZGluZy1wYWdlLS1zdWJ0aXRsZVwiPkkgZG8gY29tcGlsZXJzIGFuZCBsYW5ndWFnZXMuXG5JbnRlcmVzdGVkIGluIHN5c3RlbXMgZGVzaWduIGFuZCBVWC48L3A+XG48YnV0dG9uIG9uOmNsaWNrPXtoYW5kbGVDbGlja30+XG4gICAgcmVzcG9uc2U6IHtyZXNwb25zZX1cbjwvYnV0dG9uPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQXVEbUIsbUJBQW1CLGVBQUMsQ0FBQyxBQUN0QyxLQUFLLENBQUUsR0FBRyxDQUNWLE1BQU0sQ0FBRSxJQUFJLENBQUMsSUFBSSxDQUNqQixPQUFPLENBQUUsS0FBSyxDQUNkLGdCQUFnQixDQUFFLElBQUksUUFBUSxDQUFDLENBQy9CLGVBQWUsQ0FBRSxLQUFLLENBQ3RCLEtBQUssQ0FBRSxLQUFLLENBQ1osTUFBTSxDQUFFLEtBQUssQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var t0, div, p0, t1, p1, t2, t3, button, t4, t5, dispose;

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Marcus Mathiassen");
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I do compilers and languages.\nInterested in systems design and UX.");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("response: ");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.response);
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Marcus Mathiassen");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "I do compilers and languages.\nInterested in systems design and UX.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "BUTTON", {}, false);
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button_nodes, "response: ");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button_nodes, ctx.response);
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Home";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div, "class", "landing-page--hero svelte-1jn40vy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 70, 0, 2361);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p0, "class", "landing-page--title");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 70, 38, 2399);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p1, "class", "landing-page--subtitle");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 70, 90, 2451);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 72, 0, 2556);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(button, "click", ctx.handleClick);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, button, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(button, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(button, t5);
		},

		p: function update(changed, ctx) {
			if (changed.response) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t5, ctx.response);
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p1);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t3);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(button);
			}

			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let response = ""


    //    fetch(`https://api.github.com/graphql`, {
    //     method: 'post',
    //     headers: {
    //         Authorization: `bearer ${process.env.GITHUB_TOKEN}`,
    //         'Content-Type': 'application/json',
    //     },
    //     body: JSON.stringify({
    //         query: `query { viewer { repositories(first: 20) { edges { node { name pushedAt } } } } }`,
    //     }),
    // })
    //     .then(res => res.json())
    //     .then(json => {
    //         var edges = json.data.viewer.repositories.edges
    //         // Sort the repositories by pushdate
    //         edges.sort((a, b) => {
    //             return (
    //                 new Date(b.node.pushedAt).getTime() -
    //                 new Date(a.node.pushedAt).getTime()
    //             )
    //         })
    //         const nameOfLastRepoUpdated = edges[0].node.name
    //         fetch(`https://api.github.com/graphql`, {
    //             method: 'post',
    //             headers: {
    //                 Authorization:
    //                     `bearer ${process.env.GITHUB_TOKEN}`,
    //                 'Content-Type': 'application/json',
    //             },
    //             body: JSON.stringify({
    //                 query: `query { viewer { repository(name:"${nameOfLastRepoUpdated}") { description } } }`,
    //             }),
    //         })
    //             .then(res => res.json())
    //             .then(json => {
    //                 console.log(json)
    //                 const desc = json.data.viewer.repository.description
    //                 // $(
    //                 //     '#last-repo-updated'
    //                 // ).innerHTML = `Currently working on <h1>${nameOfLastRepoUpdated}</h1> <p>${desc}</p>`
    //             })
    //     })

    function handleClick(event) {
        fetch("/.netlify/functions/hello-world").then(res => res.text()).then(text => {
                $$invalidate('response', response = text)
            })
    }

	return { response, handleClick };
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1jn40vy-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lFQXlFZSxRQUFROzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2RkFBUixRQUFROzs7Ozs7Ozs7Ozs7OztpR0FETCxXQUFXOzs7Ozs7Ozs7Ozs7Ozs7Ozs7NkVBQ2QsUUFBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Q0F0RW5CLElBQUksUUFBUSxHQUFHLEVBQUU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQTZDakIsU0FBUyxXQUFXLENBQUMsS0FBSyxFQUFFO1FBQ3hCLEtBQUssQ0FBQyxpQ0FBaUMsQ0FBQyxDQUFDLElBQUksQ0FBQyxHQUFHLElBQUksR0FBRyxDQUFDLElBQUksRUFBRSxDQUFDLENBQUMsSUFBSSxDQUFDLElBQUksSUFBSTt5Q0FDdEUsUUFBUSxHQUFHLEtBQUk7YUFDbEIsQ0FBQztLQUNUIiwiZmlsZSI6ImEzZWRjNTViNDNlYTJjN2Y5Y2VlL2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcblxuICAgIGxldCByZXNwb25zZSA9IFwiXCJcblxuXG4gICAgLy8gICAgZmV0Y2goYGh0dHBzOi8vYXBpLmdpdGh1Yi5jb20vZ3JhcGhxbGAsIHtcbiAgICAvLyAgICAgbWV0aG9kOiAncG9zdCcsXG4gICAgLy8gICAgIGhlYWRlcnM6IHtcbiAgICAvLyAgICAgICAgIEF1dGhvcml6YXRpb246IGBiZWFyZXIgJHtwcm9jZXNzLmVudi5HSVRIVUJfVE9LRU59YCxcbiAgICAvLyAgICAgICAgICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicsXG4gICAgLy8gICAgIH0sXG4gICAgLy8gICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHtcbiAgICAvLyAgICAgICAgIHF1ZXJ5OiBgcXVlcnkgeyB2aWV3ZXIgeyByZXBvc2l0b3JpZXMoZmlyc3Q6IDIwKSB7IGVkZ2VzIHsgbm9kZSB7IG5hbWUgcHVzaGVkQXQgfSB9IH0gfSB9YCxcbiAgICAvLyAgICAgfSksXG4gICAgLy8gfSlcbiAgICAvLyAgICAgLnRoZW4ocmVzID0+IHJlcy5qc29uKCkpXG4gICAgLy8gICAgIC50aGVuKGpzb24gPT4ge1xuICAgIC8vICAgICAgICAgdmFyIGVkZ2VzID0ganNvbi5kYXRhLnZpZXdlci5yZXBvc2l0b3JpZXMuZWRnZXNcbiAgICAvLyAgICAgICAgIC8vIFNvcnQgdGhlIHJlcG9zaXRvcmllcyBieSBwdXNoZGF0ZVxuICAgIC8vICAgICAgICAgZWRnZXMuc29ydCgoYSwgYikgPT4ge1xuICAgIC8vICAgICAgICAgICAgIHJldHVybiAoXG4gICAgLy8gICAgICAgICAgICAgICAgIG5ldyBEYXRlKGIubm9kZS5wdXNoZWRBdCkuZ2V0VGltZSgpIC1cbiAgICAvLyAgICAgICAgICAgICAgICAgbmV3IERhdGUoYS5ub2RlLnB1c2hlZEF0KS5nZXRUaW1lKClcbiAgICAvLyAgICAgICAgICAgICApXG4gICAgLy8gICAgICAgICB9KVxuICAgIC8vICAgICAgICAgY29uc3QgbmFtZU9mTGFzdFJlcG9VcGRhdGVkID0gZWRnZXNbMF0ubm9kZS5uYW1lXG4gICAgLy8gICAgICAgICBmZXRjaChgaHR0cHM6Ly9hcGkuZ2l0aHViLmNvbS9ncmFwaHFsYCwge1xuICAgIC8vICAgICAgICAgICAgIG1ldGhvZDogJ3Bvc3QnLFxuICAgIC8vICAgICAgICAgICAgIGhlYWRlcnM6IHtcbiAgICAvLyAgICAgICAgICAgICAgICAgQXV0aG9yaXphdGlvbjpcbiAgICAvLyAgICAgICAgICAgICAgICAgICAgIGBiZWFyZXIgJHtwcm9jZXNzLmVudi5HSVRIVUJfVE9LRU59YCxcbiAgICAvLyAgICAgICAgICAgICAgICAgJ0NvbnRlbnQtVHlwZSc6ICdhcHBsaWNhdGlvbi9qc29uJyxcbiAgICAvLyAgICAgICAgICAgICB9LFxuICAgIC8vICAgICAgICAgICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHtcbiAgICAvLyAgICAgICAgICAgICAgICAgcXVlcnk6IGBxdWVyeSB7IHZpZXdlciB7IHJlcG9zaXRvcnkobmFtZTpcIiR7bmFtZU9mTGFzdFJlcG9VcGRhdGVkfVwiKSB7IGRlc2NyaXB0aW9uIH0gfSB9YCxcbiAgICAvLyAgICAgICAgICAgICB9KSxcbiAgICAvLyAgICAgICAgIH0pXG4gICAgLy8gICAgICAgICAgICAgLnRoZW4ocmVzID0+IHJlcy5qc29uKCkpXG4gICAgLy8gICAgICAgICAgICAgLnRoZW4oanNvbiA9PiB7XG4gICAgLy8gICAgICAgICAgICAgICAgIGNvbnNvbGUubG9nKGpzb24pXG4gICAgLy8gICAgICAgICAgICAgICAgIGNvbnN0IGRlc2MgPSBqc29uLmRhdGEudmlld2VyLnJlcG9zaXRvcnkuZGVzY3JpcHRpb25cbiAgICAvLyAgICAgICAgICAgICAgICAgLy8gJChcbiAgICAvLyAgICAgICAgICAgICAgICAgLy8gICAgICcjbGFzdC1yZXBvLXVwZGF0ZWQnXG4gICAgLy8gICAgICAgICAgICAgICAgIC8vICkuaW5uZXJIVE1MID0gYEN1cnJlbnRseSB3b3JraW5nIG9uIDxoMT4ke25hbWVPZkxhc3RSZXBvVXBkYXRlZH08L2gxPiA8cD4ke2Rlc2N9PC9wPmBcbiAgICAvLyAgICAgICAgICAgICB9KVxuICAgIC8vICAgICB9KVxuXG4gICAgZnVuY3Rpb24gaGFuZGxlQ2xpY2soZXZlbnQpIHtcbiAgICAgICAgZmV0Y2goXCIvLm5ldGxpZnkvZnVuY3Rpb25zL2hlbGxvLXdvcmxkXCIpLnRoZW4ocmVzID0+IHJlcy50ZXh0KCkpLnRoZW4odGV4dCA9PiB7XG4gICAgICAgICAgICAgICAgcmVzcG9uc2UgPSB0ZXh0XG4gICAgICAgICAgICB9KVxuICAgIH1cbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4ubGFuZGluZy1wYWdlLS1oZXJvIHtcbiAgd2lkdGg6IDUwJTtcbiAgbWFyZ2luOiAyMHB4IGF1dG87XG4gIGRpc3BsYXk6IGJsb2NrO1xuICBiYWNrZ3JvdW5kLWltYWdlOiB2YXIoLS1hdmF0YXIpO1xuICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICB3aWR0aDogMzAwcHg7XG4gIGhlaWdodDogMzAwcHg7IH1cblxuLyojIHNvdXJjZU1hcHBpbmdVUkw9aW5kZXguc3ZlbHRlLmNzcy5tYXAgKi88L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gICAgPHRpdGxlPkhvbWU8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPGRpdiBjbGFzcz1cImxhbmRpbmctcGFnZS0taGVyb1wiPjwvZGl2PjxwIGNsYXNzPVwibGFuZGluZy1wYWdlLS10aXRsZVwiPk1hcmN1cyBNYXRoaWFzc2VuPC9wPjxwIGNsYXNzPVwibGFuZGluZy1wYWdlLS1zdWJ0aXRsZVwiPkkgZG8gY29tcGlsZXJzIGFuZCBsYW5ndWFnZXMuXG5JbnRlcmVzdGVkIGluIHN5c3RlbXMgZGVzaWduIGFuZCBVWC48L3A+XG48YnV0dG9uIG9uOmNsaWNrPXtoYW5kbGVDbGlja30+XG4gICAgcmVzcG9uc2U6IHtyZXNwb25zZX1cbjwvYnV0dG9uPlxuIl0sInNvdXJjZVJvb3QiOiIifQ==