(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_p2d_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/p2d.svelte */ "./src/components/p2d.svelte");
/* src/routes/index.svelte generated by Svelte v3.9.2 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-5g0esb-style';
	style.textContent = ":root{--apple_retro_green:#61bb46;--apple_retro_yellow:#fdb827;--apple_retro_orange:#f5821f;--apple_retro_red:#e03a3e;--apple_retro_purple:#963d97;--apple_blue:rgb(64, 156, 255);--apple_gray:rgb(152, 152, 157);--apple_green:rgb(48, 219, 91);--apple_indigo:rgb(125, 122, 255);--apple_orange:rgb(255, 179, 64);--apple_pink:rgb(255, 100, 130);--apple_purple:rgb(218, 143, 255);--apple_red:rgb(255, 105, 97);--apple_teal:rgb(112, 215, 255);--apple_yellow:rgb(255, 212, 38);--c_blue:#247ba0;--c_white:#faf1d8;--c_pink:#dd7373;--c_black:#3e4e50;--c_warm_black:#02394a;--c_black_olive:#393d3f;--c_orange:#f79d65;--c_turq:#69d1c5;--c_almond:#eed7c5;--c_cadedblue:#5c9ead;--c_carib_green:#02c39a;--storage:#5c9ead;--literal:#02c39a;--comment:#f79d65;--keyword:rgb(255, 100, 130);--compile_time_resolved:rgb(125, 122, 255);--font:'pxplus_ibm_vga8regular';--text:#3e4e50;--background:#f8f0da;--text-color--normal:var(--text);--text-color--light:#3e4e50;--text-color--richer:#3e4e50;--text-color--highlight:rgb(255, 100, 130)}@media(prefers-color-scheme: light){:root{--text-color--normal:var(--text);--text-color--light:var(--c_black);--text-color--richer:var(--c_black);--text-color--highlight:var(--keyword);--text-color--comment:var(--comment);--background--content:rgb(255, 255, 255);--background:#f8f0da;--background-color--selection:yellow}}@media(prefers-color-scheme: dark){:root{--text-color--normal:var(--c_white);--text-color--light:var(--c_white);--text-color--richer:var(--c_white);--text-color--highlight:var(--apple_pink);--text-color--comment:var(--comment);--background--content:rgb(30, 30, 30);--background:#000;--background-color--selection:var(--apple_pink)}}*{color:var(--text);background:var(--background);font-family:var(--font);text-align:center;line-height:1.5;font-size:1em}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gICAgOmdsb2JhbCg6cm9vdCkge1xuICAgICAgICAtLWFwcGxlX3JldHJvX2dyZWVuOiAjNjFiYjQ2O1xuICAgICAgICAtLWFwcGxlX3JldHJvX3llbGxvdzogI2ZkYjgyNztcbiAgICAgICAgLS1hcHBsZV9yZXRyb19vcmFuZ2U6ICNmNTgyMWY7XG4gICAgICAgIC0tYXBwbGVfcmV0cm9fcmVkOiAjZTAzYTNlO1xuICAgICAgICAtLWFwcGxlX3JldHJvX3B1cnBsZTogIzk2M2Q5NztcbiAgICAgICAgLS1hcHBsZV9ibHVlOiByZ2IoNjQsIDE1NiwgMjU1KTtcbiAgICAgICAgLS1hcHBsZV9ncmF5OiByZ2IoMTUyLCAxNTIsIDE1Nyk7XG4gICAgICAgIC0tYXBwbGVfZ3JlZW46IHJnYig0OCwgMjE5LCA5MSk7XG4gICAgICAgIC0tYXBwbGVfaW5kaWdvOiByZ2IoMTI1LCAxMjIsIDI1NSk7XG4gICAgICAgIC0tYXBwbGVfb3JhbmdlOiByZ2IoMjU1LCAxNzksIDY0KTtcbiAgICAgICAgLS1hcHBsZV9waW5rOiByZ2IoMjU1LCAxMDAsIDEzMCk7XG4gICAgICAgIC0tYXBwbGVfcHVycGxlOiByZ2IoMjE4LCAxNDMsIDI1NSk7XG4gICAgICAgIC0tYXBwbGVfcmVkOiByZ2IoMjU1LCAxMDUsIDk3KTtcbiAgICAgICAgLS1hcHBsZV90ZWFsOiByZ2IoMTEyLCAyMTUsIDI1NSk7XG4gICAgICAgIC0tYXBwbGVfeWVsbG93OiByZ2IoMjU1LCAyMTIsIDM4KTtcbiAgICAgICAgLS1jX2JsdWU6ICMyNDdiYTA7XG4gICAgICAgIC0tY193aGl0ZTogI2ZhZjFkODtcbiAgICAgICAgLS1jX3Bpbms6ICNkZDczNzM7XG4gICAgICAgIC0tY19ibGFjazogIzNlNGU1MDtcbiAgICAgICAgLS1jX3dhcm1fYmxhY2s6ICMwMjM5NGE7XG4gICAgICAgIC0tY19ibGFja19vbGl2ZTogIzM5M2QzZjtcbiAgICAgICAgLS1jX29yYW5nZTogI2Y3OWQ2NTtcbiAgICAgICAgLS1jX3R1cnE6ICM2OWQxYzU7XG4gICAgICAgIC0tY19hbG1vbmQ6ICNlZWQ3YzU7XG4gICAgICAgIC0tY19jYWRlZGJsdWU6ICM1YzllYWQ7XG4gICAgICAgIC0tY19jYXJpYl9ncmVlbjogIzAyYzM5YTtcblxuICAgICAgICAtLXN0b3JhZ2U6ICM1YzllYWQ7XG4gICAgICAgIC0tbGl0ZXJhbDogIzAyYzM5YTtcbiAgICAgICAgLS1jb21tZW50OiAjZjc5ZDY1O1xuICAgICAgICAtLWtleXdvcmQ6IHJnYigyNTUsIDEwMCwgMTMwKTtcbiAgICAgICAgLS1jb21waWxlX3RpbWVfcmVzb2x2ZWQ6IHJnYigxMjUsIDEyMiwgMjU1KTtcblxuICAgICAgICAtLWZvbnQ6ICdweHBsdXNfaWJtX3ZnYThyZWd1bGFyJztcbiAgICAgICAgLS10ZXh0OiAjM2U0ZTUwO1xuICAgICAgICAtLWJhY2tncm91bmQ6ICNmOGYwZGE7XG5cbiAgICAgICAgLS10ZXh0LWNvbG9yLS1ub3JtYWw6IHZhcigtLXRleHQpO1xuICAgICAgICAtLXRleHQtY29sb3ItLWxpZ2h0OiAjM2U0ZTUwO1xuICAgICAgICAtLXRleHQtY29sb3ItLXJpY2hlcjogIzNlNGU1MDtcbiAgICAgICAgLS10ZXh0LWNvbG9yLS1oaWdobGlnaHQ6IHJnYigyNTUsIDEwMCwgMTMwKTtcbiAgICB9XG5cbiAgICBAbWVkaWEgKHByZWZlcnMtY29sb3Itc2NoZW1lOiBsaWdodCkge1xuICAgICAgICA6cm9vdCB7XG4gICAgICAgICAgICAtLXRleHQtY29sb3ItLW5vcm1hbDogdmFyKC0tdGV4dCk7XG4gICAgICAgICAgICAtLXRleHQtY29sb3ItLWxpZ2h0OiB2YXIoLS1jX2JsYWNrKTtcbiAgICAgICAgICAgIC0tdGV4dC1jb2xvci0tcmljaGVyOiB2YXIoLS1jX2JsYWNrKTtcbiAgICAgICAgICAgIC0tdGV4dC1jb2xvci0taGlnaGxpZ2h0OiB2YXIoLS1rZXl3b3JkKTtcbiAgICAgICAgICAgIC0tdGV4dC1jb2xvci0tY29tbWVudDogdmFyKC0tY29tbWVudCk7XG4gICAgICAgICAgICAtLWJhY2tncm91bmQtLWNvbnRlbnQ6IHJnYigyNTUsIDI1NSwgMjU1KTtcbiAgICAgICAgICAgIC0tYmFja2dyb3VuZDogI2Y4ZjBkYTtcbiAgICAgICAgICAgIC0tYmFja2dyb3VuZC1jb2xvci0tc2VsZWN0aW9uOiB5ZWxsb3c7XG4gICAgICAgIH1cbiAgICB9XG5cbiAgICBAbWVkaWEgKHByZWZlcnMtY29sb3Itc2NoZW1lOiBkYXJrKSB7XG4gICAgICAgIDpyb290IHtcbiAgICAgICAgICAgIC0tdGV4dC1jb2xvci0tbm9ybWFsOiB2YXIoLS1jX3doaXRlKTtcbiAgICAgICAgICAgIC0tdGV4dC1jb2xvci0tbGlnaHQ6IHZhcigtLWNfd2hpdGUpO1xuICAgICAgICAgICAgLS10ZXh0LWNvbG9yLS1yaWNoZXI6IHZhcigtLWNfd2hpdGUpO1xuICAgICAgICAgICAgLS10ZXh0LWNvbG9yLS1oaWdobGlnaHQ6IHZhcigtLWFwcGxlX3BpbmspO1xuICAgICAgICAgICAgLS10ZXh0LWNvbG9yLS1jb21tZW50OiB2YXIoLS1jb21tZW50KTtcbiAgICAgICAgICAgIC0tYmFja2dyb3VuZC0tY29udGVudDogcmdiKDMwLCAzMCwgMzApO1xuICAgICAgICAgICAgLS1iYWNrZ3JvdW5kOiAjMDAwO1xuICAgICAgICAgICAgLS1iYWNrZ3JvdW5kLWNvbG9yLS1zZWxlY3Rpb246IHZhcigtLWFwcGxlX3BpbmspO1xuICAgICAgICB9XG4gICAgfVxuXG4gICAgOmdsb2JhbCgqKSB7XG4gICAgICAgIGNvbG9yOiB2YXIoLS10ZXh0KTtcbiAgICAgICAgYmFja2dyb3VuZDogdmFyKC0tYmFja2dyb3VuZCk7XG4gICAgICAgIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250KTtcbiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgICBsaW5lLWhlaWdodDogMS41O1xuICAgICAgICBmb250LXNpemU6IDFlbTtcbiAgICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gICAgPHRpdGxlPkhvbWU8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cbjxkaXYgY2xhc3M9XCIubGFuZGluZy1wYWdlLS1oZXJvIHN3YXBPbkhvdmVyXCI+XG4gICAgPGltZyBzcmM9XCJhdmF0YXJfcGl4ZWxhdGVkLmpwZ1wiIGFsdD1cInBpY3R1cmUgb2YgbWVcIiAvPlxuICAgIDxpbWcgc3JjPVwiYXZhdGFyLnBuZ1wiIGFsdD1cInBpY3R1cmUgb2YgbWVcIiAvPlxuPC9kaXY+XG48cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tdGl0bGVcIj5NYXJjdXMgTWF0aGlhc3NlbjwvcD5cbjxwIGNsYXNzPVwibGFuZGluZy1wYWdlLS1zdWJ0aXRsZVwiPlxuICAgIEkgZG8gY29tcGlsZXJzIGFuZCBsYW5ndWFnZXMuXG4gICAgPGJyIC8+XG4gICAgSW50ZXJlc3RlZCBpbiBzeXN0ZW1zIGRlc2lnbiBhbmQgVVguXG48L3A+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBS1ksS0FBSyxBQUFFLENBQUMsQUFDWixtQkFBbUIsQ0FBRSxPQUFPLENBQzVCLG9CQUFvQixDQUFFLE9BQU8sQ0FDN0Isb0JBQW9CLENBQUUsT0FBTyxDQUM3QixpQkFBaUIsQ0FBRSxPQUFPLENBQzFCLG9CQUFvQixDQUFFLE9BQU8sQ0FDN0IsWUFBWSxDQUFFLGlCQUFpQixDQUMvQixZQUFZLENBQUUsa0JBQWtCLENBQ2hDLGFBQWEsQ0FBRSxnQkFBZ0IsQ0FDL0IsY0FBYyxDQUFFLGtCQUFrQixDQUNsQyxjQUFjLENBQUUsaUJBQWlCLENBQ2pDLFlBQVksQ0FBRSxrQkFBa0IsQ0FDaEMsY0FBYyxDQUFFLGtCQUFrQixDQUNsQyxXQUFXLENBQUUsaUJBQWlCLENBQzlCLFlBQVksQ0FBRSxrQkFBa0IsQ0FDaEMsY0FBYyxDQUFFLGlCQUFpQixDQUNqQyxRQUFRLENBQUUsT0FBTyxDQUNqQixTQUFTLENBQUUsT0FBTyxDQUNsQixRQUFRLENBQUUsT0FBTyxDQUNqQixTQUFTLENBQUUsT0FBTyxDQUNsQixjQUFjLENBQUUsT0FBTyxDQUN2QixlQUFlLENBQUUsT0FBTyxDQUN4QixVQUFVLENBQUUsT0FBTyxDQUNuQixRQUFRLENBQUUsT0FBTyxDQUNqQixVQUFVLENBQUUsT0FBTyxDQUNuQixhQUFhLENBQUUsT0FBTyxDQUN0QixlQUFlLENBQUUsT0FBTyxDQUV4QixTQUFTLENBQUUsT0FBTyxDQUNsQixTQUFTLENBQUUsT0FBTyxDQUNsQixTQUFTLENBQUUsT0FBTyxDQUNsQixTQUFTLENBQUUsa0JBQWtCLENBQzdCLHVCQUF1QixDQUFFLGtCQUFrQixDQUUzQyxNQUFNLENBQUUsd0JBQXdCLENBQ2hDLE1BQU0sQ0FBRSxPQUFPLENBQ2YsWUFBWSxDQUFFLE9BQU8sQ0FFckIsb0JBQW9CLENBQUUsV0FBVyxDQUNqQyxtQkFBbUIsQ0FBRSxPQUFPLENBQzVCLG9CQUFvQixDQUFFLE9BQU8sQ0FDN0IsdUJBQXVCLENBQUUsa0JBQWtCLEFBQy9DLENBQUMsQUFFRCxNQUFNLEFBQUMsdUJBQXVCLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDbEMsS0FBSyxBQUFDLENBQUMsQUFDSCxvQkFBb0IsQ0FBRSxXQUFXLENBQ2pDLG1CQUFtQixDQUFFLGNBQWMsQ0FDbkMsb0JBQW9CLENBQUUsY0FBYyxDQUNwQyx1QkFBdUIsQ0FBRSxjQUFjLENBQ3ZDLHFCQUFxQixDQUFFLGNBQWMsQ0FDckMscUJBQXFCLENBQUUsa0JBQWtCLENBQ3pDLFlBQVksQ0FBRSxPQUFPLENBQ3JCLDZCQUE2QixDQUFFLE1BQU0sQUFDekMsQ0FBQyxBQUNMLENBQUMsQUFFRCxNQUFNLEFBQUMsdUJBQXVCLElBQUksQ0FBQyxBQUFDLENBQUMsQUFDakMsS0FBSyxBQUFDLENBQUMsQUFDSCxvQkFBb0IsQ0FBRSxjQUFjLENBQ3BDLG1CQUFtQixDQUFFLGNBQWMsQ0FDbkMsb0JBQW9CLENBQUUsY0FBYyxDQUNwQyx1QkFBdUIsQ0FBRSxpQkFBaUIsQ0FDMUMscUJBQXFCLENBQUUsY0FBYyxDQUNyQyxxQkFBcUIsQ0FBRSxlQUFlLENBQ3RDLFlBQVksQ0FBRSxJQUFJLENBQ2xCLDZCQUE2QixDQUFFLGlCQUFpQixBQUNwRCxDQUFDLEFBQ0wsQ0FBQyxBQUVPLENBQUMsQUFBRSxDQUFDLEFBQ1IsS0FBSyxDQUFFLElBQUksTUFBTSxDQUFDLENBQ2xCLFVBQVUsQ0FBRSxJQUFJLFlBQVksQ0FBQyxDQUM3QixXQUFXLENBQUUsSUFBSSxNQUFNLENBQUMsQ0FDeEIsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsU0FBUyxDQUFFLEdBQUcsQUFDbEIsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var t0, div, img0, t1, img1, t2, p0, t3, t4, p1, t5, br, t6;

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Marcus Mathiassen");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I do compilers and languages.\n    ");
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    Interested in systems design and UX.");
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "IMG", { src: true, alt: true, class: true }, false);
			var img0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img0);

			img0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div_nodes, "\n    ");

			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "IMG", { src: true, alt: true, class: true }, false);
			var img1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img1);

			img1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Marcus Mathiassen");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "I do compilers and languages.\n    ");

			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "BR", { class: true }, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n    Interested in systems design and UX.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Home";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img0, "src", "avatar_pixelated.jpg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img0, "alt", "picture of me");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img0, "class", "svelte-5g0esb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img0, file, 89, 4, 2753);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img1, "src", "avatar.png");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img1, "alt", "picture of me");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img1, "class", "svelte-5g0esb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img1, file, 90, 4, 2812);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div, "class", ".landing-page--hero swapOnHover svelte-5g0esb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 88, 0, 2703);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p0, "class", "landing-page--title svelte-5g0esb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 92, 0, 2864);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(br, "class", "svelte-5g0esb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 95, 4, 2990);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p1, "class", "landing-page--subtitle svelte-5g0esb");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 93, 0, 2917);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, img0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, img1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t4, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, br);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t6);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t4);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p1);
			}
		}
	};
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-5g0esb-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJiMmVlZDk5NDZjOGY2OTlhY2UyZS9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbXSwic291cmNlUm9vdCI6IiJ9