(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_p2d_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/p2d.svelte */ "./src/components/p2d.svelte");
/* src/routes/index.svelte generated by Svelte v3.9.2 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-11fqv6n-style';
	style.textContent = ".landing-page--hero.svelte-11fqv6n{width:50%;margin:20px auto;display:block;background-image:var(--avatar);background-size:cover;width:300px;height:300px}li.svelte-11fqv6n,ul.svelte-11fqv6n{margin:5px;margin-top:10px;list-style-type:none}span.svelte-11fqv6n{font-family:var(--font)}.repos.svelte-11fqv6n{margin:0 auto;width:50%;padding:0}.repos.svelte-11fqv6n h2.svelte-11fqv6n{margin:5px;padding:5px;text-align:left;font-weight:500}.repo.svelte-11fqv6n{margin:5px;padding:5px;border-radius:5px;text-align:left}.repo--name.svelte-11fqv6n{font-size:1em;padding:0;margin:0}.repo--badges.svelte-11fqv6n{margin:5px;padding:5px;border-radius:5px;border:1px solid rgba(var(--text-base), 0.1);font-size:0.75em}.repo--badges.svelte-11fqv6n span.svelte-11fqv6n{margin:2px}.repo--langauge.svelte-11fqv6n{font-size:1em}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcbiAgICBsZXQgcmVwb3NcbiAgICAvLyBmZXRjaChcIi8ubmV0bGlmeS9mdW5jdGlvbnMvZ2l0aHViXCIpLnRoZW4ocmVzID0+IHJlcy5qc29uKCkpLnRoZW4oanNvbiA9PiB7XG4gICAgLy8gICAgIHJlcG9zID0ganNvblxuICAgIC8vIH0pXG5cbiAgICByZXBvcyA9IFtcbiAgICB7XG4gICAgICAgIFwiZm9ya0NvdW50XCI6IDI3LFxuICAgICAgICBcInVybFwiOiBcImJsdWVcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiTGV0aWNpYSBIYW5zZW5cIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiSmF2YVNjcmlwdFwiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiMwMGY1XCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAzMFxuICAgICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiZm9ya0NvdW50XCI6IDQwLFxuICAgICAgICBcInVybFwiOiBcImJyb3duXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIkNhbmR5IFZhc3F1ZXpcIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4gICAgICAgICAgICBcImNvbG9yXCI6IFwiI2ZmMDFcIlxuICAgICAgICB9LFxuICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDI2XG4gICAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJmb3JrQ291bnRcIjogMzYsXG4gICAgICAgIFwidXJsXCI6IFwiZ3JlZW5cIixcbiAgICAgICAgXCJuYW1lXCI6IFwiTGFtYiBKb2huc29uXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmMDA3XCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyNFxuICAgICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiZm9ya0NvdW50XCI6IDIzLFxuICAgICAgICBcInVybFwiOiBcImJsdWVcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiU29sb21vbiBNZWRpbmFcIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4gICAgICAgICAgICBcImNvbG9yXCI6IFwiI2YwMGZcIlxuICAgICAgICB9LFxuICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDM5XG4gICAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJmb3JrQ291bnRcIjogMjYsXG4gICAgICAgIFwidXJsXCI6IFwiYmx1ZVwiLFxuICAgICAgICBcIm5hbWVcIjogXCJSaWNobW9uZCBIZXNzXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjAzXCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyNFxuICAgICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiZm9ya0NvdW50XCI6IDM4LFxuICAgICAgICBcInVybFwiOiBcImdyZWVuXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlNwZW5jZXIgQnVzaFwiLFxuICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4gICAgICAgICAgICBcIm5hbWVcIjogXCJDKytcIixcbiAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZmYwNFwiXG4gICAgICAgIH0sXG4gICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4gICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMzNcbiAgICAgICAgfVxuICAgIH0sXG4gICAge1xuICAgICAgICBcImZvcmtDb3VudFwiOiAyMixcbiAgICAgICAgXCJ1cmxcIjogXCJncmVlblwiLFxuICAgICAgICBcIm5hbWVcIjogXCJIYW1tb25kIE1hbm5cIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiSmF2YVNjcmlwdFwiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjA2XCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyMlxuICAgICAgICB9XG4gICAgfVxuXVxuXG48L3NjcmlwdD5cblxuPHN0eWxlIGxhbmc9XCJzYXNzXCI+LmxhbmRpbmctcGFnZS0taGVybyB7XG4gIHdpZHRoOiA1MCU7XG4gIG1hcmdpbjogMjBweCBhdXRvO1xuICBkaXNwbGF5OiBibG9jaztcbiAgYmFja2dyb3VuZC1pbWFnZTogdmFyKC0tYXZhdGFyKTtcbiAgYmFja2dyb3VuZC1zaXplOiBjb3ZlcjtcbiAgd2lkdGg6IDMwMHB4O1xuICBoZWlnaHQ6IDMwMHB4OyB9XG5cbmxpLCB1bCB7XG4gIG1hcmdpbjogNXB4O1xuICBtYXJnaW4tdG9wOiAxMHB4O1xuICBsaXN0LXN0eWxlLXR5cGU6IG5vbmU7IH1cblxuc3BhbiB7XG4gIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250KTsgfVxuXG4ucmVwb3Mge1xuICBtYXJnaW46IDAgYXV0bztcbiAgd2lkdGg6IDUwJTtcbiAgcGFkZGluZzogMDsgfVxuICAucmVwb3MgaDIge1xuICAgIG1hcmdpbjogNXB4O1xuICAgIHBhZGRpbmc6IDVweDtcbiAgICB0ZXh0LWFsaWduOiBsZWZ0O1xuICAgIGZvbnQtd2VpZ2h0OiA1MDA7IH1cblxuLnJlcG8ge1xuICBtYXJnaW46IDVweDtcbiAgcGFkZGluZzogNXB4O1xuICBib3JkZXItcmFkaXVzOiA1cHg7XG4gIHRleHQtYWxpZ246IGxlZnQ7IH1cblxuLnJlcG8tLW5hbWUge1xuICBmb250LXNpemU6IDFlbTtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwOyB9XG5cbi5yZXBvLS1iYWRnZXMge1xuICBtYXJnaW46IDVweDtcbiAgcGFkZGluZzogNXB4O1xuICBib3JkZXItcmFkaXVzOiA1cHg7XG4gIGJvcmRlcjogMXB4IHNvbGlkIHJnYmEodmFyKC0tdGV4dC1iYXNlKSwgMC4xKTtcbiAgZm9udC1zaXplOiAwLjc1ZW07IH1cbiAgLnJlcG8tLWJhZGdlcyBzcGFuIHtcbiAgICBtYXJnaW46IDJweDsgfVxuXG4ucmVwby0tbGFuZ2F1Z2Uge1xuICBmb250LXNpemU6IDFlbTsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgICA8dGl0bGU+SG9tZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48ZGl2IGNsYXNzPVwibGFuZGluZy1wYWdlLS1oZXJvXCI+PC9kaXY+PHAgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLXRpdGxlXCI+TWFyY3VzIE1hdGhpYXNzZW48L3A+PHAgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLXN1YnRpdGxlXCI+SSBkbyBjb21waWxlcnMgYW5kIGxhbmd1YWdlcy5cbkludGVyZXN0ZWQgaW4gc3lzdGVtcyBkZXNpZ24gYW5kIFVYLjwvcD5cbjxicj5cbjx1bCBjbGFzcz1cInJlcG9zXCI+XG4gICAgPGgyPlJlcG9zaXRvcmllczwvaDI+XG5cdHsjZWFjaCByZXBvcyBhcyByZXBvfVxuICAgICAgICA8bGkgY2xhc3M9XCJyZXBvXCI+XG4gICAgICAgICAgICA8YSBocmVmPVwie3JlcG8udXJsfVwiIHRhcmdldD1cIl9ibGFua1wiIHJlbD1cIm5vb3BlbmVyXCI+XG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLW5hbWVcIj57cmVwby5uYW1lfSA8L3NwYW4+XG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLWJhZGdlc1wiIHN0eWxlPVwiYmFja2dyb3VuZDp7cmVwby5wcmltYXJ5TGFuZ3VhZ2UuY29sb3Iuc3Vic3RyaW5nKDAsIHJlcG8ucHJpbWFyeUxhbmd1YWdlLmNvbG9yLmxlbmd0aCAtIDEpXG4gICAgICAgICAgICB9NVwiPlxuICAgICAgICAgICAgeyNpZiByZXBvLnByaW1hcnlMYW5ndWFnZX1cbiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLWxhbmdhdWdlXCI+IHtyZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lfTwvc3Bhbj5cbiAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICB7I2lmIHJlcG8uc3RhcmdhemVycy50b3RhbENvdW50fVxuICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1zdGFyXCI+XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuPntyZXBvLnN0YXJnYXplcnMudG90YWxDb3VudH08L3NwYW4+PC9pPlxuICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICB7I2lmIHJlcG8uZm9ya0NvdW50fVxuICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1jb2RlLWJyYW5jaFwiPlxuICAgICAgICAgICAgICAgICAgICA8c3Bhbj57cmVwby5mb3JrQ291bnR9PC9zcGFuPjwvaT5cbiAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgPC9hPlxuICAgICAgICA8L2xpPlxuXHR7L2VhY2h9XG48L3VsPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQWdHbUIsbUJBQW1CLGVBQUMsQ0FBQyxBQUN0QyxLQUFLLENBQUUsR0FBRyxDQUNWLE1BQU0sQ0FBRSxJQUFJLENBQUMsSUFBSSxDQUNqQixPQUFPLENBQUUsS0FBSyxDQUNkLGdCQUFnQixDQUFFLElBQUksUUFBUSxDQUFDLENBQy9CLGVBQWUsQ0FBRSxLQUFLLENBQ3RCLEtBQUssQ0FBRSxLQUFLLENBQ1osTUFBTSxDQUFFLEtBQUssQUFBRSxDQUFDLEFBRWxCLGlCQUFFLENBQUUsRUFBRSxlQUFDLENBQUMsQUFDTixNQUFNLENBQUUsR0FBRyxDQUNYLFVBQVUsQ0FBRSxJQUFJLENBQ2hCLGVBQWUsQ0FBRSxJQUFJLEFBQUUsQ0FBQyxBQUUxQixJQUFJLGVBQUMsQ0FBQyxBQUNKLFdBQVcsQ0FBRSxJQUFJLE1BQU0sQ0FBQyxBQUFFLENBQUMsQUFFN0IsTUFBTSxlQUFDLENBQUMsQUFDTixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQ0FDZCxLQUFLLENBQUUsR0FBRyxDQUNWLE9BQU8sQ0FBRSxDQUFDLEFBQUUsQ0FBQyxBQUNiLHFCQUFNLENBQUMsRUFBRSxlQUFDLENBQUMsQUFDVCxNQUFNLENBQUUsR0FBRyxDQUNYLE9BQU8sQ0FBRSxHQUFHLENBQ1osVUFBVSxDQUFFLElBQUksQ0FDaEIsV0FBVyxDQUFFLEdBQUcsQUFBRSxDQUFDLEFBRXZCLEtBQUssZUFBQyxDQUFDLEFBQ0wsTUFBTSxDQUFFLEdBQUcsQ0FDWCxPQUFPLENBQUUsR0FBRyxDQUNaLGFBQWEsQ0FBRSxHQUFHLENBQ2xCLFVBQVUsQ0FBRSxJQUFJLEFBQUUsQ0FBQyxBQUVyQixXQUFXLGVBQUMsQ0FBQyxBQUNYLFNBQVMsQ0FBRSxHQUFHLENBQ2QsT0FBTyxDQUFFLENBQUMsQ0FDVixNQUFNLENBQUUsQ0FBQyxBQUFFLENBQUMsQUFFZCxhQUFhLGVBQUMsQ0FBQyxBQUNiLE1BQU0sQ0FBRSxHQUFHLENBQ1gsT0FBTyxDQUFFLEdBQUcsQ0FDWixhQUFhLENBQUUsR0FBRyxDQUNsQixNQUFNLENBQUUsR0FBRyxDQUFDLEtBQUssQ0FBQyxLQUFLLElBQUksV0FBVyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FDN0MsU0FBUyxDQUFFLE1BQU0sQUFBRSxDQUFDLEFBQ3BCLDRCQUFhLENBQUMsSUFBSSxlQUFDLENBQUMsQUFDbEIsTUFBTSxDQUFFLEdBQUcsQUFBRSxDQUFDLEFBRWxCLGVBQWUsZUFBQyxDQUFDLEFBQ2YsU0FBUyxDQUFFLEdBQUcsQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.repo = list[i];
	return child_ctx;
}

// (164:12) {#if repo.primaryLanguage}
function create_if_block_2(ctx) {
	var span, t_value = ctx.repo.primaryLanguage.name + "", t;

	return {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span, "class", "repo--langauge svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 164, 16, 3558);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.primaryLanguage.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span);
			}
		}
	};
}

// (167:12) {#if repo.stargazers.totalCount}
function create_if_block_1(ctx) {
	var span1, i, span0, t_value = ctx.repo.stargazers.totalCount + "", t;

	return {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(i_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 169, 20, 3773);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(i, "class", "fas fa-star");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 168, 20, 3729);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 167, 16, 3702);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(i, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.stargazers.totalCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span1);
			}
		}
	};
}

// (173:12) {#if repo.forkCount}
function create_if_block(ctx) {
	var span1, i, span0, t_value = ctx.repo.forkCount + "", t;

	return {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(i_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 175, 20, 3988);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(i, "class", "fas fa-code-branch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 174, 20, 3937);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 173, 16, 3910);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(i, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.forkCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span1);
			}
		}
	};
}

// (158:1) {#each repos as repo}
function create_each_block(ctx) {
	var li, a, span0, t0_value = ctx.repo.name + "", t0, t1, span1, t2, t3, a_href_value, t4;

	var if_block0 = (ctx.repo.primaryLanguage) && create_if_block_2(ctx);

	var if_block1 = (ctx.repo.stargazers.totalCount) && create_if_block_1(ctx);

	var if_block2 = (ctx.repo.forkCount) && create_if_block(ctx);

	return {
		c: function create() {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			if (if_block0) if_block0.c();
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "LI", { class: true }, false);
			var li_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "A", { href: true, target: true, rel: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t0_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a_nodes, "\n            ");

			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true, style: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			if (if_block0) if_block0.l(span1_nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n            ");
			if (if_block1) if_block1.l(span1_nodes);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n            ");
			if (if_block2) if_block2.l(span1_nodes);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li_nodes, "\n        ");
			li_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "repo--name svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 160, 12, 3304);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "repo--badges svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span1, "background", "" + ctx.repo.primaryLanguage.color.substring(0, ctx.repo.primaryLanguage.color.length - 1) + "5");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 161, 12, 3361);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "href", a_href_value = ctx.repo.url);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 159, 12, 3239);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(li, "class", "repo svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li, file, 158, 8, 3209);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, li, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, span1);
			if (if_block0) if_block0.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t2);
			if (if_block1) if_block1.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t3);
			if (if_block2) if_block2.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li, t4);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t0_value !== (t0_value = ctx.repo.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, t0_value);
			}

			if (ctx.repo.primaryLanguage) {
				if (if_block0) {
					if_block0.p(changed, ctx);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(span1, t2);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (ctx.repo.stargazers.totalCount) {
				if (if_block1) {
					if_block1.p(changed, ctx);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(span1, t3);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (ctx.repo.forkCount) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(span1, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if (changed.repos) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span1, "background", "" + ctx.repo.primaryLanguage.color.substring(0, ctx.repo.primaryLanguage.color.length - 1) + "5");
			}

			if ((changed.repos) && a_href_value !== (a_href_value = ctx.repo.url)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "href", a_href_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(li);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
		}
	};
}

function create_fragment(ctx) {
	var t0, div, p0, t1, p1, t2, t3, br, t4, ul, h2, t5, t6;

	var each_value = ctx.repos;

	var each_blocks = [];

	for (var i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Marcus Mathiassen");
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I do compilers and languages.\nInterested in systems design and UX.");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Repositories");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Marcus Mathiassen");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "I do compilers and languages.\nInterested in systems design and UX.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "BR", {}, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "H2", { class: true }, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Repositories");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n\t");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Home";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div, "class", "landing-page--hero svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 152, 0, 2933);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p0, "class", "landing-page--title");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 152, 38, 2971);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p1, "class", "landing-page--subtitle");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 152, 90, 3023);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 154, 0, 3128);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h2, "class", "svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 156, 4, 3156);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(ul, "class", "repos svelte-11fqv6n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 155, 0, 3133);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, br, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t4, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, ul, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h2, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t6);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.repos) {
				each_value = ctx.repos;

				for (var i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p1);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t3);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(br);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t4);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(ul);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let repos
    // fetch("/.netlify/functions/github").then(res => res.json()).then(json => {
    //     repos = json
    // })

    $$invalidate('repos', repos = [
    {
        "forkCount": 27,
        "url": "blue",
        "name": "Leticia Hansen",
        "primaryLanguage": {
            "name": "JavaScript",
            "color": "#00f5"
        },
        "stargazers": {
            "totalCount": 30
        }
    },
    {
        "forkCount": 40,
        "url": "brown",
        "name": "Candy Vasquez",
        "primaryLanguage": {
            "name": "C++",
            "color": "#ff01"
        },
        "stargazers": {
            "totalCount": 26
        }
    },
    {
        "forkCount": 36,
        "url": "green",
        "name": "Lamb Johnson",
        "primaryLanguage": {
            "name": "C++",
            "color": "#f007"
        },
        "stargazers": {
            "totalCount": 24
        }
    },
    {
        "forkCount": 23,
        "url": "blue",
        "name": "Solomon Medina",
        "primaryLanguage": {
            "name": "C++",
            "color": "#f00f"
        },
        "stargazers": {
            "totalCount": 39
        }
    },
    {
        "forkCount": 26,
        "url": "blue",
        "name": "Richmond Hess",
        "primaryLanguage": {
            "name": "C++",
            "color": "#ff03"
        },
        "stargazers": {
            "totalCount": 24
        }
    },
    {
        "forkCount": 38,
        "url": "green",
        "name": "Spencer Bush",
        "primaryLanguage": {
            "name": "C++",
            "color": "#ff04"
        },
        "stargazers": {
            "totalCount": 33
        }
    },
    {
        "forkCount": 22,
        "url": "green",
        "name": "Hammond Mann",
        "primaryLanguage": {
            "name": "JavaScript",
            "color": "#ff06"
        },
        "stargazers": {
            "totalCount": 22
        }
    }
])

	return { repos };
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-11fqv6n-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lCQW9LK0MsSUFBSSxDQUFDLGVBQWUsQ0FBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxREFBekIsSUFBSSxDQUFDLGVBQWUsQ0FBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7b0NBSzdDLElBQUksQ0FBQyxVQUFVLENBQUMsVUFBVTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FEQUExQixJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7OztvQ0FNMUIsSUFBSSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxREFBZCxJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7O2tDQWZILElBQUksQ0FBQyxJQUFJOztzQkFHOUIsSUFBSSxDQUFDLGVBQWU7O3NCQUdwQixJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7O3NCQU0xQixJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttR0FYMkIsSUFBSSxDQUFDLGVBQWUsQ0FBQyxLQUFLLENBQUMsU0FBUyxDQUFDLENBQUMsTUFBRSxJQUFJLENBQUMsZUFBZSxDQUFDLEtBQUssQ0FBQyxNQUFNLEdBQUcsQ0FBQyxDQUFDOzs4RkFGbEgsSUFBSSxDQUFDLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1REFDUSxJQUFJLENBQUMsSUFBSTs7OztXQUc5QixJQUFJLENBQUMsZUFBZTs7Ozs7Ozs7Ozs7OztXQUdwQixJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7V0FNMUIsSUFBSSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7O29HQVgyQixJQUFJLENBQUMsZUFBZSxDQUFDLEtBQUssQ0FBQyxTQUFTLENBQUMsQ0FBQyxNQUFFLElBQUksQ0FBQyxlQUFlLENBQUMsS0FBSyxDQUFDLE1BQU0sR0FBRyxDQUFDLENBQUM7OzsrREFGbEgsSUFBSSxDQUFDLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NCQUZ0QixLQUFLOzs7O2dDQUFWOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7cUJBQUssS0FBSzs7bUNBQVY7Ozs7Ozs7Ozs7OzsyQkFBQTs7O2dCQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0NBM0pDLElBQUksS0FBSzs7Ozs7MEJBS1QsS0FBSyxHQUFHO0lBQ1I7UUFDSSxXQUFXLEVBQUUsRUFBRTtRQUNmLEtBQUssRUFBRSxNQUFNO1FBQ2IsTUFBTSxFQUFFLGdCQUFnQjtRQUN4QixpQkFBaUIsRUFBRTtZQUNmLE1BQU0sRUFBRSxZQUFZO1lBQ3BCLE9BQU8sRUFBRSxPQUFPO1NBQ25CO1FBQ0QsWUFBWSxFQUFFO1lBQ1YsWUFBWSxFQUFFLEVBQUU7U0FDbkI7S0FDSjtJQUNEO1FBQ0ksV0FBVyxFQUFFLEVBQUU7UUFDZixLQUFLLEVBQUUsT0FBTztRQUNkLE1BQU0sRUFBRSxlQUFlO1FBQ3ZCLGlCQUFpQixFQUFFO1lBQ2YsTUFBTSxFQUFFLEtBQUs7WUFDYixPQUFPLEVBQUUsT0FBTztTQUNuQjtRQUNELFlBQVksRUFBRTtZQUNWLFlBQVksRUFBRSxFQUFFO1NBQ25CO0tBQ0o7SUFDRDtRQUNJLFdBQVcsRUFBRSxFQUFFO1FBQ2YsS0FBSyxFQUFFLE9BQU87UUFDZCxNQUFNLEVBQUUsY0FBYztRQUN0QixpQkFBaUIsRUFBRTtZQUNmLE1BQU0sRUFBRSxLQUFLO1lBQ2IsT0FBTyxFQUFFLE9BQU87U0FDbkI7UUFDRCxZQUFZLEVBQUU7WUFDVixZQUFZLEVBQUUsRUFBRTtTQUNuQjtLQUNKO0lBQ0Q7UUFDSSxXQUFXLEVBQUUsRUFBRTtRQUNmLEtBQUssRUFBRSxNQUFNO1FBQ2IsTUFBTSxFQUFFLGdCQUFnQjtRQUN4QixpQkFBaUIsRUFBRTtZQUNmLE1BQU0sRUFBRSxLQUFLO1lBQ2IsT0FBTyxFQUFFLE9BQU87U0FDbkI7UUFDRCxZQUFZLEVBQUU7WUFDVixZQUFZLEVBQUUsRUFBRTtTQUNuQjtLQUNKO0lBQ0Q7UUFDSSxXQUFXLEVBQUUsRUFBRTtRQUNmLEtBQUssRUFBRSxNQUFNO1FBQ2IsTUFBTSxFQUFFLGVBQWU7UUFDdkIsaUJBQWlCLEVBQUU7WUFDZixNQUFNLEVBQUUsS0FBSztZQUNiLE9BQU8sRUFBRSxPQUFPO1NBQ25CO1FBQ0QsWUFBWSxFQUFFO1lBQ1YsWUFBWSxFQUFFLEVBQUU7U0FDbkI7S0FDSjtJQUNEO1FBQ0ksV0FBVyxFQUFFLEVBQUU7UUFDZixLQUFLLEVBQUUsT0FBTztRQUNkLE1BQU0sRUFBRSxjQUFjO1FBQ3RCLGlCQUFpQixFQUFFO1lBQ2YsTUFBTSxFQUFFLEtBQUs7WUFDYixPQUFPLEVBQUUsT0FBTztTQUNuQjtRQUNELFlBQVksRUFBRTtZQUNWLFlBQVksRUFBRSxFQUFFO1NBQ25CO0tBQ0o7SUFDRDtRQUNJLFdBQVcsRUFBRSxFQUFFO1FBQ2YsS0FBSyxFQUFFLE9BQU87UUFDZCxNQUFNLEVBQUUsY0FBYztRQUN0QixpQkFBaUIsRUFBRTtZQUNmLE1BQU0sRUFBRSxZQUFZO1lBQ3BCLE9BQU8sRUFBRSxPQUFPO1NBQ25CO1FBQ0QsWUFBWSxFQUFFO1lBQ1YsWUFBWSxFQUFFLEVBQUU7U0FDbkI7S0FDSjtDQUNKIiwiZmlsZSI6IjNhYzY4OThkNjVjODJlYmIyMzhkL2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcbiAgICBsZXQgcmVwb3NcbiAgICAvLyBmZXRjaChcIi8ubmV0bGlmeS9mdW5jdGlvbnMvZ2l0aHViXCIpLnRoZW4ocmVzID0+IHJlcy5qc29uKCkpLnRoZW4oanNvbiA9PiB7XG4gICAgLy8gICAgIHJlcG9zID0ganNvblxuICAgIC8vIH0pXG5cbiAgICByZXBvcyA9IFtcbiAgICB7XG4gICAgICAgIFwiZm9ya0NvdW50XCI6IDI3LFxuICAgICAgICBcInVybFwiOiBcImJsdWVcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiTGV0aWNpYSBIYW5zZW5cIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiSmF2YVNjcmlwdFwiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiMwMGY1XCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAzMFxuICAgICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiZm9ya0NvdW50XCI6IDQwLFxuICAgICAgICBcInVybFwiOiBcImJyb3duXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIkNhbmR5IFZhc3F1ZXpcIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4gICAgICAgICAgICBcImNvbG9yXCI6IFwiI2ZmMDFcIlxuICAgICAgICB9LFxuICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDI2XG4gICAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJmb3JrQ291bnRcIjogMzYsXG4gICAgICAgIFwidXJsXCI6IFwiZ3JlZW5cIixcbiAgICAgICAgXCJuYW1lXCI6IFwiTGFtYiBKb2huc29uXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmMDA3XCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyNFxuICAgICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiZm9ya0NvdW50XCI6IDIzLFxuICAgICAgICBcInVybFwiOiBcImJsdWVcIixcbiAgICAgICAgXCJuYW1lXCI6IFwiU29sb21vbiBNZWRpbmFcIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4gICAgICAgICAgICBcImNvbG9yXCI6IFwiI2YwMGZcIlxuICAgICAgICB9LFxuICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDM5XG4gICAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJmb3JrQ291bnRcIjogMjYsXG4gICAgICAgIFwidXJsXCI6IFwiYmx1ZVwiLFxuICAgICAgICBcIm5hbWVcIjogXCJSaWNobW9uZCBIZXNzXCIsXG4gICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbiAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjAzXCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyNFxuICAgICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwiZm9ya0NvdW50XCI6IDM4LFxuICAgICAgICBcInVybFwiOiBcImdyZWVuXCIsXG4gICAgICAgIFwibmFtZVwiOiBcIlNwZW5jZXIgQnVzaFwiLFxuICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4gICAgICAgICAgICBcIm5hbWVcIjogXCJDKytcIixcbiAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZmYwNFwiXG4gICAgICAgIH0sXG4gICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4gICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMzNcbiAgICAgICAgfVxuICAgIH0sXG4gICAge1xuICAgICAgICBcImZvcmtDb3VudFwiOiAyMixcbiAgICAgICAgXCJ1cmxcIjogXCJncmVlblwiLFxuICAgICAgICBcIm5hbWVcIjogXCJIYW1tb25kIE1hbm5cIixcbiAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuICAgICAgICAgICAgXCJuYW1lXCI6IFwiSmF2YVNjcmlwdFwiLFxuICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjA2XCJcbiAgICAgICAgfSxcbiAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbiAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyMlxuICAgICAgICB9XG4gICAgfVxuXVxuXG48L3NjcmlwdD5cblxuPHN0eWxlIGxhbmc9XCJzYXNzXCI+LmxhbmRpbmctcGFnZS0taGVybyB7XG4gIHdpZHRoOiA1MCU7XG4gIG1hcmdpbjogMjBweCBhdXRvO1xuICBkaXNwbGF5OiBibG9jaztcbiAgYmFja2dyb3VuZC1pbWFnZTogdmFyKC0tYXZhdGFyKTtcbiAgYmFja2dyb3VuZC1zaXplOiBjb3ZlcjtcbiAgd2lkdGg6IDMwMHB4O1xuICBoZWlnaHQ6IDMwMHB4OyB9XG5cbmxpLCB1bCB7XG4gIG1hcmdpbjogNXB4O1xuICBtYXJnaW4tdG9wOiAxMHB4O1xuICBsaXN0LXN0eWxlLXR5cGU6IG5vbmU7IH1cblxuc3BhbiB7XG4gIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250KTsgfVxuXG4ucmVwb3Mge1xuICBtYXJnaW46IDAgYXV0bztcbiAgd2lkdGg6IDUwJTtcbiAgcGFkZGluZzogMDsgfVxuICAucmVwb3MgaDIge1xuICAgIG1hcmdpbjogNXB4O1xuICAgIHBhZGRpbmc6IDVweDtcbiAgICB0ZXh0LWFsaWduOiBsZWZ0O1xuICAgIGZvbnQtd2VpZ2h0OiA1MDA7IH1cblxuLnJlcG8ge1xuICBtYXJnaW46IDVweDtcbiAgcGFkZGluZzogNXB4O1xuICBib3JkZXItcmFkaXVzOiA1cHg7XG4gIHRleHQtYWxpZ246IGxlZnQ7IH1cblxuLnJlcG8tLW5hbWUge1xuICBmb250LXNpemU6IDFlbTtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwOyB9XG5cbi5yZXBvLS1iYWRnZXMge1xuICBtYXJnaW46IDVweDtcbiAgcGFkZGluZzogNXB4O1xuICBib3JkZXItcmFkaXVzOiA1cHg7XG4gIGJvcmRlcjogMXB4IHNvbGlkIHJnYmEodmFyKC0tdGV4dC1iYXNlKSwgMC4xKTtcbiAgZm9udC1zaXplOiAwLjc1ZW07IH1cbiAgLnJlcG8tLWJhZGdlcyBzcGFuIHtcbiAgICBtYXJnaW46IDJweDsgfVxuXG4ucmVwby0tbGFuZ2F1Z2Uge1xuICBmb250LXNpemU6IDFlbTsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgICA8dGl0bGU+SG9tZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48ZGl2IGNsYXNzPVwibGFuZGluZy1wYWdlLS1oZXJvXCI+PC9kaXY+PHAgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLXRpdGxlXCI+TWFyY3VzIE1hdGhpYXNzZW48L3A+PHAgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLXN1YnRpdGxlXCI+SSBkbyBjb21waWxlcnMgYW5kIGxhbmd1YWdlcy5cbkludGVyZXN0ZWQgaW4gc3lzdGVtcyBkZXNpZ24gYW5kIFVYLjwvcD5cbjxicj5cbjx1bCBjbGFzcz1cInJlcG9zXCI+XG4gICAgPGgyPlJlcG9zaXRvcmllczwvaDI+XG5cdHsjZWFjaCByZXBvcyBhcyByZXBvfVxuICAgICAgICA8bGkgY2xhc3M9XCJyZXBvXCI+XG4gICAgICAgICAgICA8YSBocmVmPVwie3JlcG8udXJsfVwiIHRhcmdldD1cIl9ibGFua1wiIHJlbD1cIm5vb3BlbmVyXCI+XG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLW5hbWVcIj57cmVwby5uYW1lfSA8L3NwYW4+XG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLWJhZGdlc1wiIHN0eWxlPVwiYmFja2dyb3VuZDp7cmVwby5wcmltYXJ5TGFuZ3VhZ2UuY29sb3Iuc3Vic3RyaW5nKDAsIHJlcG8ucHJpbWFyeUxhbmd1YWdlLmNvbG9yLmxlbmd0aCAtIDEpXG4gICAgICAgICAgICB9NVwiPlxuICAgICAgICAgICAgeyNpZiByZXBvLnByaW1hcnlMYW5ndWFnZX1cbiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLWxhbmdhdWdlXCI+IHtyZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lfTwvc3Bhbj5cbiAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICB7I2lmIHJlcG8uc3RhcmdhemVycy50b3RhbENvdW50fVxuICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1zdGFyXCI+XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuPntyZXBvLnN0YXJnYXplcnMudG90YWxDb3VudH08L3NwYW4+PC9pPlxuICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICB7I2lmIHJlcG8uZm9ya0NvdW50fVxuICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1jb2RlLWJyYW5jaFwiPlxuICAgICAgICAgICAgICAgICAgICA8c3Bhbj57cmVwby5mb3JrQ291bnR9PC9zcGFuPjwvaT5cbiAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgPC9hPlxuICAgICAgICA8L2xpPlxuXHR7L2VhY2h9XG48L3VsPlxuIl0sInNvdXJjZVJvb3QiOiIifQ==