(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_p2d_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/p2d.svelte */ "./src/components/p2d.svelte");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* src/routes/index.svelte generated by Svelte v3.9.2 */




const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-9cn10b-style';
	style.textContent = ".landing-page--hero.svelte-9cn10b{width:50%;margin:20px auto;display:block;background-image:var(--avatar);background-size:cover;width:300px;height:300px}li.svelte-9cn10b,ul.svelte-9cn10b{margin:5px;margin-top:10px;list-style-type:none}span.svelte-9cn10b{font-family:var(--font)}.repos.svelte-9cn10b{margin:0 auto;width:100%;padding:0}.repos.svelte-9cn10b h2.svelte-9cn10b{margin:5px;padding:5px;text-align:center;font-weight:500}.repo.svelte-9cn10b{margin:5px;padding:5px;text-align:center}@media only screen and (max-width: 600px){.repo.svelte-9cn10b{font-size:0.75rem}}.repo--name.svelte-9cn10b{font-size:1em;padding:0;margin:0}.repo--badges.svelte-9cn10b{--c:blue;background:var(--secondary);margin:5px;padding:5px;border-radius:var(--border-radius);font-size:0.75em}.repo--badges.svelte-9cn10b span.svelte-9cn10b{margin:2px}.repo--langauge.svelte-9cn10b{color:var(--c);padding:5px;padding-top:1px;padding-bottom:1px;border-radius:5px;font-size:1em;font-weight:700}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcbiAgICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJ1xuXG4gICAgbGV0IHJlcG9zID0gW11cblxuICAgIGNvbnN0IGdldEFwaSA9IGFzeW5jIChyb290LCBzdG9yYWdlID0gJ3Nlc3Npb24nKSA9PiB7XG4gICAgICAgIGNvbnN0IHN0b3JlID0gc3RvcmFnZSA9PT0gJ3Nlc3Npb24nIFxuICAgICAgICAgICAgICAgICAgICAgICAgPyBzZXNzaW9uU3RvcmFnZSBcbiAgICAgICAgICAgICAgICAgICAgICAgIDogc3RvcmFnZSA9PT0gJ2xvY2FsJ1xuICAgICAgICAgICAgICAgICAgICAgICAgPyBsb2NhbFN0b3JhZ2VcbiAgICAgICAgICAgICAgICAgICAgICAgIDogY29uc29sZS5lcnJvcihcImdldEFwaSBjYWxsZWQgd2l0aCB1bmtub3duIHN0b3JhZ2UgdHlwZVwiKVxuICAgICAgICBjb25zdCByZXN1bHQgPSBzdG9yZS5nZXRJdGVtKHJvb3QpXG4gICAgICAgIGlmIChyZXN1bHQgIT09IG51bGwpIHtcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKGBjYWxsaW5nICR7cm9vdH0uLi5nb3QgZnJvbSAke3N0b3JhZ2V9YClcbiAgICAgICAgICAgIHJldHVybiBKU09OLnBhcnNlKHJlc3VsdClcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKFwiZmV0Y2hpbmcgZ2l0aHViIGRhdGEuLi4gZ2l0aHViXCIpXG4gICAgICAgICAgICBjb25zdCByZXMgPSBhd2FpdCBmZXRjaChyb290KVxuICAgICAgICAgICAgY29uc3QganNvbiA9IGF3YWl0IHJlcy5qc29uKClcbiAgICAgICAgICAgIHN0b3JlLnNldEl0ZW0ocm9vdCwgSlNPTi5zdHJpbmdpZnkoanNvbikpXG4gICAgICAgICAgICByZXR1cm4ganNvblxuICAgICAgICB9XG4gICAgfVxuXG4gICAgb25Nb3VudChhc3luYyAoKSA9PiB7XG4gICAgICAgIHJlcG9zID0gYXdhaXQgZ2V0QXBpKCcvLm5ldGxpZnkvZnVuY3Rpb25zL2dpdGh1YicsICdsb2NhbCcpXG4gICAgfSlcblxuLy8gICAgIHJlcG9zID0gW1xuLy8gICAgIHtcbi8vICAgICAgICAgXCJmb3JrQ291bnRcIjogMjcsXG4vLyAgICAgICAgIFwidXJsXCI6IFwiYmx1ZVwiLFxuLy8gICAgICAgICBcIm5hbWVcIjogXCJMZXRpY2lhIEhhbnNlblwiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJKYXZhU2NyaXB0XCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiIzAwZmZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcImRlc2NyaXB0aW9uXCI6IFwidGhlIGNvbG9yIGJsdWVcIixcbi8vICAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbi8vICAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAzMFxuLy8gICAgICAgICB9XG4vLyAgICAgfSxcbi8vICAgICB7XG4vLyAgICAgICAgIFwiZm9ya0NvdW50XCI6IDQwLFxuLy8gICAgICAgICBcInVybFwiOiBcImJyb3duXCIsXG4vLyAgICAgICAgIFwibmFtZVwiOiBcIkNhbmR5IFZhc3F1ZXogVmVyb25pY1wiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJDKytcIixcbi8vICAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZmYwZlwiXG4vLyAgICAgICAgIH0sXG4vLyAgICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4vLyAgICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMjZcbi8vICAgICAgICAgfVxuLy8gICAgIH0sXG4vLyAgICAge1xuLy8gICAgICAgICBcImZvcmtDb3VudFwiOiAzNixcbi8vICAgICAgICAgXCJ1cmxcIjogXCJncmVlblwiLFxuLy8gICAgICAgICBcIm5hbWVcIjogXCJMYW1iIEpvaG5zb25cIixcbi8vICAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuLy8gICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiI2YwMGZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuLy8gICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDI0XG4vLyAgICAgICAgIH1cbi8vICAgICB9LFxuLy8gICAgIHtcbi8vICAgICAgICAgXCJmb3JrQ291bnRcIjogMjMsXG4vLyAgICAgICAgIFwidXJsXCI6IFwiYmx1ZVwiLFxuLy8gICAgICAgICBcIm5hbWVcIjogXCJTb2xvbW9uIE1lZGluYVwiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJDKytcIixcbi8vICAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZjAwZlwiXG4vLyAgICAgICAgIH0sXG4vLyAgICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4vLyAgICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMzlcbi8vICAgICAgICAgfVxuLy8gICAgIH0sXG4vLyAgICAge1xuLy8gICAgICAgICBcImZvcmtDb3VudFwiOiAyNixcbi8vICAgICAgICAgXCJ1cmxcIjogXCJibHVlXCIsXG4vLyAgICAgICAgIFwibmFtZVwiOiBcIlJpY2htb25kIEhlc3NcIixcbi8vICAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuLy8gICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiI2ZmMGZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuLy8gICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDI0XG4vLyAgICAgICAgIH1cbi8vICAgICB9LFxuLy8gICAgIHtcbi8vICAgICAgICAgXCJmb3JrQ291bnRcIjogMzgsXG4vLyAgICAgICAgIFwidXJsXCI6IFwiZ3JlZW5cIixcbi8vICAgICAgICAgXCJuYW1lXCI6IFwiU3BlbmNlciBCdXNoXCIsXG4vLyAgICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbi8vICAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuLy8gICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjBmXCJcbi8vICAgICAgICAgfSxcbi8vICAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbi8vICAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAzM1xuLy8gICAgICAgICB9XG4vLyAgICAgfSxcbi8vICAgICB7XG4vLyAgICAgICAgIFwiZm9ya0NvdW50XCI6IDIyLFxuLy8gICAgICAgICBcInVybFwiOiBcImdyZWVuXCIsXG4vLyAgICAgICAgIFwibmFtZVwiOiBcIkhhbW1vbmQgTWFublwiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJKYXZhU2NyaXB0XCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiI2ZmMGZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuLy8gICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDIyXG4vLyAgICAgICAgIH1cbi8vICAgICB9XG4vLyBdXG5cbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4ubGFuZGluZy1wYWdlLS1oZXJvIHtcbiAgd2lkdGg6IDUwJTtcbiAgbWFyZ2luOiAyMHB4IGF1dG87XG4gIGRpc3BsYXk6IGJsb2NrO1xuICBiYWNrZ3JvdW5kLWltYWdlOiB2YXIoLS1hdmF0YXIpO1xuICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICB3aWR0aDogMzAwcHg7XG4gIGhlaWdodDogMzAwcHg7IH1cblxubGksIHVsIHtcbiAgbWFyZ2luOiA1cHg7XG4gIG1hcmdpbi10b3A6IDEwcHg7XG4gIGxpc3Qtc3R5bGUtdHlwZTogbm9uZTsgfVxuXG5zcGFuIHtcbiAgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQpOyB9XG5cbi5yZXBvcyB7XG4gIG1hcmdpbjogMCBhdXRvO1xuICB3aWR0aDogMTAwJTtcbiAgcGFkZGluZzogMDsgfVxuICAucmVwb3MgaDIge1xuICAgIG1hcmdpbjogNXB4O1xuICAgIHBhZGRpbmc6IDVweDtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgZm9udC13ZWlnaHQ6IDUwMDsgfVxuXG4ucmVwbyB7XG4gIG1hcmdpbjogNXB4O1xuICBwYWRkaW5nOiA1cHg7XG4gIHRleHQtYWxpZ246IGNlbnRlcjsgfVxuICBAbWVkaWEgb25seSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDYwMHB4KSB7XG4gICAgLnJlcG8ge1xuICAgICAgZm9udC1zaXplOiAwLjc1cmVtOyB9IH1cblxuLnJlcG8tLW5hbWUge1xuICBmb250LXNpemU6IDFlbTtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwOyB9XG5cbi5yZXBvLS1iYWRnZXMge1xuICAtLWM6IGJsdWU7XG4gIGJhY2tncm91bmQ6IHZhcigtLXNlY29uZGFyeSk7XG4gIG1hcmdpbjogNXB4O1xuICBwYWRkaW5nOiA1cHg7XG4gIGJvcmRlci1yYWRpdXM6IHZhcigtLWJvcmRlci1yYWRpdXMpO1xuICBmb250LXNpemU6IDAuNzVlbTsgfVxuICAucmVwby0tYmFkZ2VzIHNwYW4ge1xuICAgIG1hcmdpbjogMnB4OyB9XG5cbi5yZXBvLS1sYW5nYXVnZSB7XG4gIGNvbG9yOiB2YXIoLS1jKTtcbiAgcGFkZGluZzogNXB4O1xuICBwYWRkaW5nLXRvcDogMXB4O1xuICBwYWRkaW5nLWJvdHRvbTogMXB4O1xuICBib3JkZXItcmFkaXVzOiA1cHg7XG4gIGZvbnQtc2l6ZTogMWVtO1xuICBmb250LXdlaWdodDogNzAwOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICAgIDx0aXRsZT5Ib21lPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG48ZGl2PlxuXG48ZGl2IGNsYXNzPVwibGFuZGluZy1wYWdlLS1oZXJvXCI+PC9kaXY+XG48cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tdGl0XCI+TWFyY3VzIE1hdGhpYXNzZW48L3A+XG48cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tc3VidGl0bGVcIj5JIGRvIGNvbXBpbGVycyBhbmQgbGFuZ3VhZ2VzLlxuPGJyPlxuICAgICAgICBJbnRlcmVzdGVkIGluIHN5c3RlbXMgZGVzaWduIGFuZCBVWC48L3A+XG48dWwgY2xhc3M9XCJyZXBvc1wiPlxuICAgIDxoMj5SZXBvc2l0b3JpZXM8L2gyPlxuXHR7I2VhY2ggcmVwb3MgYXMgcmVwb31cbiAgICAgICAgPGxpIGNsYXNzPVwicmVwb1wiPlxuICAgICAgICAgICAgPGEgaHJlZj1cIntyZXBvLnVybH1cIiB0YXJnZXQ9XCJfYmxhbmtcIiByZWw9XCJub29wZW5lclwiPlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJyZXBvLS1uYW1lXCI+e3JlcG8ubmFtZX0gPC9zcGFuPlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJyZXBvLS1iYWRnZXNcIiBzdHlsZT1cIi0tYzoge3JlcG8ucHJpbWFyeUxhbmd1YWdlLmNvbG9yfVwiPlxuICAgICAgICAgICAgeyNpZiByZXBvLnByaW1hcnlMYW5ndWFnZX1cbiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLWxhbmdhdWdlXCI+IHtyZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lfTwvc3Bhbj5cbiAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICB7I2lmIHJlcG8uc3RhcmdhemVycy50b3RhbENvdW50fVxuICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1zdGFyXCIgc3R5bGU9XCJjb2xvcjogZ29sZCAhaW1wb3J0YW50XCI+PC9pPlxuICAgICAgICAgICAgICAgICAgICA8c3Bhbj57cmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9PC9zcGFuPlxuICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICB7I2lmIHJlcG8uZm9ya0NvdW50fVxuICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1jb2RlLWJyYW5jaFwiIHN0eWxlPVwiY29sb3I6IHB1cnBsZSAhaW1wb3J0YW50XCI+PC9pPlxuICAgICAgICAgICAgICAgICAgICA8c3Bhbj57cmVwby5mb3JrQ291bnR9PC9zcGFuPlxuICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICA8L2E+XG4gICAgICAgIDwvbGk+XG5cdHsvZWFjaH1cbjwvdWw+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUF1SG1CLG1CQUFtQixjQUFDLENBQUMsQUFDdEMsS0FBSyxDQUFFLEdBQUcsQ0FDVixNQUFNLENBQUUsSUFBSSxDQUFDLElBQUksQ0FDakIsT0FBTyxDQUFFLEtBQUssQ0FDZCxnQkFBZ0IsQ0FBRSxJQUFJLFFBQVEsQ0FBQyxDQUMvQixlQUFlLENBQUUsS0FBSyxDQUN0QixLQUFLLENBQUUsS0FBSyxDQUNaLE1BQU0sQ0FBRSxLQUFLLEFBQUUsQ0FBQyxBQUVsQixnQkFBRSxDQUFFLEVBQUUsY0FBQyxDQUFDLEFBQ04sTUFBTSxDQUFFLEdBQUcsQ0FDWCxVQUFVLENBQUUsSUFBSSxDQUNoQixlQUFlLENBQUUsSUFBSSxBQUFFLENBQUMsQUFFMUIsSUFBSSxjQUFDLENBQUMsQUFDSixXQUFXLENBQUUsSUFBSSxNQUFNLENBQUMsQUFBRSxDQUFDLEFBRTdCLE1BQU0sY0FBQyxDQUFDLEFBQ04sTUFBTSxDQUFFLENBQUMsQ0FBQyxJQUFJLENBQ2QsS0FBSyxDQUFFLElBQUksQ0FDWCxPQUFPLENBQUUsQ0FBQyxBQUFFLENBQUMsQUFDYixvQkFBTSxDQUFDLEVBQUUsY0FBQyxDQUFDLEFBQ1QsTUFBTSxDQUFFLEdBQUcsQ0FDWCxPQUFPLENBQUUsR0FBRyxDQUNaLFVBQVUsQ0FBRSxNQUFNLENBQ2xCLFdBQVcsQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUV2QixLQUFLLGNBQUMsQ0FBQyxBQUNMLE1BQU0sQ0FBRSxHQUFHLENBQ1gsT0FBTyxDQUFFLEdBQUcsQ0FDWixVQUFVLENBQUUsTUFBTSxBQUFFLENBQUMsQUFDckIsT0FBTyxJQUFJLENBQUMsTUFBTSxDQUFDLEdBQUcsQ0FBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDekMsS0FBSyxjQUFDLENBQUMsQUFDTCxTQUFTLENBQUUsT0FBTyxBQUFFLENBQUMsQUFBQyxDQUFDLEFBRTdCLFdBQVcsY0FBQyxDQUFDLEFBQ1gsU0FBUyxDQUFFLEdBQUcsQ0FDZCxPQUFPLENBQUUsQ0FBQyxDQUNWLE1BQU0sQ0FBRSxDQUFDLEFBQUUsQ0FBQyxBQUVkLGFBQWEsY0FBQyxDQUFDLEFBQ2IsR0FBRyxDQUFFLElBQUksQ0FDVCxVQUFVLENBQUUsSUFBSSxXQUFXLENBQUMsQ0FDNUIsTUFBTSxDQUFFLEdBQUcsQ0FDWCxPQUFPLENBQUUsR0FBRyxDQUNaLGFBQWEsQ0FBRSxJQUFJLGVBQWUsQ0FBQyxDQUNuQyxTQUFTLENBQUUsTUFBTSxBQUFFLENBQUMsQUFDcEIsMkJBQWEsQ0FBQyxJQUFJLGNBQUMsQ0FBQyxBQUNsQixNQUFNLENBQUUsR0FBRyxBQUFFLENBQUMsQUFFbEIsZUFBZSxjQUFDLENBQUMsQUFDZixLQUFLLENBQUUsSUFBSSxHQUFHLENBQUMsQ0FDZixPQUFPLENBQUUsR0FBRyxDQUNaLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLGNBQWMsQ0FBRSxHQUFHLENBQ25CLGFBQWEsQ0FBRSxHQUFHLENBQ2xCLFNBQVMsQ0FBRSxHQUFHLENBQ2QsV0FBVyxDQUFFLEdBQUcsQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.repo = list[i];
	return child_ctx;
}

// (198:12) {#if repo.primaryLanguage}
function create_if_block_2(ctx) {
	var span, t_value = ctx.repo.primaryLanguage.name + "", t;

	return {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span, "class", "repo--langauge svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 198, 16, 4787);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.primaryLanguage.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span);
			}
		}
	};
}

// (201:12) {#if repo.stargazers.totalCount}
function create_if_block_1(ctx) {
	var span1, i, t0, span0, t1_value = ctx.repo.stargazers.totalCount + "", t1;

	return {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n                    ");

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(i, "class", "fas fa-star");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "gold", 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 202, 20, 4958);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 203, 20, 5037);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 201, 16, 4931);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t1_value !== (t1_value = ctx.repo.stargazers.totalCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span1);
			}
		}
	};
}

// (207:12) {#if repo.forkCount}
function create_if_block(ctx) {
	var span1, i, t0, span0, t1_value = ctx.repo.forkCount + "", t1;

	return {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n                    ");

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(i, "class", "fas fa-code-branch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "purple", 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 208, 20, 5197);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 209, 20, 5285);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 207, 16, 5170);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t1_value !== (t1_value = ctx.repo.forkCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span1);
			}
		}
	};
}

// (193:1) {#each repos as repo}
function create_each_block(ctx) {
	var li, a, span0, t0_value = ctx.repo.name + "", t0, t1, span1, t2, t3, a_href_value, t4;

	var if_block0 = (ctx.repo.primaryLanguage) && create_if_block_2(ctx);

	var if_block1 = (ctx.repo.stargazers.totalCount) && create_if_block_1(ctx);

	var if_block2 = (ctx.repo.forkCount) && create_if_block(ctx);

	return {
		c: function create() {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			if (if_block0) if_block0.c();
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "LI", { class: true }, false);
			var li_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "A", { href: true, target: true, rel: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t0_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a_nodes, "\n            ");

			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true, style: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			if (if_block0) if_block0.l(span1_nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n            ");
			if (if_block1) if_block1.l(span1_nodes);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n            ");
			if (if_block2) if_block2.l(span1_nodes);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li_nodes, "\n        ");
			li_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "repo--name svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 195, 12, 4605);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "repo--badges svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span1, "--c", ctx.repo.primaryLanguage.color);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 196, 12, 4662);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "href", a_href_value = ctx.repo.url);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 194, 12, 4540);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(li, "class", "repo svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li, file, 193, 8, 4510);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, li, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, span1);
			if (if_block0) if_block0.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t2);
			if (if_block1) if_block1.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t3);
			if (if_block2) if_block2.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li, t4);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t0_value !== (t0_value = ctx.repo.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, t0_value);
			}

			if (ctx.repo.primaryLanguage) {
				if (if_block0) {
					if_block0.p(changed, ctx);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(span1, t2);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (ctx.repo.stargazers.totalCount) {
				if (if_block1) {
					if_block1.p(changed, ctx);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(span1, t3);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (ctx.repo.forkCount) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(span1, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if (changed.repos) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span1, "--c", ctx.repo.primaryLanguage.color);
			}

			if ((changed.repos) && a_href_value !== (a_href_value = ctx.repo.url)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "href", a_href_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(li);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
		}
	};
}

function create_fragment(ctx) {
	var t0, div1, div0, t1, p0, t2, t3, p1, t4, br, t5, t6, ul, h2, t7, t8;

	var each_value = ctx.repos;

	var each_blocks = [];

	for (var i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Marcus Mathiassen");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I do compilers and languages.\n");
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n        Interested in systems design and UX.");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Repositories");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {}, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n");

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Marcus Mathiassen");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "I do compilers and languages.\n");

			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "BR", {}, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n        Interested in systems design and UX.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n");

			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "H2", { class: true }, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Repositories");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n\t");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Home";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "landing-page--hero svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 185, 0, 4226);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p0, "class", "landing-page--tit");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 186, 0, 4265);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 188, 0, 4380);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p1, "class", "landing-page--subtitle");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 187, 0, 4316);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h2, "class", "svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 191, 4, 4457);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(ul, "class", "repos svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 190, 0, 4434);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 183, 0, 4219);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, br);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, ul);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h2, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t8);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.repos) {
				each_value = ctx.repos;

				for (var i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div1);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	

    let repos = []

    const getApi = async (root, storage = 'session') => {
        const store = storage === 'session' 
                        ? sessionStorage 
                        : storage === 'local'
                        ? localStorage
                        : console.error("getApi called with unknown storage type")
        const result = store.getItem(root)
        if (result !== null) {
            console.log(`calling ${root}...got from ${storage}`)
            return JSON.parse(result)
        } else {
            console.log("fetching github data... github")
            const res = await fetch(root)
            const json = await res.json()
            store.setItem(root, JSON.stringify(json))
            return json
        }
    }

    Object(svelte__WEBPACK_IMPORTED_MODULE_2__["onMount"])(async () => {
        $$invalidate('repos', repos = await getApi('/.netlify/functions/github', 'local'))
    })

//     repos = [
//     {
//         "forkCount": 27,
//         "url": "blue",
//         "name": "Leticia Hansen",
//         "primaryLanguage": {
//             "name": "JavaScript",
//             "color": "#00ff"
//         },
//         "description": "the color blue",
//         "stargazers": {
//             "totalCount": 30
//         }
//     },
//     {
//         "forkCount": 40,
//         "url": "brown",
//         "name": "Candy Vasquez Veronic",
//         "primaryLanguage": {
//             "name": "C++",
//             "color": "#ff0f"
//         },
//         "stargazers": {
//             "totalCount": 26
//         }
//     },
//     {
//         "forkCount": 36,
//         "url": "green",
//         "name": "Lamb Johnson",
//         "primaryLanguage": {
//             "name": "C++",
//             "color": "#f00f"
//         },
//         "stargazers": {
//             "totalCount": 24
//         }
//     },
//     {
//         "forkCount": 23,
//         "url": "blue",
//         "name": "Solomon Medina",
//         "primaryLanguage": {
//             "name": "C++",
//             "color": "#f00f"
//         },
//         "stargazers": {
//             "totalCount": 39
//         }
//     },
//     {
//         "forkCount": 26,
//         "url": "blue",
//         "name": "Richmond Hess",
//         "primaryLanguage": {
//             "name": "C++",
//             "color": "#ff0f"
//         },
//         "stargazers": {
//             "totalCount": 24
//         }
//     },
//     {
//         "forkCount": 38,
//         "url": "green",
//         "name": "Spencer Bush",
//         "primaryLanguage": {
//             "name": "C++",
//             "color": "#ff0f"
//         },
//         "stargazers": {
//             "totalCount": 33
//         }
//     },
//     {
//         "forkCount": 22,
//         "url": "green",
//         "name": "Hammond Mann",
//         "primaryLanguage": {
//             "name": "JavaScript",
//             "color": "#ff0f"
//         },
//         "stargazers": {
//             "totalCount": 22
//         }
//     }
// ]

	return { repos };
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-9cn10b-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7eUJBc00rQyxJQUFJLENBQUMsZUFBZSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FEQUF6QixJQUFJLENBQUMsZUFBZSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozt5Q0FLN0MsSUFBSSxDQUFDLFVBQVUsQ0FBQyxVQUFVOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1REFBMUIsSUFBSSxDQUFDLFVBQVUsQ0FBQyxVQUFVOzs7Ozs7Ozs7Ozs7Ozs7eUNBTTFCLElBQUksQ0FBQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1REFBZCxJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7O2tDQWRILElBQUksQ0FBQyxJQUFJOztzQkFFOUIsSUFBSSxDQUFDLGVBQWU7O3NCQUdwQixJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7O3NCQU0xQixJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1RkFWcUIsSUFBSSxDQUFDLGVBQWUsQ0FBQyxLQUFLOzs4RkFGeEQsSUFBSSxDQUFDLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1REFDUSxJQUFJLENBQUMsSUFBSTs7OztXQUU5QixJQUFJLENBQUMsZUFBZTs7Ozs7Ozs7Ozs7OztXQUdwQixJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7V0FNMUIsSUFBSSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7O3dGQVZxQixJQUFJLENBQUMsZUFBZSxDQUFDLEtBQUs7OzsrREFGeEQsSUFBSSxDQUFDLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NCQUZ0QixLQUFLOzs7O2dDQUFWOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O21DQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O21DQUFBOzs7Ozs7O3FCQUFLLEtBQUs7O21DQUFWOzs7Ozs7Ozs7Ozs7MkJBQUE7OztnQkFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztDQTlMaUM7O0lBRWhDLElBQUksS0FBSyxHQUFHLEVBQUU7O0lBRWQsTUFBTSxNQUFNLEdBQUcsT0FBTyxJQUFJLEVBQUUsT0FBTyxHQUFHLFNBQVMsS0FBSztRQUNoRCxNQUFNLEtBQUssR0FBRyxPQUFPLEtBQUssU0FBUzswQkFDakIsY0FBYzswQkFDZCxPQUFPLEtBQUssT0FBTzswQkFDbkIsWUFBWTswQkFDWixPQUFPLENBQUMsS0FBSyxDQUFDLHlDQUF5QyxDQUFDO1FBQzFFLE1BQU0sTUFBTSxHQUFHLEtBQUssQ0FBQyxPQUFPLENBQUMsSUFBSSxDQUFDO1FBQ2xDLElBQUksTUFBTSxLQUFLLElBQUksRUFBRTtZQUNqQixPQUFPLENBQUMsR0FBRyxDQUFDLENBQUMsUUFBUSxFQUFFLElBQUksQ0FBQyxZQUFZLEVBQUUsT0FBTyxDQUFDLENBQUMsQ0FBQztZQUNwRCxPQUFPLElBQUksQ0FBQyxLQUFLLENBQUMsTUFBTSxDQUFDO1NBQzVCLE1BQU07WUFDSCxPQUFPLENBQUMsR0FBRyxDQUFDLGdDQUFnQyxDQUFDO1lBQzdDLE1BQU0sR0FBRyxHQUFHLE1BQU0sS0FBSyxDQUFDLElBQUksQ0FBQztZQUM3QixNQUFNLElBQUksR0FBRyxNQUFNLEdBQUcsQ0FBQyxJQUFJLEVBQUU7WUFDN0IsS0FBSyxDQUFDLE9BQU8sQ0FBQyxJQUFJLEVBQUUsSUFBSSxDQUFDLFNBQVMsQ0FBQyxJQUFJLENBQUMsQ0FBQztZQUN6QyxPQUFPLElBQUk7U0FDZDtLQUNKOztJQUVELHNEQUFPLENBQUMsWUFBWTs4QkFDaEIsS0FBSyxHQUFHLE1BQU0sTUFBTSxDQUFDLDRCQUE0QixFQUFFLE9BQU8sRUFBQztLQUM5RCxDQUFDOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lBd0ZGIiwiZmlsZSI6IjZhMTViNTZiMjllNWZkOTcxMTFmL2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcbiAgICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJ1xuXG4gICAgbGV0IHJlcG9zID0gW11cblxuICAgIGNvbnN0IGdldEFwaSA9IGFzeW5jIChyb290LCBzdG9yYWdlID0gJ3Nlc3Npb24nKSA9PiB7XG4gICAgICAgIGNvbnN0IHN0b3JlID0gc3RvcmFnZSA9PT0gJ3Nlc3Npb24nIFxuICAgICAgICAgICAgICAgICAgICAgICAgPyBzZXNzaW9uU3RvcmFnZSBcbiAgICAgICAgICAgICAgICAgICAgICAgIDogc3RvcmFnZSA9PT0gJ2xvY2FsJ1xuICAgICAgICAgICAgICAgICAgICAgICAgPyBsb2NhbFN0b3JhZ2VcbiAgICAgICAgICAgICAgICAgICAgICAgIDogY29uc29sZS5lcnJvcihcImdldEFwaSBjYWxsZWQgd2l0aCB1bmtub3duIHN0b3JhZ2UgdHlwZVwiKVxuICAgICAgICBjb25zdCByZXN1bHQgPSBzdG9yZS5nZXRJdGVtKHJvb3QpXG4gICAgICAgIGlmIChyZXN1bHQgIT09IG51bGwpIHtcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKGBjYWxsaW5nICR7cm9vdH0uLi5nb3QgZnJvbSAke3N0b3JhZ2V9YClcbiAgICAgICAgICAgIHJldHVybiBKU09OLnBhcnNlKHJlc3VsdClcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKFwiZmV0Y2hpbmcgZ2l0aHViIGRhdGEuLi4gZ2l0aHViXCIpXG4gICAgICAgICAgICBjb25zdCByZXMgPSBhd2FpdCBmZXRjaChyb290KVxuICAgICAgICAgICAgY29uc3QganNvbiA9IGF3YWl0IHJlcy5qc29uKClcbiAgICAgICAgICAgIHN0b3JlLnNldEl0ZW0ocm9vdCwgSlNPTi5zdHJpbmdpZnkoanNvbikpXG4gICAgICAgICAgICByZXR1cm4ganNvblxuICAgICAgICB9XG4gICAgfVxuXG4gICAgb25Nb3VudChhc3luYyAoKSA9PiB7XG4gICAgICAgIHJlcG9zID0gYXdhaXQgZ2V0QXBpKCcvLm5ldGxpZnkvZnVuY3Rpb25zL2dpdGh1YicsICdsb2NhbCcpXG4gICAgfSlcblxuLy8gICAgIHJlcG9zID0gW1xuLy8gICAgIHtcbi8vICAgICAgICAgXCJmb3JrQ291bnRcIjogMjcsXG4vLyAgICAgICAgIFwidXJsXCI6IFwiYmx1ZVwiLFxuLy8gICAgICAgICBcIm5hbWVcIjogXCJMZXRpY2lhIEhhbnNlblwiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJKYXZhU2NyaXB0XCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiIzAwZmZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcImRlc2NyaXB0aW9uXCI6IFwidGhlIGNvbG9yIGJsdWVcIixcbi8vICAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbi8vICAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAzMFxuLy8gICAgICAgICB9XG4vLyAgICAgfSxcbi8vICAgICB7XG4vLyAgICAgICAgIFwiZm9ya0NvdW50XCI6IDQwLFxuLy8gICAgICAgICBcInVybFwiOiBcImJyb3duXCIsXG4vLyAgICAgICAgIFwibmFtZVwiOiBcIkNhbmR5IFZhc3F1ZXogVmVyb25pY1wiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJDKytcIixcbi8vICAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZmYwZlwiXG4vLyAgICAgICAgIH0sXG4vLyAgICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4vLyAgICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMjZcbi8vICAgICAgICAgfVxuLy8gICAgIH0sXG4vLyAgICAge1xuLy8gICAgICAgICBcImZvcmtDb3VudFwiOiAzNixcbi8vICAgICAgICAgXCJ1cmxcIjogXCJncmVlblwiLFxuLy8gICAgICAgICBcIm5hbWVcIjogXCJMYW1iIEpvaG5zb25cIixcbi8vICAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuLy8gICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiI2YwMGZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuLy8gICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDI0XG4vLyAgICAgICAgIH1cbi8vICAgICB9LFxuLy8gICAgIHtcbi8vICAgICAgICAgXCJmb3JrQ291bnRcIjogMjMsXG4vLyAgICAgICAgIFwidXJsXCI6IFwiYmx1ZVwiLFxuLy8gICAgICAgICBcIm5hbWVcIjogXCJTb2xvbW9uIE1lZGluYVwiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJDKytcIixcbi8vICAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZjAwZlwiXG4vLyAgICAgICAgIH0sXG4vLyAgICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4vLyAgICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMzlcbi8vICAgICAgICAgfVxuLy8gICAgIH0sXG4vLyAgICAge1xuLy8gICAgICAgICBcImZvcmtDb3VudFwiOiAyNixcbi8vICAgICAgICAgXCJ1cmxcIjogXCJibHVlXCIsXG4vLyAgICAgICAgIFwibmFtZVwiOiBcIlJpY2htb25kIEhlc3NcIixcbi8vICAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuLy8gICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiI2ZmMGZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuLy8gICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDI0XG4vLyAgICAgICAgIH1cbi8vICAgICB9LFxuLy8gICAgIHtcbi8vICAgICAgICAgXCJmb3JrQ291bnRcIjogMzgsXG4vLyAgICAgICAgIFwidXJsXCI6IFwiZ3JlZW5cIixcbi8vICAgICAgICAgXCJuYW1lXCI6IFwiU3BlbmNlciBCdXNoXCIsXG4vLyAgICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbi8vICAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuLy8gICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjBmXCJcbi8vICAgICAgICAgfSxcbi8vICAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbi8vICAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAzM1xuLy8gICAgICAgICB9XG4vLyAgICAgfSxcbi8vICAgICB7XG4vLyAgICAgICAgIFwiZm9ya0NvdW50XCI6IDIyLFxuLy8gICAgICAgICBcInVybFwiOiBcImdyZWVuXCIsXG4vLyAgICAgICAgIFwibmFtZVwiOiBcIkhhbW1vbmQgTWFublwiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJKYXZhU2NyaXB0XCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiI2ZmMGZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuLy8gICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDIyXG4vLyAgICAgICAgIH1cbi8vICAgICB9XG4vLyBdXG5cbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4ubGFuZGluZy1wYWdlLS1oZXJvIHtcbiAgd2lkdGg6IDUwJTtcbiAgbWFyZ2luOiAyMHB4IGF1dG87XG4gIGRpc3BsYXk6IGJsb2NrO1xuICBiYWNrZ3JvdW5kLWltYWdlOiB2YXIoLS1hdmF0YXIpO1xuICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICB3aWR0aDogMzAwcHg7XG4gIGhlaWdodDogMzAwcHg7IH1cblxubGksIHVsIHtcbiAgbWFyZ2luOiA1cHg7XG4gIG1hcmdpbi10b3A6IDEwcHg7XG4gIGxpc3Qtc3R5bGUtdHlwZTogbm9uZTsgfVxuXG5zcGFuIHtcbiAgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQpOyB9XG5cbi5yZXBvcyB7XG4gIG1hcmdpbjogMCBhdXRvO1xuICB3aWR0aDogMTAwJTtcbiAgcGFkZGluZzogMDsgfVxuICAucmVwb3MgaDIge1xuICAgIG1hcmdpbjogNXB4O1xuICAgIHBhZGRpbmc6IDVweDtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgZm9udC13ZWlnaHQ6IDUwMDsgfVxuXG4ucmVwbyB7XG4gIG1hcmdpbjogNXB4O1xuICBwYWRkaW5nOiA1cHg7XG4gIHRleHQtYWxpZ246IGNlbnRlcjsgfVxuICBAbWVkaWEgb25seSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDYwMHB4KSB7XG4gICAgLnJlcG8ge1xuICAgICAgZm9udC1zaXplOiAwLjc1cmVtOyB9IH1cblxuLnJlcG8tLW5hbWUge1xuICBmb250LXNpemU6IDFlbTtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwOyB9XG5cbi5yZXBvLS1iYWRnZXMge1xuICAtLWM6IGJsdWU7XG4gIGJhY2tncm91bmQ6IHZhcigtLXNlY29uZGFyeSk7XG4gIG1hcmdpbjogNXB4O1xuICBwYWRkaW5nOiA1cHg7XG4gIGJvcmRlci1yYWRpdXM6IHZhcigtLWJvcmRlci1yYWRpdXMpO1xuICBmb250LXNpemU6IDAuNzVlbTsgfVxuICAucmVwby0tYmFkZ2VzIHNwYW4ge1xuICAgIG1hcmdpbjogMnB4OyB9XG5cbi5yZXBvLS1sYW5nYXVnZSB7XG4gIGNvbG9yOiB2YXIoLS1jKTtcbiAgcGFkZGluZzogNXB4O1xuICBwYWRkaW5nLXRvcDogMXB4O1xuICBwYWRkaW5nLWJvdHRvbTogMXB4O1xuICBib3JkZXItcmFkaXVzOiA1cHg7XG4gIGZvbnQtc2l6ZTogMWVtO1xuICBmb250LXdlaWdodDogNzAwOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICAgIDx0aXRsZT5Ib21lPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG48ZGl2PlxuXG48ZGl2IGNsYXNzPVwibGFuZGluZy1wYWdlLS1oZXJvXCI+PC9kaXY+XG48cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tdGl0XCI+TWFyY3VzIE1hdGhpYXNzZW48L3A+XG48cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tc3VidGl0bGVcIj5JIGRvIGNvbXBpbGVycyBhbmQgbGFuZ3VhZ2VzLlxuPGJyPlxuICAgICAgICBJbnRlcmVzdGVkIGluIHN5c3RlbXMgZGVzaWduIGFuZCBVWC48L3A+XG48dWwgY2xhc3M9XCJyZXBvc1wiPlxuICAgIDxoMj5SZXBvc2l0b3JpZXM8L2gyPlxuXHR7I2VhY2ggcmVwb3MgYXMgcmVwb31cbiAgICAgICAgPGxpIGNsYXNzPVwicmVwb1wiPlxuICAgICAgICAgICAgPGEgaHJlZj1cIntyZXBvLnVybH1cIiB0YXJnZXQ9XCJfYmxhbmtcIiByZWw9XCJub29wZW5lclwiPlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJyZXBvLS1uYW1lXCI+e3JlcG8ubmFtZX0gPC9zcGFuPlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJyZXBvLS1iYWRnZXNcIiBzdHlsZT1cIi0tYzoge3JlcG8ucHJpbWFyeUxhbmd1YWdlLmNvbG9yfVwiPlxuICAgICAgICAgICAgeyNpZiByZXBvLnByaW1hcnlMYW5ndWFnZX1cbiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLWxhbmdhdWdlXCI+IHtyZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lfTwvc3Bhbj5cbiAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICB7I2lmIHJlcG8uc3RhcmdhemVycy50b3RhbENvdW50fVxuICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1zdGFyXCIgc3R5bGU9XCJjb2xvcjogZ29sZCAhaW1wb3J0YW50XCI+PC9pPlxuICAgICAgICAgICAgICAgICAgICA8c3Bhbj57cmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9PC9zcGFuPlxuICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICB7I2lmIHJlcG8uZm9ya0NvdW50fVxuICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1jb2RlLWJyYW5jaFwiIHN0eWxlPVwiY29sb3I6IHB1cnBsZSAhaW1wb3J0YW50XCI+PC9pPlxuICAgICAgICAgICAgICAgICAgICA8c3Bhbj57cmVwby5mb3JrQ291bnR9PC9zcGFuPlxuICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICA8L2E+XG4gICAgICAgIDwvbGk+XG5cdHsvZWFjaH1cbjwvdWw+XG48L2Rpdj5cbiJdLCJzb3VyY2VSb290IjoiIn0=