(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* src/routes/index.svelte generated by Svelte v3.9.2 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-323th6-style';
	style.textContent = ".landing-page--hero.svelte-323th6{width:50%;margin:20px auto;display:block;background-image:var(--avatar);background-size:cover;width:300px;height:300px}li.svelte-323th6,ul.svelte-323th6{margin:5px;margin-top:10px;list-style-type:none}span.svelte-323th6{font-family:var(--font)}.container.svelte-323th6{display:flex;flex-flow:row wrap;justify-content:space-around}.container--repos.svelte-323th6{text-align:center}.repos.svelte-323th6{margin:20px;display:inline-block}.repos.svelte-323th6 h2.svelte-323th6{padding:5px;text-align:left;font-weight:500}@media only screen and (max-width: 600px){.repos.svelte-323th6{margin:0;padding:0}}.repo.svelte-323th6{display:flex;margin:5px;padding:5px;opacity:0.7}.repo.svelte-323th6:hover{opacity:1.0}@media only screen and (max-width: 600px){.repo.svelte-323th6{font-size:0.75em}}.repo--name.svelte-323th6{font-size:1em;padding:0;margin:0;text-align:left}.repo--badges.svelte-323th6{--c:blue;background:var(--secondary);margin:5px;padding:5px;border-radius:var(--border-radius);font-size:0.75em}.repo--badges.svelte-323th6 span.svelte-323th6{margin:2px}.repo--langauge.svelte-323th6{color:var(--c);padding:5px;padding-top:1px;padding-bottom:1px;border-radius:5px;font-size:1em;font-weight:700}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJ1xuXG4gICAgbGV0IHJlcG9zID0gW11cblxuICAgIGNvbnN0IGdldEFwaSA9IGFzeW5jIChyb290LCBzdG9yYWdlID0gc2Vzc2lvblN0b3JhZ2UpID0+IHtcbiAgICAgICAgY29uc3QgcmVzdWx0ID0gc3RvcmFnZS5nZXRJdGVtKHJvb3QpXG4gICAgICAgIGlmIChyZXN1bHQgIT09IG51bGwpIHtcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKFwiZmV0Y2hpbmcgZ2l0aHViIGRhdGEuLi4gZnJvbSBzdG9yYWdlXCIpXG4gICAgICAgICAgICByZXR1cm4gSlNPTi5wYXJzZShyZXN1bHQpXG4gICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgICBjb25zb2xlLmxvZyhcImZldGNoaW5nIGdpdGh1YiBkYXRhLi4uIGdpdGh1YlwiKVxuICAgICAgICAgICAgY29uc3QgcmVzID0gYXdhaXQgZmV0Y2gocm9vdClcbiAgICAgICAgICAgIGNvbnN0IGpzb24gPSBhd2FpdCByZXMuanNvbigpXG4gICAgICAgICAgICBzdG9yYWdlLnNldEl0ZW0ocm9vdCwgSlNPTi5zdHJpbmdpZnkoanNvbikpXG4gICAgICAgICAgICByZXR1cm4ganNvblxuICAgICAgICB9XG4gICAgfVxuICAgIG9uTW91bnQoYXN5bmMgKCkgPT4ge1xuICAgICAgICAvLyByZXBvcyA9IGF3YWl0IGdldEFwaSgnLy5uZXRsaWZ5L2Z1bmN0aW9ucy9naXRodWInKVxuICAgIH0pXG5cbiAgICAvLyBUZXN0IGRhdGFcbiAgICAvLyBAUmVtb3ZlIHdoZW4gZGVwbG95aW5nISEhXG4gICAgcmVwb3MgPSBKU09OLnBhcnNlKCdbe1wicHJpbWFyeUxhbmd1YWdlXCI6e1wibmFtZVwiOlwiSmF2YVNjcmlwdFwiLFwiY29sb3JcIjpcIiNmMWUwNWFcIn0sXCJzdGFyZ2F6ZXJzXCI6e1widG90YWxDb3VudFwiOjF9LFwiZm9ya0NvdW50XCI6MCxcImNyZWF0ZWRBdFwiOlwiMjAxOS0wMy0zMVQxMzoyNjozMFpcIixcIm5hbWVXaXRoT3duZXJcIjpcIk1hcmN1c01hdGhpYXNzZW4vaG9tZXBhZ2VcIixcIm5hbWVcIjpcImhvbWVwYWdlXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMTktMDktMDhUMTM6MjY6MjJaXCIsXCJwdXNoZWRBdFwiOlwiMjAxOS0wOS0wOFQxMzoyNjoyMFpcIixcImRlc2NyaXB0aW9uXCI6XCJteSBwZXJzb25hbCBwYWdlIFwiLFwidXJsXCI6XCJodHRwczovL2dpdGh1Yi5jb20vTWFyY3VzTWF0aGlhc3Nlbi9ob21lcGFnZVwiLFwibGljZW5zZUluZm9cIjpudWxsfSx7XCJwcmltYXJ5TGFuZ3VhZ2VcIjp7XCJuYW1lXCI6XCJDXCIsXCJjb2xvclwiOlwiIzU1NTU1NVwifSxcInN0YXJnYXplcnNcIjp7XCJ0b3RhbENvdW50XCI6MH0sXCJmb3JrQ291bnRcIjoxLFwiY3JlYXRlZEF0XCI6XCIyMDE4LTA5LTEzVDIyOjIzOjE2WlwiLFwibmFtZVdpdGhPd25lclwiOlwiTWFyY3VzTWF0aGlhc3Nlbi90aGlcIixcIm5hbWVcIjpcInRoaVwiLFwidXBkYXRlZEF0XCI6XCIyMDE5LTA4LTMwVDE2OjU3OjQ3WlwiLFwicHVzaGVkQXRcIjpcIjIwMTktMDgtMzBUMTY6NTc6NDVaXCIsXCJkZXNjcmlwdGlvblwiOlwiQSBDIGxpa2UgcHJvZ3JhbW1pbmcgbGFuZ3VhZ2VcIixcInVybFwiOlwiaHR0cHM6Ly9naXRodWIuY29tL01hcmN1c01hdGhpYXNzZW4vdGhpXCIsXCJsaWNlbnNlSW5mb1wiOm51bGx9LHtcInByaW1hcnlMYW5ndWFnZVwiOntcIm5hbWVcIjpcIkMrK1wiLFwiY29sb3JcIjpcIiNmMzRiN2RcIn0sXCJzdGFyZ2F6ZXJzXCI6e1widG90YWxDb3VudFwiOjB9LFwiZm9ya0NvdW50XCI6MCxcImNyZWF0ZWRBdFwiOlwiMjAxNy0wNy0yOFQwMTo1MDo0OFpcIixcIm5hbWVXaXRoT3duZXJcIjpcIk1hcmN1c01hdGhpYXNzZW4vQXRoaVwiLFwibmFtZVwiOlwiQXRoaVwiLFwidXBkYXRlZEF0XCI6XCIyMDE5LTA4LTMwVDE0OjQyOjMzWlwiLFwicHVzaGVkQXRcIjpcIjIwMTktMDgtMzBUMTQ6NDI6MjZaXCIsXCJkZXNjcmlwdGlvblwiOlwiQSBjb250aW51YXRpb24gb2YgbXkgUDJEIHByb2plY3RcIixcInVybFwiOlwiaHR0cHM6Ly9naXRodWIuY29tL01hcmN1c01hdGhpYXNzZW4vQXRoaVwiLFwibGljZW5zZUluZm9cIjpudWxsfSx7XCJwcmltYXJ5TGFuZ3VhZ2VcIjp7XCJuYW1lXCI6XCJDKytcIixcImNvbG9yXCI6XCIjZjM0YjdkXCJ9LFwic3RhcmdhemVyc1wiOntcInRvdGFsQ291bnRcIjozMn0sXCJmb3JrQ291bnRcIjoxNSxcImNyZWF0ZWRBdFwiOlwiMjAxNy0wMy0xOFQyMDowNTowNFpcIixcIm5hbWVXaXRoT3duZXJcIjpcIk1hcmN1c01hdGhpYXNzZW4vQmFzaWNSYXl0cmFjZXIzMG1pblwiLFwibmFtZVwiOlwiQmFzaWNSYXl0cmFjZXIzMG1pblwiLFwidXBkYXRlZEF0XCI6XCIyMDE5LTA4LTI3VDAyOjA4OjM0WlwiLFwicHVzaGVkQXRcIjpcIjIwMTctMDMtMTlUMDE6Mzg6NTlaXCIsXCJkZXNjcmlwdGlvblwiOlwiaHR0cHM6Ly95b3V0dS5iZS9BUm5feWhnazdhRVwiLFwidXJsXCI6XCJodHRwczovL2dpdGh1Yi5jb20vTWFyY3VzTWF0aGlhc3Nlbi9CYXNpY1JheXRyYWNlcjMwbWluXCIsXCJsaWNlbnNlSW5mb1wiOm51bGx9LHtcInByaW1hcnlMYW5ndWFnZVwiOntcIm5hbWVcIjpcIkMrK1wiLFwiY29sb3JcIjpcIiNmMzRiN2RcIn0sXCJzdGFyZ2F6ZXJzXCI6e1widG90YWxDb3VudFwiOjF9LFwiZm9ya0NvdW50XCI6MCxcImNyZWF0ZWRBdFwiOlwiMjAxNy0wOS0wNVQwMDo1NDoxMlpcIixcIm5hbWVXaXRoT3duZXJcIjpcIk1hcmN1c01hdGhpYXNzZW4vUmV2b3JrXCIsXCJuYW1lXCI6XCJSZXZvcmtcIixcInVwZGF0ZWRBdFwiOlwiMjAxOS0wNC0wMlQyMDo1MzoyN1pcIixcInB1c2hlZEF0XCI6XCIyMDE3LTEyLTEzVDA3OjQwOjU1WlwiLFwiZGVzY3JpcHRpb25cIjpcIjNEIGVuZ2luZVwiLFwidXJsXCI6XCJodHRwczovL2dpdGh1Yi5jb20vTWFyY3VzTWF0aGlhc3Nlbi9SZXZvcmtcIixcImxpY2Vuc2VJbmZvXCI6bnVsbH0se1wicHJpbWFyeUxhbmd1YWdlXCI6e1wibmFtZVwiOlwiQ1wiLFwiY29sb3JcIjpcIiM1NTU1NTVcIn0sXCJzdGFyZ2F6ZXJzXCI6e1widG90YWxDb3VudFwiOjB9LFwiZm9ya0NvdW50XCI6MCxcImNyZWF0ZWRBdFwiOlwiMjAxOS0wMi0wM1QxODo0NToyNlpcIixcIm5hbWVXaXRoT3duZXJcIjpcIk1hcmN1c01hdGhpYXNzZW4vY2hpcDhcIixcIm5hbWVcIjpcImNoaXA4XCIsXCJ1cGRhdGVkQXRcIjpcIjIwMTktMDQtMDJUMTI6MTE6MDlaXCIsXCJwdXNoZWRBdFwiOlwiMjAxOS0wMi0wM1QyMTo0MzozMVpcIixcImRlc2NyaXB0aW9uXCI6XCJDSElQLTggRW11bGF0b3JcIixcInVybFwiOlwiaHR0cHM6Ly9naXRodWIuY29tL01hcmN1c01hdGhpYXNzZW4vY2hpcDhcIixcImxpY2Vuc2VJbmZvXCI6bnVsbH0se1wicHJpbWFyeUxhbmd1YWdlXCI6e1wibmFtZVwiOlwiU3dpZnRcIixcImNvbG9yXCI6XCIjZmZhYzQ1XCJ9LFwic3RhcmdhemVyc1wiOntcInRvdGFsQ291bnRcIjowfSxcImZvcmtDb3VudFwiOjAsXCJjcmVhdGVkQXRcIjpcIjIwMTgtMDQtMDVUMTY6NTM6MDBaXCIsXCJuYW1lV2l0aE93bmVyXCI6XCJNYXJjdXNNYXRoaWFzc2VuL2F0aGlOYXRpdmVcIixcIm5hbWVcIjpcImF0aGlOYXRpdmVcIixcInVwZGF0ZWRBdFwiOlwiMjAxOS0wNC0wMlQxMjowOTo0NlpcIixcInB1c2hlZEF0XCI6XCIyMDE5LTAyLTE0VDAyOjE1OjMxWlwiLFwiZGVzY3JpcHRpb25cIjpcIlRoZSBzYW1lIGFzIG15IEF0aGkgcHJvamVjdCBidXQgaW4gU3dpZnQgYW5kIE1ldGFsLlwiLFwidXJsXCI6XCJodHRwczovL2dpdGh1Yi5jb20vTWFyY3VzTWF0aGlhc3Nlbi9hdGhpTmF0aXZlXCIsXCJsaWNlbnNlSW5mb1wiOm51bGx9LHtcInByaW1hcnlMYW5ndWFnZVwiOntcIm5hbWVcIjpcIkNcIixcImNvbG9yXCI6XCIjNTU1NTU1XCJ9LFwic3RhcmdhemVyc1wiOntcInRvdGFsQ291bnRcIjoxMH0sXCJmb3JrQ291bnRcIjoyLFwiY3JlYXRlZEF0XCI6XCIyMDE2LTA2LTA1VDE5OjAxOjMxWlwiLFwibmFtZVdpdGhPd25lclwiOlwiTWFyY3VzTWF0aGlhc3Nlbi9QMkRcIixcIm5hbWVcIjpcIlAyRFwiLFwidXBkYXRlZEF0XCI6XCIyMDE5LTAyLTA0VDE3OjE5OjAzWlwiLFwicHVzaGVkQXRcIjpcIjIwMTctMDMtMThUMjE6NTI6NTBaXCIsXCJkZXNjcmlwdGlvblwiOlwiQm91bmN5IGJhbGxzXCIsXCJ1cmxcIjpcImh0dHBzOi8vZ2l0aHViLmNvbS9NYXJjdXNNYXRoaWFzc2VuL1AyRFwiLFwibGljZW5zZUluZm9cIjpudWxsfSx7XCJwcmltYXJ5TGFuZ3VhZ2VcIjp7XCJuYW1lXCI6XCJHb1wiLFwiY29sb3JcIjpcIiMwMEFERDhcIn0sXCJzdGFyZ2F6ZXJzXCI6e1widG90YWxDb3VudFwiOjB9LFwiZm9ya0NvdW50XCI6MCxcImNyZWF0ZWRBdFwiOlwiMjAxOC0xMS0wNlQyMTowNTowMFpcIixcIm5hbWVXaXRoT3duZXJcIjpcImtyaXNrb2cvOGJhbGwtYmFja2VuZFwiLFwibmFtZVwiOlwiOGJhbGwtYmFja2VuZFwiLFwidXBkYXRlZEF0XCI6XCIyMDE4LTExLTIwVDA5OjMzOjI2WlwiLFwicHVzaGVkQXRcIjpcIjIwMTgtMTEtMjBUMDk6MzM6MjRaXCIsXCJkZXNjcmlwdGlvblwiOm51bGwsXCJ1cmxcIjpcImh0dHBzOi8vZ2l0aHViLmNvbS9rcmlza29nLzhiYWxsLWJhY2tlbmRcIixcImxpY2Vuc2VJbmZvXCI6bnVsbH0se1wicHJpbWFyeUxhbmd1YWdlXCI6e1wibmFtZVwiOlwiSFRNTFwiLFwiY29sb3JcIjpcIiNlMzRjMjZcIn0sXCJzdGFyZ2F6ZXJzXCI6e1widG90YWxDb3VudFwiOjB9LFwiZm9ya0NvdW50XCI6MCxcImNyZWF0ZWRBdFwiOlwiMjAxOC0xMS0wNlQyMTo1NDoyMVpcIixcIm5hbWVXaXRoT3duZXJcIjpcImtyaXNrb2cvOGJhbGwtZnJvbnRlbmRcIixcIm5hbWVcIjpcIjhiYWxsLWZyb250ZW5kXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMTgtMTEtMjBUMDY6MjM6MjBaXCIsXCJwdXNoZWRBdFwiOlwiMjAxOC0xMS0yMFQwNjoyMzoxOVpcIixcImRlc2NyaXB0aW9uXCI6bnVsbCxcInVybFwiOlwiaHR0cHM6Ly9naXRodWIuY29tL2tyaXNrb2cvOGJhbGwtZnJvbnRlbmRcIixcImxpY2Vuc2VJbmZvXCI6bnVsbH0se1wicHJpbWFyeUxhbmd1YWdlXCI6e1wibmFtZVwiOlwiR29cIixcImNvbG9yXCI6XCIjMDBBREQ4XCJ9LFwic3RhcmdhemVyc1wiOntcInRvdGFsQ291bnRcIjowfSxcImZvcmtDb3VudFwiOjAsXCJjcmVhdGVkQXRcIjpcIjIwMTgtMTAtMjRUMjM6MTg6MjVaXCIsXCJuYW1lV2l0aE93bmVyXCI6XCJNYXJjdXNNYXRoaWFzc2VuL0lHQ0luZm9WaWV3ZXIyXCIsXCJuYW1lXCI6XCJJR0NJbmZvVmlld2VyMlwiLFwidXBkYXRlZEF0XCI6XCIyMDE4LTEwLTI5VDIyOjAyOjQ5WlwiLFwicHVzaGVkQXRcIjpcIjIwMTgtMTAtMjlUMjI6MDI6NDhaXCIsXCJkZXNjcmlwdGlvblwiOm51bGwsXCJ1cmxcIjpcImh0dHBzOi8vZ2l0aHViLmNvbS9NYXJjdXNNYXRoaWFzc2VuL0lHQ0luZm9WaWV3ZXIyXCIsXCJsaWNlbnNlSW5mb1wiOm51bGx9LHtcInByaW1hcnlMYW5ndWFnZVwiOntcIm5hbWVcIjpcIkdvXCIsXCJjb2xvclwiOlwiIzAwQUREOFwifSxcInN0YXJnYXplcnNcIjp7XCJ0b3RhbENvdW50XCI6MH0sXCJmb3JrQ291bnRcIjowLFwiY3JlYXRlZEF0XCI6XCIyMDE4LTEwLTEwVDEzOjM1OjMxWlwiLFwibmFtZVdpdGhPd25lclwiOlwiTWFyY3VzTWF0aGlhc3Nlbi9JR0NJbmZvVmlld2VyXCIsXCJuYW1lXCI6XCJJR0NJbmZvVmlld2VyXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMTgtMTAtMjRUMjI6NDg6MjNaXCIsXCJwdXNoZWRBdFwiOlwiMjAxOC0xMC0yNFQyMjo0ODoyMVpcIixcImRlc2NyaXB0aW9uXCI6bnVsbCxcInVybFwiOlwiaHR0cHM6Ly9naXRodWIuY29tL01hcmN1c01hdGhpYXNzZW4vSUdDSW5mb1ZpZXdlclwiLFwibGljZW5zZUluZm9cIjpudWxsfSx7XCJwcmltYXJ5TGFuZ3VhZ2VcIjp7XCJuYW1lXCI6XCJDXCIsXCJjb2xvclwiOlwiIzU1NTU1NVwifSxcInN0YXJnYXplcnNcIjp7XCJ0b3RhbENvdW50XCI6MH0sXCJmb3JrQ291bnRcIjowLFwiY3JlYXRlZEF0XCI6XCIyMDE3LTA0LTE5VDIxOjIwOjMzWlwiLFwibmFtZVdpdGhPd25lclwiOlwiTWFyY3VzTWF0aGlhc3Nlbi9Hb256YWxlc1wiLFwibmFtZVwiOlwiR29uemFsZXNcIixcInVwZGF0ZWRBdFwiOlwiMjAxNy0wNC0yNlQxMTo0NzoxMFpcIixcInB1c2hlZEF0XCI6XCIyMDE3LTA5LTAzVDExOjQ0OjE3WlwiLFwiZGVzY3JpcHRpb25cIjpudWxsLFwidXJsXCI6XCJodHRwczovL2dpdGh1Yi5jb20vTWFyY3VzTWF0aGlhc3Nlbi9Hb256YWxlc1wiLFwibGljZW5zZUluZm9cIjpudWxsfV0nKVxuXG48L3NjcmlwdD5cblxuPHN0eWxlIGxhbmc9XCJzYXNzXCI+LmxhbmRpbmctcGFnZS0taGVybyB7XG4gIHdpZHRoOiA1MCU7XG4gIG1hcmdpbjogMjBweCBhdXRvO1xuICBkaXNwbGF5OiBibG9jaztcbiAgYmFja2dyb3VuZC1pbWFnZTogdmFyKC0tYXZhdGFyKTtcbiAgYmFja2dyb3VuZC1zaXplOiBjb3ZlcjtcbiAgd2lkdGg6IDMwMHB4O1xuICBoZWlnaHQ6IDMwMHB4OyB9XG5cbmxpLCB1bCB7XG4gIG1hcmdpbjogNXB4O1xuICBtYXJnaW4tdG9wOiAxMHB4O1xuICBsaXN0LXN0eWxlLXR5cGU6IG5vbmU7IH1cblxuc3BhbiB7XG4gIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250KTsgfVxuXG4uY29udGFpbmVyIHtcbiAgZGlzcGxheTogZmxleDtcbiAgZmxleC1mbG93OiByb3cgd3JhcDtcbiAganVzdGlmeS1jb250ZW50OiBzcGFjZS1hcm91bmQ7IH1cblxuLmNvbnRhaW5lci0tcmVwb3Mge1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7IH1cblxuLnJlcG9zIHtcbiAgbWFyZ2luOiAyMHB4O1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7IH1cbiAgLnJlcG9zIGgyIHtcbiAgICBwYWRkaW5nOiA1cHg7XG4gICAgdGV4dC1hbGlnbjogbGVmdDtcbiAgICBmb250LXdlaWdodDogNTAwOyB9XG4gIEBtZWRpYSBvbmx5IHNjcmVlbiBhbmQgKG1heC13aWR0aDogNjAwcHgpIHtcbiAgICAucmVwb3Mge1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgcGFkZGluZzogMDsgfSB9XG5cbi5yZXBvIHtcbiAgZGlzcGxheTogZmxleDtcbiAgbWFyZ2luOiA1cHg7XG4gIHBhZGRpbmc6IDVweDtcbiAgb3BhY2l0eTogMC43OyB9XG4gIC5yZXBvOmhvdmVyIHtcbiAgICBvcGFjaXR5OiAxLjA7IH1cbiAgQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiA2MDBweCkge1xuICAgIC5yZXBvIHtcbiAgICAgIGZvbnQtc2l6ZTogMC43NWVtOyB9IH1cblxuLnJlcG8tLW5hbWUge1xuICBmb250LXNpemU6IDFlbTtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwO1xuICB0ZXh0LWFsaWduOiBsZWZ0OyB9XG5cbi5yZXBvLS1iYWRnZXMge1xuICAtLWM6IGJsdWU7XG4gIGJhY2tncm91bmQ6IHZhcigtLXNlY29uZGFyeSk7XG4gIG1hcmdpbjogNXB4O1xuICBwYWRkaW5nOiA1cHg7XG4gIGJvcmRlci1yYWRpdXM6IHZhcigtLWJvcmRlci1yYWRpdXMpO1xuICBmb250LXNpemU6IDAuNzVlbTsgfVxuICAucmVwby0tYmFkZ2VzIHNwYW4ge1xuICAgIG1hcmdpbjogMnB4OyB9XG5cbi5yZXBvLS1sYW5nYXVnZSB7XG4gIGNvbG9yOiB2YXIoLS1jKTtcbiAgcGFkZGluZzogNXB4O1xuICBwYWRkaW5nLXRvcDogMXB4O1xuICBwYWRkaW5nLWJvdHRvbTogMXB4O1xuICBib3JkZXItcmFkaXVzOiA1cHg7XG4gIGZvbnQtc2l6ZTogMWVtO1xuICBmb250LXdlaWdodDogNzAwOyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICAgIDx0aXRsZT5Ib21lPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyLS1oZXJvXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLWhlcm9cIj48L2Rpdj5cbiAgICAgICAgPHAgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLXRpdFwiPk1hcmN1cyBNYXRoaWFzc2VuPC9wPlxuICAgICAgICA8cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tc3VidGl0bGVcIj5JIGRvIGNvbXBpbGVycyBhbmQgbGFuZ3VhZ2VzLiA8YnI+SW50ZXJlc3RlZCBpbiBzeXN0ZW1zIGRlc2lnbiBhbmQgVVguPC9wPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJjb250YWluZXItLXJlcG9zXCI+XG4gICAgICAgIDx1bCBjbGFzcz1cInJlcG9zXCI+XG4gICAgICAgICAgICA8aDI+UmVwb3NpdG9yaWVzPC9oMj5cbiAgICAgICAgXHR7I2VhY2ggcmVwb3MgYXMgcmVwb31cbiAgICAgICAgICAgICAgICA8bGkgY2xhc3M9XCJyZXBvXCI+XG4gICAgICAgICAgICAgICAgICAgIDxhIGhyZWY9XCJ7cmVwby51cmx9XCIgdGFyZ2V0PVwiX2JsYW5rXCIgcmVsPVwibm9vcGVuZXJcIj5cbiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJyZXBvLS1uYW1lXCI+e3JlcG8ubmFtZX0gPC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLWJhZGdlc1wiIHN0eWxlPVwiLS1jOiB7cmVwby5wcmltYXJ5TGFuZ3VhZ2UuY29sb3J9XCI+XG4gICAgICAgICAgICAgICAgICAgIHsjaWYgcmVwby5wcmltYXJ5TGFuZ3VhZ2V9XG4gICAgICAgICAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLWxhbmdhdWdlXCI+IHtyZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lfTwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgICAgICAgICAgeyNpZiByZXBvLnN0YXJnYXplcnMudG90YWxDb3VudH1cbiAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpIGNsYXNzPVwiZmFzIGZhLXN0YXJcIiBzdHlsZT1cImNvbG9yOiBnb2xkICFpbXBvcnRhbnRcIj48L2k+XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4+e3JlcG8uc3RhcmdhemVycy50b3RhbENvdW50fTwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgICAgICAgICAgeyNpZiByZXBvLmZvcmtDb3VudH1cbiAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpIGNsYXNzPVwiZmFzIGZhLWNvZGUtYnJhbmNoXCIgc3R5bGU9XCJjb2xvcjogI2M5NGRhMCAhaW1wb3J0YW50XCI+PC9pPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPntyZXBvLmZvcmtDb3VudH08L3NwYW4+XG4gICAgICAgICAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPC9hPlxuICAgICAgICAgICAgICAgIDwvbGk+XG4gICAgICAgIFx0ey9lYWNofVxuICAgICAgICA8L3VsPlxuICAgIDwvZGl2PlxuPC9kaXY+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBNEJtQixtQkFBbUIsY0FBQyxDQUFDLEFBQ3RDLEtBQUssQ0FBRSxHQUFHLENBQ1YsTUFBTSxDQUFFLElBQUksQ0FBQyxJQUFJLENBQ2pCLE9BQU8sQ0FBRSxLQUFLLENBQ2QsZ0JBQWdCLENBQUUsSUFBSSxRQUFRLENBQUMsQ0FDL0IsZUFBZSxDQUFFLEtBQUssQ0FDdEIsS0FBSyxDQUFFLEtBQUssQ0FDWixNQUFNLENBQUUsS0FBSyxBQUFFLENBQUMsQUFFbEIsZ0JBQUUsQ0FBRSxFQUFFLGNBQUMsQ0FBQyxBQUNOLE1BQU0sQ0FBRSxHQUFHLENBQ1gsVUFBVSxDQUFFLElBQUksQ0FDaEIsZUFBZSxDQUFFLElBQUksQUFBRSxDQUFDLEFBRTFCLElBQUksY0FBQyxDQUFDLEFBQ0osV0FBVyxDQUFFLElBQUksTUFBTSxDQUFDLEFBQUUsQ0FBQyxBQUU3QixVQUFVLGNBQUMsQ0FBQyxBQUNWLE9BQU8sQ0FBRSxJQUFJLENBQ2IsU0FBUyxDQUFFLEdBQUcsQ0FBQyxJQUFJLENBQ25CLGVBQWUsQ0FBRSxZQUFZLEFBQUUsQ0FBQyxBQUVsQyxpQkFBaUIsY0FBQyxDQUFDLEFBQ2pCLFVBQVUsQ0FBRSxNQUFNLEFBQUUsQ0FBQyxBQUV2QixNQUFNLGNBQUMsQ0FBQyxBQUNOLE1BQU0sQ0FBRSxJQUFJLENBQ1osT0FBTyxDQUFFLFlBQVksQUFBRSxDQUFDLEFBQ3hCLG9CQUFNLENBQUMsRUFBRSxjQUFDLENBQUMsQUFDVCxPQUFPLENBQUUsR0FBRyxDQUNaLFVBQVUsQ0FBRSxJQUFJLENBQ2hCLFdBQVcsQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUNyQixPQUFPLElBQUksQ0FBQyxNQUFNLENBQUMsR0FBRyxDQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUN6QyxNQUFNLGNBQUMsQ0FBQyxBQUNOLE1BQU0sQ0FBRSxDQUFDLENBQ1QsT0FBTyxDQUFFLENBQUMsQUFBRSxDQUFDLEFBQUMsQ0FBQyxBQUVyQixLQUFLLGNBQUMsQ0FBQyxBQUNMLE9BQU8sQ0FBRSxJQUFJLENBQ2IsTUFBTSxDQUFFLEdBQUcsQ0FDWCxPQUFPLENBQUUsR0FBRyxDQUNaLE9BQU8sQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUNmLG1CQUFLLE1BQU0sQUFBQyxDQUFDLEFBQ1gsT0FBTyxDQUFFLEdBQUcsQUFBRSxDQUFDLEFBQ2pCLE9BQU8sSUFBSSxDQUFDLE1BQU0sQ0FBQyxHQUFHLENBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pDLEtBQUssY0FBQyxDQUFDLEFBQ0wsU0FBUyxDQUFFLE1BQU0sQUFBRSxDQUFDLEFBQUMsQ0FBQyxBQUU1QixXQUFXLGNBQUMsQ0FBQyxBQUNYLFNBQVMsQ0FBRSxHQUFHLENBQ2QsT0FBTyxDQUFFLENBQUMsQ0FDVixNQUFNLENBQUUsQ0FBQyxDQUNULFVBQVUsQ0FBRSxJQUFJLEFBQUUsQ0FBQyxBQUVyQixhQUFhLGNBQUMsQ0FBQyxBQUNiLEdBQUcsQ0FBRSxJQUFJLENBQ1QsVUFBVSxDQUFFLElBQUksV0FBVyxDQUFDLENBQzVCLE1BQU0sQ0FBRSxHQUFHLENBQ1gsT0FBTyxDQUFFLEdBQUcsQ0FDWixhQUFhLENBQUUsSUFBSSxlQUFlLENBQUMsQ0FDbkMsU0FBUyxDQUFFLE1BQU0sQUFBRSxDQUFDLEFBQ3BCLDJCQUFhLENBQUMsSUFBSSxjQUFDLENBQUMsQUFDbEIsTUFBTSxDQUFFLEdBQUcsQUFBRSxDQUFDLEFBRWxCLGVBQWUsY0FBQyxDQUFDLEFBQ2YsS0FBSyxDQUFFLElBQUksR0FBRyxDQUFDLENBQ2YsT0FBTyxDQUFFLEdBQUcsQ0FDWixXQUFXLENBQUUsR0FBRyxDQUNoQixjQUFjLENBQUUsR0FBRyxDQUNuQixhQUFhLENBQUUsR0FBRyxDQUNsQixTQUFTLENBQUUsR0FBRyxDQUNkLFdBQVcsQ0FBRSxHQUFHLEFBQUUsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.repo = list[i];
	return child_ctx;
}

// (122:20) {#if repo.primaryLanguage}
function create_if_block_2(ctx) {
	var span, t_value = ctx.repo.primaryLanguage.name + "", t;

	return {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span, "class", "repo--langauge svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 122, 24, 7702);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.primaryLanguage.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span);
			}
		}
	};
}

// (125:20) {#if repo.stargazers.totalCount}
function create_if_block_1(ctx) {
	var span1, i, t0, span0, t1_value = ctx.repo.stargazers.totalCount + "", t1;

	return {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n                            ");

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(i, "class", "fas fa-star");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "gold", 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 126, 28, 7905);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 127, 28, 7992);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 125, 24, 7870);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t1_value !== (t1_value = ctx.repo.stargazers.totalCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span1);
			}
		}
	};
}

// (131:20) {#if repo.forkCount}
function create_if_block(ctx) {
	var span1, i, t0, span0, t1_value = ctx.repo.forkCount + "", t1;

	return {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n                            ");

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(i, "class", "fas fa-code-branch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "#c94da0", 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 132, 28, 8192);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 133, 28, 8289);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 131, 24, 8157);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t1_value !== (t1_value = ctx.repo.forkCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span1);
			}
		}
	};
}

// (117:9) {#each repos as repo}
function create_each_block(ctx) {
	var li, a, span0, t0_value = ctx.repo.name + "", t0, t1, span1, t2, t3, a_href_value, t4;

	var if_block0 = (ctx.repo.primaryLanguage) && create_if_block_2(ctx);

	var if_block1 = (ctx.repo.stargazers.totalCount) && create_if_block_1(ctx);

	var if_block2 = (ctx.repo.forkCount) && create_if_block(ctx);

	return {
		c: function create() {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			if (if_block0) if_block0.c();
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "LI", { class: true }, false);
			var li_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "A", { href: true, target: true, rel: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t0_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a_nodes, "\n                    ");

			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true, style: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			if (if_block0) if_block0.l(span1_nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n                    ");
			if (if_block1) if_block1.l(span1_nodes);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n                    ");
			if (if_block2) if_block2.l(span1_nodes);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li_nodes, "\n                ");
			li_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "repo--name svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 119, 20, 7496);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "repo--badges svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span1, "--c", ctx.repo.primaryLanguage.color);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 120, 20, 7561);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "href", a_href_value = ctx.repo.url);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 118, 20, 7423);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(li, "class", "repo svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li, file, 117, 16, 7385);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, li, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, span1);
			if (if_block0) if_block0.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t2);
			if (if_block1) if_block1.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t3);
			if (if_block2) if_block2.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li, t4);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t0_value !== (t0_value = ctx.repo.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, t0_value);
			}

			if (ctx.repo.primaryLanguage) {
				if (if_block0) {
					if_block0.p(changed, ctx);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(span1, t2);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (ctx.repo.stargazers.totalCount) {
				if (if_block1) {
					if_block1.p(changed, ctx);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(span1, t3);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (ctx.repo.forkCount) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(span1, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if (changed.repos) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span1, "--c", ctx.repo.primaryLanguage.color);
			}

			if ((changed.repos) && a_href_value !== (a_href_value = ctx.repo.url)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "href", a_href_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(li);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
		}
	};
}

function create_fragment(ctx) {
	var t0, div3, div1, div0, t1, p0, t2, t3, p1, t4, br, t5, t6, div2, ul, h2, t7, t8;

	var each_value = ctx.repos;

	var each_blocks = [];

	for (var i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Marcus Mathiassen");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I do compilers and languages. ");
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Interested in systems design and UX.");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Repositories");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n        ");

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Marcus Mathiassen");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n        ");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "I do compilers and languages. ");

			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "BR", {}, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Interested in systems design and UX.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div3_nodes, "\n    ");

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "H2", { class: true }, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Repositories");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n        \t");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Home";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "landing-page--hero svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 109, 8, 7016);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p0, "class", "landing-page--tit");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 110, 8, 7063);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 111, 72, 7186);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p1, "class", "landing-page--subtitle");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 111, 8, 7122);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div1, "class", "container--hero svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 108, 4, 6978);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h2, "class", "svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 115, 12, 7316);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(ul, "class", "repos svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 114, 8, 7285);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div2, "class", "container--repos svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 113, 4, 7246);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "class", "container svelte-323th6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 107, 0, 6950);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, br);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, ul);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h2, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t8);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.repos) {
				each_value = ctx.repos;

				for (var i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div3);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let repos = []

    const getApi = async (root, storage = sessionStorage) => {
        const result = storage.getItem(root)
        if (result !== null) {
            console.log("fetching github data... from storage")
            return JSON.parse(result)
        } else {
            console.log("fetching github data... github")
            const res = await fetch(root)
            const json = await res.json()
            storage.setItem(root, JSON.stringify(json))
            return json
        }
    }
    Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
        // repos = await getApi('/.netlify/functions/github')
    })

    // Test data
    // @Remove when deploying!!!
    $$invalidate('repos', repos = JSON.parse('[{"primaryLanguage":{"name":"JavaScript","color":"#f1e05a"},"stargazers":{"totalCount":1},"forkCount":0,"createdAt":"2019-03-31T13:26:30Z","nameWithOwner":"MarcusMathiassen/homepage","name":"homepage","updatedAt":"2019-09-08T13:26:22Z","pushedAt":"2019-09-08T13:26:20Z","description":"my personal page ","url":"https://github.com/MarcusMathiassen/homepage","licenseInfo":null},{"primaryLanguage":{"name":"C","color":"#555555"},"stargazers":{"totalCount":0},"forkCount":1,"createdAt":"2018-09-13T22:23:16Z","nameWithOwner":"MarcusMathiassen/thi","name":"thi","updatedAt":"2019-08-30T16:57:47Z","pushedAt":"2019-08-30T16:57:45Z","description":"A C like programming language","url":"https://github.com/MarcusMathiassen/thi","licenseInfo":null},{"primaryLanguage":{"name":"C++","color":"#f34b7d"},"stargazers":{"totalCount":0},"forkCount":0,"createdAt":"2017-07-28T01:50:48Z","nameWithOwner":"MarcusMathiassen/Athi","name":"Athi","updatedAt":"2019-08-30T14:42:33Z","pushedAt":"2019-08-30T14:42:26Z","description":"A continuation of my P2D project","url":"https://github.com/MarcusMathiassen/Athi","licenseInfo":null},{"primaryLanguage":{"name":"C++","color":"#f34b7d"},"stargazers":{"totalCount":32},"forkCount":15,"createdAt":"2017-03-18T20:05:04Z","nameWithOwner":"MarcusMathiassen/BasicRaytracer30min","name":"BasicRaytracer30min","updatedAt":"2019-08-27T02:08:34Z","pushedAt":"2017-03-19T01:38:59Z","description":"https://youtu.be/ARn_yhgk7aE","url":"https://github.com/MarcusMathiassen/BasicRaytracer30min","licenseInfo":null},{"primaryLanguage":{"name":"C++","color":"#f34b7d"},"stargazers":{"totalCount":1},"forkCount":0,"createdAt":"2017-09-05T00:54:12Z","nameWithOwner":"MarcusMathiassen/Revork","name":"Revork","updatedAt":"2019-04-02T20:53:27Z","pushedAt":"2017-12-13T07:40:55Z","description":"3D engine","url":"https://github.com/MarcusMathiassen/Revork","licenseInfo":null},{"primaryLanguage":{"name":"C","color":"#555555"},"stargazers":{"totalCount":0},"forkCount":0,"createdAt":"2019-02-03T18:45:26Z","nameWithOwner":"MarcusMathiassen/chip8","name":"chip8","updatedAt":"2019-04-02T12:11:09Z","pushedAt":"2019-02-03T21:43:31Z","description":"CHIP-8 Emulator","url":"https://github.com/MarcusMathiassen/chip8","licenseInfo":null},{"primaryLanguage":{"name":"Swift","color":"#ffac45"},"stargazers":{"totalCount":0},"forkCount":0,"createdAt":"2018-04-05T16:53:00Z","nameWithOwner":"MarcusMathiassen/athiNative","name":"athiNative","updatedAt":"2019-04-02T12:09:46Z","pushedAt":"2019-02-14T02:15:31Z","description":"The same as my Athi project but in Swift and Metal.","url":"https://github.com/MarcusMathiassen/athiNative","licenseInfo":null},{"primaryLanguage":{"name":"C","color":"#555555"},"stargazers":{"totalCount":10},"forkCount":2,"createdAt":"2016-06-05T19:01:31Z","nameWithOwner":"MarcusMathiassen/P2D","name":"P2D","updatedAt":"2019-02-04T17:19:03Z","pushedAt":"2017-03-18T21:52:50Z","description":"Bouncy balls","url":"https://github.com/MarcusMathiassen/P2D","licenseInfo":null},{"primaryLanguage":{"name":"Go","color":"#00ADD8"},"stargazers":{"totalCount":0},"forkCount":0,"createdAt":"2018-11-06T21:05:00Z","nameWithOwner":"kriskog/8ball-backend","name":"8ball-backend","updatedAt":"2018-11-20T09:33:26Z","pushedAt":"2018-11-20T09:33:24Z","description":null,"url":"https://github.com/kriskog/8ball-backend","licenseInfo":null},{"primaryLanguage":{"name":"HTML","color":"#e34c26"},"stargazers":{"totalCount":0},"forkCount":0,"createdAt":"2018-11-06T21:54:21Z","nameWithOwner":"kriskog/8ball-frontend","name":"8ball-frontend","updatedAt":"2018-11-20T06:23:20Z","pushedAt":"2018-11-20T06:23:19Z","description":null,"url":"https://github.com/kriskog/8ball-frontend","licenseInfo":null},{"primaryLanguage":{"name":"Go","color":"#00ADD8"},"stargazers":{"totalCount":0},"forkCount":0,"createdAt":"2018-10-24T23:18:25Z","nameWithOwner":"MarcusMathiassen/IGCInfoViewer2","name":"IGCInfoViewer2","updatedAt":"2018-10-29T22:02:49Z","pushedAt":"2018-10-29T22:02:48Z","description":null,"url":"https://github.com/MarcusMathiassen/IGCInfoViewer2","licenseInfo":null},{"primaryLanguage":{"name":"Go","color":"#00ADD8"},"stargazers":{"totalCount":0},"forkCount":0,"createdAt":"2018-10-10T13:35:31Z","nameWithOwner":"MarcusMathiassen/IGCInfoViewer","name":"IGCInfoViewer","updatedAt":"2018-10-24T22:48:23Z","pushedAt":"2018-10-24T22:48:21Z","description":null,"url":"https://github.com/MarcusMathiassen/IGCInfoViewer","licenseInfo":null},{"primaryLanguage":{"name":"C","color":"#555555"},"stargazers":{"totalCount":0},"forkCount":0,"createdAt":"2017-04-19T21:20:33Z","nameWithOwner":"MarcusMathiassen/Gonzales","name":"Gonzales","updatedAt":"2017-04-26T11:47:10Z","pushedAt":"2017-09-03T11:44:17Z","description":null,"url":"https://github.com/MarcusMathiassen/Gonzales","licenseInfo":null}]'))

	return { repos };
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-323th6-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9pbmRleC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkEwSHVELElBQUksQ0FBQyxlQUFlLENBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7cURBQXpCLElBQUksQ0FBQyxlQUFlLENBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7O3lDQUs3QyxJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VEQUExQixJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7Ozt5Q0FNMUIsSUFBSSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VEQUFkLElBQUksQ0FBQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7a0NBZEgsSUFBSSxDQUFDLElBQUk7O3NCQUU5QixJQUFJLENBQUMsZUFBZTs7c0JBR3BCLElBQUksQ0FBQyxVQUFVLENBQUMsVUFBVTs7c0JBTTFCLElBQUksQ0FBQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VGQVZxQixJQUFJLENBQUMsZUFBZSxDQUFDLEtBQUs7OzhGQUZ4RCxJQUFJLENBQUMsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VEQUNRLElBQUksQ0FBQyxJQUFJOzs7O1dBRTlCLElBQUksQ0FBQyxlQUFlOzs7Ozs7Ozs7Ozs7O1dBR3BCLElBQUksQ0FBQyxVQUFVLENBQUMsVUFBVTs7Ozs7Ozs7Ozs7OztXQU0xQixJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7d0ZBVnFCLElBQUksQ0FBQyxlQUFlLENBQUMsS0FBSzs7OytEQUZ4RCxJQUFJLENBQUMsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0JBRnRCLEtBQUs7Ozs7Z0NBQVY7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7OztxQkFBSyxLQUFLOzttQ0FBVjs7Ozs7Ozs7Ozs7OzJCQUFBOzs7Z0JBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Q0FqSFAsSUFBSSxLQUFLLEdBQUcsRUFBRTs7SUFFZCxNQUFNLE1BQU0sR0FBRyxPQUFPLElBQUksRUFBRSxPQUFPLEdBQUcsY0FBYyxLQUFLO1FBQ3JELE1BQU0sTUFBTSxHQUFHLE9BQU8sQ0FBQyxPQUFPLENBQUMsSUFBSSxDQUFDO1FBQ3BDLElBQUksTUFBTSxLQUFLLElBQUksRUFBRTtZQUNqQixPQUFPLENBQUMsR0FBRyxDQUFDLHNDQUFzQyxDQUFDO1lBQ25ELE9BQU8sSUFBSSxDQUFDLEtBQUssQ0FBQyxNQUFNLENBQUM7U0FDNUIsTUFBTTtZQUNILE9BQU8sQ0FBQyxHQUFHLENBQUMsZ0NBQWdDLENBQUM7WUFDN0MsTUFBTSxHQUFHLEdBQUcsTUFBTSxLQUFLLENBQUMsSUFBSSxDQUFDO1lBQzdCLE1BQU0sSUFBSSxHQUFHLE1BQU0sR0FBRyxDQUFDLElBQUksRUFBRTtZQUM3QixPQUFPLENBQUMsT0FBTyxDQUFDLElBQUksRUFBRSxJQUFJLENBQUMsU0FBUyxDQUFDLElBQUksQ0FBQyxDQUFDO1lBQzNDLE9BQU8sSUFBSTtTQUNkO0tBQ0o7SUFDRCxzREFBTyxDQUFDLFlBQVk7O0tBRW5CLENBQUM7Ozs7MEJBSUYsS0FBSyxHQUFHLElBQUksQ0FBQyxLQUFLLENBQUMsNHJKQUE0ckosQ0FBQyIsImZpbGUiOiI2MDlkODc0ZTRlMDcyYjE4NDE4NC9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gICAgaW1wb3J0IHsgb25Nb3VudCB9IGZyb20gJ3N2ZWx0ZSdcblxuICAgIGxldCByZXBvcyA9IFtdXG5cbiAgICBjb25zdCBnZXRBcGkgPSBhc3luYyAocm9vdCwgc3RvcmFnZSA9IHNlc3Npb25TdG9yYWdlKSA9PiB7XG4gICAgICAgIGNvbnN0IHJlc3VsdCA9IHN0b3JhZ2UuZ2V0SXRlbShyb290KVxuICAgICAgICBpZiAocmVzdWx0ICE9PSBudWxsKSB7XG4gICAgICAgICAgICBjb25zb2xlLmxvZyhcImZldGNoaW5nIGdpdGh1YiBkYXRhLi4uIGZyb20gc3RvcmFnZVwiKVxuICAgICAgICAgICAgcmV0dXJuIEpTT04ucGFyc2UocmVzdWx0KVxuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgICAgY29uc29sZS5sb2coXCJmZXRjaGluZyBnaXRodWIgZGF0YS4uLiBnaXRodWJcIilcbiAgICAgICAgICAgIGNvbnN0IHJlcyA9IGF3YWl0IGZldGNoKHJvb3QpXG4gICAgICAgICAgICBjb25zdCBqc29uID0gYXdhaXQgcmVzLmpzb24oKVxuICAgICAgICAgICAgc3RvcmFnZS5zZXRJdGVtKHJvb3QsIEpTT04uc3RyaW5naWZ5KGpzb24pKVxuICAgICAgICAgICAgcmV0dXJuIGpzb25cbiAgICAgICAgfVxuICAgIH1cbiAgICBvbk1vdW50KGFzeW5jICgpID0+IHtcbiAgICAgICAgLy8gcmVwb3MgPSBhd2FpdCBnZXRBcGkoJy8ubmV0bGlmeS9mdW5jdGlvbnMvZ2l0aHViJylcbiAgICB9KVxuXG4gICAgLy8gVGVzdCBkYXRhXG4gICAgLy8gQFJlbW92ZSB3aGVuIGRlcGxveWluZyEhIVxuICAgIHJlcG9zID0gSlNPTi5wYXJzZSgnW3tcInByaW1hcnlMYW5ndWFnZVwiOntcIm5hbWVcIjpcIkphdmFTY3JpcHRcIixcImNvbG9yXCI6XCIjZjFlMDVhXCJ9LFwic3RhcmdhemVyc1wiOntcInRvdGFsQ291bnRcIjoxfSxcImZvcmtDb3VudFwiOjAsXCJjcmVhdGVkQXRcIjpcIjIwMTktMDMtMzFUMTM6MjY6MzBaXCIsXCJuYW1lV2l0aE93bmVyXCI6XCJNYXJjdXNNYXRoaWFzc2VuL2hvbWVwYWdlXCIsXCJuYW1lXCI6XCJob21lcGFnZVwiLFwidXBkYXRlZEF0XCI6XCIyMDE5LTA5LTA4VDEzOjI2OjIyWlwiLFwicHVzaGVkQXRcIjpcIjIwMTktMDktMDhUMTM6MjY6MjBaXCIsXCJkZXNjcmlwdGlvblwiOlwibXkgcGVyc29uYWwgcGFnZSBcIixcInVybFwiOlwiaHR0cHM6Ly9naXRodWIuY29tL01hcmN1c01hdGhpYXNzZW4vaG9tZXBhZ2VcIixcImxpY2Vuc2VJbmZvXCI6bnVsbH0se1wicHJpbWFyeUxhbmd1YWdlXCI6e1wibmFtZVwiOlwiQ1wiLFwiY29sb3JcIjpcIiM1NTU1NTVcIn0sXCJzdGFyZ2F6ZXJzXCI6e1widG90YWxDb3VudFwiOjB9LFwiZm9ya0NvdW50XCI6MSxcImNyZWF0ZWRBdFwiOlwiMjAxOC0wOS0xM1QyMjoyMzoxNlpcIixcIm5hbWVXaXRoT3duZXJcIjpcIk1hcmN1c01hdGhpYXNzZW4vdGhpXCIsXCJuYW1lXCI6XCJ0aGlcIixcInVwZGF0ZWRBdFwiOlwiMjAxOS0wOC0zMFQxNjo1Nzo0N1pcIixcInB1c2hlZEF0XCI6XCIyMDE5LTA4LTMwVDE2OjU3OjQ1WlwiLFwiZGVzY3JpcHRpb25cIjpcIkEgQyBsaWtlIHByb2dyYW1taW5nIGxhbmd1YWdlXCIsXCJ1cmxcIjpcImh0dHBzOi8vZ2l0aHViLmNvbS9NYXJjdXNNYXRoaWFzc2VuL3RoaVwiLFwibGljZW5zZUluZm9cIjpudWxsfSx7XCJwcmltYXJ5TGFuZ3VhZ2VcIjp7XCJuYW1lXCI6XCJDKytcIixcImNvbG9yXCI6XCIjZjM0YjdkXCJ9LFwic3RhcmdhemVyc1wiOntcInRvdGFsQ291bnRcIjowfSxcImZvcmtDb3VudFwiOjAsXCJjcmVhdGVkQXRcIjpcIjIwMTctMDctMjhUMDE6NTA6NDhaXCIsXCJuYW1lV2l0aE93bmVyXCI6XCJNYXJjdXNNYXRoaWFzc2VuL0F0aGlcIixcIm5hbWVcIjpcIkF0aGlcIixcInVwZGF0ZWRBdFwiOlwiMjAxOS0wOC0zMFQxNDo0MjozM1pcIixcInB1c2hlZEF0XCI6XCIyMDE5LTA4LTMwVDE0OjQyOjI2WlwiLFwiZGVzY3JpcHRpb25cIjpcIkEgY29udGludWF0aW9uIG9mIG15IFAyRCBwcm9qZWN0XCIsXCJ1cmxcIjpcImh0dHBzOi8vZ2l0aHViLmNvbS9NYXJjdXNNYXRoaWFzc2VuL0F0aGlcIixcImxpY2Vuc2VJbmZvXCI6bnVsbH0se1wicHJpbWFyeUxhbmd1YWdlXCI6e1wibmFtZVwiOlwiQysrXCIsXCJjb2xvclwiOlwiI2YzNGI3ZFwifSxcInN0YXJnYXplcnNcIjp7XCJ0b3RhbENvdW50XCI6MzJ9LFwiZm9ya0NvdW50XCI6MTUsXCJjcmVhdGVkQXRcIjpcIjIwMTctMDMtMThUMjA6MDU6MDRaXCIsXCJuYW1lV2l0aE93bmVyXCI6XCJNYXJjdXNNYXRoaWFzc2VuL0Jhc2ljUmF5dHJhY2VyMzBtaW5cIixcIm5hbWVcIjpcIkJhc2ljUmF5dHJhY2VyMzBtaW5cIixcInVwZGF0ZWRBdFwiOlwiMjAxOS0wOC0yN1QwMjowODozNFpcIixcInB1c2hlZEF0XCI6XCIyMDE3LTAzLTE5VDAxOjM4OjU5WlwiLFwiZGVzY3JpcHRpb25cIjpcImh0dHBzOi8veW91dHUuYmUvQVJuX3loZ2s3YUVcIixcInVybFwiOlwiaHR0cHM6Ly9naXRodWIuY29tL01hcmN1c01hdGhpYXNzZW4vQmFzaWNSYXl0cmFjZXIzMG1pblwiLFwibGljZW5zZUluZm9cIjpudWxsfSx7XCJwcmltYXJ5TGFuZ3VhZ2VcIjp7XCJuYW1lXCI6XCJDKytcIixcImNvbG9yXCI6XCIjZjM0YjdkXCJ9LFwic3RhcmdhemVyc1wiOntcInRvdGFsQ291bnRcIjoxfSxcImZvcmtDb3VudFwiOjAsXCJjcmVhdGVkQXRcIjpcIjIwMTctMDktMDVUMDA6NTQ6MTJaXCIsXCJuYW1lV2l0aE93bmVyXCI6XCJNYXJjdXNNYXRoaWFzc2VuL1Jldm9ya1wiLFwibmFtZVwiOlwiUmV2b3JrXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMTktMDQtMDJUMjA6NTM6MjdaXCIsXCJwdXNoZWRBdFwiOlwiMjAxNy0xMi0xM1QwNzo0MDo1NVpcIixcImRlc2NyaXB0aW9uXCI6XCIzRCBlbmdpbmVcIixcInVybFwiOlwiaHR0cHM6Ly9naXRodWIuY29tL01hcmN1c01hdGhpYXNzZW4vUmV2b3JrXCIsXCJsaWNlbnNlSW5mb1wiOm51bGx9LHtcInByaW1hcnlMYW5ndWFnZVwiOntcIm5hbWVcIjpcIkNcIixcImNvbG9yXCI6XCIjNTU1NTU1XCJ9LFwic3RhcmdhemVyc1wiOntcInRvdGFsQ291bnRcIjowfSxcImZvcmtDb3VudFwiOjAsXCJjcmVhdGVkQXRcIjpcIjIwMTktMDItMDNUMTg6NDU6MjZaXCIsXCJuYW1lV2l0aE93bmVyXCI6XCJNYXJjdXNNYXRoaWFzc2VuL2NoaXA4XCIsXCJuYW1lXCI6XCJjaGlwOFwiLFwidXBkYXRlZEF0XCI6XCIyMDE5LTA0LTAyVDEyOjExOjA5WlwiLFwicHVzaGVkQXRcIjpcIjIwMTktMDItMDNUMjE6NDM6MzFaXCIsXCJkZXNjcmlwdGlvblwiOlwiQ0hJUC04IEVtdWxhdG9yXCIsXCJ1cmxcIjpcImh0dHBzOi8vZ2l0aHViLmNvbS9NYXJjdXNNYXRoaWFzc2VuL2NoaXA4XCIsXCJsaWNlbnNlSW5mb1wiOm51bGx9LHtcInByaW1hcnlMYW5ndWFnZVwiOntcIm5hbWVcIjpcIlN3aWZ0XCIsXCJjb2xvclwiOlwiI2ZmYWM0NVwifSxcInN0YXJnYXplcnNcIjp7XCJ0b3RhbENvdW50XCI6MH0sXCJmb3JrQ291bnRcIjowLFwiY3JlYXRlZEF0XCI6XCIyMDE4LTA0LTA1VDE2OjUzOjAwWlwiLFwibmFtZVdpdGhPd25lclwiOlwiTWFyY3VzTWF0aGlhc3Nlbi9hdGhpTmF0aXZlXCIsXCJuYW1lXCI6XCJhdGhpTmF0aXZlXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMTktMDQtMDJUMTI6MDk6NDZaXCIsXCJwdXNoZWRBdFwiOlwiMjAxOS0wMi0xNFQwMjoxNTozMVpcIixcImRlc2NyaXB0aW9uXCI6XCJUaGUgc2FtZSBhcyBteSBBdGhpIHByb2plY3QgYnV0IGluIFN3aWZ0IGFuZCBNZXRhbC5cIixcInVybFwiOlwiaHR0cHM6Ly9naXRodWIuY29tL01hcmN1c01hdGhpYXNzZW4vYXRoaU5hdGl2ZVwiLFwibGljZW5zZUluZm9cIjpudWxsfSx7XCJwcmltYXJ5TGFuZ3VhZ2VcIjp7XCJuYW1lXCI6XCJDXCIsXCJjb2xvclwiOlwiIzU1NTU1NVwifSxcInN0YXJnYXplcnNcIjp7XCJ0b3RhbENvdW50XCI6MTB9LFwiZm9ya0NvdW50XCI6MixcImNyZWF0ZWRBdFwiOlwiMjAxNi0wNi0wNVQxOTowMTozMVpcIixcIm5hbWVXaXRoT3duZXJcIjpcIk1hcmN1c01hdGhpYXNzZW4vUDJEXCIsXCJuYW1lXCI6XCJQMkRcIixcInVwZGF0ZWRBdFwiOlwiMjAxOS0wMi0wNFQxNzoxOTowM1pcIixcInB1c2hlZEF0XCI6XCIyMDE3LTAzLTE4VDIxOjUyOjUwWlwiLFwiZGVzY3JpcHRpb25cIjpcIkJvdW5jeSBiYWxsc1wiLFwidXJsXCI6XCJodHRwczovL2dpdGh1Yi5jb20vTWFyY3VzTWF0aGlhc3Nlbi9QMkRcIixcImxpY2Vuc2VJbmZvXCI6bnVsbH0se1wicHJpbWFyeUxhbmd1YWdlXCI6e1wibmFtZVwiOlwiR29cIixcImNvbG9yXCI6XCIjMDBBREQ4XCJ9LFwic3RhcmdhemVyc1wiOntcInRvdGFsQ291bnRcIjowfSxcImZvcmtDb3VudFwiOjAsXCJjcmVhdGVkQXRcIjpcIjIwMTgtMTEtMDZUMjE6MDU6MDBaXCIsXCJuYW1lV2l0aE93bmVyXCI6XCJrcmlza29nLzhiYWxsLWJhY2tlbmRcIixcIm5hbWVcIjpcIjhiYWxsLWJhY2tlbmRcIixcInVwZGF0ZWRBdFwiOlwiMjAxOC0xMS0yMFQwOTozMzoyNlpcIixcInB1c2hlZEF0XCI6XCIyMDE4LTExLTIwVDA5OjMzOjI0WlwiLFwiZGVzY3JpcHRpb25cIjpudWxsLFwidXJsXCI6XCJodHRwczovL2dpdGh1Yi5jb20va3Jpc2tvZy84YmFsbC1iYWNrZW5kXCIsXCJsaWNlbnNlSW5mb1wiOm51bGx9LHtcInByaW1hcnlMYW5ndWFnZVwiOntcIm5hbWVcIjpcIkhUTUxcIixcImNvbG9yXCI6XCIjZTM0YzI2XCJ9LFwic3RhcmdhemVyc1wiOntcInRvdGFsQ291bnRcIjowfSxcImZvcmtDb3VudFwiOjAsXCJjcmVhdGVkQXRcIjpcIjIwMTgtMTEtMDZUMjE6NTQ6MjFaXCIsXCJuYW1lV2l0aE93bmVyXCI6XCJrcmlza29nLzhiYWxsLWZyb250ZW5kXCIsXCJuYW1lXCI6XCI4YmFsbC1mcm9udGVuZFwiLFwidXBkYXRlZEF0XCI6XCIyMDE4LTExLTIwVDA2OjIzOjIwWlwiLFwicHVzaGVkQXRcIjpcIjIwMTgtMTEtMjBUMDY6MjM6MTlaXCIsXCJkZXNjcmlwdGlvblwiOm51bGwsXCJ1cmxcIjpcImh0dHBzOi8vZ2l0aHViLmNvbS9rcmlza29nLzhiYWxsLWZyb250ZW5kXCIsXCJsaWNlbnNlSW5mb1wiOm51bGx9LHtcInByaW1hcnlMYW5ndWFnZVwiOntcIm5hbWVcIjpcIkdvXCIsXCJjb2xvclwiOlwiIzAwQUREOFwifSxcInN0YXJnYXplcnNcIjp7XCJ0b3RhbENvdW50XCI6MH0sXCJmb3JrQ291bnRcIjowLFwiY3JlYXRlZEF0XCI6XCIyMDE4LTEwLTI0VDIzOjE4OjI1WlwiLFwibmFtZVdpdGhPd25lclwiOlwiTWFyY3VzTWF0aGlhc3Nlbi9JR0NJbmZvVmlld2VyMlwiLFwibmFtZVwiOlwiSUdDSW5mb1ZpZXdlcjJcIixcInVwZGF0ZWRBdFwiOlwiMjAxOC0xMC0yOVQyMjowMjo0OVpcIixcInB1c2hlZEF0XCI6XCIyMDE4LTEwLTI5VDIyOjAyOjQ4WlwiLFwiZGVzY3JpcHRpb25cIjpudWxsLFwidXJsXCI6XCJodHRwczovL2dpdGh1Yi5jb20vTWFyY3VzTWF0aGlhc3Nlbi9JR0NJbmZvVmlld2VyMlwiLFwibGljZW5zZUluZm9cIjpudWxsfSx7XCJwcmltYXJ5TGFuZ3VhZ2VcIjp7XCJuYW1lXCI6XCJHb1wiLFwiY29sb3JcIjpcIiMwMEFERDhcIn0sXCJzdGFyZ2F6ZXJzXCI6e1widG90YWxDb3VudFwiOjB9LFwiZm9ya0NvdW50XCI6MCxcImNyZWF0ZWRBdFwiOlwiMjAxOC0xMC0xMFQxMzozNTozMVpcIixcIm5hbWVXaXRoT3duZXJcIjpcIk1hcmN1c01hdGhpYXNzZW4vSUdDSW5mb1ZpZXdlclwiLFwibmFtZVwiOlwiSUdDSW5mb1ZpZXdlclwiLFwidXBkYXRlZEF0XCI6XCIyMDE4LTEwLTI0VDIyOjQ4OjIzWlwiLFwicHVzaGVkQXRcIjpcIjIwMTgtMTAtMjRUMjI6NDg6MjFaXCIsXCJkZXNjcmlwdGlvblwiOm51bGwsXCJ1cmxcIjpcImh0dHBzOi8vZ2l0aHViLmNvbS9NYXJjdXNNYXRoaWFzc2VuL0lHQ0luZm9WaWV3ZXJcIixcImxpY2Vuc2VJbmZvXCI6bnVsbH0se1wicHJpbWFyeUxhbmd1YWdlXCI6e1wibmFtZVwiOlwiQ1wiLFwiY29sb3JcIjpcIiM1NTU1NTVcIn0sXCJzdGFyZ2F6ZXJzXCI6e1widG90YWxDb3VudFwiOjB9LFwiZm9ya0NvdW50XCI6MCxcImNyZWF0ZWRBdFwiOlwiMjAxNy0wNC0xOVQyMToyMDozM1pcIixcIm5hbWVXaXRoT3duZXJcIjpcIk1hcmN1c01hdGhpYXNzZW4vR29uemFsZXNcIixcIm5hbWVcIjpcIkdvbnphbGVzXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMTctMDQtMjZUMTE6NDc6MTBaXCIsXCJwdXNoZWRBdFwiOlwiMjAxNy0wOS0wM1QxMTo0NDoxN1pcIixcImRlc2NyaXB0aW9uXCI6bnVsbCxcInVybFwiOlwiaHR0cHM6Ly9naXRodWIuY29tL01hcmN1c01hdGhpYXNzZW4vR29uemFsZXNcIixcImxpY2Vuc2VJbmZvXCI6bnVsbH1dJylcblxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBsYW5nPVwic2Fzc1wiPi5sYW5kaW5nLXBhZ2UtLWhlcm8ge1xuICB3aWR0aDogNTAlO1xuICBtYXJnaW46IDIwcHggYXV0bztcbiAgZGlzcGxheTogYmxvY2s7XG4gIGJhY2tncm91bmQtaW1hZ2U6IHZhcigtLWF2YXRhcik7XG4gIGJhY2tncm91bmQtc2l6ZTogY292ZXI7XG4gIHdpZHRoOiAzMDBweDtcbiAgaGVpZ2h0OiAzMDBweDsgfVxuXG5saSwgdWwge1xuICBtYXJnaW46IDVweDtcbiAgbWFyZ2luLXRvcDogMTBweDtcbiAgbGlzdC1zdHlsZS10eXBlOiBub25lOyB9XG5cbnNwYW4ge1xuICBmb250LWZhbWlseTogdmFyKC0tZm9udCk7IH1cblxuLmNvbnRhaW5lciB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZmxvdzogcm93IHdyYXA7XG4gIGp1c3RpZnktY29udGVudDogc3BhY2UtYXJvdW5kOyB9XG5cbi5jb250YWluZXItLXJlcG9zIHtcbiAgdGV4dC1hbGlnbjogY2VudGVyOyB9XG5cbi5yZXBvcyB7XG4gIG1hcmdpbjogMjBweDtcbiAgZGlzcGxheTogaW5saW5lLWJsb2NrOyB9XG4gIC5yZXBvcyBoMiB7XG4gICAgcGFkZGluZzogNXB4O1xuICAgIHRleHQtYWxpZ246IGxlZnQ7XG4gICAgZm9udC13ZWlnaHQ6IDUwMDsgfVxuICBAbWVkaWEgb25seSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDYwMHB4KSB7XG4gICAgLnJlcG9zIHtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIHBhZGRpbmc6IDA7IH0gfVxuXG4ucmVwbyB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIG1hcmdpbjogNXB4O1xuICBwYWRkaW5nOiA1cHg7XG4gIG9wYWNpdHk6IDAuNzsgfVxuICAucmVwbzpob3ZlciB7XG4gICAgb3BhY2l0eTogMS4wOyB9XG4gIEBtZWRpYSBvbmx5IHNjcmVlbiBhbmQgKG1heC13aWR0aDogNjAwcHgpIHtcbiAgICAucmVwbyB7XG4gICAgICBmb250LXNpemU6IDAuNzVlbTsgfSB9XG5cbi5yZXBvLS1uYW1lIHtcbiAgZm9udC1zaXplOiAxZW07XG4gIHBhZGRpbmc6IDA7XG4gIG1hcmdpbjogMDtcbiAgdGV4dC1hbGlnbjogbGVmdDsgfVxuXG4ucmVwby0tYmFkZ2VzIHtcbiAgLS1jOiBibHVlO1xuICBiYWNrZ3JvdW5kOiB2YXIoLS1zZWNvbmRhcnkpO1xuICBtYXJnaW46IDVweDtcbiAgcGFkZGluZzogNXB4O1xuICBib3JkZXItcmFkaXVzOiB2YXIoLS1ib3JkZXItcmFkaXVzKTtcbiAgZm9udC1zaXplOiAwLjc1ZW07IH1cbiAgLnJlcG8tLWJhZGdlcyBzcGFuIHtcbiAgICBtYXJnaW46IDJweDsgfVxuXG4ucmVwby0tbGFuZ2F1Z2Uge1xuICBjb2xvcjogdmFyKC0tYyk7XG4gIHBhZGRpbmc6IDVweDtcbiAgcGFkZGluZy10b3A6IDFweDtcbiAgcGFkZGluZy1ib3R0b206IDFweDtcbiAgYm9yZGVyLXJhZGl1czogNXB4O1xuICBmb250LXNpemU6IDFlbTtcbiAgZm9udC13ZWlnaHQ6IDcwMDsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgICA8dGl0bGU+SG9tZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgPGRpdiBjbGFzcz1cImNvbnRhaW5lci0taGVyb1wiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwibGFuZGluZy1wYWdlLS1oZXJvXCI+PC9kaXY+XG4gICAgICAgIDxwIGNsYXNzPVwibGFuZGluZy1wYWdlLS10aXRcIj5NYXJjdXMgTWF0aGlhc3NlbjwvcD5cbiAgICAgICAgPHAgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLXN1YnRpdGxlXCI+SSBkbyBjb21waWxlcnMgYW5kIGxhbmd1YWdlcy4gPGJyPkludGVyZXN0ZWQgaW4gc3lzdGVtcyBkZXNpZ24gYW5kIFVYLjwvcD5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyLS1yZXBvc1wiPlxuICAgICAgICA8dWwgY2xhc3M9XCJyZXBvc1wiPlxuICAgICAgICAgICAgPGgyPlJlcG9zaXRvcmllczwvaDI+XG4gICAgICAgIFx0eyNlYWNoIHJlcG9zIGFzIHJlcG99XG4gICAgICAgICAgICAgICAgPGxpIGNsYXNzPVwicmVwb1wiPlxuICAgICAgICAgICAgICAgICAgICA8YSBocmVmPVwie3JlcG8udXJsfVwiIHRhcmdldD1cIl9ibGFua1wiIHJlbD1cIm5vb3BlbmVyXCI+XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwicmVwby0tbmFtZVwiPntyZXBvLm5hbWV9IDwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJyZXBvLS1iYWRnZXNcIiBzdHlsZT1cIi0tYzoge3JlcG8ucHJpbWFyeUxhbmd1YWdlLmNvbG9yfVwiPlxuICAgICAgICAgICAgICAgICAgICB7I2lmIHJlcG8ucHJpbWFyeUxhbmd1YWdlfVxuICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJyZXBvLS1sYW5nYXVnZVwiPiB7cmVwby5wcmltYXJ5TGFuZ3VhZ2UubmFtZX08L3NwYW4+XG4gICAgICAgICAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICAgICAgICAgIHsjaWYgcmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9XG4gICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1zdGFyXCIgc3R5bGU9XCJjb2xvcjogZ29sZCAhaW1wb3J0YW50XCI+PC9pPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuPntyZXBvLnN0YXJnYXplcnMudG90YWxDb3VudH08L3NwYW4+XG4gICAgICAgICAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICAgICAgICAgIHsjaWYgcmVwby5mb3JrQ291bnR9XG4gICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1jb2RlLWJyYW5jaFwiIHN0eWxlPVwiY29sb3I6ICNjOTRkYTAgIWltcG9ydGFudFwiPjwvaT5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3Bhbj57cmVwby5mb3JrQ291bnR9PC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICAgICAgICAgIDwvYT5cbiAgICAgICAgICAgICAgICA8L2xpPlxuICAgICAgICBcdHsvZWFjaH1cbiAgICAgICAgPC91bD5cbiAgICA8L2Rpdj5cbjwvZGl2PlxuIl0sInNvdXJjZVJvb3QiOiIifQ==