(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/repos.svelte":
/*!*************************************!*\
  !*** ./src/components/repos.svelte ***!
  \*************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _utils_utility__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./utils/utility */ "./src/components/utils/utility.js");
/* src/components/repos.svelte generated by Svelte v3.12.0 */




const file = "src/components/repos.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1jarja4-style';
	style.textContent = ".repos.svelte-1jarja4{text-align:left;display:inline-block}.repos.svelte-1jarja4 h2.svelte-1jarja4{padding:5px;text-align:left;font-weight:500}@media only screen and (max-width: 600px){.repos.svelte-1jarja4{margin:0;padding:0}}a.svelte-1jarja4{padding:0;margin:0}.repo.svelte-1jarja4{display:flex;opacity:0.0;animation:svelte-1jarja4-reveal 1s forwards}@media only screen and (max-width: 600px){.repo.svelte-1jarja4{font-size:0.75em}}.title.svelte-1jarja4{font-size:1em;padding:0;margin:0;text-align:left}.langauge.svelte-1jarja4{font-weight:500}.badge.svelte-1jarja4{background:var(--secondary);margin:0;padding:5px;border-radius:var(--border-radius);font-size:0.75em}.badge--item.svelte-1jarja4{margin:2px}@keyframes svelte-1jarja4-reveal{from{opacity:0.0}to{opacity:1.0}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVwb3Muc3ZlbHRlIiwic291cmNlcyI6WyJyZXBvcy5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJ1xuICAgIGltcG9ydCB7IGNhY2hlZEZldGNoIH0gZnJvbSAnLi91dGlscy91dGlsaXR5J1xuXG4gICAgbGV0IHJlcG9zID0gW11cblxuICAgIGxldCBsYW5ndWFnZUNvbG9yQ2hvaWNlc0l0ZXIgPSAwXG4gICAgbGV0IGxhbmd1YWdlQ29sb3JzID0gbmV3IE1hcCgpXG4gICAgY29uc3QgbGFuZ3VhZ2VDb2xvckNob2ljZXMgPSBbXG4gICAgICAgICd2YXIoLS1zeXN0ZW1CbHVlKScsXG4gICAgICAgICd2YXIoLS1zeXN0ZW1HcmF5KScsXG4gICAgICAgICd2YXIoLS1zeXN0ZW1HcmVlbiknLFxuICAgICAgICAndmFyKC0tc3lzdGVtSW5kaWdvKScsXG4gICAgICAgICd2YXIoLS1zeXN0ZW1PcmFuZ2UpJyxcbiAgICAgICAgJ3ZhcigtLXN5c3RlbVBpbmspJyxcbiAgICAgICAgJ3ZhcigtLXN5c3RlbVB1cnBsZSknLFxuICAgICAgICAndmFyKC0tc3lzdGVtUmVkKScsXG4gICAgICAgICd2YXIoLS1zeXN0ZW1UZWFsKScsXG4gICAgICAgICd2YXIoLS1zeXN0ZW1ZZWxsb3cpJ1xuICAgIF1cblxuICAgIGNvbnN0IHN0YXJCaWFzID0gMS41XG4gICAgY29uc3QgZm9ya0JpYXMgPSAyLjAgLy8gdmFsdWUgZm9ya3MgbW9yZSB0aGFuIHN0YXJzXG5cbiAgICBvbk1vdW50KGFzeW5jICgpID0+IHtcbiAgICAgICAgcmVwb3MgPSBhd2FpdCBjYWNoZWRGZXRjaCgnLy5uZXRsaWZ5L2Z1bmN0aW9ucy9naXRodWInKVxuICAgICAgICByZXBvcy5zb3J0KChhLCBiKSA9PiAoYi5zdGFyZ2F6ZXJzLnRvdGFsQ291bnQqc3RhckJpYXMgKyBiLmZvcmtDb3VudCpmb3JrQmlhcykgLSAgKGEuc3RhcmdhemVycy50b3RhbENvdW50KnN0YXJCaWFzICsgYS5mb3JrQ291bnQqZm9ya0JpYXMpKVxuXG4gICAgICAgIHJlcG9zLmZvckVhY2gocmVwbyA9PiB7XG4gICAgICAgICAgICBjb25zdCBuYW1lID0gcmVwby5wcmltYXJ5TGFuZ3VhZ2UubmFtZVxuXG4gICAgICAgICAgICBsZXQgY29sb3IgXG4gICAgICAgICAgICBpZiAobGFuZ3VhZ2VDb2xvcnMuaGFzKG5hbWUpKSB7XG4gICAgICAgICAgICAgICAgY29sb3IgPSBsYW5ndWFnZUNvbG9ycy5nZXQobmFtZSlcbiAgICAgICAgICAgIH0gZWxzZSBjb2xvciA9IGxhbmd1YWdlQ29sb3JDaG9pY2VzW2xhbmd1YWdlQ29sb3JDaG9pY2VzSXRlcisrICUgbGFuZ3VhZ2VDb2xvckNob2ljZXMubGVuZ3RoXVxuICAgICAgICAgICAgXG4gICAgICAgICAgICBjb25zb2xlLmxvZyhuYW1lLCBjb2xvcilcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbGFuZ3VhZ2VDb2xvcnMuc2V0KG5hbWUsIGNvbG9yKVxuICAgICAgICB9KVxuICAgIH0pXG5cbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4ucmVwb3Mge1xuICB0ZXh0LWFsaWduOiBsZWZ0O1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7IH1cbiAgLnJlcG9zIGgyIHtcbiAgICBwYWRkaW5nOiA1cHg7XG4gICAgdGV4dC1hbGlnbjogbGVmdDtcbiAgICBmb250LXdlaWdodDogNTAwOyB9XG4gIEBtZWRpYSBvbmx5IHNjcmVlbiBhbmQgKG1heC13aWR0aDogNjAwcHgpIHtcbiAgICAucmVwb3Mge1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgcGFkZGluZzogMDsgfSB9XG5cbmEge1xuICBwYWRkaW5nOiAwO1xuICBtYXJnaW46IDA7IH1cblxuLnJlcG8ge1xuICBkaXNwbGF5OiBmbGV4O1xuICBvcGFjaXR5OiAwLjA7XG4gIGFuaW1hdGlvbjogcmV2ZWFsIDFzIGZvcndhcmRzOyB9XG4gIEBtZWRpYSBvbmx5IHNjcmVlbiBhbmQgKG1heC13aWR0aDogNjAwcHgpIHtcbiAgICAucmVwbyB7XG4gICAgICBmb250LXNpemU6IDAuNzVlbTsgfSB9XG5cbi50aXRsZSB7XG4gIGZvbnQtc2l6ZTogMWVtO1xuICBwYWRkaW5nOiAwO1xuICBtYXJnaW46IDA7XG4gIHRleHQtYWxpZ246IGxlZnQ7IH1cblxuLmxhbmdhdWdlIHtcbiAgZm9udC13ZWlnaHQ6IDUwMDsgfVxuXG4uYmFkZ2Uge1xuICBiYWNrZ3JvdW5kOiB2YXIoLS1zZWNvbmRhcnkpO1xuICBtYXJnaW46IDA7XG4gIHBhZGRpbmc6IDVweDtcbiAgYm9yZGVyLXJhZGl1czogdmFyKC0tYm9yZGVyLXJhZGl1cyk7XG4gIGZvbnQtc2l6ZTogMC43NWVtOyB9XG5cbi5iYWRnZS0taXRlbSB7XG4gIG1hcmdpbjogMnB4OyB9XG5cbkBrZXlmcmFtZXMgcmV2ZWFsIHtcbiAgZnJvbSB7XG4gICAgb3BhY2l0eTogMC4wOyB9XG4gIHRvIHtcbiAgICBvcGFjaXR5OiAxLjA7IH0gfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1yZXBvcy5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjx1bCBjbGFzcz1cInJlcG9zXCI+XG4gICAgPGgyPlJlcG9zaXRvcmllczwvaDI+XG4gICAgeyNlYWNoIHJlcG9zIGFzIHJlcG8sIGl9XG4gICAgICAgIDxsaSBjbGFzcz1cInJlcG9cIiBzdHlsZT1cImFuaW1hdGlvbi1kZWxheToge2kqMTB9bXNcIj5cbiAgICAgICAgICAgIDxhIGhyZWY9XCJ7cmVwby51cmx9XCIgdGFyZ2V0PVwiX2JsYW5rXCIgcmVsPVwibm9vcGVuZXJcIj5cbiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cInRpdGxlXCI+e3JlcG8ubmFtZX1cbiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPVwiYmFkZ2VcIj5cbiAgICAgICAgICAgICAgICAgICAgeyNpZiByZXBvLnByaW1hcnlMYW5ndWFnZX1cbiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJsYW5nYXVnZVwiIHN0eWxlPVwiY29sb3I6IHtsYW5ndWFnZUNvbG9ycy5nZXQocmVwby5wcmltYXJ5TGFuZ3VhZ2UubmFtZSl9XCI+XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAge3JlcG8ucHJpbWFyeUxhbmd1YWdlLm5hbWV9XG4gICAgICAgICAgICAgICAgICAgICAgICA8L3NwYW4+IFxuICAgICAgICAgICAgICAgICAgICA8L3NwYW4+IFxuICAgICAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgICAgICB7I2lmIHJlcG8uc3RhcmdhemVycy50b3RhbENvdW50fSBcbiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtc3RhclwiIHN0eWxlPVwiY29sb3I6IHZhcigtLWFwcGxlX3JldHJvX3llbGxvdylcIj48L2k+XG4gICAgICAgICAgICAgICAgICAgICAgICA8c3BhbiBzdHlsZT1cImNvbG9yOiB2YXIoLS1hcHBsZV9yZXRyb195ZWxsb3cpXCI+e3JlcG8uc3RhcmdhemVycy50b3RhbENvdW50fTwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgICAgICB7I2lmIHJlcG8uZm9ya0NvdW50fSBcbiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtY29kZS1icmFuY2hcIiBzdHlsZT1cImNvbG9yOiAjYzk0ZGEwXCI+PC9pPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9XCJjb2xvcjogI2M5NGRhMFwiPntyZXBvLmZvcmtDb3VudH08L3NwYW4+XG4gICAgICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICA8L2E+XG4gICAgICAgIDwvbGk+XG4gICAgey9lYWNofVxuPC91bD5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUE0Q21CLE1BQU0sZUFBQyxDQUFDLEFBQ3pCLFVBQVUsQ0FBRSxJQUFJLENBQ2hCLE9BQU8sQ0FBRSxZQUFZLEFBQUUsQ0FBQyxBQUN4QixxQkFBTSxDQUFDLEVBQUUsZUFBQyxDQUFDLEFBQ1QsT0FBTyxDQUFFLEdBQUcsQ0FDWixVQUFVLENBQUUsSUFBSSxDQUNoQixXQUFXLENBQUUsR0FBRyxBQUFFLENBQUMsQUFDckIsT0FBTyxJQUFJLENBQUMsTUFBTSxDQUFDLEdBQUcsQ0FBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDekMsTUFBTSxlQUFDLENBQUMsQUFDTixNQUFNLENBQUUsQ0FBQyxDQUNULE9BQU8sQ0FBRSxDQUFDLEFBQUUsQ0FBQyxBQUFDLENBQUMsQUFFckIsQ0FBQyxlQUFDLENBQUMsQUFDRCxPQUFPLENBQUUsQ0FBQyxDQUNWLE1BQU0sQ0FBRSxDQUFDLEFBQUUsQ0FBQyxBQUVkLEtBQUssZUFBQyxDQUFDLEFBQ0wsT0FBTyxDQUFFLElBQUksQ0FDYixPQUFPLENBQUUsR0FBRyxDQUNaLFNBQVMsQ0FBRSxxQkFBTSxDQUFDLEVBQUUsQ0FBQyxRQUFRLEFBQUUsQ0FBQyxBQUNoQyxPQUFPLElBQUksQ0FBQyxNQUFNLENBQUMsR0FBRyxDQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUN6QyxLQUFLLGVBQUMsQ0FBQyxBQUNMLFNBQVMsQ0FBRSxNQUFNLEFBQUUsQ0FBQyxBQUFDLENBQUMsQUFFNUIsTUFBTSxlQUFDLENBQUMsQUFDTixTQUFTLENBQUUsR0FBRyxDQUNkLE9BQU8sQ0FBRSxDQUFDLENBQ1YsTUFBTSxDQUFFLENBQUMsQ0FDVCxVQUFVLENBQUUsSUFBSSxBQUFFLENBQUMsQUFFckIsU0FBUyxlQUFDLENBQUMsQUFDVCxXQUFXLENBQUUsR0FBRyxBQUFFLENBQUMsQUFFckIsTUFBTSxlQUFDLENBQUMsQUFDTixVQUFVLENBQUUsSUFBSSxXQUFXLENBQUMsQ0FDNUIsTUFBTSxDQUFFLENBQUMsQ0FDVCxPQUFPLENBQUUsR0FBRyxDQUNaLGFBQWEsQ0FBRSxJQUFJLGVBQWUsQ0FBQyxDQUNuQyxTQUFTLENBQUUsTUFBTSxBQUFFLENBQUMsQUFFdEIsWUFBWSxlQUFDLENBQUMsQUFDWixNQUFNLENBQUUsR0FBRyxBQUFFLENBQUMsQUFFaEIsV0FBVyxxQkFBTyxDQUFDLEFBQ2pCLElBQUksQUFBQyxDQUFDLEFBQ0osT0FBTyxDQUFFLEdBQUcsQUFBRSxDQUFDLEFBQ2pCLEVBQUUsQUFBQyxDQUFDLEFBQ0YsT0FBTyxDQUFFLEdBQUcsQUFBRSxDQUFDLEFBQUMsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.repo = list[i];
	child_ctx.i = i;
	return child_ctx;
}

// (103:20) {#if repo.primaryLanguage}
function create_if_block_2(ctx) {
	var span1, span0, t_value = ctx.repo.primaryLanguage.name + "", t;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true, style: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "langauge svelte-1jarja4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", ctx.languageColors.get(ctx.repo.primaryLanguage.name));
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 104, 24, 2555);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-1jarja4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 103, 20, 2504);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.primaryLanguage.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
			}

			if (changed.repos) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", ctx.languageColors.get(ctx.repo.primaryLanguage.name));
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block_2.name, type: "if", source: "(103:20) {#if repo.primaryLanguage}", ctx });
	return block;
}

// (110:20) {#if repo.stargazers.totalCount}
function create_if_block_1(ctx) {
	var span1, i, t0, span0, t1_value = ctx.repo.stargazers.totalCount + "", t1;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span1_nodes);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { style: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-star");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "var(--apple_retro_yellow)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 111, 24, 2911);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", "var(--apple_retro_yellow)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 112, 24, 3004);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-1jarja4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 110, 20, 2860);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t1_value !== (t1_value = ctx.repo.stargazers.totalCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block_1.name, type: "if", source: "(110:20) {#if repo.stargazers.totalCount}", ctx });
	return block;
}

// (116:20) {#if repo.forkCount}
function create_if_block(ctx) {
	var span1, i, t0, span0, t1_value = ctx.repo.forkCount + "", t1;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span1_nodes);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { style: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-code-branch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "#c94da0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 117, 24, 3254);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", "#c94da0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 118, 24, 3336);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-1jarja4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 116, 20, 3203);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t1_value !== (t1_value = ctx.repo.forkCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block.name, type: "if", source: "(116:20) {#if repo.forkCount}", ctx });
	return block;
}

// (98:4) {#each repos as repo, i}
function create_each_block(ctx) {
	var li, a, span, t0_value = ctx.repo.name + "", t0, t1, div, t2, t3, a_href_value, t4;

	var if_block0 = (ctx.repo.primaryLanguage) && create_if_block_2(ctx);

	var if_block1 = (ctx.repo.stargazers.totalCount) && create_if_block_1(ctx);

	var if_block2 = (ctx.repo.forkCount) && create_if_block(ctx);

	const block = {
		c: function create() {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if (if_block0) if_block0.c();
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "LI", { class: true, style: true }, false);
			var li_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "A", { href: true, target: true, rel: true, class: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true }, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span_nodes);

			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			if (if_block0) if_block0.l(div_nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);
			if (if_block1) if_block1.l(div_nodes);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);
			if (if_block2) if_block2.l(div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(li_nodes);
			li_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "badge svelte-1jarja4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 101, 16, 2417);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "title svelte-1jarja4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 100, 16, 2369);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", a_href_value = ctx.repo.url);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "svelte-1jarja4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 99, 12, 2300);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(li, "class", "repo svelte-1jarja4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(li, "animation-delay", "" + ctx.i*10 + "ms");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li, file, 98, 8, 2236);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, li, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, div);
			if (if_block0) if_block0.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t2);
			if (if_block1) if_block1.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t3);
			if (if_block2) if_block2.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li, t4);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t0_value !== (t0_value = ctx.repo.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, t0_value);
			}

			if (ctx.repo.primaryLanguage) {
				if (if_block0) {
					if_block0.p(changed, ctx);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(div, t2);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (ctx.repo.stargazers.totalCount) {
				if (if_block1) {
					if_block1.p(changed, ctx);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(div, t3);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (ctx.repo.forkCount) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(div, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if ((changed.repos) && a_href_value !== (a_href_value = ctx.repo.url)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", a_href_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(li);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_each_block.name, type: "each", source: "(98:4) {#each repos as repo, i}", ctx });
	return block;
}

function create_fragment(ctx) {
	var ul, h2, t0, t1;

	let each_value = ctx.repos;

	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const block = {
		c: function create() {
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Repositories");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "H2", { class: true }, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Repositories");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "svelte-1jarja4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 96, 4, 2177);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(ul, "class", "repos svelte-1jarja4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 95, 0, 2154);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, ul, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t1);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.repos || changed.languageColors) {
				each_value = ctx.repos;

				let i;
				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(ul);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_fragment.name, type: "component", source: "", ctx });
	return block;
}

const starBias = 1.5

const forkBias = 2.0

function instance($$self, $$props, $$invalidate) {
	

    let repos = []

    let languageColorChoicesIter = 0
    let languageColors = new Map()
    const languageColorChoices = [
        'var(--systemBlue)',
        'var(--systemGray)',
        'var(--systemGreen)',
        'var(--systemIndigo)',
        'var(--systemOrange)',
        'var(--systemPink)',
        'var(--systemPurple)',
        'var(--systemRed)',
        'var(--systemTeal)',
        'var(--systemYellow)'
    ] // value forks more than stars

    Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
        $$invalidate('repos', repos = await Object(_utils_utility__WEBPACK_IMPORTED_MODULE_2__["cachedFetch"])('/.netlify/functions/github'))
        repos.sort((a, b) => (b.stargazers.totalCount*starBias + b.forkCount*forkBias) -  (a.stargazers.totalCount*starBias + a.forkCount*forkBias))

        repos.forEach(repo => {
            const name = repo.primaryLanguage.name

            let color 
            if (languageColors.has(name)) {
                color = languageColors.get(name)
            } else color = languageColorChoices[languageColorChoicesIter++ % languageColorChoices.length]
            
            console.log(name, color)
            
            languageColors.set(name, color)
        })
    })

	$$self.$capture_state = () => {
		return {};
	};

	$$self.$inject_state = $$props => {
		if ('repos' in $$props) $$invalidate('repos', repos = $$props.repos);
		if ('languageColorChoicesIter' in $$props) languageColorChoicesIter = $$props.languageColorChoicesIter;
		if ('languageColors' in $$props) $$invalidate('languageColors', languageColors = $$props.languageColors);
	};

	return { repos, languageColors };
}

class Repos extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1jarja4-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", { component: this, tagName: "Repos", options, id: create_fragment.name });
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Repos);

/***/ }),

/***/ "./src/components/youtube-videos.svelte":
/*!**********************************************!*\
  !*** ./src/components/youtube-videos.svelte ***!
  \**********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _utils_utility__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./utils/utility */ "./src/components/utils/utility.js");
/* src/components/youtube-videos.svelte generated by Svelte v3.12.0 */




const file = "src/components/youtube-videos.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-d6r0wr-style';
	style.textContent = ".videos.svelte-d6r0wr{text-align:left;display:inline-block}.videos.svelte-d6r0wr h2.svelte-d6r0wr{padding:5px;text-align:left;font-weight:500}@media only screen and (max-width: 600px){.videos.svelte-d6r0wr{margin:0;padding:0}}a.svelte-d6r0wr{padding:0;margin:0}.video.svelte-d6r0wr{display:flex;opacity:0.0;animation:svelte-d6r0wr-reveal 1s forwards}@media only screen and (max-width: 600px){.video.svelte-d6r0wr{font-size:0.75em}}.title.svelte-d6r0wr{font-size:1em;padding:0;margin:0;text-align:left}.badge.svelte-d6r0wr{background:var(--secondary);margin:0;padding:5px;border-radius:var(--border-radius);font-size:0.75em}.badge--item.svelte-d6r0wr{margin:2px}@keyframes svelte-d6r0wr-reveal{from{opacity:0.0}to{opacity:0.8}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoieW91dHViZS12aWRlb3Muc3ZlbHRlIiwic291cmNlcyI6WyJ5b3V0dWJlLXZpZGVvcy5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJ1xuICAgIGltcG9ydCB7IGNhY2hlZEZldGNoIH0gZnJvbSAnLi91dGlscy91dGlsaXR5J1xuXG4gICAgbGV0IHZpZGVvcyA9IFtdXG5cbiAgICBvbk1vdW50KGFzeW5jICgpID0+IHtcbiAgICAgICAgdmlkZW9zID0gYXdhaXQgY2FjaGVkRmV0Y2goJy8ubmV0bGlmeS9mdW5jdGlvbnMveW91dHViZScpXG5cbiAgICAgICAgLy8gU29ydCB0aGUgdmlkZW9zIGJhc2VkIG9uIHZpZXcgY291bnRcbiAgICAgICAgdmlkZW9zLnNvcnQoKGEsIGIpID0+IHBhcnNlSW50KGIuc3RhdGlzdGljcy52aWV3Q291bnQpIC0gcGFyc2VJbnQoYS5zdGF0aXN0aWNzLnZpZXdDb3VudCkpXG4gICAgfSlcbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4udmlkZW9zIHtcbiAgdGV4dC1hbGlnbjogbGVmdDtcbiAgZGlzcGxheTogaW5saW5lLWJsb2NrOyB9XG4gIC52aWRlb3MgaDIge1xuICAgIHBhZGRpbmc6IDVweDtcbiAgICB0ZXh0LWFsaWduOiBsZWZ0O1xuICAgIGZvbnQtd2VpZ2h0OiA1MDA7IH1cbiAgQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiA2MDBweCkge1xuICAgIC52aWRlb3Mge1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgcGFkZGluZzogMDsgfSB9XG5cbmEge1xuICBwYWRkaW5nOiAwO1xuICBtYXJnaW46IDA7IH1cblxuLnZpZGVvIHtcbiAgZGlzcGxheTogZmxleDtcbiAgb3BhY2l0eTogMC4wO1xuICBhbmltYXRpb246IHJldmVhbCAxcyBmb3J3YXJkczsgfVxuICBAbWVkaWEgb25seSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDYwMHB4KSB7XG4gICAgLnZpZGVvIHtcbiAgICAgIGZvbnQtc2l6ZTogMC43NWVtOyB9IH1cblxuLnRpdGxlIHtcbiAgZm9udC1zaXplOiAxZW07XG4gIHBhZGRpbmc6IDA7XG4gIG1hcmdpbjogMDtcbiAgdGV4dC1hbGlnbjogbGVmdDsgfVxuXG4uYmFkZ2Uge1xuICBiYWNrZ3JvdW5kOiB2YXIoLS1zZWNvbmRhcnkpO1xuICBtYXJnaW46IDA7XG4gIHBhZGRpbmc6IDVweDtcbiAgYm9yZGVyLXJhZGl1czogdmFyKC0tYm9yZGVyLXJhZGl1cyk7XG4gIGZvbnQtc2l6ZTogMC43NWVtOyB9XG5cbi5iYWRnZS0taXRlbSB7XG4gIG1hcmdpbjogMnB4OyB9XG5cbkBrZXlmcmFtZXMgcmV2ZWFsIHtcbiAgZnJvbSB7XG4gICAgb3BhY2l0eTogMC4wOyB9XG4gIHRvIHtcbiAgICBvcGFjaXR5OiAwLjg7IH0gfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD15b3V0dWJlLXZpZGVvcy5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjx1bCBjbGFzcz1cInZpZGVvc1wiPlxuICAgIDxoMj5WaWRlb3M8L2gyPlxuICAgIHsjZWFjaCB2aWRlb3MgYXMgdmlkZW8sIGl9ICAgICAgICAgICAgXG4gICAgICAgIDxsaSBjbGFzcz1cInZpZGVvXCIgc3R5bGU9XCJhbmltYXRpb24tZGVsYXk6IHtpKjEwfW1zXCI+XG4gICAgICAgICAgICA8YSBocmVmPVwiaHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj17dmlkZW8uaWR9XCIgdGFyZ2V0PVwiX2JsYW5rXCIgcmVsPVwibm9vcGVuZXJcIj5cbiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cInRpdGxlXCI+e3ZpZGVvLnRpdGxlfVxuICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJiYWRnZVwiPlxuICAgICAgICAgICAgICAgICAgICB7I2lmIHBhcnNlSW50KHZpZGVvLnN0YXRpc3RpY3Mudmlld0NvdW50KX1cbiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtZXllXCIgc3R5bGU9XCJjb2xvcjogdmFyKC0tc3lzdGVtR3JheSlcIj48L2k+XG4gICAgICAgICAgICAgICAgICAgICAgICA8c3BhbiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1HcmF5KVwiPiB7dmlkZW8uc3RhdGlzdGljcy52aWV3Q291bnR9IDwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgICAgICB7I2lmIHBhcnNlSW50KHZpZGVvLnN0YXRpc3RpY3MubGlrZUNvdW50KX1cbiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtaGVhcnRcIiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1SZWQpXCI+PC9pPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9XCJjb2xvcjogdmFyKC0tc3lzdGVtUmVkKVwiPnt2aWRlby5zdGF0aXN0aWNzLmxpa2VDb3VudH08L3NwYW4+XG4gICAgICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgICAgICAgICAgeyNpZiBwYXJzZUludCh2aWRlby5zdGF0aXN0aWNzLmNvbW1lbnRDb3VudCl9XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwiYmFkZ2UtLWl0ZW1cIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxpIGNsYXNzPVwiZmFzIGZhLWNvbW1lbnRcIiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1CbHVlKVwiPjwvaT5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuIHN0eWxlPVwiY29sb3I6IHZhcigtLXN5c3RlbUJsdWUpXCI+e3ZpZGVvLnN0YXRpc3RpY3MuY29tbWVudENvdW50fTwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgIDwvYT5cbiAgICAgICAgPC9saT5cbiAgICB7L2VhY2h9XG48L3VsPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQWNtQixPQUFPLGNBQUMsQ0FBQyxBQUMxQixVQUFVLENBQUUsSUFBSSxDQUNoQixPQUFPLENBQUUsWUFBWSxBQUFFLENBQUMsQUFDeEIscUJBQU8sQ0FBQyxFQUFFLGNBQUMsQ0FBQyxBQUNWLE9BQU8sQ0FBRSxHQUFHLENBQ1osVUFBVSxDQUFFLElBQUksQ0FDaEIsV0FBVyxDQUFFLEdBQUcsQUFBRSxDQUFDLEFBQ3JCLE9BQU8sSUFBSSxDQUFDLE1BQU0sQ0FBQyxHQUFHLENBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pDLE9BQU8sY0FBQyxDQUFDLEFBQ1AsTUFBTSxDQUFFLENBQUMsQ0FDVCxPQUFPLENBQUUsQ0FBQyxBQUFFLENBQUMsQUFBQyxDQUFDLEFBRXJCLENBQUMsY0FBQyxDQUFDLEFBQ0QsT0FBTyxDQUFFLENBQUMsQ0FDVixNQUFNLENBQUUsQ0FBQyxBQUFFLENBQUMsQUFFZCxNQUFNLGNBQUMsQ0FBQyxBQUNOLE9BQU8sQ0FBRSxJQUFJLENBQ2IsT0FBTyxDQUFFLEdBQUcsQ0FDWixTQUFTLENBQUUsb0JBQU0sQ0FBQyxFQUFFLENBQUMsUUFBUSxBQUFFLENBQUMsQUFDaEMsT0FBTyxJQUFJLENBQUMsTUFBTSxDQUFDLEdBQUcsQ0FBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDekMsTUFBTSxjQUFDLENBQUMsQUFDTixTQUFTLENBQUUsTUFBTSxBQUFFLENBQUMsQUFBQyxDQUFDLEFBRTVCLE1BQU0sY0FBQyxDQUFDLEFBQ04sU0FBUyxDQUFFLEdBQUcsQ0FDZCxPQUFPLENBQUUsQ0FBQyxDQUNWLE1BQU0sQ0FBRSxDQUFDLENBQ1QsVUFBVSxDQUFFLElBQUksQUFBRSxDQUFDLEFBRXJCLE1BQU0sY0FBQyxDQUFDLEFBQ04sVUFBVSxDQUFFLElBQUksV0FBVyxDQUFDLENBQzVCLE1BQU0sQ0FBRSxDQUFDLENBQ1QsT0FBTyxDQUFFLEdBQUcsQ0FDWixhQUFhLENBQUUsSUFBSSxlQUFlLENBQUMsQ0FDbkMsU0FBUyxDQUFFLE1BQU0sQUFBRSxDQUFDLEFBRXRCLFlBQVksY0FBQyxDQUFDLEFBQ1osTUFBTSxDQUFFLEdBQUcsQUFBRSxDQUFDLEFBRWhCLFdBQVcsb0JBQU8sQ0FBQyxBQUNqQixJQUFJLEFBQUMsQ0FBQyxBQUNKLE9BQU8sQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUNqQixFQUFFLEFBQUMsQ0FBQyxBQUNGLE9BQU8sQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUFDLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.video = list[i];
	child_ctx.i = i;
	return child_ctx;
}

// (70:20) {#if parseInt(video.statistics.viewCount)}
function create_if_block_2(ctx) {
	var span1, i, t0, span0, t1_value = ctx.video.statistics.viewCount + "", t1;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span1_nodes);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { style: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-eye");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "var(--systemGray)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 71, 24, 1676);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", "var(--systemGray)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 72, 24, 1760);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-d6r0wr");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 70, 20, 1625);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.videos) && t1_value !== (t1_value = ctx.video.statistics.viewCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block_2.name, type: "if", source: "(70:20) {#if parseInt(video.statistics.viewCount)}", ctx });
	return block;
}

// (76:20) {#if parseInt(video.statistics.likeCount)}
function create_if_block_1(ctx) {
	var span1, i, t0, span0, t1_value = ctx.video.statistics.likeCount + "", t1;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span1_nodes);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { style: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-heart");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "var(--systemRed)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 77, 24, 2025);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", "var(--systemRed)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 78, 24, 2110);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-d6r0wr");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 76, 20, 1974);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.videos) && t1_value !== (t1_value = ctx.video.statistics.likeCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block_1.name, type: "if", source: "(76:20) {#if parseInt(video.statistics.likeCount)}", ctx });
	return block;
}

// (82:20) {#if parseInt(video.statistics.commentCount)}
function create_if_block(ctx) {
	var span1, i, t0, span0, t1_value = ctx.video.statistics.commentCount + "", t1;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span1_nodes);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { style: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-comment");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "var(--systemBlue)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 83, 24, 2375);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", "var(--systemBlue)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 84, 24, 2463);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-d6r0wr");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 82, 20, 2324);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.videos) && t1_value !== (t1_value = ctx.video.statistics.commentCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block.name, type: "if", source: "(82:20) {#if parseInt(video.statistics.commentCount)}", ctx });
	return block;
}

// (65:4) {#each videos as video, i}
function create_each_block(ctx) {
	var li, a, span, t0_value = ctx.video.title + "", t0, t1, div, show_if_2 = ctx.parseInt(ctx.video.statistics.viewCount), t2, show_if_1 = ctx.parseInt(ctx.video.statistics.likeCount), t3, show_if = ctx.parseInt(ctx.video.statistics.commentCount), a_href_value, t4;

	var if_block0 = (show_if_2) && create_if_block_2(ctx);

	var if_block1 = (show_if_1) && create_if_block_1(ctx);

	var if_block2 = (show_if) && create_if_block(ctx);

	const block = {
		c: function create() {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if (if_block0) if_block0.c();
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "LI", { class: true, style: true }, false);
			var li_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "A", { href: true, target: true, rel: true, class: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true }, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span_nodes);

			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			if (if_block0) if_block0.l(div_nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);
			if (if_block1) if_block1.l(div_nodes);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);
			if (if_block2) if_block2.l(div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(li_nodes);
			li_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "badge svelte-d6r0wr");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 68, 16, 1522);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "title svelte-d6r0wr");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 67, 16, 1472);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", a_href_value = "https://www.youtube.com/watch?v=" + ctx.video.id);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "svelte-d6r0wr");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 66, 12, 1371);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(li, "class", "video svelte-d6r0wr");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(li, "animation-delay", "" + ctx.i*10 + "ms");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li, file, 65, 8, 1306);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, li, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, div);
			if (if_block0) if_block0.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t2);
			if (if_block1) if_block1.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t3);
			if (if_block2) if_block2.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li, t4);
		},

		p: function update(changed, ctx) {
			if ((changed.videos) && t0_value !== (t0_value = ctx.video.title + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, t0_value);
			}

			if (changed.videos) show_if_2 = ctx.parseInt(ctx.video.statistics.viewCount)

			if (show_if_2) {
				if (if_block0) {
					if_block0.p(changed, ctx);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(div, t2);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (changed.videos) show_if_1 = ctx.parseInt(ctx.video.statistics.likeCount)

			if (show_if_1) {
				if (if_block1) {
					if_block1.p(changed, ctx);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(div, t3);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (changed.videos) show_if = ctx.parseInt(ctx.video.statistics.commentCount)

			if (show_if) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(div, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if ((changed.videos) && a_href_value !== (a_href_value = "https://www.youtube.com/watch?v=" + ctx.video.id)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", a_href_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(li);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_each_block.name, type: "each", source: "(65:4) {#each videos as video, i}", ctx });
	return block;
}

function create_fragment(ctx) {
	var ul, h2, t0, t1;

	let each_value = ctx.videos;

	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const block = {
		c: function create() {
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Videos");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "H2", { class: true }, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Videos");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "svelte-d6r0wr");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 63, 4, 1239);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(ul, "class", "videos svelte-d6r0wr");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 62, 0, 1215);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, ul, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t1);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.videos || changed.parseInt) {
				each_value = ctx.videos;

				let i;
				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(ul);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_fragment.name, type: "component", source: "", ctx });
	return block;
}

function instance($$self, $$props, $$invalidate) {
	

    let videos = []

    Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
        $$invalidate('videos', videos = await Object(_utils_utility__WEBPACK_IMPORTED_MODULE_2__["cachedFetch"])('/.netlify/functions/youtube'))

        // Sort the videos based on view count
        videos.sort((a, b) => parseInt(b.statistics.viewCount) - parseInt(a.statistics.viewCount))
    })

	$$self.$capture_state = () => {
		return {};
	};

	$$self.$inject_state = $$props => {
		if ('videos' in $$props) $$invalidate('videos', videos = $$props.videos);
	};

	return { videos, parseInt };
}

class Youtube_videos extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-d6r0wr-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", { component: this, tagName: "Youtube_videos", options, id: create_fragment.name });
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Youtube_videos);

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _components_repos_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/repos.svelte */ "./src/components/repos.svelte");
/* harmony import */ var _components_youtube_videos_svelte__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../components/youtube-videos.svelte */ "./src/components/youtube-videos.svelte");
/* src/routes/index.svelte generated by Svelte v3.12.0 */





const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1f7hjrv-style';
	style.textContent = ".landing-page--title.svelte-1f7hjrv{font-size:1.5em;font-weight:700;padding:0;margin:0}.landing-page--subtitle.svelte-1f7hjrv{margin:0;padding:0;font-size:0.75em;opacity:0.8}.landing-page--hero.svelte-1f7hjrv{margin:0;margin-bottom:20px;-webkit-transform:translate3d(0, 0, 0);background-image:var(--avatar);background-size:cover;width:300px;height:300px}.container--item.svelte-1f7hjrv{margin:20px}@media only screen and (max-width: 750px){.container--item.svelte-1f7hjrv{margin:5px}}.container.svelte-1f7hjrv{padding:0;display:flex;flex-flow:row wrap;justify-content:space-around}@media only screen and (max-width: 600px){.container.svelte-1f7hjrv{justify-content:left}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJ1xuICAgIGltcG9ydCBSZXBvcyBmcm9tICcuLi9jb21wb25lbnRzL3JlcG9zLnN2ZWx0ZSdcbiAgICBpbXBvcnQgWW91dHViZVZpZGVvcyBmcm9tICcuLi9jb21wb25lbnRzL3lvdXR1YmUtdmlkZW9zLnN2ZWx0ZSdcbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4ubGFuZGluZy1wYWdlLS10aXRsZSB7XG4gIGZvbnQtc2l6ZTogMS41ZW07XG4gIGZvbnQtd2VpZ2h0OiA3MDA7XG4gIHBhZGRpbmc6IDA7XG4gIG1hcmdpbjogMDsgfVxuXG4ubGFuZGluZy1wYWdlLS1zdWJ0aXRsZSB7XG4gIG1hcmdpbjogMDtcbiAgcGFkZGluZzogMDtcbiAgZm9udC1zaXplOiAwLjc1ZW07XG4gIG9wYWNpdHk6IDAuODsgfVxuXG4ubGFuZGluZy1wYWdlLS1oZXJvIHtcbiAgbWFyZ2luOiAwO1xuICBtYXJnaW4tYm90dG9tOiAyMHB4O1xuICAtd2Via2l0LXRyYW5zZm9ybTogdHJhbnNsYXRlM2QoMCwgMCwgMCk7XG4gIGJhY2tncm91bmQtaW1hZ2U6IHZhcigtLWF2YXRhcik7XG4gIGJhY2tncm91bmQtc2l6ZTogY292ZXI7XG4gIHdpZHRoOiAzMDBweDtcbiAgaGVpZ2h0OiAzMDBweDsgfVxuXG4uY29udGFpbmVyLS1pdGVtIHtcbiAgbWFyZ2luOiAyMHB4OyB9XG4gIEBtZWRpYSBvbmx5IHNjcmVlbiBhbmQgKG1heC13aWR0aDogNzUwcHgpIHtcbiAgICAuY29udGFpbmVyLS1pdGVtIHtcbiAgICAgIG1hcmdpbjogNXB4OyB9IH1cblxuLmNvbnRhaW5lciB7XG4gIHBhZGRpbmc6IDA7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZmxvdzogcm93IHdyYXA7XG4gIGp1c3RpZnktY29udGVudDogc3BhY2UtYXJvdW5kOyB9XG4gIEBtZWRpYSBvbmx5IHNjcmVlbiBhbmQgKG1heC13aWR0aDogNjAwcHgpIHtcbiAgICAuY29udGFpbmVyIHtcbiAgICAgIGp1c3RpZnktY29udGVudDogbGVmdDsgfSB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICAgIDx0aXRsZT5Ib21lPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyLS1pdGVtXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLWhlcm9cIj48L2Rpdj5cbiAgICAgICAgPHAgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLXRpdGxlXCI+XG4gICAgICAgICAgICBNYXJjdXMgTWF0aGlhc3NlblxuICAgICAgICA8L3A+XG4gICAgICAgIDxwIGNsYXNzPVwibGFuZGluZy1wYWdlLS1zdWJ0aXRsZVwiPlxuICAgICAgICAgICAgSSBkbyBjb21waWxlcnMgYW5kIGxhbmd1YWdlcy48YnI+XG4gICAgICAgICAgICBJbnRlcmVzdGVkIGluIHN5c3RlbXMgZGVzaWduIGFuZCBVWC5cbiAgICAgICAgPC9wPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJjb250YWluZXItLWl0ZW1cIj4gPFJlcG9zLz4gPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cImNvbnRhaW5lci0taXRlbVwiPiA8WW91dHViZVZpZGVvcy8+IDwvZGl2PlxuPC9kaXY+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBTW1CLG9CQUFvQixlQUFDLENBQUMsQUFDdkMsU0FBUyxDQUFFLEtBQUssQ0FDaEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsT0FBTyxDQUFFLENBQUMsQ0FDVixNQUFNLENBQUUsQ0FBQyxBQUFFLENBQUMsQUFFZCx1QkFBdUIsZUFBQyxDQUFDLEFBQ3ZCLE1BQU0sQ0FBRSxDQUFDLENBQ1QsT0FBTyxDQUFFLENBQUMsQ0FDVixTQUFTLENBQUUsTUFBTSxDQUNqQixPQUFPLENBQUUsR0FBRyxBQUFFLENBQUMsQUFFakIsbUJBQW1CLGVBQUMsQ0FBQyxBQUNuQixNQUFNLENBQUUsQ0FBQyxDQUNULGFBQWEsQ0FBRSxJQUFJLENBQ25CLGlCQUFpQixDQUFFLFlBQVksQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQ3ZDLGdCQUFnQixDQUFFLElBQUksUUFBUSxDQUFDLENBQy9CLGVBQWUsQ0FBRSxLQUFLLENBQ3RCLEtBQUssQ0FBRSxLQUFLLENBQ1osTUFBTSxDQUFFLEtBQUssQUFBRSxDQUFDLEFBRWxCLGdCQUFnQixlQUFDLENBQUMsQUFDaEIsTUFBTSxDQUFFLElBQUksQUFBRSxDQUFDLEFBQ2YsT0FBTyxJQUFJLENBQUMsTUFBTSxDQUFDLEdBQUcsQ0FBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDekMsZ0JBQWdCLGVBQUMsQ0FBQyxBQUNoQixNQUFNLENBQUUsR0FBRyxBQUFFLENBQUMsQUFBQyxDQUFDLEFBRXRCLFVBQVUsZUFBQyxDQUFDLEFBQ1YsT0FBTyxDQUFFLENBQUMsQ0FDVixPQUFPLENBQUUsSUFBSSxDQUNiLFNBQVMsQ0FBRSxHQUFHLENBQUMsSUFBSSxDQUNuQixlQUFlLENBQUUsWUFBWSxBQUFFLENBQUMsQUFDaEMsT0FBTyxJQUFJLENBQUMsTUFBTSxDQUFDLEdBQUcsQ0FBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDekMsVUFBVSxlQUFDLENBQUMsQUFDVixlQUFlLENBQUUsSUFBSSxBQUFFLENBQUMsQUFBQyxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	var t0, div4, div1, div0, t1, p0, t2, t3, p1, t4, br, t5, t6, div2, t7, div3, current;

	var repos = new _components_repos_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({ $$inline: true });

	var youtubevideos = new _components_youtube_videos_svelte__WEBPACK_IMPORTED_MODULE_3__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Marcus Mathiassen");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I do compilers and languages.");
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            Interested in systems design and UX.");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			repos.$$.fragment.c();
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			youtubevideos.$$.fragment.c();
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);

			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Marcus Mathiassen");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "I do compilers and languages.");

			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "BR", {}, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n            Interested in systems design and UX.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div4_nodes);

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			repos.$$.fragment.l(div2_nodes);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div4_nodes);

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			youtubevideos.$$.fragment.l(div3_nodes);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Home";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "landing-page--hero svelte-1f7hjrv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 50, 8, 1082);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "landing-page--title svelte-1f7hjrv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 51, 8, 1129);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 55, 41, 1288);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p1, "class", "landing-page--subtitle svelte-1f7hjrv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 54, 8, 1212);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "container--item svelte-1f7hjrv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 49, 4, 1044);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "container--item svelte-1f7hjrv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 59, 4, 1370);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "container--item svelte-1f7hjrv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 60, 4, 1420);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "container svelte-1f7hjrv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 48, 0, 1016);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div4, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, br);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(repos, div2, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(youtubevideos, div3, null);
			current = true;
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(repos.$$.fragment, local);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(youtubevideos.$$.fragment, local);

			current = true;
		},

		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(repos.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(youtubevideos.$$.fragment, local);
			current = false;
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div4);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(repos);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(youtubevideos);
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_fragment.name, type: "component", source: "", ctx });
	return block;
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1f7hjrv-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", { component: this, tagName: "Routes", options, id: create_fragment.name });
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9jb21wb25lbnRzL3JlcG9zLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9jb21wb25lbnRzL3lvdXR1YmUtdmlkZW9zLnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2lDQXlHNkIsSUFBSSxDQUFDLGVBQWUsQ0FBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lGQURRLGNBQWMsQ0FBQyxHQUFHLEtBQUMsSUFBSSxDQUFDLGVBQWUsQ0FBQyxJQUFJLENBQUM7Ozs7Ozs7Ozs7Ozs7cURBQzlFLElBQUksQ0FBQyxlQUFlLENBQUMsSUFBSTs7Ozs7MEZBRFEsY0FBYyxDQUFDLEdBQUcsS0FBQyxJQUFJLENBQUMsZUFBZSxDQUFDLElBQUksQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozt5Q0FRbkMsSUFBSSxDQUFDLFVBQVUsQ0FBQyxVQUFVOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1REFBMUIsSUFBSSxDQUFDLFVBQVUsQ0FBQyxVQUFVOzs7Ozs7Ozs7Ozs7Ozs7Ozt5Q0FNNUMsSUFBSSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VEQUFkLElBQUksQ0FBQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7OztpQ0FsQi9CLElBQUksQ0FBQyxJQUFJOztzQkFFckIsSUFBSSxDQUFDLGVBQWU7O3NCQU9wQixJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7O3NCQU0xQixJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7a0dBaEJqQixJQUFJLENBQUMsR0FBRzs7Ozs7O3FHQURvQixDQUFDLENBQUMsRUFBRTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7dURBRWpCLElBQUksQ0FBQyxJQUFJOzs7O1dBRXJCLElBQUksQ0FBQyxlQUFlOzs7Ozs7Ozs7Ozs7O1dBT3BCLElBQUksQ0FBQyxVQUFVLENBQUMsVUFBVTs7Ozs7Ozs7Ozs7OztXQU0xQixJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7OzsrREFoQmpCLElBQUksQ0FBQyxHQUFHOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NCQUZuQixLQUFLOzs7O2dDQUFWOzs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7OztxQkFBSyxLQUFLOzs7K0JBQVY7Ozs7Ozs7Ozs7OzsyQkFBQTs7O2dCQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBNUVGLE1BQU0sUUFBUSxHQUFHLEdBQUc7O0FBQ3BCLE1BQU0sUUFBUSxHQUFHLEdBQUc7OztDQXBCeUI7O0lBRTdDLElBQUksS0FBSyxHQUFHLEVBQUU7O0lBRWQsSUFBSSx3QkFBd0IsR0FBRyxDQUFDO0lBQ2hDLElBQUksY0FBYyxHQUFHLElBQUksR0FBRyxFQUFFO0lBQzlCLE1BQU0sb0JBQW9CLEdBQUc7UUFDekIsbUJBQW1CO1FBQ25CLG1CQUFtQjtRQUNuQixvQkFBb0I7UUFDcEIscUJBQXFCO1FBQ3JCLHFCQUFxQjtRQUNyQixtQkFBbUI7UUFDbkIscUJBQXFCO1FBQ3JCLGtCQUFrQjtRQUNsQixtQkFBbUI7UUFDbkIscUJBQXFCO0tBSUw7O0lBRXBCLHNEQUFPLENBQUMsWUFBWTs4QkFDaEIsS0FBSyxHQUFHLE1BQU0sa0VBQVcsQ0FBQyw0QkFBNEIsRUFBQztRQUN2RCxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxVQUFVLENBQUMsVUFBVSxDQUFDLFFBQVEsR0FBRyxDQUFDLENBQUMsU0FBUyxDQUFDLFFBQVEsQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDLFVBQVUsQ0FBQyxVQUFVLENBQUMsUUFBUSxHQUFHLENBQUMsQ0FBQyxTQUFTLENBQUMsUUFBUSxDQUFDLENBQUM7O1FBRTVJLEtBQUssQ0FBQyxPQUFPLENBQUMsSUFBSSxJQUFJO1lBQ2xCLE1BQU0sSUFBSSxHQUFHLElBQUksQ0FBQyxlQUFlLENBQUMsSUFBSTs7WUFFdEMsSUFBSSxLQUFLO1lBQ1QsSUFBSSxjQUFjLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxFQUFFO2dCQUMxQixLQUFLLEdBQUcsY0FBYyxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUM7YUFDbkMsTUFBTSxLQUFLLEdBQUcsb0JBQW9CLENBQUMsd0JBQXdCLEVBQUUsR0FBRyxvQkFBb0IsQ0FBQyxNQUFNLENBQUM7O1lBRTdGLE9BQU8sQ0FBQyxHQUFHLENBQUMsSUFBSSxFQUFFLEtBQUssQ0FBQzs7WUFFeEIsY0FBYyxDQUFDLEdBQUcsQ0FBQyxJQUFJLEVBQUUsS0FBSyxDQUFDO1NBQ2xDLENBQUM7S0FDTCxDQUFDOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7eUNDZ0MyRCxLQUFLLENBQUMsVUFBVSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3dEQUExQixLQUFLLENBQUMsVUFBVSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7O3lDQU01QixLQUFLLENBQUMsVUFBVSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3dEQUExQixLQUFLLENBQUMsVUFBVSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7O3lDQU16QixLQUFLLENBQUMsVUFBVSxDQUFDLFlBQVk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3dEQUE3QixLQUFLLENBQUMsVUFBVSxDQUFDLFlBQVk7Ozs7Ozs7Ozs7Ozs7Ozs7O2lDQWpCeEQsS0FBSyxDQUFDLEtBQUssb0NBRXZCLFFBQVEsS0FBQyxLQUFLLENBQUMsVUFBVSxDQUFDLFNBQVMsQ0FBQyxzQkFNcEMsUUFBUSxLQUFDLEtBQUssQ0FBQyxVQUFVLENBQUMsU0FBUyxDQUFDLG9CQU1wQyxRQUFRLEtBQUMsS0FBSyxDQUFDLFVBQVUsQ0FBQyxZQUFZLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VJQWZWLEtBQUssQ0FBQyxFQUFFOzs7Ozs7cUdBRFgsQ0FBQyxDQUFDLEVBQUU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3dEQUVsQixLQUFLLENBQUMsS0FBSzs7Ozt1Q0FFdkIsUUFBUSxLQUFDLEtBQUssQ0FBQyxVQUFVLENBQUMsU0FBUyxDQUFDOzs7Ozs7Ozs7Ozs7Ozs7dUNBTXBDLFFBQVEsS0FBQyxLQUFLLENBQUMsVUFBVSxDQUFDLFNBQVMsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7O3FDQU1wQyxRQUFRLEtBQUMsS0FBSyxDQUFDLFVBQVUsQ0FBQyxZQUFZLENBQUM7Ozs7Ozs7Ozs7Ozs7OztxR0FmVixLQUFLLENBQUMsRUFBRTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztzQkFGbkQsTUFBTTs7OztnQ0FBWDs7Ozs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O21DQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7cUJBQUssTUFBTTs7OytCQUFYOzs7Ozs7Ozs7Ozs7MkJBQUE7OztnQkFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Q0E5RDJDOztJQUU3QyxJQUFJLE1BQU0sR0FBRyxFQUFFOztJQUVmLHNEQUFPLENBQUMsWUFBWTsrQkFDaEIsTUFBTSxHQUFHLE1BQU0sa0VBQVcsQ0FBQyw2QkFBNkIsRUFBQzs7O1FBR3pELE1BQU0sQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxLQUFLLFFBQVEsQ0FBQyxDQUFDLENBQUMsVUFBVSxDQUFDLFNBQVMsQ0FBQyxHQUFHLFFBQVEsQ0FBQyxDQUFDLENBQUMsVUFBVSxDQUFDLFNBQVMsQ0FBQyxDQUFDO0tBQzdGLENBQUMiLCJmaWxlIjoiZmQ0MWMxZTg5NzExNDk1MjQ1YjgvaW5kZXguaW5kZXguanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICAgIGltcG9ydCB7IG9uTW91bnQgfSBmcm9tICdzdmVsdGUnXG4gICAgaW1wb3J0IHsgY2FjaGVkRmV0Y2ggfSBmcm9tICcuL3V0aWxzL3V0aWxpdHknXG5cbiAgICBsZXQgcmVwb3MgPSBbXVxuXG4gICAgbGV0IGxhbmd1YWdlQ29sb3JDaG9pY2VzSXRlciA9IDBcbiAgICBsZXQgbGFuZ3VhZ2VDb2xvcnMgPSBuZXcgTWFwKClcbiAgICBjb25zdCBsYW5ndWFnZUNvbG9yQ2hvaWNlcyA9IFtcbiAgICAgICAgJ3ZhcigtLXN5c3RlbUJsdWUpJyxcbiAgICAgICAgJ3ZhcigtLXN5c3RlbUdyYXkpJyxcbiAgICAgICAgJ3ZhcigtLXN5c3RlbUdyZWVuKScsXG4gICAgICAgICd2YXIoLS1zeXN0ZW1JbmRpZ28pJyxcbiAgICAgICAgJ3ZhcigtLXN5c3RlbU9yYW5nZSknLFxuICAgICAgICAndmFyKC0tc3lzdGVtUGluayknLFxuICAgICAgICAndmFyKC0tc3lzdGVtUHVycGxlKScsXG4gICAgICAgICd2YXIoLS1zeXN0ZW1SZWQpJyxcbiAgICAgICAgJ3ZhcigtLXN5c3RlbVRlYWwpJyxcbiAgICAgICAgJ3ZhcigtLXN5c3RlbVllbGxvdyknXG4gICAgXVxuXG4gICAgY29uc3Qgc3RhckJpYXMgPSAxLjVcbiAgICBjb25zdCBmb3JrQmlhcyA9IDIuMCAvLyB2YWx1ZSBmb3JrcyBtb3JlIHRoYW4gc3RhcnNcblxuICAgIG9uTW91bnQoYXN5bmMgKCkgPT4ge1xuICAgICAgICByZXBvcyA9IGF3YWl0IGNhY2hlZEZldGNoKCcvLm5ldGxpZnkvZnVuY3Rpb25zL2dpdGh1YicpXG4gICAgICAgIHJlcG9zLnNvcnQoKGEsIGIpID0+IChiLnN0YXJnYXplcnMudG90YWxDb3VudCpzdGFyQmlhcyArIGIuZm9ya0NvdW50KmZvcmtCaWFzKSAtICAoYS5zdGFyZ2F6ZXJzLnRvdGFsQ291bnQqc3RhckJpYXMgKyBhLmZvcmtDb3VudCpmb3JrQmlhcykpXG5cbiAgICAgICAgcmVwb3MuZm9yRWFjaChyZXBvID0+IHtcbiAgICAgICAgICAgIGNvbnN0IG5hbWUgPSByZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lXG5cbiAgICAgICAgICAgIGxldCBjb2xvciBcbiAgICAgICAgICAgIGlmIChsYW5ndWFnZUNvbG9ycy5oYXMobmFtZSkpIHtcbiAgICAgICAgICAgICAgICBjb2xvciA9IGxhbmd1YWdlQ29sb3JzLmdldChuYW1lKVxuICAgICAgICAgICAgfSBlbHNlIGNvbG9yID0gbGFuZ3VhZ2VDb2xvckNob2ljZXNbbGFuZ3VhZ2VDb2xvckNob2ljZXNJdGVyKysgJSBsYW5ndWFnZUNvbG9yQ2hvaWNlcy5sZW5ndGhdXG4gICAgICAgICAgICBcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKG5hbWUsIGNvbG9yKVxuICAgICAgICAgICAgXG4gICAgICAgICAgICBsYW5ndWFnZUNvbG9ycy5zZXQobmFtZSwgY29sb3IpXG4gICAgICAgIH0pXG4gICAgfSlcblxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBsYW5nPVwic2Fzc1wiPi5yZXBvcyB7XG4gIHRleHQtYWxpZ246IGxlZnQ7XG4gIGRpc3BsYXk6IGlubGluZS1ibG9jazsgfVxuICAucmVwb3MgaDIge1xuICAgIHBhZGRpbmc6IDVweDtcbiAgICB0ZXh0LWFsaWduOiBsZWZ0O1xuICAgIGZvbnQtd2VpZ2h0OiA1MDA7IH1cbiAgQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiA2MDBweCkge1xuICAgIC5yZXBvcyB7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBwYWRkaW5nOiAwOyB9IH1cblxuYSB7XG4gIHBhZGRpbmc6IDA7XG4gIG1hcmdpbjogMDsgfVxuXG4ucmVwbyB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIG9wYWNpdHk6IDAuMDtcbiAgYW5pbWF0aW9uOiByZXZlYWwgMXMgZm9yd2FyZHM7IH1cbiAgQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiA2MDBweCkge1xuICAgIC5yZXBvIHtcbiAgICAgIGZvbnQtc2l6ZTogMC43NWVtOyB9IH1cblxuLnRpdGxlIHtcbiAgZm9udC1zaXplOiAxZW07XG4gIHBhZGRpbmc6IDA7XG4gIG1hcmdpbjogMDtcbiAgdGV4dC1hbGlnbjogbGVmdDsgfVxuXG4ubGFuZ2F1Z2Uge1xuICBmb250LXdlaWdodDogNTAwOyB9XG5cbi5iYWRnZSB7XG4gIGJhY2tncm91bmQ6IHZhcigtLXNlY29uZGFyeSk7XG4gIG1hcmdpbjogMDtcbiAgcGFkZGluZzogNXB4O1xuICBib3JkZXItcmFkaXVzOiB2YXIoLS1ib3JkZXItcmFkaXVzKTtcbiAgZm9udC1zaXplOiAwLjc1ZW07IH1cblxuLmJhZGdlLS1pdGVtIHtcbiAgbWFyZ2luOiAycHg7IH1cblxuQGtleWZyYW1lcyByZXZlYWwge1xuICBmcm9tIHtcbiAgICBvcGFjaXR5OiAwLjA7IH1cbiAgdG8ge1xuICAgIG9wYWNpdHk6IDEuMDsgfSB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPXJlcG9zLnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHVsIGNsYXNzPVwicmVwb3NcIj5cbiAgICA8aDI+UmVwb3NpdG9yaWVzPC9oMj5cbiAgICB7I2VhY2ggcmVwb3MgYXMgcmVwbywgaX1cbiAgICAgICAgPGxpIGNsYXNzPVwicmVwb1wiIHN0eWxlPVwiYW5pbWF0aW9uLWRlbGF5OiB7aSoxMH1tc1wiPlxuICAgICAgICAgICAgPGEgaHJlZj1cIntyZXBvLnVybH1cIiB0YXJnZXQ9XCJfYmxhbmtcIiByZWw9XCJub29wZW5lclwiPlxuICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwidGl0bGVcIj57cmVwby5uYW1lfVxuICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJiYWRnZVwiPlxuICAgICAgICAgICAgICAgICAgICB7I2lmIHJlcG8ucHJpbWFyeUxhbmd1YWdlfVxuICAgICAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cImJhZGdlLS1pdGVtXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cImxhbmdhdWdlXCIgc3R5bGU9XCJjb2xvcjoge2xhbmd1YWdlQ29sb3JzLmdldChyZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lKX1cIj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICB7cmVwby5wcmltYXJ5TGFuZ3VhZ2UubmFtZX1cbiAgICAgICAgICAgICAgICAgICAgICAgIDwvc3Bhbj4gXG4gICAgICAgICAgICAgICAgICAgIDwvc3Bhbj4gXG4gICAgICAgICAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICAgICAgICAgIHsjaWYgcmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9IFxuICAgICAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cImJhZGdlLS1pdGVtXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1zdGFyXCIgc3R5bGU9XCJjb2xvcjogdmFyKC0tYXBwbGVfcmV0cm9feWVsbG93KVwiPjwvaT5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuIHN0eWxlPVwiY29sb3I6IHZhcigtLWFwcGxlX3JldHJvX3llbGxvdylcIj57cmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9PC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgICAgICAgICAgIHsjaWYgcmVwby5mb3JrQ291bnR9IFxuICAgICAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cImJhZGdlLS1pdGVtXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1jb2RlLWJyYW5jaFwiIHN0eWxlPVwiY29sb3I6ICNjOTRkYTBcIj48L2k+XG4gICAgICAgICAgICAgICAgICAgICAgICA8c3BhbiBzdHlsZT1cImNvbG9yOiAjYzk0ZGEwXCI+e3JlcG8uZm9ya0NvdW50fTwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgIDwvYT5cbiAgICAgICAgPC9saT5cbiAgICB7L2VhY2h9XG48L3VsPlxuIiwiPHNjcmlwdD5cbiAgICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSAnc3ZlbHRlJ1xuICAgIGltcG9ydCB7IGNhY2hlZEZldGNoIH0gZnJvbSAnLi91dGlscy91dGlsaXR5J1xuXG4gICAgbGV0IHZpZGVvcyA9IFtdXG5cbiAgICBvbk1vdW50KGFzeW5jICgpID0+IHtcbiAgICAgICAgdmlkZW9zID0gYXdhaXQgY2FjaGVkRmV0Y2goJy8ubmV0bGlmeS9mdW5jdGlvbnMveW91dHViZScpXG5cbiAgICAgICAgLy8gU29ydCB0aGUgdmlkZW9zIGJhc2VkIG9uIHZpZXcgY291bnRcbiAgICAgICAgdmlkZW9zLnNvcnQoKGEsIGIpID0+IHBhcnNlSW50KGIuc3RhdGlzdGljcy52aWV3Q291bnQpIC0gcGFyc2VJbnQoYS5zdGF0aXN0aWNzLnZpZXdDb3VudCkpXG4gICAgfSlcbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4udmlkZW9zIHtcbiAgdGV4dC1hbGlnbjogbGVmdDtcbiAgZGlzcGxheTogaW5saW5lLWJsb2NrOyB9XG4gIC52aWRlb3MgaDIge1xuICAgIHBhZGRpbmc6IDVweDtcbiAgICB0ZXh0LWFsaWduOiBsZWZ0O1xuICAgIGZvbnQtd2VpZ2h0OiA1MDA7IH1cbiAgQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiA2MDBweCkge1xuICAgIC52aWRlb3Mge1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgcGFkZGluZzogMDsgfSB9XG5cbmEge1xuICBwYWRkaW5nOiAwO1xuICBtYXJnaW46IDA7IH1cblxuLnZpZGVvIHtcbiAgZGlzcGxheTogZmxleDtcbiAgb3BhY2l0eTogMC4wO1xuICBhbmltYXRpb246IHJldmVhbCAxcyBmb3J3YXJkczsgfVxuICBAbWVkaWEgb25seSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDYwMHB4KSB7XG4gICAgLnZpZGVvIHtcbiAgICAgIGZvbnQtc2l6ZTogMC43NWVtOyB9IH1cblxuLnRpdGxlIHtcbiAgZm9udC1zaXplOiAxZW07XG4gIHBhZGRpbmc6IDA7XG4gIG1hcmdpbjogMDtcbiAgdGV4dC1hbGlnbjogbGVmdDsgfVxuXG4uYmFkZ2Uge1xuICBiYWNrZ3JvdW5kOiB2YXIoLS1zZWNvbmRhcnkpO1xuICBtYXJnaW46IDA7XG4gIHBhZGRpbmc6IDVweDtcbiAgYm9yZGVyLXJhZGl1czogdmFyKC0tYm9yZGVyLXJhZGl1cyk7XG4gIGZvbnQtc2l6ZTogMC43NWVtOyB9XG5cbi5iYWRnZS0taXRlbSB7XG4gIG1hcmdpbjogMnB4OyB9XG5cbkBrZXlmcmFtZXMgcmV2ZWFsIHtcbiAgZnJvbSB7XG4gICAgb3BhY2l0eTogMC4wOyB9XG4gIHRvIHtcbiAgICBvcGFjaXR5OiAwLjg7IH0gfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD15b3V0dWJlLXZpZGVvcy5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjx1bCBjbGFzcz1cInZpZGVvc1wiPlxuICAgIDxoMj5WaWRlb3M8L2gyPlxuICAgIHsjZWFjaCB2aWRlb3MgYXMgdmlkZW8sIGl9ICAgICAgICAgICAgXG4gICAgICAgIDxsaSBjbGFzcz1cInZpZGVvXCIgc3R5bGU9XCJhbmltYXRpb24tZGVsYXk6IHtpKjEwfW1zXCI+XG4gICAgICAgICAgICA8YSBocmVmPVwiaHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj17dmlkZW8uaWR9XCIgdGFyZ2V0PVwiX2JsYW5rXCIgcmVsPVwibm9vcGVuZXJcIj5cbiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzcz1cInRpdGxlXCI+e3ZpZGVvLnRpdGxlfVxuICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJiYWRnZVwiPlxuICAgICAgICAgICAgICAgICAgICB7I2lmIHBhcnNlSW50KHZpZGVvLnN0YXRpc3RpY3Mudmlld0NvdW50KX1cbiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtZXllXCIgc3R5bGU9XCJjb2xvcjogdmFyKC0tc3lzdGVtR3JheSlcIj48L2k+XG4gICAgICAgICAgICAgICAgICAgICAgICA8c3BhbiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1HcmF5KVwiPiB7dmlkZW8uc3RhdGlzdGljcy52aWV3Q291bnR9IDwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgICAgICB7I2lmIHBhcnNlSW50KHZpZGVvLnN0YXRpc3RpY3MubGlrZUNvdW50KX1cbiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtaGVhcnRcIiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1SZWQpXCI+PC9pPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9XCJjb2xvcjogdmFyKC0tc3lzdGVtUmVkKVwiPnt2aWRlby5zdGF0aXN0aWNzLmxpa2VDb3VudH08L3NwYW4+XG4gICAgICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgICAgICAgICAgeyNpZiBwYXJzZUludCh2aWRlby5zdGF0aXN0aWNzLmNvbW1lbnRDb3VudCl9XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwiYmFkZ2UtLWl0ZW1cIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxpIGNsYXNzPVwiZmFzIGZhLWNvbW1lbnRcIiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1CbHVlKVwiPjwvaT5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxzcGFuIHN0eWxlPVwiY29sb3I6IHZhcigtLXN5c3RlbUJsdWUpXCI+e3ZpZGVvLnN0YXRpc3RpY3MuY29tbWVudENvdW50fTwvc3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgIDwvYT5cbiAgICAgICAgPC9saT5cbiAgICB7L2VhY2h9XG48L3VsPlxuIl0sInNvdXJjZVJvb3QiOiIifQ==