(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_p2d_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/p2d.svelte */ "./src/components/p2d.svelte");
/* src/routes/index.svelte generated by Svelte v3.9.2 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-zw8qc-style';
	style.textContent = "@font-face{font-family:'pxplus_ibm_vga8regular';src:url('pxplus_ibm_vga8-webfont.woff2') format('woff2'),\n            url('pxplus_ibm_vga8-webfont.woff') format('woff');font-weight:normal;font-style:normal}button:focus{outline:0}:root{--apple_retro_green:#61bb46;--apple_retro_yellow:#fdb827;--apple_retro_orange:#f5821f;--apple_retro_red:#e03a3e;--apple_retro_purple:#963d97;--apple_blue:rgb(64, 156, 255);--apple_gray:rgb(152, 152, 157);--apple_green:rgb(48, 219, 91);--apple_indigo:rgb(125, 122, 255);--apple_orange:rgb(255, 179, 64);--apple_pink:rgb(255, 100, 130);--apple_purple:rgb(218, 143, 255);--apple_red:rgb(255, 105, 97);--apple_teal:rgb(112, 215, 255);--apple_yellow:rgb(255, 212, 38);--c_blue:#247ba0;--c_white:#faf1d8;--c_pink:#dd7373;--c_black:#3e4e50;--c_warm_black:#02394a;--c_black_olive:#393d3f;--c_orange:#f79d65;--c_turq:#69d1c5;--c_almond:#eed7c5;--c_cadedblue:#5c9ead;--c_carib_green:#02c39a;--storage:#5c9ead;--literal:#02c39a;--comment:#f79d65;--keyword:rgb(255, 100, 130);--compile_time_resolved:rgb(125, 122, 255);--font:'pxplus_ibm_vga8regular';--text:#3e4e50;--background:#f8f0da;--text-color--normal:var(--text);--text-color--light:#3e4e50;--text-color--richer:#3e4e50;--text-color--highlight:rgb(255, 100, 130)}@media(prefers-color-scheme: light){:root{--text-color--normal:var(--text);--text-color--light:var(--c_black);--text-color--richer:var(--c_black);--text-color--highlight:var(--keyword);--text-color--comment:var(--comment);--background--content:rgb(255, 255, 255);--background:#f8f0da;--background-color--selection:yellow}}@media(prefers-color-scheme: dark){:root{--text-color--normal:var(--c_white);--text-color--light:var(--c_white);--text-color--richer:var(--c_white);--text-color--highlight:var(--apple_pink);--text-color--comment:var(--comment);--background--content:rgb(30, 30, 30);--background:#000;--background-color--selection:var(--apple_pink)}}*{color:var(--text);background:var(--background);font-family:var(--font);text-align:center;line-height:1.5;font-size:1em}img.svelte-zw8qc{max-width:200px;border-radius:50px}.landing-page--hero.svelte-zw8qc{display:inline}.swapOnHover.svelte-zw8qc img.svelte-zw8qc:last-child{display:none}.swapOnHover.svelte-zw8qc:hover img.svelte-zw8qc:first-child{display:none}.swapOnHover.svelte-zw8qc:hover img.svelte-zw8qc:last-child{display:inline}.landing-page--subtitle.svelte-zw8qc{display:block;text-align:center}.landing-page--title.svelte-zw8qc{display:block;font-size:30px;font-weight:900;text-align:center}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gICAgOmdsb2JhbChAZm9udC1mYWNlKSB7XG4gICAgICAgIGZvbnQtZmFtaWx5OiAncHhwbHVzX2libV92Z2E4cmVndWxhcic7XG4gICAgICAgIHNyYzogdXJsKCdweHBsdXNfaWJtX3ZnYTgtd2ViZm9udC53b2ZmMicpIGZvcm1hdCgnd29mZjInKSxcbiAgICAgICAgICAgIHVybCgncHhwbHVzX2libV92Z2E4LXdlYmZvbnQud29mZicpIGZvcm1hdCgnd29mZicpO1xuICAgICAgICBmb250LXdlaWdodDogbm9ybWFsO1xuICAgICAgICBmb250LXN0eWxlOiBub3JtYWw7XG4gICAgfVxuICAgIDpnbG9iYWwoYnV0dG9uOmZvY3VzKSB7XG4gICAgICAgIG91dGxpbmU6IDA7XG4gICAgfVxuXG4gICAgOmdsb2JhbCg6cm9vdCkge1xuICAgICAgICAtLWFwcGxlX3JldHJvX2dyZWVuOiAjNjFiYjQ2O1xuICAgICAgICAtLWFwcGxlX3JldHJvX3llbGxvdzogI2ZkYjgyNztcbiAgICAgICAgLS1hcHBsZV9yZXRyb19vcmFuZ2U6ICNmNTgyMWY7XG4gICAgICAgIC0tYXBwbGVfcmV0cm9fcmVkOiAjZTAzYTNlO1xuICAgICAgICAtLWFwcGxlX3JldHJvX3B1cnBsZTogIzk2M2Q5NztcbiAgICAgICAgLS1hcHBsZV9ibHVlOiByZ2IoNjQsIDE1NiwgMjU1KTtcbiAgICAgICAgLS1hcHBsZV9ncmF5OiByZ2IoMTUyLCAxNTIsIDE1Nyk7XG4gICAgICAgIC0tYXBwbGVfZ3JlZW46IHJnYig0OCwgMjE5LCA5MSk7XG4gICAgICAgIC0tYXBwbGVfaW5kaWdvOiByZ2IoMTI1LCAxMjIsIDI1NSk7XG4gICAgICAgIC0tYXBwbGVfb3JhbmdlOiByZ2IoMjU1LCAxNzksIDY0KTtcbiAgICAgICAgLS1hcHBsZV9waW5rOiByZ2IoMjU1LCAxMDAsIDEzMCk7XG4gICAgICAgIC0tYXBwbGVfcHVycGxlOiByZ2IoMjE4LCAxNDMsIDI1NSk7XG4gICAgICAgIC0tYXBwbGVfcmVkOiByZ2IoMjU1LCAxMDUsIDk3KTtcbiAgICAgICAgLS1hcHBsZV90ZWFsOiByZ2IoMTEyLCAyMTUsIDI1NSk7XG4gICAgICAgIC0tYXBwbGVfeWVsbG93OiByZ2IoMjU1LCAyMTIsIDM4KTtcbiAgICAgICAgLS1jX2JsdWU6ICMyNDdiYTA7XG4gICAgICAgIC0tY193aGl0ZTogI2ZhZjFkODtcbiAgICAgICAgLS1jX3Bpbms6ICNkZDczNzM7XG4gICAgICAgIC0tY19ibGFjazogIzNlNGU1MDtcbiAgICAgICAgLS1jX3dhcm1fYmxhY2s6ICMwMjM5NGE7XG4gICAgICAgIC0tY19ibGFja19vbGl2ZTogIzM5M2QzZjtcbiAgICAgICAgLS1jX29yYW5nZTogI2Y3OWQ2NTtcbiAgICAgICAgLS1jX3R1cnE6ICM2OWQxYzU7XG4gICAgICAgIC0tY19hbG1vbmQ6ICNlZWQ3YzU7XG4gICAgICAgIC0tY19jYWRlZGJsdWU6ICM1YzllYWQ7XG4gICAgICAgIC0tY19jYXJpYl9ncmVlbjogIzAyYzM5YTtcblxuICAgICAgICAtLXN0b3JhZ2U6ICM1YzllYWQ7XG4gICAgICAgIC0tbGl0ZXJhbDogIzAyYzM5YTtcbiAgICAgICAgLS1jb21tZW50OiAjZjc5ZDY1O1xuICAgICAgICAtLWtleXdvcmQ6IHJnYigyNTUsIDEwMCwgMTMwKTtcbiAgICAgICAgLS1jb21waWxlX3RpbWVfcmVzb2x2ZWQ6IHJnYigxMjUsIDEyMiwgMjU1KTtcblxuICAgICAgICAtLWZvbnQ6ICdweHBsdXNfaWJtX3ZnYThyZWd1bGFyJztcbiAgICAgICAgLS10ZXh0OiAjM2U0ZTUwO1xuICAgICAgICAtLWJhY2tncm91bmQ6ICNmOGYwZGE7XG5cbiAgICAgICAgLS10ZXh0LWNvbG9yLS1ub3JtYWw6IHZhcigtLXRleHQpO1xuICAgICAgICAtLXRleHQtY29sb3ItLWxpZ2h0OiAjM2U0ZTUwO1xuICAgICAgICAtLXRleHQtY29sb3ItLXJpY2hlcjogIzNlNGU1MDtcbiAgICAgICAgLS10ZXh0LWNvbG9yLS1oaWdobGlnaHQ6IHJnYigyNTUsIDEwMCwgMTMwKTtcbiAgICB9XG5cbiAgICBAbWVkaWEgKHByZWZlcnMtY29sb3Itc2NoZW1lOiBsaWdodCkge1xuICAgICAgICA6cm9vdCB7XG4gICAgICAgICAgICAtLXRleHQtY29sb3ItLW5vcm1hbDogdmFyKC0tdGV4dCk7XG4gICAgICAgICAgICAtLXRleHQtY29sb3ItLWxpZ2h0OiB2YXIoLS1jX2JsYWNrKTtcbiAgICAgICAgICAgIC0tdGV4dC1jb2xvci0tcmljaGVyOiB2YXIoLS1jX2JsYWNrKTtcbiAgICAgICAgICAgIC0tdGV4dC1jb2xvci0taGlnaGxpZ2h0OiB2YXIoLS1rZXl3b3JkKTtcbiAgICAgICAgICAgIC0tdGV4dC1jb2xvci0tY29tbWVudDogdmFyKC0tY29tbWVudCk7XG4gICAgICAgICAgICAtLWJhY2tncm91bmQtLWNvbnRlbnQ6IHJnYigyNTUsIDI1NSwgMjU1KTtcbiAgICAgICAgICAgIC0tYmFja2dyb3VuZDogI2Y4ZjBkYTtcbiAgICAgICAgICAgIC0tYmFja2dyb3VuZC1jb2xvci0tc2VsZWN0aW9uOiB5ZWxsb3c7XG4gICAgICAgIH1cbiAgICB9XG5cbiAgICBAbWVkaWEgKHByZWZlcnMtY29sb3Itc2NoZW1lOiBkYXJrKSB7XG4gICAgICAgIDpyb290IHtcbiAgICAgICAgICAgIC0tdGV4dC1jb2xvci0tbm9ybWFsOiB2YXIoLS1jX3doaXRlKTtcbiAgICAgICAgICAgIC0tdGV4dC1jb2xvci0tbGlnaHQ6IHZhcigtLWNfd2hpdGUpO1xuICAgICAgICAgICAgLS10ZXh0LWNvbG9yLS1yaWNoZXI6IHZhcigtLWNfd2hpdGUpO1xuICAgICAgICAgICAgLS10ZXh0LWNvbG9yLS1oaWdobGlnaHQ6IHZhcigtLWFwcGxlX3BpbmspO1xuICAgICAgICAgICAgLS10ZXh0LWNvbG9yLS1jb21tZW50OiB2YXIoLS1jb21tZW50KTtcbiAgICAgICAgICAgIC0tYmFja2dyb3VuZC0tY29udGVudDogcmdiKDMwLCAzMCwgMzApO1xuICAgICAgICAgICAgLS1iYWNrZ3JvdW5kOiAjMDAwO1xuICAgICAgICAgICAgLS1iYWNrZ3JvdW5kLWNvbG9yLS1zZWxlY3Rpb246IHZhcigtLWFwcGxlX3BpbmspO1xuICAgICAgICB9XG4gICAgfVxuXG4gICAgOmdsb2JhbCgqKSB7XG4gICAgICAgIGNvbG9yOiB2YXIoLS10ZXh0KTtcbiAgICAgICAgYmFja2dyb3VuZDogdmFyKC0tYmFja2dyb3VuZCk7XG4gICAgICAgIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250KTtcbiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgICBsaW5lLWhlaWdodDogMS41O1xuICAgICAgICBmb250LXNpemU6IDFlbTtcbiAgICB9XG5cbiAgICAuZW50aXR5IHtcbiAgICAgICAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICAgICAgICBwYWRkaW5nOiAxcHg7XG4gICAgICAgIGNvbG9yOiAjZjc5ZDY1O1xuICAgICAgICBiYWNrZ3JvdW5kOiByZ2JhKCNmNzlkNjUsIDAuMSk7XG4gICAgICAgIGZvbnQtc3R5bGU6IGl0YWxpYztcbiAgICB9XG5cbiAgICAua2V5d29yZCB7XG4gICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgICAgICAgcGFkZGluZzogMXB4O1xuICAgICAgICBjb2xvcjogI2ZmNjQ4MjtcbiAgICAgICAgYmFja2dyb3VuZDogcmdiYSgjZmY2NDgyLCAwLjEpO1xuICAgICAgICBmb250LXN0eWxlOiBub3JtYWw7XG4gICAgfVxuXG4gICAgLmZhaW50IHtcbiAgICAgICAgZm9udC1zaXplOiAwLjc1ZW07XG4gICAgICAgIGNvbG9yOiByZ2JhKHZhcigtLXRleHQpLCAwLjUpO1xuICAgIH1cbiAgICBhIHtcbiAgICAgICAgdGV4dC1kZWNvcmF0aW9uOiBub25lO1xuICAgIH1cblxuICAgIGltZyB7XG4gICAgICAgIG1heC13aWR0aDogMjAwcHg7XG4gICAgICAgIGJvcmRlci1yYWRpdXM6IDUwcHg7XG4gICAgfVxuICAgIC5sYW5kaW5nLXBhZ2UtLWhlcm8ge1xuICAgICAgICBkaXNwbGF5OiBpbmxpbmU7XG4gICAgfVxuXG4gICAgLnN3YXBPbkhvdmVyIGltZzpsYXN0LWNoaWxkIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG5cbiAgICAuc3dhcE9uSG92ZXI6aG92ZXIgaW1nOmZpcnN0LWNoaWxkIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG4gICAgLnN3YXBPbkhvdmVyOmhvdmVyIGltZzpsYXN0LWNoaWxkIHtcbiAgICAgICAgZGlzcGxheTogaW5saW5lO1xuICAgIH1cblxuICAgIC5sYW5kaW5nLXBhZ2UtLXN1YnRpdGxlIHtcbiAgICAgICAgZGlzcGxheTogYmxvY2s7XG4gICAgICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICB9XG4gICAgLmxhbmRpbmctcGFnZS0tdGl0bGUge1xuICAgICAgICBkaXNwbGF5OiBibG9jaztcbiAgICAgICAgZm9udC1zaXplOiAzMHB4O1xuICAgICAgICBmb250LXdlaWdodDogOTAwO1xuICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgfVxuPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICAgIDx0aXRsZT5Ib21lPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG48ZGl2IGNsYXNzPVwiLmxhbmRpbmctcGFnZS0taGVybyBzd2FwT25Ib3ZlclwiPlxuICAgIDxpbWcgc3JjPVwiYXZhdGFyX3BpeGVsYXRlZC5qcGdcIiBhbHQ9XCJwaWN0dXJlIG9mIG1lXCIgLz5cbiAgICA8aW1nIHNyYz1cImF2YXRhci5wbmdcIiBhbHQ9XCJwaWN0dXJlIG9mIG1lXCIgLz5cbjwvZGl2PlxuPHAgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLXRpdGxlXCI+TWFyY3VzIE1hdGhpYXNzZW48L3A+XG48cCBjbGFzcz1cImxhbmRpbmctcGFnZS0tc3VidGl0bGVcIj5cbiAgICBJIGRvIGNvbXBpbGVycyBhbmQgbGFuZ3VhZ2VzLlxuICAgIDxiciAvPlxuICAgIEludGVyZXN0ZWQgaW4gc3lzdGVtcyBkZXNpZ24gYW5kIFVYLlxuPC9wPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUtZLFVBQVUsQUFBRSxDQUFDLEFBQ2pCLFdBQVcsQ0FBRSx3QkFBd0IsQ0FDckMsR0FBRyxDQUFFLElBQUksK0JBQStCLENBQUMsQ0FBQyxPQUFPLE9BQU8sQ0FBQyxDQUFDO1lBQ3RELElBQUksOEJBQThCLENBQUMsQ0FBQyxPQUFPLE1BQU0sQ0FBQyxDQUN0RCxXQUFXLENBQUUsTUFBTSxDQUNuQixVQUFVLENBQUUsTUFBTSxBQUN0QixDQUFDLEFBQ08sWUFBWSxBQUFFLENBQUMsQUFDbkIsT0FBTyxDQUFFLENBQUMsQUFDZCxDQUFDLEFBRU8sS0FBSyxBQUFFLENBQUMsQUFDWixtQkFBbUIsQ0FBRSxPQUFPLENBQzVCLG9CQUFvQixDQUFFLE9BQU8sQ0FDN0Isb0JBQW9CLENBQUUsT0FBTyxDQUM3QixpQkFBaUIsQ0FBRSxPQUFPLENBQzFCLG9CQUFvQixDQUFFLE9BQU8sQ0FDN0IsWUFBWSxDQUFFLGlCQUFpQixDQUMvQixZQUFZLENBQUUsa0JBQWtCLENBQ2hDLGFBQWEsQ0FBRSxnQkFBZ0IsQ0FDL0IsY0FBYyxDQUFFLGtCQUFrQixDQUNsQyxjQUFjLENBQUUsaUJBQWlCLENBQ2pDLFlBQVksQ0FBRSxrQkFBa0IsQ0FDaEMsY0FBYyxDQUFFLGtCQUFrQixDQUNsQyxXQUFXLENBQUUsaUJBQWlCLENBQzlCLFlBQVksQ0FBRSxrQkFBa0IsQ0FDaEMsY0FBYyxDQUFFLGlCQUFpQixDQUNqQyxRQUFRLENBQUUsT0FBTyxDQUNqQixTQUFTLENBQUUsT0FBTyxDQUNsQixRQUFRLENBQUUsT0FBTyxDQUNqQixTQUFTLENBQUUsT0FBTyxDQUNsQixjQUFjLENBQUUsT0FBTyxDQUN2QixlQUFlLENBQUUsT0FBTyxDQUN4QixVQUFVLENBQUUsT0FBTyxDQUNuQixRQUFRLENBQUUsT0FBTyxDQUNqQixVQUFVLENBQUUsT0FBTyxDQUNuQixhQUFhLENBQUUsT0FBTyxDQUN0QixlQUFlLENBQUUsT0FBTyxDQUV4QixTQUFTLENBQUUsT0FBTyxDQUNsQixTQUFTLENBQUUsT0FBTyxDQUNsQixTQUFTLENBQUUsT0FBTyxDQUNsQixTQUFTLENBQUUsa0JBQWtCLENBQzdCLHVCQUF1QixDQUFFLGtCQUFrQixDQUUzQyxNQUFNLENBQUUsd0JBQXdCLENBQ2hDLE1BQU0sQ0FBRSxPQUFPLENBQ2YsWUFBWSxDQUFFLE9BQU8sQ0FFckIsb0JBQW9CLENBQUUsV0FBVyxDQUNqQyxtQkFBbUIsQ0FBRSxPQUFPLENBQzVCLG9CQUFvQixDQUFFLE9BQU8sQ0FDN0IsdUJBQXVCLENBQUUsa0JBQWtCLEFBQy9DLENBQUMsQUFFRCxNQUFNLEFBQUMsdUJBQXVCLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDbEMsS0FBSyxBQUFDLENBQUMsQUFDSCxvQkFBb0IsQ0FBRSxXQUFXLENBQ2pDLG1CQUFtQixDQUFFLGNBQWMsQ0FDbkMsb0JBQW9CLENBQUUsY0FBYyxDQUNwQyx1QkFBdUIsQ0FBRSxjQUFjLENBQ3ZDLHFCQUFxQixDQUFFLGNBQWMsQ0FDckMscUJBQXFCLENBQUUsa0JBQWtCLENBQ3pDLFlBQVksQ0FBRSxPQUFPLENBQ3JCLDZCQUE2QixDQUFFLE1BQU0sQUFDekMsQ0FBQyxBQUNMLENBQUMsQUFFRCxNQUFNLEFBQUMsdUJBQXVCLElBQUksQ0FBQyxBQUFDLENBQUMsQUFDakMsS0FBSyxBQUFDLENBQUMsQUFDSCxvQkFBb0IsQ0FBRSxjQUFjLENBQ3BDLG1CQUFtQixDQUFFLGNBQWMsQ0FDbkMsb0JBQW9CLENBQUUsY0FBYyxDQUNwQyx1QkFBdUIsQ0FBRSxpQkFBaUIsQ0FDMUMscUJBQXFCLENBQUUsY0FBYyxDQUNyQyxxQkFBcUIsQ0FBRSxlQUFlLENBQ3RDLFlBQVksQ0FBRSxJQUFJLENBQ2xCLDZCQUE2QixDQUFFLGlCQUFpQixBQUNwRCxDQUFDLEFBQ0wsQ0FBQyxBQUVPLENBQUMsQUFBRSxDQUFDLEFBQ1IsS0FBSyxDQUFFLElBQUksTUFBTSxDQUFDLENBQ2xCLFVBQVUsQ0FBRSxJQUFJLFlBQVksQ0FBQyxDQUM3QixXQUFXLENBQUUsSUFBSSxNQUFNLENBQUMsQ0FDeEIsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsU0FBUyxDQUFFLEdBQUcsQUFDbEIsQ0FBQyxBQTBCRCxHQUFHLGFBQUMsQ0FBQyxBQUNELFNBQVMsQ0FBRSxLQUFLLENBQ2hCLGFBQWEsQ0FBRSxJQUFJLEFBQ3ZCLENBQUMsQUFDRCxtQkFBbUIsYUFBQyxDQUFDLEFBQ2pCLE9BQU8sQ0FBRSxNQUFNLEFBQ25CLENBQUMsQUFFRCx5QkFBWSxDQUFDLGdCQUFHLFdBQVcsQUFBQyxDQUFDLEFBQ3pCLE9BQU8sQ0FBRSxJQUFJLEFBQ2pCLENBQUMsQUFFRCx5QkFBWSxNQUFNLENBQUMsZ0JBQUcsWUFBWSxBQUFDLENBQUMsQUFDaEMsT0FBTyxDQUFFLElBQUksQUFDakIsQ0FBQyxBQUNELHlCQUFZLE1BQU0sQ0FBQyxnQkFBRyxXQUFXLEFBQUMsQ0FBQyxBQUMvQixPQUFPLENBQUUsTUFBTSxBQUNuQixDQUFDLEFBRUQsdUJBQXVCLGFBQUMsQ0FBQyxBQUNyQixPQUFPLENBQUUsS0FBSyxDQUNkLFVBQVUsQ0FBRSxNQUFNLEFBQ3RCLENBQUMsQUFDRCxvQkFBb0IsYUFBQyxDQUFDLEFBQ2xCLE9BQU8sQ0FBRSxLQUFLLENBQ2QsU0FBUyxDQUFFLElBQUksQ0FDZixXQUFXLENBQUUsR0FBRyxDQUNoQixVQUFVLENBQUUsTUFBTSxBQUN0QixDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var t0, div, img0, t1, img1, t2, p0, t3, t4, p1, t5, br, t6;

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Marcus Mathiassen");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I do compilers and languages.\n    ");
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    Interested in systems design and UX.");
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "IMG", { src: true, alt: true, class: true }, false);
			var img0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img0);

			img0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div_nodes, "\n    ");

			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "IMG", { src: true, alt: true, class: true }, false);
			var img1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img1);

			img1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Marcus Mathiassen");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "I do compilers and languages.\n    ");

			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "BR", { class: true }, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n    Interested in systems design and UX.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Home";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img0, "src", "avatar_pixelated.jpg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img0, "alt", "picture of me");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img0, "class", "svelte-zw8qc");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img0, file, 154, 4, 4099);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img1, "src", "avatar.png");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img1, "alt", "picture of me");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img1, "class", "svelte-zw8qc");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img1, file, 155, 4, 4158);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div, "class", ".landing-page--hero swapOnHover svelte-zw8qc");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 153, 0, 4049);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p0, "class", "landing-page--title svelte-zw8qc");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 157, 0, 4210);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(br, "class", "svelte-zw8qc");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 160, 4, 4336);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p1, "class", "landing-page--subtitle svelte-zw8qc");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 158, 0, 4263);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, img0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div, img1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t4, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, p1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, br);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t6);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t4);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(p1);
			}
		}
	};
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-zw8qc-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJmYmFmMTZhZTQ1NGQ5YThhNGNhOC9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbXSwic291cmNlUm9vdCI6IiJ9