(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_p2d_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/p2d.svelte */ "./src/components/p2d.svelte");
/* src/routes/index.svelte generated by Svelte v3.9.2 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-9cn10b-style';
	style.textContent = ".landing-page--hero.svelte-9cn10b{width:50%;margin:20px auto;display:block;background-image:var(--avatar);background-size:cover;width:300px;height:300px}li.svelte-9cn10b,ul.svelte-9cn10b{margin:5px;margin-top:10px;list-style-type:none}span.svelte-9cn10b{font-family:var(--font)}.repos.svelte-9cn10b{margin:0 auto;width:100%;padding:0}.repos.svelte-9cn10b h2.svelte-9cn10b{margin:5px;padding:5px;text-align:center;font-weight:500}.repo.svelte-9cn10b{margin:5px;padding:5px;text-align:center}@media only screen and (max-width: 600px){.repo.svelte-9cn10b{font-size:0.75rem}}.repo--name.svelte-9cn10b{font-size:1em;padding:0;margin:0}.repo--badges.svelte-9cn10b{--c:blue;background:var(--secondary);margin:5px;padding:5px;border-radius:var(--border-radius);font-size:0.75em}.repo--badges.svelte-9cn10b span.svelte-9cn10b{margin:2px}.repo--langauge.svelte-9cn10b{color:var(--c);padding:5px;padding-top:1px;padding-bottom:1px;border-radius:5px;font-size:1em;font-weight:700}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBpbXBvcnQgUDJEIGZyb20gJy4uL2NvbXBvbmVudHMvcDJkLnN2ZWx0ZSdcbiAgICBsZXQgcmVwb3MgPSBcIlwiXG4gICAgZmV0Y2goXCIvLm5ldGxpZnkvZnVuY3Rpb25zL2dpdGh1YlwiKS50aGVuKHJlcyA9PiByZXMuanNvbigpKS50aGVuKGpzb24gPT4ge1xuICAgICAgICByZXBvcyA9IGpzb25cbiAgICB9KVxuXG4vLyAgICAgcmVwb3MgPSBbXG4vLyAgICAge1xuLy8gICAgICAgICBcImZvcmtDb3VudFwiOiAyNyxcbi8vICAgICAgICAgXCJ1cmxcIjogXCJibHVlXCIsXG4vLyAgICAgICAgIFwibmFtZVwiOiBcIkxldGljaWEgSGFuc2VuXCIsXG4vLyAgICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbi8vICAgICAgICAgICAgIFwibmFtZVwiOiBcIkphdmFTY3JpcHRcIixcbi8vICAgICAgICAgICAgIFwiY29sb3JcIjogXCIjMDBmZlwiXG4vLyAgICAgICAgIH0sXG4vLyAgICAgICAgIFwiZGVzY3JpcHRpb25cIjogXCJ0aGUgY29sb3IgYmx1ZVwiLFxuLy8gICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuLy8gICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDMwXG4vLyAgICAgICAgIH1cbi8vICAgICB9LFxuLy8gICAgIHtcbi8vICAgICAgICAgXCJmb3JrQ291bnRcIjogNDAsXG4vLyAgICAgICAgIFwidXJsXCI6IFwiYnJvd25cIixcbi8vICAgICAgICAgXCJuYW1lXCI6IFwiQ2FuZHkgVmFzcXVleiBWZXJvbmljXCIsXG4vLyAgICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbi8vICAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuLy8gICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjBmXCJcbi8vICAgICAgICAgfSxcbi8vICAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbi8vICAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyNlxuLy8gICAgICAgICB9XG4vLyAgICAgfSxcbi8vICAgICB7XG4vLyAgICAgICAgIFwiZm9ya0NvdW50XCI6IDM2LFxuLy8gICAgICAgICBcInVybFwiOiBcImdyZWVuXCIsXG4vLyAgICAgICAgIFwibmFtZVwiOiBcIkxhbWIgSm9obnNvblwiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJDKytcIixcbi8vICAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZjAwZlwiXG4vLyAgICAgICAgIH0sXG4vLyAgICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4vLyAgICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMjRcbi8vICAgICAgICAgfVxuLy8gICAgIH0sXG4vLyAgICAge1xuLy8gICAgICAgICBcImZvcmtDb3VudFwiOiAyMyxcbi8vICAgICAgICAgXCJ1cmxcIjogXCJibHVlXCIsXG4vLyAgICAgICAgIFwibmFtZVwiOiBcIlNvbG9tb24gTWVkaW5hXCIsXG4vLyAgICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbi8vICAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuLy8gICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmMDBmXCJcbi8vICAgICAgICAgfSxcbi8vICAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbi8vICAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAzOVxuLy8gICAgICAgICB9XG4vLyAgICAgfSxcbi8vICAgICB7XG4vLyAgICAgICAgIFwiZm9ya0NvdW50XCI6IDI2LFxuLy8gICAgICAgICBcInVybFwiOiBcImJsdWVcIixcbi8vICAgICAgICAgXCJuYW1lXCI6IFwiUmljaG1vbmQgSGVzc1wiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJDKytcIixcbi8vICAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZmYwZlwiXG4vLyAgICAgICAgIH0sXG4vLyAgICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4vLyAgICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMjRcbi8vICAgICAgICAgfVxuLy8gICAgIH0sXG4vLyAgICAge1xuLy8gICAgICAgICBcImZvcmtDb3VudFwiOiAzOCxcbi8vICAgICAgICAgXCJ1cmxcIjogXCJncmVlblwiLFxuLy8gICAgICAgICBcIm5hbWVcIjogXCJTcGVuY2VyIEJ1c2hcIixcbi8vICAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuLy8gICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiI2ZmMGZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuLy8gICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDMzXG4vLyAgICAgICAgIH1cbi8vICAgICB9LFxuLy8gICAgIHtcbi8vICAgICAgICAgXCJmb3JrQ291bnRcIjogMjIsXG4vLyAgICAgICAgIFwidXJsXCI6IFwiZ3JlZW5cIixcbi8vICAgICAgICAgXCJuYW1lXCI6IFwiSGFtbW9uZCBNYW5uXCIsXG4vLyAgICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbi8vICAgICAgICAgICAgIFwibmFtZVwiOiBcIkphdmFTY3JpcHRcIixcbi8vICAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZmYwZlwiXG4vLyAgICAgICAgIH0sXG4vLyAgICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4vLyAgICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMjJcbi8vICAgICAgICAgfVxuLy8gICAgIH1cbi8vIF1cblxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBsYW5nPVwic2Fzc1wiPi5sYW5kaW5nLXBhZ2UtLWhlcm8ge1xuICB3aWR0aDogNTAlO1xuICBtYXJnaW46IDIwcHggYXV0bztcbiAgZGlzcGxheTogYmxvY2s7XG4gIGJhY2tncm91bmQtaW1hZ2U6IHZhcigtLWF2YXRhcik7XG4gIGJhY2tncm91bmQtc2l6ZTogY292ZXI7XG4gIHdpZHRoOiAzMDBweDtcbiAgaGVpZ2h0OiAzMDBweDsgfVxuXG5saSwgdWwge1xuICBtYXJnaW46IDVweDtcbiAgbWFyZ2luLXRvcDogMTBweDtcbiAgbGlzdC1zdHlsZS10eXBlOiBub25lOyB9XG5cbnNwYW4ge1xuICBmb250LWZhbWlseTogdmFyKC0tZm9udCk7IH1cblxuLnJlcG9zIHtcbiAgbWFyZ2luOiAwIGF1dG87XG4gIHdpZHRoOiAxMDAlO1xuICBwYWRkaW5nOiAwOyB9XG4gIC5yZXBvcyBoMiB7XG4gICAgbWFyZ2luOiA1cHg7XG4gICAgcGFkZGluZzogNXB4O1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBmb250LXdlaWdodDogNTAwOyB9XG5cbi5yZXBvIHtcbiAgbWFyZ2luOiA1cHg7XG4gIHBhZGRpbmc6IDVweDtcbiAgdGV4dC1hbGlnbjogY2VudGVyOyB9XG4gIEBtZWRpYSBvbmx5IHNjcmVlbiBhbmQgKG1heC13aWR0aDogNjAwcHgpIHtcbiAgICAucmVwbyB7XG4gICAgICBmb250LXNpemU6IDAuNzVyZW07IH0gfVxuXG4ucmVwby0tbmFtZSB7XG4gIGZvbnQtc2l6ZTogMWVtO1xuICBwYWRkaW5nOiAwO1xuICBtYXJnaW46IDA7IH1cblxuLnJlcG8tLWJhZGdlcyB7XG4gIC0tYzogYmx1ZTtcbiAgYmFja2dyb3VuZDogdmFyKC0tc2Vjb25kYXJ5KTtcbiAgbWFyZ2luOiA1cHg7XG4gIHBhZGRpbmc6IDVweDtcbiAgYm9yZGVyLXJhZGl1czogdmFyKC0tYm9yZGVyLXJhZGl1cyk7XG4gIGZvbnQtc2l6ZTogMC43NWVtOyB9XG4gIC5yZXBvLS1iYWRnZXMgc3BhbiB7XG4gICAgbWFyZ2luOiAycHg7IH1cblxuLnJlcG8tLWxhbmdhdWdlIHtcbiAgY29sb3I6IHZhcigtLWMpO1xuICBwYWRkaW5nOiA1cHg7XG4gIHBhZGRpbmctdG9wOiAxcHg7XG4gIHBhZGRpbmctYm90dG9tOiAxcHg7XG4gIGJvcmRlci1yYWRpdXM6IDVweDtcbiAgZm9udC1zaXplOiAxZW07XG4gIGZvbnQtd2VpZ2h0OiA3MDA7IH1cblxuLyojIHNvdXJjZU1hcHBpbmdVUkw9aW5kZXguc3ZlbHRlLmNzcy5tYXAgKi88L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gICAgPHRpdGxlPkhvbWU8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cbjxkaXY+XG5cbjxkaXYgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLWhlcm9cIj48L2Rpdj5cbjxwIGNsYXNzPVwibGFuZGluZy1wYWdlLS10aXRcIj5NYXJjdXMgTWF0aGlhc3NlbjwvcD5cbjxwIGNsYXNzPVwibGFuZGluZy1wYWdlLS1zdWJ0aXRsZVwiPkkgZG8gY29tcGlsZXJzIGFuZCBsYW5ndWFnZXMuXG48YnI+XG4gICAgICAgIEludGVyZXN0ZWQgaW4gc3lzdGVtcyBkZXNpZ24gYW5kIFVYLjwvcD5cbjx1bCBjbGFzcz1cInJlcG9zXCI+XG4gICAgPGgyPlJlcG9zaXRvcmllczwvaDI+XG5cdHsjZWFjaCByZXBvcyBhcyByZXBvfVxuICAgICAgICA8bGkgY2xhc3M9XCJyZXBvXCI+XG4gICAgICAgICAgICA8YSBocmVmPVwie3JlcG8udXJsfVwiIHRhcmdldD1cIl9ibGFua1wiIHJlbD1cIm5vb3BlbmVyXCI+XG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLW5hbWVcIj57cmVwby5uYW1lfSA8L3NwYW4+XG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cInJlcG8tLWJhZGdlc1wiIHN0eWxlPVwiLS1jOiB7cmVwby5wcmltYXJ5TGFuZ3VhZ2UuY29sb3J9XCI+XG4gICAgICAgICAgICB7I2lmIHJlcG8ucHJpbWFyeUxhbmd1YWdlfVxuICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwicmVwby0tbGFuZ2F1Z2VcIj4ge3JlcG8ucHJpbWFyeUxhbmd1YWdlLm5hbWV9PC9zcGFuPlxuICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgIHsjaWYgcmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9XG4gICAgICAgICAgICAgICAgPHNwYW4+XG4gICAgICAgICAgICAgICAgICAgIDxpIGNsYXNzPVwiZmFzIGZhLXN0YXJcIiBzdHlsZT1cImNvbG9yOiBnb2xkICFpbXBvcnRhbnRcIj48L2k+XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuPntyZXBvLnN0YXJnYXplcnMudG90YWxDb3VudH08L3NwYW4+XG4gICAgICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgIHsjaWYgcmVwby5mb3JrQ291bnR9XG4gICAgICAgICAgICAgICAgPHNwYW4+XG4gICAgICAgICAgICAgICAgICAgIDxpIGNsYXNzPVwiZmFzIGZhLWNvZGUtYnJhbmNoXCIgc3R5bGU9XCJjb2xvcjogcHVycGxlICFpbXBvcnRhbnRcIj48L2k+XG4gICAgICAgICAgICAgICAgICAgIDxzcGFuPntyZXBvLmZvcmtDb3VudH08L3NwYW4+XG4gICAgICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgey9pZn1cbiAgICAgICAgICAgIDwvc3Bhbj5cbiAgICAgICAgICAgIDwvYT5cbiAgICAgICAgPC9saT5cblx0ey9lYWNofVxuPC91bD5cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQWlHbUIsbUJBQW1CLGNBQUMsQ0FBQyxBQUN0QyxLQUFLLENBQUUsR0FBRyxDQUNWLE1BQU0sQ0FBRSxJQUFJLENBQUMsSUFBSSxDQUNqQixPQUFPLENBQUUsS0FBSyxDQUNkLGdCQUFnQixDQUFFLElBQUksUUFBUSxDQUFDLENBQy9CLGVBQWUsQ0FBRSxLQUFLLENBQ3RCLEtBQUssQ0FBRSxLQUFLLENBQ1osTUFBTSxDQUFFLEtBQUssQUFBRSxDQUFDLEFBRWxCLGdCQUFFLENBQUUsRUFBRSxjQUFDLENBQUMsQUFDTixNQUFNLENBQUUsR0FBRyxDQUNYLFVBQVUsQ0FBRSxJQUFJLENBQ2hCLGVBQWUsQ0FBRSxJQUFJLEFBQUUsQ0FBQyxBQUUxQixJQUFJLGNBQUMsQ0FBQyxBQUNKLFdBQVcsQ0FBRSxJQUFJLE1BQU0sQ0FBQyxBQUFFLENBQUMsQUFFN0IsTUFBTSxjQUFDLENBQUMsQUFDTixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQ0FDZCxLQUFLLENBQUUsSUFBSSxDQUNYLE9BQU8sQ0FBRSxDQUFDLEFBQUUsQ0FBQyxBQUNiLG9CQUFNLENBQUMsRUFBRSxjQUFDLENBQUMsQUFDVCxNQUFNLENBQUUsR0FBRyxDQUNYLE9BQU8sQ0FBRSxHQUFHLENBQ1osVUFBVSxDQUFFLE1BQU0sQ0FDbEIsV0FBVyxDQUFFLEdBQUcsQUFBRSxDQUFDLEFBRXZCLEtBQUssY0FBQyxDQUFDLEFBQ0wsTUFBTSxDQUFFLEdBQUcsQ0FDWCxPQUFPLENBQUUsR0FBRyxDQUNaLFVBQVUsQ0FBRSxNQUFNLEFBQUUsQ0FBQyxBQUNyQixPQUFPLElBQUksQ0FBQyxNQUFNLENBQUMsR0FBRyxDQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUN6QyxLQUFLLGNBQUMsQ0FBQyxBQUNMLFNBQVMsQ0FBRSxPQUFPLEFBQUUsQ0FBQyxBQUFDLENBQUMsQUFFN0IsV0FBVyxjQUFDLENBQUMsQUFDWCxTQUFTLENBQUUsR0FBRyxDQUNkLE9BQU8sQ0FBRSxDQUFDLENBQ1YsTUFBTSxDQUFFLENBQUMsQUFBRSxDQUFDLEFBRWQsYUFBYSxjQUFDLENBQUMsQUFDYixHQUFHLENBQUUsSUFBSSxDQUNULFVBQVUsQ0FBRSxJQUFJLFdBQVcsQ0FBQyxDQUM1QixNQUFNLENBQUUsR0FBRyxDQUNYLE9BQU8sQ0FBRSxHQUFHLENBQ1osYUFBYSxDQUFFLElBQUksZUFBZSxDQUFDLENBQ25DLFNBQVMsQ0FBRSxNQUFNLEFBQUUsQ0FBQyxBQUNwQiwyQkFBYSxDQUFDLElBQUksY0FBQyxDQUFDLEFBQ2xCLE1BQU0sQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUVsQixlQUFlLGNBQUMsQ0FBQyxBQUNmLEtBQUssQ0FBRSxJQUFJLEdBQUcsQ0FBQyxDQUNmLE9BQU8sQ0FBRSxHQUFHLENBQ1osV0FBVyxDQUFFLEdBQUcsQ0FDaEIsY0FBYyxDQUFFLEdBQUcsQ0FDbkIsYUFBYSxDQUFFLEdBQUcsQ0FDbEIsU0FBUyxDQUFFLEdBQUcsQ0FDZCxXQUFXLENBQUUsR0FBRyxBQUFFLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.repo = list[i];
	return child_ctx;
}

// (176:12) {#if repo.primaryLanguage}
function create_if_block_2(ctx) {
	var span, t_value = ctx.repo.primaryLanguage.name + "", t;

	return {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span, "class", "repo--langauge svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 176, 16, 4010);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.primaryLanguage.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span);
			}
		}
	};
}

// (179:12) {#if repo.stargazers.totalCount}
function create_if_block_1(ctx) {
	var span1, i, t0, span0, t1_value = ctx.repo.stargazers.totalCount + "", t1;

	return {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n                    ");

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(i, "class", "fas fa-star");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "gold", 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 180, 20, 4181);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 181, 20, 4260);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 179, 16, 4154);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t1_value !== (t1_value = ctx.repo.stargazers.totalCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span1);
			}
		}
	};
}

// (185:12) {#if repo.forkCount}
function create_if_block(ctx) {
	var span1, i, t0, span0, t1_value = ctx.repo.forkCount + "", t1;

	return {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n                    ");

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t1_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(i, "class", "fas fa-code-branch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "purple", 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 186, 20, 4420);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 187, 20, 4508);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 185, 16, 4393);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t1);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t1_value !== (t1_value = ctx.repo.forkCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t1, t1_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(span1);
			}
		}
	};
}

// (171:1) {#each repos as repo}
function create_each_block(ctx) {
	var li, a, span0, t0_value = ctx.repo.name + "", t0, t1, span1, t2, t3, a_href_value, t4;

	var if_block0 = (ctx.repo.primaryLanguage) && create_if_block_2(ctx);

	var if_block1 = (ctx.repo.stargazers.totalCount) && create_if_block_1(ctx);

	var if_block2 = (ctx.repo.forkCount) && create_if_block(ctx);

	return {
		c: function create() {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			if (if_block0) if_block0.c();
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "LI", { class: true }, false);
			var li_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "A", { href: true, target: true, rel: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t0_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a_nodes, "\n            ");

			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true, style: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			if (if_block0) if_block0.l(span1_nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n            ");
			if (if_block1) if_block1.l(span1_nodes);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span1_nodes, "\n            ");
			if (if_block2) if_block2.l(span1_nodes);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li_nodes, "\n        ");
			li_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span0, "class", "repo--name svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 173, 12, 3828);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(span1, "class", "repo--badges svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span1, "--c", ctx.repo.primaryLanguage.color);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 174, 12, 3885);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "href", a_href_value = ctx.repo.url);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 172, 12, 3763);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(li, "class", "repo svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li, file, 171, 8, 3733);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, li, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span0, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, span1);
			if (if_block0) if_block0.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t2);
			if (if_block1) if_block1.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span1, t3);
			if (if_block2) if_block2.m(span1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li, t4);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t0_value !== (t0_value = ctx.repo.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, t0_value);
			}

			if (ctx.repo.primaryLanguage) {
				if (if_block0) {
					if_block0.p(changed, ctx);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(span1, t2);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (ctx.repo.stargazers.totalCount) {
				if (if_block1) {
					if_block1.p(changed, ctx);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(span1, t3);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (ctx.repo.forkCount) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(span1, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if (changed.repos) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span1, "--c", ctx.repo.primaryLanguage.color);
			}

			if ((changed.repos) && a_href_value !== (a_href_value = ctx.repo.url)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(a, "href", a_href_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(li);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
		}
	};
}

function create_fragment(ctx) {
	var t0, div1, div0, t1, p0, t2, t3, p1, t4, br, t5, t6, ul, h2, t7, t8;

	var each_value = ctx.repos;

	var each_blocks = [];

	for (var i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Marcus Mathiassen");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I do compilers and languages.\n");
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n        Interested in systems design and UX.");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Repositories");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {}, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n");

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Marcus Mathiassen");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "I do compilers and languages.\n");

			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "BR", {}, false);
			var br_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br);

			br_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n        Interested in systems design and UX.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n");

			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "H2", { class: true }, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Repositories");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n\t");

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Home";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "landing-page--hero svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 163, 0, 3449);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p0, "class", "landing-page--tit");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 164, 0, 3488);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 166, 0, 3603);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(p1, "class", "landing-page--subtitle");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 165, 0, 3539);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(h2, "class", "svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 169, 4, 3680);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(ul, "class", "repos svelte-9cn10b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 168, 0, 3657);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 161, 0, 3442);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, br);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, ul);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h2, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t8);

			for (var i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.repos) {
				each_value = ctx.repos;

				for (var i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div1);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let repos = ""
    fetch("/.netlify/functions/github").then(res => res.json()).then(json => {
        $$invalidate('repos', repos = json)
    })

//     repos = [
//     {
//         "forkCount": 27,
//         "url": "blue",
//         "name": "Leticia Hansen",
//         "primaryLanguage": {
//             "name": "JavaScript",
//             "color": "#00ff"
//         },
//         "description": "the color blue",
//         "stargazers": {
//             "totalCount": 30
//         }
//     },
//     {
//         "forkCount": 40,
//         "url": "brown",
//         "name": "Candy Vasquez Veronic",
//         "primaryLanguage": {
//             "name": "C++",
//             "color": "#ff0f"
//         },
//         "stargazers": {
//             "totalCount": 26
//         }
//     },
//     {
//         "forkCount": 36,
//         "url": "green",
//         "name": "Lamb Johnson",
//         "primaryLanguage": {
//             "name": "C++",
//             "color": "#f00f"
//         },
//         "stargazers": {
//             "totalCount": 24
//         }
//     },
//     {
//         "forkCount": 23,
//         "url": "blue",
//         "name": "Solomon Medina",
//         "primaryLanguage": {
//             "name": "C++",
//             "color": "#f00f"
//         },
//         "stargazers": {
//             "totalCount": 39
//         }
//     },
//     {
//         "forkCount": 26,
//         "url": "blue",
//         "name": "Richmond Hess",
//         "primaryLanguage": {
//             "name": "C++",
//             "color": "#ff0f"
//         },
//         "stargazers": {
//             "totalCount": 24
//         }
//     },
//     {
//         "forkCount": 38,
//         "url": "green",
//         "name": "Spencer Bush",
//         "primaryLanguage": {
//             "name": "C++",
//             "color": "#ff0f"
//         },
//         "stargazers": {
//             "totalCount": 33
//         }
//     },
//     {
//         "forkCount": 22,
//         "url": "green",
//         "name": "Hammond Mann",
//         "primaryLanguage": {
//             "name": "JavaScript",
//             "color": "#ff0f"
//         },
//         "stargazers": {
//             "totalCount": 22
//         }
//     }
// ]

	return { repos };
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-9cn10b-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9yb3V0ZXMvaW5kZXguc3ZlbHRlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7eUJBZ0wrQyxJQUFJLENBQUMsZUFBZSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FEQUF6QixJQUFJLENBQUMsZUFBZSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozt5Q0FLN0MsSUFBSSxDQUFDLFVBQVUsQ0FBQyxVQUFVOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1REFBMUIsSUFBSSxDQUFDLFVBQVUsQ0FBQyxVQUFVOzs7Ozs7Ozs7Ozs7Ozs7eUNBTTFCLElBQUksQ0FBQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1REFBZCxJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7O2tDQWRILElBQUksQ0FBQyxJQUFJOztzQkFFOUIsSUFBSSxDQUFDLGVBQWU7O3NCQUdwQixJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7O3NCQU0xQixJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1RkFWcUIsSUFBSSxDQUFDLGVBQWUsQ0FBQyxLQUFLOzs4RkFGeEQsSUFBSSxDQUFDLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1REFDUSxJQUFJLENBQUMsSUFBSTs7OztXQUU5QixJQUFJLENBQUMsZUFBZTs7Ozs7Ozs7Ozs7OztXQUdwQixJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7V0FNMUIsSUFBSSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7O3dGQVZxQixJQUFJLENBQUMsZUFBZSxDQUFDLEtBQUs7OzsrREFGeEQsSUFBSSxDQUFDLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NCQUZ0QixLQUFLOzs7O2dDQUFWOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O21DQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O21DQUFBOzs7Ozs7O3FCQUFLLEtBQUs7O21DQUFWOzs7Ozs7Ozs7Ozs7MkJBQUE7OztnQkFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztDQXhLQyxJQUFJLEtBQUssR0FBRyxFQUFFO0lBQ2QsS0FBSyxDQUFDLDRCQUE0QixDQUFDLENBQUMsSUFBSSxDQUFDLEdBQUcsSUFBSSxHQUFHLENBQUMsSUFBSSxFQUFFLENBQUMsQ0FBQyxJQUFJLENBQUMsSUFBSSxJQUFJOzhCQUNyRSxLQUFLLEdBQUcsS0FBSTtLQUNmLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUF3RkYiLCJmaWxlIjoiZTVmMmFkNDdiMWExMTE5NTA2OGIvaW5kZXguaW5kZXguanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICAgIGltcG9ydCBQMkQgZnJvbSAnLi4vY29tcG9uZW50cy9wMmQuc3ZlbHRlJ1xuICAgIGxldCByZXBvcyA9IFwiXCJcbiAgICBmZXRjaChcIi8ubmV0bGlmeS9mdW5jdGlvbnMvZ2l0aHViXCIpLnRoZW4ocmVzID0+IHJlcy5qc29uKCkpLnRoZW4oanNvbiA9PiB7XG4gICAgICAgIHJlcG9zID0ganNvblxuICAgIH0pXG5cbi8vICAgICByZXBvcyA9IFtcbi8vICAgICB7XG4vLyAgICAgICAgIFwiZm9ya0NvdW50XCI6IDI3LFxuLy8gICAgICAgICBcInVybFwiOiBcImJsdWVcIixcbi8vICAgICAgICAgXCJuYW1lXCI6IFwiTGV0aWNpYSBIYW5zZW5cIixcbi8vICAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuLy8gICAgICAgICAgICAgXCJuYW1lXCI6IFwiSmF2YVNjcmlwdFwiLFxuLy8gICAgICAgICAgICAgXCJjb2xvclwiOiBcIiMwMGZmXCJcbi8vICAgICAgICAgfSxcbi8vICAgICAgICAgXCJkZXNjcmlwdGlvblwiOiBcInRoZSBjb2xvciBibHVlXCIsXG4vLyAgICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4vLyAgICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMzBcbi8vICAgICAgICAgfVxuLy8gICAgIH0sXG4vLyAgICAge1xuLy8gICAgICAgICBcImZvcmtDb3VudFwiOiA0MCxcbi8vICAgICAgICAgXCJ1cmxcIjogXCJicm93blwiLFxuLy8gICAgICAgICBcIm5hbWVcIjogXCJDYW5keSBWYXNxdWV6IFZlcm9uaWNcIixcbi8vICAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuLy8gICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiI2ZmMGZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuLy8gICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDI2XG4vLyAgICAgICAgIH1cbi8vICAgICB9LFxuLy8gICAgIHtcbi8vICAgICAgICAgXCJmb3JrQ291bnRcIjogMzYsXG4vLyAgICAgICAgIFwidXJsXCI6IFwiZ3JlZW5cIixcbi8vICAgICAgICAgXCJuYW1lXCI6IFwiTGFtYiBKb2huc29uXCIsXG4vLyAgICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbi8vICAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuLy8gICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmMDBmXCJcbi8vICAgICAgICAgfSxcbi8vICAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbi8vICAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyNFxuLy8gICAgICAgICB9XG4vLyAgICAgfSxcbi8vICAgICB7XG4vLyAgICAgICAgIFwiZm9ya0NvdW50XCI6IDIzLFxuLy8gICAgICAgICBcInVybFwiOiBcImJsdWVcIixcbi8vICAgICAgICAgXCJuYW1lXCI6IFwiU29sb21vbiBNZWRpbmFcIixcbi8vICAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuLy8gICAgICAgICAgICAgXCJuYW1lXCI6IFwiQysrXCIsXG4vLyAgICAgICAgICAgICBcImNvbG9yXCI6IFwiI2YwMGZcIlxuLy8gICAgICAgICB9LFxuLy8gICAgICAgICBcInN0YXJnYXplcnNcIjoge1xuLy8gICAgICAgICAgICAgXCJ0b3RhbENvdW50XCI6IDM5XG4vLyAgICAgICAgIH1cbi8vICAgICB9LFxuLy8gICAgIHtcbi8vICAgICAgICAgXCJmb3JrQ291bnRcIjogMjYsXG4vLyAgICAgICAgIFwidXJsXCI6IFwiYmx1ZVwiLFxuLy8gICAgICAgICBcIm5hbWVcIjogXCJSaWNobW9uZCBIZXNzXCIsXG4vLyAgICAgICAgIFwicHJpbWFyeUxhbmd1YWdlXCI6IHtcbi8vICAgICAgICAgICAgIFwibmFtZVwiOiBcIkMrK1wiLFxuLy8gICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjBmXCJcbi8vICAgICAgICAgfSxcbi8vICAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbi8vICAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyNFxuLy8gICAgICAgICB9XG4vLyAgICAgfSxcbi8vICAgICB7XG4vLyAgICAgICAgIFwiZm9ya0NvdW50XCI6IDM4LFxuLy8gICAgICAgICBcInVybFwiOiBcImdyZWVuXCIsXG4vLyAgICAgICAgIFwibmFtZVwiOiBcIlNwZW5jZXIgQnVzaFwiLFxuLy8gICAgICAgICBcInByaW1hcnlMYW5ndWFnZVwiOiB7XG4vLyAgICAgICAgICAgICBcIm5hbWVcIjogXCJDKytcIixcbi8vICAgICAgICAgICAgIFwiY29sb3JcIjogXCIjZmYwZlwiXG4vLyAgICAgICAgIH0sXG4vLyAgICAgICAgIFwic3RhcmdhemVyc1wiOiB7XG4vLyAgICAgICAgICAgICBcInRvdGFsQ291bnRcIjogMzNcbi8vICAgICAgICAgfVxuLy8gICAgIH0sXG4vLyAgICAge1xuLy8gICAgICAgICBcImZvcmtDb3VudFwiOiAyMixcbi8vICAgICAgICAgXCJ1cmxcIjogXCJncmVlblwiLFxuLy8gICAgICAgICBcIm5hbWVcIjogXCJIYW1tb25kIE1hbm5cIixcbi8vICAgICAgICAgXCJwcmltYXJ5TGFuZ3VhZ2VcIjoge1xuLy8gICAgICAgICAgICAgXCJuYW1lXCI6IFwiSmF2YVNjcmlwdFwiLFxuLy8gICAgICAgICAgICAgXCJjb2xvclwiOiBcIiNmZjBmXCJcbi8vICAgICAgICAgfSxcbi8vICAgICAgICAgXCJzdGFyZ2F6ZXJzXCI6IHtcbi8vICAgICAgICAgICAgIFwidG90YWxDb3VudFwiOiAyMlxuLy8gICAgICAgICB9XG4vLyAgICAgfVxuLy8gXVxuXG48L3NjcmlwdD5cblxuPHN0eWxlIGxhbmc9XCJzYXNzXCI+LmxhbmRpbmctcGFnZS0taGVybyB7XG4gIHdpZHRoOiA1MCU7XG4gIG1hcmdpbjogMjBweCBhdXRvO1xuICBkaXNwbGF5OiBibG9jaztcbiAgYmFja2dyb3VuZC1pbWFnZTogdmFyKC0tYXZhdGFyKTtcbiAgYmFja2dyb3VuZC1zaXplOiBjb3ZlcjtcbiAgd2lkdGg6IDMwMHB4O1xuICBoZWlnaHQ6IDMwMHB4OyB9XG5cbmxpLCB1bCB7XG4gIG1hcmdpbjogNXB4O1xuICBtYXJnaW4tdG9wOiAxMHB4O1xuICBsaXN0LXN0eWxlLXR5cGU6IG5vbmU7IH1cblxuc3BhbiB7XG4gIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250KTsgfVxuXG4ucmVwb3Mge1xuICBtYXJnaW46IDAgYXV0bztcbiAgd2lkdGg6IDEwMCU7XG4gIHBhZGRpbmc6IDA7IH1cbiAgLnJlcG9zIGgyIHtcbiAgICBtYXJnaW46IDVweDtcbiAgICBwYWRkaW5nOiA1cHg7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGZvbnQtd2VpZ2h0OiA1MDA7IH1cblxuLnJlcG8ge1xuICBtYXJnaW46IDVweDtcbiAgcGFkZGluZzogNXB4O1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7IH1cbiAgQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiA2MDBweCkge1xuICAgIC5yZXBvIHtcbiAgICAgIGZvbnQtc2l6ZTogMC43NXJlbTsgfSB9XG5cbi5yZXBvLS1uYW1lIHtcbiAgZm9udC1zaXplOiAxZW07XG4gIHBhZGRpbmc6IDA7XG4gIG1hcmdpbjogMDsgfVxuXG4ucmVwby0tYmFkZ2VzIHtcbiAgLS1jOiBibHVlO1xuICBiYWNrZ3JvdW5kOiB2YXIoLS1zZWNvbmRhcnkpO1xuICBtYXJnaW46IDVweDtcbiAgcGFkZGluZzogNXB4O1xuICBib3JkZXItcmFkaXVzOiB2YXIoLS1ib3JkZXItcmFkaXVzKTtcbiAgZm9udC1zaXplOiAwLjc1ZW07IH1cbiAgLnJlcG8tLWJhZGdlcyBzcGFuIHtcbiAgICBtYXJnaW46IDJweDsgfVxuXG4ucmVwby0tbGFuZ2F1Z2Uge1xuICBjb2xvcjogdmFyKC0tYyk7XG4gIHBhZGRpbmc6IDVweDtcbiAgcGFkZGluZy10b3A6IDFweDtcbiAgcGFkZGluZy1ib3R0b206IDFweDtcbiAgYm9yZGVyLXJhZGl1czogNXB4O1xuICBmb250LXNpemU6IDFlbTtcbiAgZm9udC13ZWlnaHQ6IDcwMDsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgICA8dGl0bGU+SG9tZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuPGRpdj5cblxuPGRpdiBjbGFzcz1cImxhbmRpbmctcGFnZS0taGVyb1wiPjwvZGl2PlxuPHAgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLXRpdFwiPk1hcmN1cyBNYXRoaWFzc2VuPC9wPlxuPHAgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLXN1YnRpdGxlXCI+SSBkbyBjb21waWxlcnMgYW5kIGxhbmd1YWdlcy5cbjxicj5cbiAgICAgICAgSW50ZXJlc3RlZCBpbiBzeXN0ZW1zIGRlc2lnbiBhbmQgVVguPC9wPlxuPHVsIGNsYXNzPVwicmVwb3NcIj5cbiAgICA8aDI+UmVwb3NpdG9yaWVzPC9oMj5cblx0eyNlYWNoIHJlcG9zIGFzIHJlcG99XG4gICAgICAgIDxsaSBjbGFzcz1cInJlcG9cIj5cbiAgICAgICAgICAgIDxhIGhyZWY9XCJ7cmVwby51cmx9XCIgdGFyZ2V0PVwiX2JsYW5rXCIgcmVsPVwibm9vcGVuZXJcIj5cbiAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwicmVwby0tbmFtZVwiPntyZXBvLm5hbWV9IDwvc3Bhbj5cbiAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwicmVwby0tYmFkZ2VzXCIgc3R5bGU9XCItLWM6IHtyZXBvLnByaW1hcnlMYW5ndWFnZS5jb2xvcn1cIj5cbiAgICAgICAgICAgIHsjaWYgcmVwby5wcmltYXJ5TGFuZ3VhZ2V9XG4gICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJyZXBvLS1sYW5nYXVnZVwiPiB7cmVwby5wcmltYXJ5TGFuZ3VhZ2UubmFtZX08L3NwYW4+XG4gICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgeyNpZiByZXBvLnN0YXJnYXplcnMudG90YWxDb3VudH1cbiAgICAgICAgICAgICAgICA8c3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtc3RhclwiIHN0eWxlPVwiY29sb3I6IGdvbGQgIWltcG9ydGFudFwiPjwvaT5cbiAgICAgICAgICAgICAgICAgICAgPHNwYW4+e3JlcG8uc3RhcmdhemVycy50b3RhbENvdW50fTwvc3Bhbj5cbiAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgeyNpZiByZXBvLmZvcmtDb3VudH1cbiAgICAgICAgICAgICAgICA8c3Bhbj5cbiAgICAgICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtY29kZS1icmFuY2hcIiBzdHlsZT1cImNvbG9yOiBwdXJwbGUgIWltcG9ydGFudFwiPjwvaT5cbiAgICAgICAgICAgICAgICAgICAgPHNwYW4+e3JlcG8uZm9ya0NvdW50fTwvc3Bhbj5cbiAgICAgICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgICAgICB7L2lmfVxuICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICAgICAgPC9hPlxuICAgICAgICA8L2xpPlxuXHR7L2VhY2h9XG48L3VsPlxuPC9kaXY+XG4iXSwic291cmNlUm9vdCI6IiJ9