(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/hero.svelte":
/*!************************************!*\
  !*** ./src/components/hero.svelte ***!
  \************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/hero.svelte generated by Svelte v3.12.0 */


const file = "src/components/hero.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-5t46jh-style';
	style.textContent = ".landing-page--title.svelte-5t46jh{font-size:1.5em;font-weight:700;padding:0;margin:0}.landing-page--subtitle.svelte-5t46jh{margin:0;padding:0;font-size:0.75em;opacity:0.8}.landing-page--hero.svelte-5t46jh{margin:0;margin-bottom:20px;transform:translate3d(0, 0, 0);background-image:var(--avatar);background-size:cover;width:300px;height:300px}.contact-me.svelte-5t46jh{font-weight:600}.icon-list.svelte-5t46jh{display:flex;justify-content:center}.icon-list.svelte-5t46jh a.svelte-5t46jh{font-size:2em;margin:5px}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaGVyby5zdmVsdGUiLCJzb3VyY2VzIjpbImhlcm8uc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzdHlsZSBsYW5nPVwic2Fzc1wiPi5sYW5kaW5nLXBhZ2UtLXRpdGxlIHtcbiAgZm9udC1zaXplOiAxLjVlbTtcbiAgZm9udC13ZWlnaHQ6IDcwMDtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwOyB9XG5cbi5sYW5kaW5nLXBhZ2UtLXN1YnRpdGxlIHtcbiAgbWFyZ2luOiAwO1xuICBwYWRkaW5nOiAwO1xuICBmb250LXNpemU6IDAuNzVlbTtcbiAgb3BhY2l0eTogMC44OyB9XG5cbi5sYW5kaW5nLXBhZ2UtLWhlcm8ge1xuICBtYXJnaW46IDA7XG4gIG1hcmdpbi1ib3R0b206IDIwcHg7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlM2QoMCwgMCwgMCk7XG4gIGJhY2tncm91bmQtaW1hZ2U6IHZhcigtLWF2YXRhcik7XG4gIGJhY2tncm91bmQtc2l6ZTogY292ZXI7XG4gIHdpZHRoOiAzMDBweDtcbiAgaGVpZ2h0OiAzMDBweDsgfVxuXG4uY29udGFjdC1tZSB7XG4gIGZvbnQtd2VpZ2h0OiA2MDA7IH1cblxuLmljb24tbGlzdCB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyOyB9XG4gIC5pY29uLWxpc3QgYSB7XG4gICAgZm9udC1zaXplOiAyZW07XG4gICAgbWFyZ2luOiA1cHg7IH1cblxuLyojIHNvdXJjZU1hcHBpbmdVUkw9aGVyby5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cbjxkaXYgY2xhc3M9XCJsYW5kaW5nLXBhZ2UtLWhlcm9cIj48L2Rpdj48ZGl2IGNsYXNzPVwibGFuZGluZy1wYWdlLS10aXRsZVwiPk1hcmN1cyBNYXRoaWFzc2VuPC9kaXY+PGRpdiBjbGFzcz1cImxhbmRpbmctcGFnZS0tc3VidGl0bGVcIj5JIGRvIGNvbXBpbGVycyBhbmQgbGFuZ3VhZ2VzLjxicj5cbkludGVyZXN0ZWQgaW4gc3lzdGVtcyBkZXNpZ24gYW5kIFVYLjwvZGl2Pjxicj48YSBjbGFzcz1cImNvbnRhY3QtbWVcIiBocmVmPVwibWFpbHRvOm1hdGhpYXNzZW5tYXJjdXNAbWUuY29tXCI+Q29udGFjdCBNZTwvYT48ZGl2IGNsYXNzPVwiaWNvbi1saXN0XCI+PGEgaHJlZj1cImh0dHBzOi8vZ2l0aHViLmNvbS9NYXJjdXNNYXRoaWFzc2VuXCIgdGFyZ2V0PVwiX2JsYW5rXCIgcmVsPVwibm9vcGVuZXJcIj48aSBjbGFzcz1cImZhYiBmYS1naXRodWJcIj48L2k+PC9hPjxhIGhyZWY9XCJodHRwczovL3d3dy55b3V0dWJlLmNvbS9jaGFubmVsL1VDWjdGYlE0QnZpM0drVjBrNUVOb1hZUVwiIHRhcmdldD1cIl9ibGFua1wiIHJlbD1cIm5vb3BlbmVyXCI+PGkgY2xhc3M9XCJmYWIgZmEteW91dHViZVwiPjwvaT48L2E+PC9kaXY+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQW1CLG9CQUFvQixjQUFDLENBQUMsQUFDdkMsU0FBUyxDQUFFLEtBQUssQ0FDaEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsT0FBTyxDQUFFLENBQUMsQ0FDVixNQUFNLENBQUUsQ0FBQyxBQUFFLENBQUMsQUFFZCx1QkFBdUIsY0FBQyxDQUFDLEFBQ3ZCLE1BQU0sQ0FBRSxDQUFDLENBQ1QsT0FBTyxDQUFFLENBQUMsQ0FDVixTQUFTLENBQUUsTUFBTSxDQUNqQixPQUFPLENBQUUsR0FBRyxBQUFFLENBQUMsQUFFakIsbUJBQW1CLGNBQUMsQ0FBQyxBQUNuQixNQUFNLENBQUUsQ0FBQyxDQUNULGFBQWEsQ0FBRSxJQUFJLENBQ25CLFNBQVMsQ0FBRSxZQUFZLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUMvQixnQkFBZ0IsQ0FBRSxJQUFJLFFBQVEsQ0FBQyxDQUMvQixlQUFlLENBQUUsS0FBSyxDQUN0QixLQUFLLENBQUUsS0FBSyxDQUNaLE1BQU0sQ0FBRSxLQUFLLEFBQUUsQ0FBQyxBQUVsQixXQUFXLGNBQUMsQ0FBQyxBQUNYLFdBQVcsQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUVyQixVQUFVLGNBQUMsQ0FBQyxBQUNWLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZUFBZSxDQUFFLE1BQU0sQUFBRSxDQUFDLEFBQzFCLHdCQUFVLENBQUMsQ0FBQyxjQUFDLENBQUMsQUFDWixTQUFTLENBQUUsR0FBRyxDQUNkLE1BQU0sQ0FBRSxHQUFHLEFBQUUsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	var div0, div1, t0, div2, t1, br0, t2, br1, a0, t3, div3, a1, i0, a2, i1;

	const block = {
		c: function create() {
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Marcus Mathiassen");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I do compilers and languages.");
			br0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\nInterested in systems design and UX.");
			br1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Contact Me");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			i0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			i1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			this.h()
		},

		l: function claim(nodes) {
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "Marcus Mathiassen");
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "I do compilers and languages.");

			br0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "BR", {}, false);
			var br0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br0);

			br0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\nInterested in systems design and UX.");
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			br1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "BR", {}, false);
			var br1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(br1);

			br1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "A", { class: true, href: true }, false);
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);

			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "Contact Me");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "A", { href: true, target: true, rel: true, class: true }, false);
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);

			i0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a1_nodes, "I", { class: true }, false);
			var i0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i0);

			i0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "A", { href: true, target: true, rel: true, class: true }, false);
			var a2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a2);

			i1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a2_nodes, "I", { class: true }, false);
			var i1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i1);

			i1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			a2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "landing-page--hero svelte-5t46jh");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 33, 0, 601);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "landing-page--title svelte-5t46jh");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 33, 38, 639);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br0, file, 33, 159, 760);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "landing-page--subtitle svelte-5t46jh");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 33, 94, 695);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br1, file, 34, 42, 807);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a0, "class", "contact-me svelte-5t46jh");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a0, "href", "mailto:mathiassenmarcus@me.com");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 34, 46, 811);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i0, "class", "fab fa-github");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i0, file, 34, 220, 985);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "href", "https://github.com/MarcusMathiassen");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "class", "svelte-5t46jh");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 34, 143, 908);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i1, "class", "fab fa-youtube");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i1, file, 34, 351, 1116);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a2, "href", "https://www.youtube.com/channel/UCZ7FbQ4Bvi3GkV0k5ENoXYQ");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a2, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a2, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a2, "class", "svelte-5t46jh");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a2, file, 34, 253, 1018);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "icon-list svelte-5t46jh");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 34, 120, 885);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, br0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, br1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, a0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a1, i0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, a2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a2, i1);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div1);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(br1);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(a0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div3);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_fragment.name, type: "component", source: "", ctx });
	return block;
}

class Hero extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-5t46jh-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", { component: this, tagName: "Hero", options, id: create_fragment.name });
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Hero);

/***/ }),

/***/ "./src/components/repos.svelte":
/*!*************************************!*\
  !*** ./src/components/repos.svelte ***!
  \*************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _utils_utility__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./utils/utility */ "./src/components/utils/utility.js");
/* src/components/repos.svelte generated by Svelte v3.12.0 */




const file = "src/components/repos.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-g5y020-style';
	style.textContent = ".repos.svelte-g5y020{text-align:left;display:inline-block}.repos.svelte-g5y020 h2.svelte-g5y020{margin:5px;text-align:left;font-size:1.50em;font-weight:700}@media only screen and (max-width: 600px){.repos.svelte-g5y020{margin:0;padding:0;font-size:0.85em}}a.svelte-g5y020{padding:0;margin:0}.repo.svelte-g5y020{display:flex;opacity:0.0;animation:svelte-g5y020-reveal 1s forwards}.title.svelte-g5y020{font-size:1em;padding:0;margin:0;margin-right:5px;text-align:left}.badge.svelte-g5y020{display:inline-block;margin-left:5px;background:var(--secondary);padding:5px;padding-top:2px;padding-bottom:2px;border-radius:var(--border-radius);font-size:0.75em}.badge--item.svelte-g5y020{margin:2px}@keyframes svelte-g5y020-reveal{from{opacity:0.0}to{opacity:1.0}}span.svelte-g5y020{margin-left:2px}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVwb3Muc3ZlbHRlIiwic291cmNlcyI6WyJyZXBvcy5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdCBsYW5nPVwiY29mZmVlXCI+dmFyIGZvcmtCaWFzLCBsYW5ndWFnZUNvbG9yQ2hvaWNlcywgbGFuZ3VhZ2VDb2xvckNob2ljZXNJdGVyLCBsYW5ndWFnZUNvbG9ycywgcmVwb3MsIHN0YXJCaWFzO1xuXG5pbXBvcnQge1xuICBvbk1vdW50XG59IGZyb20gJ3N2ZWx0ZSc7XG5cbmltcG9ydCB7XG4gIGNhY2hlZEZldGNoXG59IGZyb20gJy4vdXRpbHMvdXRpbGl0eSc7XG5cbnJlcG9zID0gW107XG5cbmxhbmd1YWdlQ29sb3JDaG9pY2VzSXRlciA9IDA7XG5cbmxhbmd1YWdlQ29sb3JzID0gbmV3IE1hcCgpO1xuXG5sYW5ndWFnZUNvbG9yQ2hvaWNlcyA9IFsndmFyKC0tc3lzdGVtQmx1ZSknLCAndmFyKC0tc3lzdGVtR3JheSknLCAndmFyKC0tc3lzdGVtR3JlZW4pJywgJ3ZhcigtLXN5c3RlbUluZGlnbyknLCAndmFyKC0tc3lzdGVtT3JhbmdlKScsICd2YXIoLS1zeXN0ZW1QaW5rKScsICd2YXIoLS1zeXN0ZW1QdXJwbGUpJywgJ3ZhcigtLXN5c3RlbVJlZCknLCAndmFyKC0tc3lzdGVtVGVhbCknLCAndmFyKC0tc3lzdGVtWWVsbG93KSddO1xuXG5zdGFyQmlhcyA9IDEuNTtcblxuZm9ya0JpYXMgPSAyLjA7IC8vIHZhbHVlIGZvcmtzIG1vcmUgdGhhbiBzdGFyc1xuXG5vbk1vdW50KGFzeW5jKCkgPT4ge1xuICB2YXIgY29sb3IsIGksIGxlbiwgbmFtZSwgcmVwbywgcmVzdWx0cztcbiAgcmVwb3MgPSAoYXdhaXQgY2FjaGVkRmV0Y2goJy8ubmV0bGlmeS9mdW5jdGlvbnMvZ2l0aHViJykpO1xuICByZXBvcy5zb3J0KChhLCBiKSA9PiB7XG4gICAgcmV0dXJuIChiLnN0YXJnYXplcnMudG90YWxDb3VudCAqIHN0YXJCaWFzICsgYi5mb3JrQ291bnQgKiBmb3JrQmlhcykgLSAoYS5zdGFyZ2F6ZXJzLnRvdGFsQ291bnQgKiBzdGFyQmlhcyArIGEuZm9ya0NvdW50ICogZm9ya0JpYXMpO1xuICB9KTtcbiAgcmVzdWx0cyA9IFtdO1xuICBmb3IgKGkgPSAwLCBsZW4gPSByZXBvcy5sZW5ndGg7IGkgPCBsZW47IGkrKykge1xuICAgIHJlcG8gPSByZXBvc1tpXTtcbiAgICBuYW1lID0gcmVwby5wcmltYXJ5TGFuZ3VhZ2UubmFtZTtcbiAgICBjb2xvciA9IGxhbmd1YWdlQ29sb3JzLmhhcyhuYW1lKSA/IGxhbmd1YWdlQ29sb3JzLmdldChuYW1lKSA6IGxhbmd1YWdlQ29sb3JDaG9pY2VzW2xhbmd1YWdlQ29sb3JDaG9pY2VzSXRlcisrICUgbGFuZ3VhZ2VDb2xvckNob2ljZXMubGVuZ3RoXTtcbiAgICByZXN1bHRzLnB1c2gobGFuZ3VhZ2VDb2xvcnMuc2V0KG5hbWUsIGNvbG9yKSk7XG4gIH1cbiAgcmV0dXJuIHJlc3VsdHM7XG59KTtcbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4ucmVwb3Mge1xuICB0ZXh0LWFsaWduOiBsZWZ0O1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7IH1cbiAgLnJlcG9zIGgyIHtcbiAgICBtYXJnaW46IDVweDtcbiAgICB0ZXh0LWFsaWduOiBsZWZ0O1xuICAgIGZvbnQtc2l6ZTogMS41MGVtO1xuICAgIGZvbnQtd2VpZ2h0OiA3MDA7IH1cbiAgQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiA2MDBweCkge1xuICAgIC5yZXBvcyB7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBwYWRkaW5nOiAwO1xuICAgICAgZm9udC1zaXplOiAwLjg1ZW07IH0gfVxuXG5hIHtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwOyB9XG5cbi5yZXBvIHtcbiAgZGlzcGxheTogZmxleDtcbiAgb3BhY2l0eTogMC4wO1xuICBhbmltYXRpb246IHJldmVhbCAxcyBmb3J3YXJkczsgfVxuXG4udGl0bGUge1xuICBmb250LXNpemU6IDFlbTtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwO1xuICBtYXJnaW4tcmlnaHQ6IDVweDtcbiAgdGV4dC1hbGlnbjogbGVmdDsgfVxuXG4ubGFuZ2F1Z2Uge1xuICBmb250LXdlaWdodDogNzAwOyB9XG5cbi5iYWRnZSB7XG4gIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgbWFyZ2luLWxlZnQ6IDVweDtcbiAgYmFja2dyb3VuZDogdmFyKC0tc2Vjb25kYXJ5KTtcbiAgcGFkZGluZzogNXB4O1xuICBwYWRkaW5nLXRvcDogMnB4O1xuICBwYWRkaW5nLWJvdHRvbTogMnB4O1xuICBib3JkZXItcmFkaXVzOiB2YXIoLS1ib3JkZXItcmFkaXVzKTtcbiAgZm9udC1zaXplOiAwLjc1ZW07IH1cblxuLmJhZGdlLS1pdGVtIHtcbiAgbWFyZ2luOiAycHg7IH1cblxuQGtleWZyYW1lcyByZXZlYWwge1xuICBmcm9tIHtcbiAgICBvcGFjaXR5OiAwLjA7IH1cbiAgdG8ge1xuICAgIG9wYWNpdHk6IDEuMDsgfSB9XG5cbnNwYW4ge1xuICBtYXJnaW4tbGVmdDogMnB4OyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPXJlcG9zLnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHVsIGNsYXNzPVwicmVwb3NcIj48aDI+UmVwb3NpdG9yaWVzPC9oMj57I2VhY2ggcmVwb3MgYXMgcmVwbywgaX08bGkgY2xhc3M9XCJyZXBvXCIgc3R5bGU9XCJhbmltYXRpb24tZGVsYXk6IHtpKjEwfW1zXCI+PGEgaHJlZj1cIntyZXBvLnVybH1cIiB0YXJnZXQ9XCJfYmxhbmtcIiByZWw9XCJub29wZW5lclwiPjxzcGFuIGNsYXNzPVwidGl0bGVcIj57cmVwby5uYW1lfTwvc3Bhbj48ZGl2IGNsYXNzPVwiYmFkZ2VcIj57I2lmIHJlcG8ucHJpbWFyeUxhbmd1YWdlfTxzcGFuIGNsYXNzPVwiYmFkZ2UtLWl0ZW0gbGFudWdhZ2VcIiBzdHlsZT1cImNvbG9yOiB7bGFuZ3VhZ2VDb2xvcnMuZ2V0KHJlcG8ucHJpbWFyeUxhbmd1YWdlLm5hbWUpfVwiPntyZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lfTwvc3Bhbj57L2lmfXsjaWYgcmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9PHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPjxpIGNsYXNzPVwiZmFzIGZhLXN0YXJcIiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1ZZWxsb3cpXCI+PC9pPjxzcGFuIHN0eWxlPVwiY29sb3I6IHZhcigtLXN5c3RlbVllbGxvdylcIj57cmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9PC9zcGFuPjwvc3Bhbj57L2lmfXsjaWYgcmVwby5mb3JrQ291bnR9PHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPjxpIGNsYXNzPVwiZmFzIGZhLWNvZGUtYnJhbmNoXCIgc3R5bGU9XCJjb2xvcjogI2M5NGRhMFwiPjwvaT48c3BhbiBzdHlsZT1cImNvbG9yOiAjYzk0ZGEwXCI+e3JlcG8uZm9ya0NvdW50fTwvc3Bhbj48L3NwYW4+ey9pZn08L2Rpdj48L2E+PC9saT57L2VhY2h9PC91bD5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUF1Q21CLE1BQU0sY0FBQyxDQUFDLEFBQ3pCLFVBQVUsQ0FBRSxJQUFJLENBQ2hCLE9BQU8sQ0FBRSxZQUFZLEFBQUUsQ0FBQyxBQUN4QixvQkFBTSxDQUFDLEVBQUUsY0FBQyxDQUFDLEFBQ1QsTUFBTSxDQUFFLEdBQUcsQ0FDWCxVQUFVLENBQUUsSUFBSSxDQUNoQixTQUFTLENBQUUsTUFBTSxDQUNqQixXQUFXLENBQUUsR0FBRyxBQUFFLENBQUMsQUFDckIsT0FBTyxJQUFJLENBQUMsTUFBTSxDQUFDLEdBQUcsQ0FBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDekMsTUFBTSxjQUFDLENBQUMsQUFDTixNQUFNLENBQUUsQ0FBQyxDQUNULE9BQU8sQ0FBRSxDQUFDLENBQ1YsU0FBUyxDQUFFLE1BQU0sQUFBRSxDQUFDLEFBQUMsQ0FBQyxBQUU1QixDQUFDLGNBQUMsQ0FBQyxBQUNELE9BQU8sQ0FBRSxDQUFDLENBQ1YsTUFBTSxDQUFFLENBQUMsQUFBRSxDQUFDLEFBRWQsS0FBSyxjQUFDLENBQUMsQUFDTCxPQUFPLENBQUUsSUFBSSxDQUNiLE9BQU8sQ0FBRSxHQUFHLENBQ1osU0FBUyxDQUFFLG9CQUFNLENBQUMsRUFBRSxDQUFDLFFBQVEsQUFBRSxDQUFDLEFBRWxDLE1BQU0sY0FBQyxDQUFDLEFBQ04sU0FBUyxDQUFFLEdBQUcsQ0FDZCxPQUFPLENBQUUsQ0FBQyxDQUNWLE1BQU0sQ0FBRSxDQUFDLENBQ1QsWUFBWSxDQUFFLEdBQUcsQ0FDakIsVUFBVSxDQUFFLElBQUksQUFBRSxDQUFDLEFBS3JCLE1BQU0sY0FBQyxDQUFDLEFBQ04sT0FBTyxDQUFFLFlBQVksQ0FDckIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsVUFBVSxDQUFFLElBQUksV0FBVyxDQUFDLENBQzVCLE9BQU8sQ0FBRSxHQUFHLENBQ1osV0FBVyxDQUFFLEdBQUcsQ0FDaEIsY0FBYyxDQUFFLEdBQUcsQ0FDbkIsYUFBYSxDQUFFLElBQUksZUFBZSxDQUFDLENBQ25DLFNBQVMsQ0FBRSxNQUFNLEFBQUUsQ0FBQyxBQUV0QixZQUFZLGNBQUMsQ0FBQyxBQUNaLE1BQU0sQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUVoQixXQUFXLG9CQUFPLENBQUMsQUFDakIsSUFBSSxBQUFDLENBQUMsQUFDSixPQUFPLENBQUUsR0FBRyxBQUFFLENBQUMsQUFDakIsRUFBRSxBQUFDLENBQUMsQUFDRixPQUFPLENBQUUsR0FBRyxBQUFFLENBQUMsQUFBQyxDQUFDLEFBRXJCLElBQUksY0FBQyxDQUFDLEFBQ0osV0FBVyxDQUFFLEdBQUcsQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.repo = list[i];
	child_ctx.i = i;
	return child_ctx;
}

// (97:223) {#if repo.primaryLanguage}
function create_if_block_2(ctx) {
	var span, t_value = ctx.repo.primaryLanguage.name + "", t;

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true, style: true }, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "badge--item lanugage svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span, "color", ctx.languageColors.get(ctx.repo.primaryLanguage.name));
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 96, 249, 2435);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.primaryLanguage.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
			}

			if (changed.languageColors || changed.repos) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span, "color", ctx.languageColors.get(ctx.repo.primaryLanguage.name));
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block_2.name, type: "if", source: "(97:223) {#if repo.primaryLanguage}", ctx });
	return block;
}

// (97:386) {#if repo.stargazers.totalCount}
function create_if_block_1(ctx) {
	var span1, i, span0, t_value = ctx.repo.stargazers.totalCount + "", t;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { style: true, class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-star");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "var(--systemYellow)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 96, 444, 2630);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", "var(--systemYellow)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 96, 506, 2692);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 96, 418, 2604);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.stargazers.totalCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block_1.name, type: "if", source: "(97:386) {#if repo.stargazers.totalCount}", ctx });
	return block;
}

// (97:594) {#if repo.forkCount}
function create_if_block(ctx) {
	var span1, i, span0, t_value = ctx.repo.forkCount + "", t;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { style: true, class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-code-branch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "#c94da0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 96, 640, 2826);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", "#c94da0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 96, 697, 2883);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 96, 614, 2800);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.forkCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block.name, type: "if", source: "(97:594) {#if repo.forkCount}", ctx });
	return block;
}

// (97:39) {#each repos as repo, i}
function create_each_block(ctx) {
	var li, a, span, t_value = ctx.repo.name + "", t, div, if_block0_anchor, if_block1_anchor, a_href_value;

	var if_block0 = (ctx.repo.primaryLanguage) && create_if_block_2(ctx);

	var if_block1 = (ctx.repo.stargazers.totalCount) && create_if_block_1(ctx);

	var if_block2 = (ctx.repo.forkCount) && create_if_block(ctx);

	const block = {
		c: function create() {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if (if_block0) if_block0.c();
			if_block0_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			if (if_block1) if_block1.c();
			if_block1_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			if (if_block2) if_block2.c();
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "LI", { class: true, style: true }, false);
			var li_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "A", { href: true, target: true, rel: true, class: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true }, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			if (if_block0) if_block0.l(div_nodes);
			if_block0_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			if (if_block1) if_block1.l(div_nodes);
			if_block1_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			if (if_block2) if_block2.l(div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "title svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 96, 166, 2352);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "badge svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 96, 204, 2390);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", a_href_value = ctx.repo.url);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 96, 114, 2300);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(li, "class", "repo svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(li, "animation-delay", "" + ctx.i*10 + "ms");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li, file, 96, 63, 2249);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, li, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, div);
			if (if_block0) if_block0.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, if_block0_anchor);
			if (if_block1) if_block1.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, if_block1_anchor);
			if (if_block2) if_block2.m(div, null);
		},

		p: function update(changed, ctx) {
			if ((changed.repos) && t_value !== (t_value = ctx.repo.name + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
			}

			if (ctx.repo.primaryLanguage) {
				if (if_block0) {
					if_block0.p(changed, ctx);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(div, if_block0_anchor);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (ctx.repo.stargazers.totalCount) {
				if (if_block1) {
					if_block1.p(changed, ctx);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(div, if_block1_anchor);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (ctx.repo.forkCount) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(div, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if ((changed.repos) && a_href_value !== (a_href_value = ctx.repo.url)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", a_href_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(li);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_each_block.name, type: "each", source: "(97:39) {#each repos as repo, i}", ctx });
	return block;
}

function create_fragment(ctx) {
	var ul, h2, t;

	let each_value = ctx.repos;

	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const block = {
		c: function create() {
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Repositories");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "H2", { class: true }, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Repositories");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 96, 18, 2204);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(ul, "class", "repos svelte-g5y020");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 96, 0, 2186);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, ul, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.repos || changed.languageColors) {
				each_value = ctx.repos;

				let i;
				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(ul);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_fragment.name, type: "component", source: "", ctx });
	return block;
}

function instance($$self, $$props, $$invalidate) {
	var forkBias, languageColorChoices, languageColorChoicesIter, languageColors, repos, starBias;

$$invalidate('repos', repos = []);

languageColorChoicesIter = 0;

$$invalidate('languageColors', languageColors = new Map());

languageColorChoices = ['var(--systemBlue)', 'var(--systemGray)', 'var(--systemGreen)', 'var(--systemIndigo)', 'var(--systemOrange)', 'var(--systemPink)', 'var(--systemPurple)', 'var(--systemRed)', 'var(--systemTeal)', 'var(--systemYellow)'];

starBias = 1.5;

forkBias = 2.0; // value forks more than stars

Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async() => {
  var color, i, len, name, repo, results;
  $$invalidate('repos', repos = (await Object(_utils_utility__WEBPACK_IMPORTED_MODULE_2__["cachedFetch"])('/.netlify/functions/github')));
  repos.sort((a, b) => {
    return (b.stargazers.totalCount * starBias + b.forkCount * forkBias) - (a.stargazers.totalCount * starBias + a.forkCount * forkBias);
  });
  results = [];
  for (i = 0, len = repos.length; i < len; i++) {
    repo = repos[i];
    name = repo.primaryLanguage.name;
    color = languageColors.has(name) ? languageColors.get(name) : languageColorChoices[languageColorChoicesIter++ % languageColorChoices.length];
    results.push(languageColors.set(name, color));
  }
  return results;
});

	$$self.$capture_state = () => {
		return {};
	};

	$$self.$inject_state = $$props => {
		if ('forkBias' in $$props) forkBias = $$props.forkBias;
		if ('languageColorChoices' in $$props) languageColorChoices = $$props.languageColorChoices;
		if ('languageColorChoicesIter' in $$props) languageColorChoicesIter = $$props.languageColorChoicesIter;
		if ('languageColors' in $$props) $$invalidate('languageColors', languageColors = $$props.languageColors);
		if ('repos' in $$props) $$invalidate('repos', repos = $$props.repos);
		if ('starBias' in $$props) starBias = $$props.starBias;
	};

	return { languageColors, repos };
}

class Repos extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-g5y020-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", { component: this, tagName: "Repos", options, id: create_fragment.name });
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Repos);

/***/ }),

/***/ "./src/components/youtube-videos.svelte":
/*!**********************************************!*\
  !*** ./src/components/youtube-videos.svelte ***!
  \**********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _utils_utility__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./utils/utility */ "./src/components/utils/utility.js");
/* src/components/youtube-videos.svelte generated by Svelte v3.12.0 */




const file = "src/components/youtube-videos.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-arqnso-style';
	style.textContent = ".videos.svelte-arqnso{text-align:left;display:inline-block}.videos.svelte-arqnso h2.svelte-arqnso{margin:5px;text-align:left;font-size:1.50em;font-weight:700}@media only screen and (max-width: 600px){.videos.svelte-arqnso{margin:0;padding:0;font-size:0.85em}}a.svelte-arqnso{padding:0;margin:0}.video.svelte-arqnso{display:flex;opacity:0.0;animation:svelte-arqnso-reveal 1s forwards}.title.svelte-arqnso{font-size:1em;padding:0;margin:0;margin-right:5px;text-align:left}.badge.svelte-arqnso{display:inline-block;margin-left:5px;background:var(--secondary);padding:5px;padding-top:2px;padding-bottom:2px;border-radius:var(--border-radius);font-size:0.75em}.badge--item.svelte-arqnso{margin-left:5px}@keyframes svelte-arqnso-reveal{from{opacity:0.0}to{opacity:1.0}}span.svelte-arqnso{margin-left:2px}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoieW91dHViZS12aWRlb3Muc3ZlbHRlIiwic291cmNlcyI6WyJ5b3V0dWJlLXZpZGVvcy5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdCBsYW5nPVwiY29mZmVlXCI+dmFyIHZpZGVvcztcblxuaW1wb3J0IHtcbiAgb25Nb3VudFxufSBmcm9tICdzdmVsdGUnO1xuXG5pbXBvcnQge1xuICBjYWNoZWRGZXRjaFxufSBmcm9tICcuL3V0aWxzL3V0aWxpdHknO1xuXG52aWRlb3MgPSBbXTtcblxub25Nb3VudChhc3luYygpID0+IHtcbiAgdmlkZW9zID0gKGF3YWl0IGNhY2hlZEZldGNoKCcvLm5ldGxpZnkvZnVuY3Rpb25zL3lvdXR1YmUnKSk7XG4gIC8vIFNvcnQgdGhlIHZpZGVvcyBiYXNlZCBvbiB2aWV3IGNvdW50XG4gIHJldHVybiB2aWRlb3Muc29ydCgoYSwgYikgPT4ge1xuICAgIHJldHVybiBwYXJzZUludChiLnN0YXRpc3RpY3Mudmlld0NvdW50KSAtIHBhcnNlSW50KGEuc3RhdGlzdGljcy52aWV3Q291bnQpO1xuICB9KTtcbn0pO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZSBsYW5nPVwic2Fzc1wiPi52aWRlb3Mge1xuICB0ZXh0LWFsaWduOiBsZWZ0O1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7IH1cbiAgLnZpZGVvcyBoMiB7XG4gICAgbWFyZ2luOiA1cHg7XG4gICAgdGV4dC1hbGlnbjogbGVmdDtcbiAgICBmb250LXNpemU6IDEuNTBlbTtcbiAgICBmb250LXdlaWdodDogNzAwOyB9XG4gIEBtZWRpYSBvbmx5IHNjcmVlbiBhbmQgKG1heC13aWR0aDogNjAwcHgpIHtcbiAgICAudmlkZW9zIHtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIHBhZGRpbmc6IDA7XG4gICAgICBmb250LXNpemU6IDAuODVlbTsgfSB9XG5cbmEge1xuICBwYWRkaW5nOiAwO1xuICBtYXJnaW46IDA7IH1cblxuLnZpZGVvIHtcbiAgZGlzcGxheTogZmxleDtcbiAgb3BhY2l0eTogMC4wO1xuICBhbmltYXRpb246IHJldmVhbCAxcyBmb3J3YXJkczsgfVxuXG4udGl0bGUge1xuICBmb250LXNpemU6IDFlbTtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwO1xuICBtYXJnaW4tcmlnaHQ6IDVweDtcbiAgdGV4dC1hbGlnbjogbGVmdDsgfVxuXG4uYmFkZ2Uge1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gIG1hcmdpbi1sZWZ0OiA1cHg7XG4gIGJhY2tncm91bmQ6IHZhcigtLXNlY29uZGFyeSk7XG4gIHBhZGRpbmc6IDVweDtcbiAgcGFkZGluZy10b3A6IDJweDtcbiAgcGFkZGluZy1ib3R0b206IDJweDtcbiAgYm9yZGVyLXJhZGl1czogdmFyKC0tYm9yZGVyLXJhZGl1cyk7XG4gIGZvbnQtc2l6ZTogMC43NWVtOyB9XG5cbi5iYWRnZS0taXRlbSB7XG4gIG1hcmdpbi1sZWZ0OiA1cHg7IH1cblxuQGtleWZyYW1lcyByZXZlYWwge1xuICBmcm9tIHtcbiAgICBvcGFjaXR5OiAwLjA7IH1cbiAgdG8ge1xuICAgIG9wYWNpdHk6IDEuMDsgfSB9XG5cbnNwYW4ge1xuICBtYXJnaW4tbGVmdDogMnB4OyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPXlvdXR1YmUtdmlkZW9zLnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuXG48dWwgY2xhc3M9XCJ2aWRlb3NcIj48aDI+VmlkZW9zPC9oMj57I2VhY2ggdmlkZW9zIGFzIHZpZGVvLCBpfTxsaSBjbGFzcz1cInZpZGVvXCIgc3R5bGU9XCJhbmltYXRpb24tZGVsYXk6IHtpKjEwfW1zXCI+PGEgaHJlZj1cImh0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9e3ZpZGVvLmlkfVwiIHRhcmdldD1cIl9ibGFua1wiIHJlbD1cIm5vb3BlbmVyXCI+PHNwYW4gY2xhc3M9XCJ0aXRsZVwiPnt2aWRlby50aXRsZX08L3NwYW4+PGRpdiBjbGFzcz1cImJhZGdlXCI+eyNpZiBwYXJzZUludCh2aWRlby5zdGF0aXN0aWNzLnZpZXdDb3VudCl9PHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPjxpIGNsYXNzPVwiZmFzIGZhLWV5ZVwiIHN0eWxlPVwiY29sb3I6IHZhcigtLXN5c3RlbUdyYXkpXCI+PC9pPjxzcGFuIHN0eWxlPVwiY29sb3I6IHZhcigtLXN5c3RlbUdyYXkpXCI+e3ZpZGVvLnN0YXRpc3RpY3Mudmlld0NvdW50fTwvc3Bhbj48L3NwYW4+ey9pZn17I2lmIHBhcnNlSW50KHZpZGVvLnN0YXRpc3RpY3MubGlrZUNvdW50KX08c3BhbiBjbGFzcz1cImJhZGdlLS1pdGVtXCI+PGkgY2xhc3M9XCJmYXMgZmEtaGVhcnRcIiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1SZWQpXCI+PC9pPjxzcGFuIHN0eWxlPVwiY29sb3I6IHZhcigtLXN5c3RlbVJlZClcIj57dmlkZW8uc3RhdGlzdGljcy5saWtlQ291bnR9PC9zcGFuPjwvc3Bhbj57L2lmfXsjaWYgcGFyc2VJbnQodmlkZW8uc3RhdGlzdGljcy5jb21tZW50Q291bnQpfTxzcGFuIGNsYXNzPVwiYmFkZ2UtLWl0ZW1cIj48aSBjbGFzcz1cImZhcyBmYS1jb21tZW50XCIgc3R5bGU9XCJjb2xvcjogdmFyKC0tc3lzdGVtVGVhbClcIj48L2k+PHNwYW4gc3R5bGU9XCJjb2xvcjogdmFyKC0tc3lzdGVtVGVhbClcIj57dmlkZW8uc3RhdGlzdGljcy5jb21tZW50Q291bnR9PC9zcGFuPjwvc3Bhbj57L2lmfTwvZGl2PjwvYT48L2xpPnsvZWFjaH08L3VsPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQXFCbUIsT0FBTyxjQUFDLENBQUMsQUFDMUIsVUFBVSxDQUFFLElBQUksQ0FDaEIsT0FBTyxDQUFFLFlBQVksQUFBRSxDQUFDLEFBQ3hCLHFCQUFPLENBQUMsRUFBRSxjQUFDLENBQUMsQUFDVixNQUFNLENBQUUsR0FBRyxDQUNYLFVBQVUsQ0FBRSxJQUFJLENBQ2hCLFNBQVMsQ0FBRSxNQUFNLENBQ2pCLFdBQVcsQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUNyQixPQUFPLElBQUksQ0FBQyxNQUFNLENBQUMsR0FBRyxDQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUN6QyxPQUFPLGNBQUMsQ0FBQyxBQUNQLE1BQU0sQ0FBRSxDQUFDLENBQ1QsT0FBTyxDQUFFLENBQUMsQ0FDVixTQUFTLENBQUUsTUFBTSxBQUFFLENBQUMsQUFBQyxDQUFDLEFBRTVCLENBQUMsY0FBQyxDQUFDLEFBQ0QsT0FBTyxDQUFFLENBQUMsQ0FDVixNQUFNLENBQUUsQ0FBQyxBQUFFLENBQUMsQUFFZCxNQUFNLGNBQUMsQ0FBQyxBQUNOLE9BQU8sQ0FBRSxJQUFJLENBQ2IsT0FBTyxDQUFFLEdBQUcsQ0FDWixTQUFTLENBQUUsb0JBQU0sQ0FBQyxFQUFFLENBQUMsUUFBUSxBQUFFLENBQUMsQUFFbEMsTUFBTSxjQUFDLENBQUMsQUFDTixTQUFTLENBQUUsR0FBRyxDQUNkLE9BQU8sQ0FBRSxDQUFDLENBQ1YsTUFBTSxDQUFFLENBQUMsQ0FDVCxZQUFZLENBQUUsR0FBRyxDQUNqQixVQUFVLENBQUUsSUFBSSxBQUFFLENBQUMsQUFFckIsTUFBTSxjQUFDLENBQUMsQUFDTixPQUFPLENBQUUsWUFBWSxDQUNyQixXQUFXLENBQUUsR0FBRyxDQUNoQixVQUFVLENBQUUsSUFBSSxXQUFXLENBQUMsQ0FDNUIsT0FBTyxDQUFFLEdBQUcsQ0FDWixXQUFXLENBQUUsR0FBRyxDQUNoQixjQUFjLENBQUUsR0FBRyxDQUNuQixhQUFhLENBQUUsSUFBSSxlQUFlLENBQUMsQ0FDbkMsU0FBUyxDQUFFLE1BQU0sQUFBRSxDQUFDLEFBRXRCLFlBQVksY0FBQyxDQUFDLEFBQ1osV0FBVyxDQUFFLEdBQUcsQUFBRSxDQUFDLEFBRXJCLFdBQVcsb0JBQU8sQ0FBQyxBQUNqQixJQUFJLEFBQUMsQ0FBQyxBQUNKLE9BQU8sQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUNqQixFQUFFLEFBQUMsQ0FBQyxBQUNGLE9BQU8sQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUFDLENBQUMsQUFFckIsSUFBSSxjQUFDLENBQUMsQUFDSixXQUFXLENBQUUsR0FBRyxBQUFFLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.video = list[i];
	child_ctx.i = i;
	return child_ctx;
}

// (77:255) {#if parseInt(video.statistics.viewCount)}
function create_if_block_2(ctx) {
	var span1, i, span0, t_value = ctx.video.statistics.viewCount + "", t;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { style: true, class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-eye");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "var(--systemGray)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 76, 323, 1649);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", "var(--systemGray)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 76, 382, 1708);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 76, 297, 1623);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t);
		},

		p: function update(changed, ctx) {
			if ((changed.videos) && t_value !== (t_value = ctx.video.statistics.viewCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block_2.name, type: "if", source: "(77:255) {#if parseInt(video.statistics.viewCount)}", ctx });
	return block;
}

// (77:468) {#if parseInt(video.statistics.likeCount)}
function create_if_block_1(ctx) {
	var span1, i, span0, t_value = ctx.video.statistics.likeCount + "", t;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { style: true, class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-heart");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "var(--systemRed)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 76, 536, 1862);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", "var(--systemRed)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 76, 596, 1922);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 76, 510, 1836);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t);
		},

		p: function update(changed, ctx) {
			if ((changed.videos) && t_value !== (t_value = ctx.video.statistics.likeCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block_1.name, type: "if", source: "(77:468) {#if parseInt(video.statistics.likeCount)}", ctx });
	return block;
}

// (77:681) {#if parseInt(video.statistics.commentCount)}
function create_if_block(ctx) {
	var span1, i, span0, t_value = ctx.video.statistics.commentCount + "", t;

	const block = {
		c: function create() {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h()
		},

		l: function claim(nodes) {
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true }, false);
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);

			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "I", { class: true, style: true }, false);
			var i_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i);

			i_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span1_nodes, "SPAN", { style: true, class: true }, false);
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, t_value);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-comment");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(i, "color", "var(--systemTeal)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 76, 752, 2078);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(span0, "color", "var(--systemTeal)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 76, 815, 2141);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "badge--item svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 76, 726, 2052);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span1, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t);
		},

		p: function update(changed, ctx) {
			if ((changed.videos) && t_value !== (t_value = ctx.video.statistics.commentCount + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span1);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_if_block.name, type: "if", source: "(77:681) {#if parseInt(video.statistics.commentCount)}", ctx });
	return block;
}

// (77:34) {#each videos as video, i}
function create_each_block(ctx) {
	var li, a, span, t_value = ctx.video.title + "", t, div, show_if_2 = ctx.parseInt(ctx.video.statistics.viewCount), if_block0_anchor, show_if_1 = ctx.parseInt(ctx.video.statistics.likeCount), if_block1_anchor, show_if = ctx.parseInt(ctx.video.statistics.commentCount), a_href_value;

	var if_block0 = (show_if_2) && create_if_block_2(ctx);

	var if_block1 = (show_if_1) && create_if_block_1(ctx);

	var if_block2 = (show_if) && create_if_block(ctx);

	const block = {
		c: function create() {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if (if_block0) if_block0.c();
			if_block0_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			if (if_block1) if_block1.c();
			if_block1_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			if (if_block2) if_block2.c();
			this.h()
		},

		l: function claim(nodes) {
			li = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "LI", { class: true, style: true }, false);
			var li_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li_nodes, "A", { href: true, target: true, rel: true, class: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "SPAN", { class: true }, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			if (if_block0) if_block0.l(div_nodes);
			if_block0_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			if (if_block1) if_block1.l(div_nodes);
			if_block1_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
			if (if_block2) if_block2.l(div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "title svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 76, 196, 1522);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "badge svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 76, 236, 1562);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", a_href_value = "https://www.youtube.com/watch?v=" + ctx.video.id);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "rel", "noopener");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 76, 112, 1438);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(li, "class", "video svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(li, "animation-delay", "" + ctx.i*10 + "ms");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li, file, 76, 60, 1386);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, li, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, div);
			if (if_block0) if_block0.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, if_block0_anchor);
			if (if_block1) if_block1.m(div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, if_block1_anchor);
			if (if_block2) if_block2.m(div, null);
		},

		p: function update(changed, ctx) {
			if ((changed.videos) && t_value !== (t_value = ctx.video.title + "")) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
			}

			if (changed.videos) show_if_2 = ctx.parseInt(ctx.video.statistics.viewCount)

			if (show_if_2) {
				if (if_block0) {
					if_block0.p(changed, ctx);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(div, if_block0_anchor);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (changed.videos) show_if_1 = ctx.parseInt(ctx.video.statistics.likeCount)

			if (show_if_1) {
				if (if_block1) {
					if_block1.p(changed, ctx);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(div, if_block1_anchor);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (changed.videos) show_if = ctx.parseInt(ctx.video.statistics.commentCount)

			if (show_if) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(div, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}

			if ((changed.videos) && a_href_value !== (a_href_value = "https://www.youtube.com/watch?v=" + ctx.video.id)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", a_href_value);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(li);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_each_block.name, type: "each", source: "(77:34) {#each videos as video, i}", ctx });
	return block;
}

function create_fragment(ctx) {
	var ul, h2, t;

	let each_value = ctx.videos;

	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const block = {
		c: function create() {
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Videos");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "H2", { class: true }, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Videos");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(ul_nodes);
			}

			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 76, 19, 1345);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(ul, "class", "videos svelte-arqnso");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 76, 0, 1326);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, ul, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},

		p: function update(changed, ctx) {
			if (changed.videos || changed.parseInt) {
				each_value = ctx.videos;

				let i;
				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}
				each_blocks.length = each_value.length;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(ul);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_fragment.name, type: "component", source: "", ctx });
	return block;
}

function instance($$self, $$props, $$invalidate) {
	var videos;

$$invalidate('videos', videos = []);

Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async() => {
  $$invalidate('videos', videos = (await Object(_utils_utility__WEBPACK_IMPORTED_MODULE_2__["cachedFetch"])('/.netlify/functions/youtube')));
  // Sort the videos based on view count
  return videos.sort((a, b) => {
    return parseInt(b.statistics.viewCount) - parseInt(a.statistics.viewCount);
  });
});

	$$self.$capture_state = () => {
		return {};
	};

	$$self.$inject_state = $$props => {
		if ('videos' in $$props) $$invalidate('videos', videos = $$props.videos);
	};

	return { videos, parseInt };
}

class Youtube_videos extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-arqnso-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", { component: this, tagName: "Youtube_videos", options, id: create_fragment.name });
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Youtube_videos);

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_hero_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/hero.svelte */ "./src/components/hero.svelte");
/* harmony import */ var _components_repos_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/repos.svelte */ "./src/components/repos.svelte");
/* harmony import */ var _components_youtube_videos_svelte__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../components/youtube-videos.svelte */ "./src/components/youtube-videos.svelte");
/* src/routes/index.svelte generated by Svelte v3.12.0 */





const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-gefebq-style';
	style.textContent = ".container.svelte-gefebq{margin:0;padding:0;display:flex;flex-flow:row wrap;justify-content:center}@media only screen and (max-width: 800px){.container.svelte-gefebq{margin:0;padding:0}}.container--item.svelte-gefebq{margin:20px}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdCBsYW5nPVwiY29mZmVlXCI+dmFyIGNvbXBvbmVudHM7XG5cbmltcG9ydCBIZXJvIGZyb20gJy4uL2NvbXBvbmVudHMvaGVyby5zdmVsdGUnO1xuXG5pbXBvcnQgUmVwb3MgZnJvbSAnLi4vY29tcG9uZW50cy9yZXBvcy5zdmVsdGUnO1xuXG5pbXBvcnQgWW91dHViZVZpZGVvcyBmcm9tICcuLi9jb21wb25lbnRzL3lvdXR1YmUtdmlkZW9zLnN2ZWx0ZSc7XG5cbmNvbXBvbmVudHMgPSBbSGVybywgUmVwb3MsIFlvdXR1YmVWaWRlb3NdO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZSBsYW5nPVwic2Fzc1wiPi5jb250YWluZXIge1xuICBtYXJnaW46IDA7XG4gIHBhZGRpbmc6IDA7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGZsZXgtZmxvdzogcm93IHdyYXA7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyOyB9XG4gIEBtZWRpYSBvbmx5IHNjcmVlbiBhbmQgKG1heC13aWR0aDogODAwcHgpIHtcbiAgICAuY29udGFpbmVyIHtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIHBhZGRpbmc6IDA7IH0gfVxuXG4uY29udGFpbmVyLS1pdGVtIHtcbiAgbWFyZ2luOiAyMHB4OyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuXG48c3ZlbHRlOmhlYWQ+PHRpdGxlPkhvbWU8L3RpdGxlPjwvc3ZlbHRlOmhlYWQ+PGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPnsjZWFjaCBjb21wb25lbnRzIGFzIGNvbXBvbmVudH08ZGl2IGNsYXNzPVwiY29udGFpbmVyLS1pdGVtXCI+PHN2ZWx0ZTpjb21wb25lbnQgdGhpcz1cIntjb21wb25lbnR9XCI+PC9zdmVsdGU6Y29tcG9uZW50PjwvZGl2PnsvZWFjaH08L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFXbUIsVUFBVSxjQUFDLENBQUMsQUFDN0IsTUFBTSxDQUFFLENBQUMsQ0FDVCxPQUFPLENBQUUsQ0FBQyxDQUNWLE9BQU8sQ0FBRSxJQUFJLENBQ2IsU0FBUyxDQUFFLEdBQUcsQ0FBQyxJQUFJLENBQ25CLGVBQWUsQ0FBRSxNQUFNLEFBQUUsQ0FBQyxBQUMxQixPQUFPLElBQUksQ0FBQyxNQUFNLENBQUMsR0FBRyxDQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUN6QyxVQUFVLGNBQUMsQ0FBQyxBQUNWLE1BQU0sQ0FBRSxDQUFDLENBQ1QsT0FBTyxDQUFFLENBQUMsQUFBRSxDQUFDLEFBQUMsQ0FBQyxBQUVyQixnQkFBZ0IsY0FBQyxDQUFDLEFBQ2hCLE1BQU0sQ0FBRSxJQUFJLEFBQUUsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.component = list[i];
	return child_ctx;
}

// (29:69) {#each components as component}
function create_each_block(ctx) {
	var div, current;

	var switch_value = ctx.component;

	function switch_props(ctx) {
		return { $$inline: true };
	}

	if (switch_value) {
		var switch_instance = new switch_value(switch_props(ctx));
	}

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if (switch_instance) switch_instance.$$.fragment.c();
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			if (switch_instance) switch_instance.$$.fragment.l(div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "container--item svelte-gefebq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 28, 100, 679);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);

			if (switch_instance) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(switch_instance, div, null);
			}

			current = true;
		},

		p: function update(changed, ctx) {
			if (switch_value !== (switch_value = ctx.component)) {
				if (switch_instance) {
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();
					const old_component = switch_instance;
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(old_component.$$.fragment, 1, 0, () => {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(old_component, 1);
					});
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				}

				if (switch_value) {
					switch_instance = new switch_value(switch_props(ctx));

					switch_instance.$$.fragment.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(switch_instance.$$.fragment, 1);
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(switch_instance, div, null);
				} else {
					switch_instance = null;
				}
			}
		},

		i: function intro(local) {
			if (current) return;
			if (switch_instance) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(switch_instance.$$.fragment, local);

			current = true;
		},

		o: function outro(local) {
			if (switch_instance) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(switch_instance.$$.fragment, local);
			current = false;
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			}

			if (switch_instance) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(switch_instance);
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_each_block.name, type: "each", source: "(29:69) {#each components as component}", ctx });
	return block;
}

function create_fragment(ctx) {
	var div, current;

	let each_value = ctx.components;

	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(div_nodes);
			}

			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Home";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "container svelte-gefebq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 28, 46, 625);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(div, null);
			}

			current = true;
		},

		p: function update(changed, ctx) {
			if (changed.components) {
				each_value = ctx.components;

				let i;
				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(changed, child_ctx);
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
						each_blocks[i].m(div, null);
					}
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();
				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}
		},

		i: function intro(local) {
			if (current) return;
			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			current = true;
		},

		o: function outro(local) {
			each_blocks = each_blocks.filter(Boolean);
			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			current = false;
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_fragment.name, type: "component", source: "", ctx });
	return block;
}

function instance($$self, $$props, $$invalidate) {
	var components;

$$invalidate('components', components = [_components_hero_svelte__WEBPACK_IMPORTED_MODULE_1__["default"], _components_repos_svelte__WEBPACK_IMPORTED_MODULE_2__["default"], _components_youtube_videos_svelte__WEBPACK_IMPORTED_MODULE_3__["default"]]);

	$$self.$capture_state = () => {
		return {};
	};

	$$self.$inject_state = $$props => {
		if ('components' in $$props) $$invalidate('components', components = $$props.components);
	};

	return { components };
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-gefebq-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", { component: this, tagName: "Routes", options, id: create_fragment.name });
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9yZXBvcy5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL2NvbXBvbmVudHMveW91dHViZS12aWRlb3Muc3ZlbHRlIiwid2VicGFjazovLy8uL3NyYy9yb3V0ZXMvaW5kZXguc3ZlbHRlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lCQWdHNFYsSUFBSSxDQUFDLGVBQWUsQ0FBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt3RkFBMUUsY0FBYyxDQUFDLEdBQUcsS0FBQyxJQUFJLENBQUMsZUFBZSxDQUFDLElBQUksQ0FBQzs7Ozs7Ozs7OztxREFBSSxJQUFJLENBQUMsZUFBZSxDQUFDLElBQUk7Ozs7O3lGQUExRSxjQUFjLENBQUMsR0FBRyxLQUFDLElBQUksQ0FBQyxlQUFlLENBQUMsSUFBSSxDQUFDOzs7Ozs7Ozs7Ozs7Ozs7O29DQUE0TSxJQUFJLENBQUMsVUFBVSxDQUFDLFVBQVU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxREFBMUIsSUFBSSxDQUFDLFVBQVUsQ0FBQyxVQUFVOzs7Ozs7Ozs7Ozs7Ozs7OztvQ0FBeUosSUFBSSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxREFBZCxJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Z0NBQTFpQixJQUFJLENBQUMsSUFBSTs7c0JBQWdDLElBQUksQ0FBQyxlQUFlOztzQkFBK0ksSUFBSSxDQUFDLFVBQVUsQ0FBQyxVQUFVOztzQkFBc0wsSUFBSSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7a0dBQXplLElBQUksQ0FBQyxHQUFHOzs7Ozs7cUdBQTNCLENBQUMsQ0FBQyxFQUFFOzs7Ozs7Ozs7Ozs7Ozs7Ozs7cURBQThFLElBQUksQ0FBQyxJQUFJOzs7O1dBQWdDLElBQUksQ0FBQyxlQUFlOzs7Ozs7Ozs7Ozs7O1dBQStJLElBQUksQ0FBQyxVQUFVLENBQUMsVUFBVTs7Ozs7Ozs7Ozs7OztXQUFzTCxJQUFJLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7OzsrREFBemUsSUFBSSxDQUFDLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0JBQXRGLEtBQUs7Ozs7Z0NBQVY7Ozs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O21DQUFBOzs7Ozs7O3FCQUFLLEtBQUs7OzsrQkFBVjs7Ozs7Ozs7Ozs7OzJCQUFBOzs7Z0JBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0NBaEduQixJQUFJLFFBQVEsRUFBRSxvQkFBb0IsRUFBRSx3QkFBd0IsRUFBRSxjQUFjLEVBQUUsS0FBSyxFQUFFLFFBQVEsQ0FRMUY7O3NCQUV6QixLQUFLLEdBQUcsR0FBRSxDQUFDOztBQUVYLHdCQUF3QixHQUFHLENBQUMsQ0FBQzs7K0JBRTdCLGNBQWMsR0FBRyxJQUFJLEdBQUcsR0FBRSxDQUFDOztBQUUzQixvQkFBb0IsR0FBRyxDQUFDLG1CQUFtQixFQUFFLG1CQUFtQixFQUFFLG9CQUFvQixFQUFFLHFCQUFxQixFQUFFLHFCQUFxQixFQUFFLG1CQUFtQixFQUFFLHFCQUFxQixFQUFFLGtCQUFrQixFQUFFLG1CQUFtQixFQUFFLHFCQUFxQixDQUFDLENBQUM7O0FBRWxQLFFBQVEsR0FBRyxHQUFHLENBQUM7O0FBRWYsUUFBUSxHQUFHLEdBQUcsQ0FBQzs7QUFFZixzREFBTyxDQUFDLFdBQVc7RUFDakIsSUFBSSxLQUFLLEVBQUUsQ0FBQyxFQUFFLEdBQUcsRUFBRSxJQUFJLEVBQUUsSUFBSSxFQUFFLE9BQU8sQ0FBQzt3QkFDdkMsS0FBSyxHQUFHLENBQUMsTUFBTSxrRUFBVyxDQUFDLDRCQUE0QixDQUFDLEVBQUMsQ0FBQztFQUMxRCxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsS0FBSztJQUNuQixPQUFPLENBQUMsQ0FBQyxDQUFDLFVBQVUsQ0FBQyxVQUFVLEdBQUcsUUFBUSxHQUFHLENBQUMsQ0FBQyxTQUFTLEdBQUcsUUFBUSxDQUFDLEdBQUcsQ0FBQyxDQUFDLENBQUMsVUFBVSxDQUFDLFVBQVUsR0FBRyxRQUFRLEdBQUcsQ0FBQyxDQUFDLFNBQVMsR0FBRyxRQUFRLENBQUMsQ0FBQztHQUN0SSxDQUFDLENBQUM7RUFDSCxPQUFPLEdBQUcsRUFBRSxDQUFDO0VBQ2IsS0FBSyxDQUFDLEdBQUcsQ0FBQyxFQUFFLEdBQUcsR0FBRyxLQUFLLENBQUMsTUFBTSxFQUFFLENBQUMsR0FBRyxHQUFHLEVBQUUsQ0FBQyxFQUFFLEVBQUU7SUFDNUMsSUFBSSxHQUFHLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQztJQUNoQixJQUFJLEdBQUcsSUFBSSxDQUFDLGVBQWUsQ0FBQyxJQUFJLENBQUM7SUFDakMsS0FBSyxHQUFHLGNBQWMsQ0FBQyxHQUFHLENBQUMsSUFBSSxDQUFDLEdBQUcsY0FBYyxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUMsR0FBRyxvQkFBb0IsQ0FBQyx3QkFBd0IsRUFBRSxHQUFHLG9CQUFvQixDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQzdJLE9BQU8sQ0FBQyxJQUFJLENBQUMsY0FBYyxDQUFDLEdBQUcsQ0FBQyxJQUFJLEVBQUUsS0FBSyxDQUFDLENBQUMsQ0FBQztHQUMvQztFQUNELE9BQU8sT0FBTyxDQUFDO0NBQ2hCLENBQUMsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29DQ3dDbWEsS0FBSyxDQUFDLFVBQVUsQ0FBQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0RBQTFCLEtBQUssQ0FBQyxVQUFVLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0NBQTJMLEtBQUssQ0FBQyxVQUFVLENBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NEQUExQixLQUFLLENBQUMsVUFBVSxDQUFDLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7O29DQUFrTSxLQUFLLENBQUMsVUFBVSxDQUFDLFlBQVk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztzREFBN0IsS0FBSyxDQUFDLFVBQVUsQ0FBQyxZQUFZOzs7Ozs7Ozs7Ozs7Ozs7OztnQ0FBM3BCLEtBQUssQ0FBQyxLQUFLLCtCQUFnQyxRQUFRLEtBQUMsS0FBSyxDQUFDLFVBQVUsQ0FBQyxTQUFTLENBQUMsb0NBQWlMLFFBQVEsS0FBQyxLQUFLLENBQUMsVUFBVSxDQUFDLFNBQVMsQ0FBQyxrQ0FBaUwsUUFBUSxLQUFDLEtBQUssQ0FBQyxVQUFVLENBQUMsWUFBWSxDQUFDOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3VJQUEzakIsS0FBSyxDQUFDLEVBQUU7Ozs7OztxR0FBM0QsQ0FBQyxDQUFDLEVBQUU7Ozs7Ozs7Ozs7Ozs7Ozs7OztzREFBOEcsS0FBSyxDQUFDLEtBQUs7Ozs7dUNBQWdDLFFBQVEsS0FBQyxLQUFLLENBQUMsVUFBVSxDQUFDLFNBQVMsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7O3VDQUFpTCxRQUFRLEtBQUMsS0FBSyxDQUFDLFVBQVUsQ0FBQyxTQUFTLENBQUM7Ozs7Ozs7Ozs7Ozs7OztxQ0FBaUwsUUFBUSxLQUFDLEtBQUssQ0FBQyxVQUFVLENBQUMsWUFBWSxDQUFDOzs7Ozs7Ozs7Ozs7Ozs7cUdBQTNqQixLQUFLLENBQUMsRUFBRTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztzQkFBekgsTUFBTTs7OztnQ0FBWDs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7cUJBQUssTUFBTTs7OytCQUFYOzs7Ozs7Ozs7Ozs7MkJBQUE7OztnQkFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Q0E1RWQsSUFBSSxNQUFNLENBUVA7O3VCQUV6QixNQUFNLEdBQUcsR0FBRSxDQUFDOztBQUVaLHNEQUFPLENBQUMsV0FBVzt5QkFDakIsTUFBTSxHQUFHLENBQUMsTUFBTSxrRUFBVyxDQUFDLDZCQUE2QixDQUFDLEVBQUMsQ0FBQzs7RUFFNUQsT0FBTyxNQUFNLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsS0FBSztJQUMzQixPQUFPLFFBQVEsQ0FBQyxDQUFDLENBQUMsVUFBVSxDQUFDLFNBQVMsQ0FBQyxHQUFHLFFBQVEsQ0FBQyxDQUFDLENBQUMsVUFBVSxDQUFDLFNBQVMsQ0FBQyxDQUFDO0dBQzVFLENBQUMsQ0FBQztDQUNKLENBQUMsQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt3QkNVdUosU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzRDQUFULFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0JBQXZGLFVBQVU7Ozs7Z0NBQWY7Ozs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7OzttQ0FBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7OztxQkFBSyxVQUFVOzs7K0JBQWY7Ozs7Ozs7Ozs7Ozs7Ozt3QkFBQTs7Ozs7Ozs7O2tDQUFBOzs7Ozs7Ozs7bUNBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0NBNUJqRCxJQUFJLFVBQVUsQ0FNNEI7OzJCQUVoRSxVQUFVLEdBQUcsQ0FBQywrREFBSSxFQUFFLGdFQUFLLEVBQUUseUVBQWEsRUFBQyxDQUFDIiwiZmlsZSI6IjkxNjQyMjk3ZWIzMjVjNzU5NzE5L2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdCBsYW5nPVwiY29mZmVlXCI+dmFyIGZvcmtCaWFzLCBsYW5ndWFnZUNvbG9yQ2hvaWNlcywgbGFuZ3VhZ2VDb2xvckNob2ljZXNJdGVyLCBsYW5ndWFnZUNvbG9ycywgcmVwb3MsIHN0YXJCaWFzO1xuXG5pbXBvcnQge1xuICBvbk1vdW50XG59IGZyb20gJ3N2ZWx0ZSc7XG5cbmltcG9ydCB7XG4gIGNhY2hlZEZldGNoXG59IGZyb20gJy4vdXRpbHMvdXRpbGl0eSc7XG5cbnJlcG9zID0gW107XG5cbmxhbmd1YWdlQ29sb3JDaG9pY2VzSXRlciA9IDA7XG5cbmxhbmd1YWdlQ29sb3JzID0gbmV3IE1hcCgpO1xuXG5sYW5ndWFnZUNvbG9yQ2hvaWNlcyA9IFsndmFyKC0tc3lzdGVtQmx1ZSknLCAndmFyKC0tc3lzdGVtR3JheSknLCAndmFyKC0tc3lzdGVtR3JlZW4pJywgJ3ZhcigtLXN5c3RlbUluZGlnbyknLCAndmFyKC0tc3lzdGVtT3JhbmdlKScsICd2YXIoLS1zeXN0ZW1QaW5rKScsICd2YXIoLS1zeXN0ZW1QdXJwbGUpJywgJ3ZhcigtLXN5c3RlbVJlZCknLCAndmFyKC0tc3lzdGVtVGVhbCknLCAndmFyKC0tc3lzdGVtWWVsbG93KSddO1xuXG5zdGFyQmlhcyA9IDEuNTtcblxuZm9ya0JpYXMgPSAyLjA7IC8vIHZhbHVlIGZvcmtzIG1vcmUgdGhhbiBzdGFyc1xuXG5vbk1vdW50KGFzeW5jKCkgPT4ge1xuICB2YXIgY29sb3IsIGksIGxlbiwgbmFtZSwgcmVwbywgcmVzdWx0cztcbiAgcmVwb3MgPSAoYXdhaXQgY2FjaGVkRmV0Y2goJy8ubmV0bGlmeS9mdW5jdGlvbnMvZ2l0aHViJykpO1xuICByZXBvcy5zb3J0KChhLCBiKSA9PiB7XG4gICAgcmV0dXJuIChiLnN0YXJnYXplcnMudG90YWxDb3VudCAqIHN0YXJCaWFzICsgYi5mb3JrQ291bnQgKiBmb3JrQmlhcykgLSAoYS5zdGFyZ2F6ZXJzLnRvdGFsQ291bnQgKiBzdGFyQmlhcyArIGEuZm9ya0NvdW50ICogZm9ya0JpYXMpO1xuICB9KTtcbiAgcmVzdWx0cyA9IFtdO1xuICBmb3IgKGkgPSAwLCBsZW4gPSByZXBvcy5sZW5ndGg7IGkgPCBsZW47IGkrKykge1xuICAgIHJlcG8gPSByZXBvc1tpXTtcbiAgICBuYW1lID0gcmVwby5wcmltYXJ5TGFuZ3VhZ2UubmFtZTtcbiAgICBjb2xvciA9IGxhbmd1YWdlQ29sb3JzLmhhcyhuYW1lKSA/IGxhbmd1YWdlQ29sb3JzLmdldChuYW1lKSA6IGxhbmd1YWdlQ29sb3JDaG9pY2VzW2xhbmd1YWdlQ29sb3JDaG9pY2VzSXRlcisrICUgbGFuZ3VhZ2VDb2xvckNob2ljZXMubGVuZ3RoXTtcbiAgICByZXN1bHRzLnB1c2gobGFuZ3VhZ2VDb2xvcnMuc2V0KG5hbWUsIGNvbG9yKSk7XG4gIH1cbiAgcmV0dXJuIHJlc3VsdHM7XG59KTtcbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4ucmVwb3Mge1xuICB0ZXh0LWFsaWduOiBsZWZ0O1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7IH1cbiAgLnJlcG9zIGgyIHtcbiAgICBtYXJnaW46IDVweDtcbiAgICB0ZXh0LWFsaWduOiBsZWZ0O1xuICAgIGZvbnQtc2l6ZTogMS41MGVtO1xuICAgIGZvbnQtd2VpZ2h0OiA3MDA7IH1cbiAgQG1lZGlhIG9ubHkgc2NyZWVuIGFuZCAobWF4LXdpZHRoOiA2MDBweCkge1xuICAgIC5yZXBvcyB7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBwYWRkaW5nOiAwO1xuICAgICAgZm9udC1zaXplOiAwLjg1ZW07IH0gfVxuXG5hIHtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwOyB9XG5cbi5yZXBvIHtcbiAgZGlzcGxheTogZmxleDtcbiAgb3BhY2l0eTogMC4wO1xuICBhbmltYXRpb246IHJldmVhbCAxcyBmb3J3YXJkczsgfVxuXG4udGl0bGUge1xuICBmb250LXNpemU6IDFlbTtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwO1xuICBtYXJnaW4tcmlnaHQ6IDVweDtcbiAgdGV4dC1hbGlnbjogbGVmdDsgfVxuXG4ubGFuZ2F1Z2Uge1xuICBmb250LXdlaWdodDogNzAwOyB9XG5cbi5iYWRnZSB7XG4gIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgbWFyZ2luLWxlZnQ6IDVweDtcbiAgYmFja2dyb3VuZDogdmFyKC0tc2Vjb25kYXJ5KTtcbiAgcGFkZGluZzogNXB4O1xuICBwYWRkaW5nLXRvcDogMnB4O1xuICBwYWRkaW5nLWJvdHRvbTogMnB4O1xuICBib3JkZXItcmFkaXVzOiB2YXIoLS1ib3JkZXItcmFkaXVzKTtcbiAgZm9udC1zaXplOiAwLjc1ZW07IH1cblxuLmJhZGdlLS1pdGVtIHtcbiAgbWFyZ2luOiAycHg7IH1cblxuQGtleWZyYW1lcyByZXZlYWwge1xuICBmcm9tIHtcbiAgICBvcGFjaXR5OiAwLjA7IH1cbiAgdG8ge1xuICAgIG9wYWNpdHk6IDEuMDsgfSB9XG5cbnNwYW4ge1xuICBtYXJnaW4tbGVmdDogMnB4OyB9XG5cbi8qIyBzb3VyY2VNYXBwaW5nVVJMPXJlcG9zLnN2ZWx0ZS5jc3MubWFwICovPC9zdHlsZT5cblxuPHVsIGNsYXNzPVwicmVwb3NcIj48aDI+UmVwb3NpdG9yaWVzPC9oMj57I2VhY2ggcmVwb3MgYXMgcmVwbywgaX08bGkgY2xhc3M9XCJyZXBvXCIgc3R5bGU9XCJhbmltYXRpb24tZGVsYXk6IHtpKjEwfW1zXCI+PGEgaHJlZj1cIntyZXBvLnVybH1cIiB0YXJnZXQ9XCJfYmxhbmtcIiByZWw9XCJub29wZW5lclwiPjxzcGFuIGNsYXNzPVwidGl0bGVcIj57cmVwby5uYW1lfTwvc3Bhbj48ZGl2IGNsYXNzPVwiYmFkZ2VcIj57I2lmIHJlcG8ucHJpbWFyeUxhbmd1YWdlfTxzcGFuIGNsYXNzPVwiYmFkZ2UtLWl0ZW0gbGFudWdhZ2VcIiBzdHlsZT1cImNvbG9yOiB7bGFuZ3VhZ2VDb2xvcnMuZ2V0KHJlcG8ucHJpbWFyeUxhbmd1YWdlLm5hbWUpfVwiPntyZXBvLnByaW1hcnlMYW5ndWFnZS5uYW1lfTwvc3Bhbj57L2lmfXsjaWYgcmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9PHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPjxpIGNsYXNzPVwiZmFzIGZhLXN0YXJcIiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1ZZWxsb3cpXCI+PC9pPjxzcGFuIHN0eWxlPVwiY29sb3I6IHZhcigtLXN5c3RlbVllbGxvdylcIj57cmVwby5zdGFyZ2F6ZXJzLnRvdGFsQ291bnR9PC9zcGFuPjwvc3Bhbj57L2lmfXsjaWYgcmVwby5mb3JrQ291bnR9PHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPjxpIGNsYXNzPVwiZmFzIGZhLWNvZGUtYnJhbmNoXCIgc3R5bGU9XCJjb2xvcjogI2M5NGRhMFwiPjwvaT48c3BhbiBzdHlsZT1cImNvbG9yOiAjYzk0ZGEwXCI+e3JlcG8uZm9ya0NvdW50fTwvc3Bhbj48L3NwYW4+ey9pZn08L2Rpdj48L2E+PC9saT57L2VhY2h9PC91bD5cbiIsIjxzY3JpcHQgbGFuZz1cImNvZmZlZVwiPnZhciB2aWRlb3M7XG5cbmltcG9ydCB7XG4gIG9uTW91bnRcbn0gZnJvbSAnc3ZlbHRlJztcblxuaW1wb3J0IHtcbiAgY2FjaGVkRmV0Y2hcbn0gZnJvbSAnLi91dGlscy91dGlsaXR5JztcblxudmlkZW9zID0gW107XG5cbm9uTW91bnQoYXN5bmMoKSA9PiB7XG4gIHZpZGVvcyA9IChhd2FpdCBjYWNoZWRGZXRjaCgnLy5uZXRsaWZ5L2Z1bmN0aW9ucy95b3V0dWJlJykpO1xuICAvLyBTb3J0IHRoZSB2aWRlb3MgYmFzZWQgb24gdmlldyBjb3VudFxuICByZXR1cm4gdmlkZW9zLnNvcnQoKGEsIGIpID0+IHtcbiAgICByZXR1cm4gcGFyc2VJbnQoYi5zdGF0aXN0aWNzLnZpZXdDb3VudCkgLSBwYXJzZUludChhLnN0YXRpc3RpY3Mudmlld0NvdW50KTtcbiAgfSk7XG59KTtcbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4udmlkZW9zIHtcbiAgdGV4dC1hbGlnbjogbGVmdDtcbiAgZGlzcGxheTogaW5saW5lLWJsb2NrOyB9XG4gIC52aWRlb3MgaDIge1xuICAgIG1hcmdpbjogNXB4O1xuICAgIHRleHQtYWxpZ246IGxlZnQ7XG4gICAgZm9udC1zaXplOiAxLjUwZW07XG4gICAgZm9udC13ZWlnaHQ6IDcwMDsgfVxuICBAbWVkaWEgb25seSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDYwMHB4KSB7XG4gICAgLnZpZGVvcyB7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBwYWRkaW5nOiAwO1xuICAgICAgZm9udC1zaXplOiAwLjg1ZW07IH0gfVxuXG5hIHtcbiAgcGFkZGluZzogMDtcbiAgbWFyZ2luOiAwOyB9XG5cbi52aWRlbyB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIG9wYWNpdHk6IDAuMDtcbiAgYW5pbWF0aW9uOiByZXZlYWwgMXMgZm9yd2FyZHM7IH1cblxuLnRpdGxlIHtcbiAgZm9udC1zaXplOiAxZW07XG4gIHBhZGRpbmc6IDA7XG4gIG1hcmdpbjogMDtcbiAgbWFyZ2luLXJpZ2h0OiA1cHg7XG4gIHRleHQtYWxpZ246IGxlZnQ7IH1cblxuLmJhZGdlIHtcbiAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICBtYXJnaW4tbGVmdDogNXB4O1xuICBiYWNrZ3JvdW5kOiB2YXIoLS1zZWNvbmRhcnkpO1xuICBwYWRkaW5nOiA1cHg7XG4gIHBhZGRpbmctdG9wOiAycHg7XG4gIHBhZGRpbmctYm90dG9tOiAycHg7XG4gIGJvcmRlci1yYWRpdXM6IHZhcigtLWJvcmRlci1yYWRpdXMpO1xuICBmb250LXNpemU6IDAuNzVlbTsgfVxuXG4uYmFkZ2UtLWl0ZW0ge1xuICBtYXJnaW4tbGVmdDogNXB4OyB9XG5cbkBrZXlmcmFtZXMgcmV2ZWFsIHtcbiAgZnJvbSB7XG4gICAgb3BhY2l0eTogMC4wOyB9XG4gIHRvIHtcbiAgICBvcGFjaXR5OiAxLjA7IH0gfVxuXG5zcGFuIHtcbiAgbWFyZ2luLWxlZnQ6IDJweDsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD15b3V0dWJlLXZpZGVvcy5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cblxuPHVsIGNsYXNzPVwidmlkZW9zXCI+PGgyPlZpZGVvczwvaDI+eyNlYWNoIHZpZGVvcyBhcyB2aWRlbywgaX08bGkgY2xhc3M9XCJ2aWRlb1wiIHN0eWxlPVwiYW5pbWF0aW9uLWRlbGF5OiB7aSoxMH1tc1wiPjxhIGhyZWY9XCJodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PXt2aWRlby5pZH1cIiB0YXJnZXQ9XCJfYmxhbmtcIiByZWw9XCJub29wZW5lclwiPjxzcGFuIGNsYXNzPVwidGl0bGVcIj57dmlkZW8udGl0bGV9PC9zcGFuPjxkaXYgY2xhc3M9XCJiYWRnZVwiPnsjaWYgcGFyc2VJbnQodmlkZW8uc3RhdGlzdGljcy52aWV3Q291bnQpfTxzcGFuIGNsYXNzPVwiYmFkZ2UtLWl0ZW1cIj48aSBjbGFzcz1cImZhcyBmYS1leWVcIiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1HcmF5KVwiPjwvaT48c3BhbiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1HcmF5KVwiPnt2aWRlby5zdGF0aXN0aWNzLnZpZXdDb3VudH08L3NwYW4+PC9zcGFuPnsvaWZ9eyNpZiBwYXJzZUludCh2aWRlby5zdGF0aXN0aWNzLmxpa2VDb3VudCl9PHNwYW4gY2xhc3M9XCJiYWRnZS0taXRlbVwiPjxpIGNsYXNzPVwiZmFzIGZhLWhlYXJ0XCIgc3R5bGU9XCJjb2xvcjogdmFyKC0tc3lzdGVtUmVkKVwiPjwvaT48c3BhbiBzdHlsZT1cImNvbG9yOiB2YXIoLS1zeXN0ZW1SZWQpXCI+e3ZpZGVvLnN0YXRpc3RpY3MubGlrZUNvdW50fTwvc3Bhbj48L3NwYW4+ey9pZn17I2lmIHBhcnNlSW50KHZpZGVvLnN0YXRpc3RpY3MuY29tbWVudENvdW50KX08c3BhbiBjbGFzcz1cImJhZGdlLS1pdGVtXCI+PGkgY2xhc3M9XCJmYXMgZmEtY29tbWVudFwiIHN0eWxlPVwiY29sb3I6IHZhcigtLXN5c3RlbVRlYWwpXCI+PC9pPjxzcGFuIHN0eWxlPVwiY29sb3I6IHZhcigtLXN5c3RlbVRlYWwpXCI+e3ZpZGVvLnN0YXRpc3RpY3MuY29tbWVudENvdW50fTwvc3Bhbj48L3NwYW4+ey9pZn08L2Rpdj48L2E+PC9saT57L2VhY2h9PC91bD5cbiIsIjxzY3JpcHQgbGFuZz1cImNvZmZlZVwiPnZhciBjb21wb25lbnRzO1xuXG5pbXBvcnQgSGVybyBmcm9tICcuLi9jb21wb25lbnRzL2hlcm8uc3ZlbHRlJztcblxuaW1wb3J0IFJlcG9zIGZyb20gJy4uL2NvbXBvbmVudHMvcmVwb3Muc3ZlbHRlJztcblxuaW1wb3J0IFlvdXR1YmVWaWRlb3MgZnJvbSAnLi4vY29tcG9uZW50cy95b3V0dWJlLXZpZGVvcy5zdmVsdGUnO1xuXG5jb21wb25lbnRzID0gW0hlcm8sIFJlcG9zLCBZb3V0dWJlVmlkZW9zXTtcbjwvc2NyaXB0PlxuXG48c3R5bGUgbGFuZz1cInNhc3NcIj4uY29udGFpbmVyIHtcbiAgbWFyZ2luOiAwO1xuICBwYWRkaW5nOiAwO1xuICBkaXNwbGF5OiBmbGV4O1xuICBmbGV4LWZsb3c6IHJvdyB3cmFwO1xuICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsgfVxuICBAbWVkaWEgb25seSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDgwMHB4KSB7XG4gICAgLmNvbnRhaW5lciB7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBwYWRkaW5nOiAwOyB9IH1cblxuLmNvbnRhaW5lci0taXRlbSB7XG4gIG1hcmdpbjogMjBweDsgfVxuXG4vKiMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5zdmVsdGUuY3NzLm1hcCAqLzwvc3R5bGU+XG5cblxuPHN2ZWx0ZTpoZWFkPjx0aXRsZT5Ib21lPC90aXRsZT48L3N2ZWx0ZTpoZWFkPjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj57I2VhY2ggY29tcG9uZW50cyBhcyBjb21wb25lbnR9PGRpdiBjbGFzcz1cImNvbnRhaW5lci0taXRlbVwiPjxzdmVsdGU6Y29tcG9uZW50IHRoaXM9XCJ7Y29tcG9uZW50fVwiPjwvc3ZlbHRlOmNvbXBvbmVudD48L2Rpdj57L2VhY2h9PC9kaXY+XG4iXSwic291cmNlUm9vdCI6IiJ9